### ISSUE TITLE
Collection of sites with sticky headers

### ISSUE THREAD

**Issue by elypter** [yourduskquibbles/webannoyances#1]
During my regular browsing i blocked a number of sticky menus. i didnt check it for dublicates or if everything is still correct but i thought it might help you to expand your list.

! 26.12.2016, 17:31:17 http://www.androidauthority.com/oneplus-one-india-575171/
www.androidauthority.com###tt_hot_products_menu

! 26.12.2016, 17:31:38 http://www.androidauthority.com/oneplus-one-india-575171/
www.androidauthority.com###sticky-bar

! 29.12.2016, 19:57:56 https://freshideen.com/diy-do-it-yourself/diy-mobel-aus-autoreifen-altreifen-recycling.html
freshideen.com###embed_popup_cont

! 25.11.2016, 01:15:05 https://www.zdf.de/
www.zdf.de##.js-rb-attached.m-filter.b-cluster:nth-of-type(1)

! 25.11.2016, 01:15:28 https://www.zdf.de/
www.zdf.de##.js-rb-attached.m-filter.b-cluster:nth-of-type(2)

! 25.11.2016, 01:15:44 https://www.zdf.de/
www.zdf.de##.js-rb-attached.m-filter.b-cluster:nth-of-type(3)

! 25.11.2016, 01:15:59 https://www.zdf.de/
www.zdf.de##.js-rb-attached.m-filter.b-cluster:nth-of-type(4)

! 29.11.2016, 02:55:24 http://www.space.com/34824-nasa-x-ray-tech-deep-space-communication.html
www.space.com###sticky-header

! 2.12.2016, 05:00:56 https://www.neo-magazin-royale.de/zdi/
www.neo-magazin-royale.de##.gradient

! 2.12.2016, 05:01:17 https://www.neo-magazin-royale.de/zdi/
www.neo-magazin-royale.de##.push.header

! 3.12.2016, 07:01:38 https://www.zdf.de/comedy/heute-show/heute-show-vom-2-dezember-2016-102.html
www.zdf.de##.m-slim.js-rb-attached.b-header

! 9.12.2016, 19:34:11 https://itsfoss.com/play-retro-games-linux/
itsfoss.com##.light.site-header

! 15.12.2016, 23:51:19 http://www.sueddeutsche.de/digital/inside-facebook-im-netz-des-boesen-1.3295206?reduced=true
www.sueddeutsche.de##.opc-placeholder

! 16.12.2016, 05:02:08 http://doku5.com/mineralien-entstehung-lebens/
doku5.com###msgWindowX

! 21.12.2016, 01:34:56 https://www.manualslib.com/manual/814467/Viasat-Surfbeam.html
www.manualslib.com##.policy

! 21.12.2016, 05:29:38 http://www.exede.com/
www.exede.com##.visible-lg.visible-md.hidden-sm.hidden-xs.navbar-fixed-top.navbar-default.navbar.desktop-navbar

! 23.12.2016, 15:32:53 https://www.stardsl.net/produkt/tooway-flex/
www.stardsl.net##.fusion-secondary-main-menu

! 23.12.2016, 15:33:03 https://www.stardsl.net/produkt/tooway-flex/
www.stardsl.net##.fusion-header

! 23.12.2016, 15:33:15 https://www.stardsl.net/produkt/tooway-flex/
www.stardsl.net##.fusion-sticky-header-wrapper

! 5.1.2017, 07:29:58 http://www.justanswer.com/printers/7ca9a-no-paper-printer-says-paper-jam-code-3533.html
www.justanswer.com##.th-chat-header

! 5.1.2017, 07:40:14 http://www.justanswer.com/printers/69nvp-c310-printer-stopped-printing-paper-jam.html
www.justanswer.com##.th-chat-dialog

! 5.1.2017, 07:40:25 http://www.justanswer.com/printers/69nvp-c310-printer-stopped-printing-paper-jam.html
www.justanswer.com##.th-chat-question-box

! 5.1.2017, 07:40:33 http://www.justanswer.com/printers/69nvp-c310-printer-stopped-printing-paper-jam.html
www.justanswer.com##.background

! 6.1.2017, 18:44:14 http://rtlnext.rtl.de/cms/aldi-thermomix-klon-ambiano-kuechenmaschine-mit-kochfunktion-wieder-da-4026229.html
rtlnext.rtl.de##.sticky.rtlnext-next-layer:nth-of-type(2)

! 6.1.2017, 18:44:24 http://rtlnext.rtl.de/cms/aldi-thermomix-klon-ambiano-kuechenmaschine-mit-kochfunktion-wieder-da-4026229.html
rtlnext.rtl.de##.sticky.rtlnext-next-layer:nth-of-type(1)

! 6.1.2017, 18:44:39 http://rtlnext.rtl.de/cms/aldi-thermomix-klon-ambiano-kuechenmaschine-mit-kochfunktion-wieder-da-4026229.html
rtlnext.rtl.de###header

! 9.1.2017, 16:45:09 http://www.justanswer.co.uk/electronics/80g1g-printer-esp-c310-showing-error-3523-paper-jam.html
www.justanswer.co.uk##.th-chat-header

! 9.1.2017, 16:45:18 http://www.justanswer.co.uk/electronics/80g1g-printer-esp-c310-showing-error-3523-paper-jam.html
www.justanswer.co.uk##.background

! 9.1.2017, 16:45:28 http://www.justanswer.co.uk/electronics/80g1g-printer-esp-c310-showing-error-3523-paper-jam.html
www.justanswer.co.uk##.th-chat-dialog

! 9.1.2017, 16:45:36 http://www.justanswer.co.uk/electronics/80g1g-printer-esp-c310-showing-error-3523-paper-jam.html
www.justanswer.co.uk##.th-chat-question-box

! 9.1.2017, 16:52:05 http://www.fixya.com/support/t1619831-paper_jam_in_kodak_esp_printer
www.fixya.com###locked-footer-ad-wrapper

! 1.2.2017, 11:30:36 http://www.theverge.com/2017/1/25/14371450/indus-valley-civilization-ancient-seals-symbols-language-algorithms-ai
www.theverge.com##.tab-bar-fixed.c-tab-bar

! 11.2.2017, 05:07:17 http://www.universetoday.com/133348/time-build-venus-rover/
www.universetoday.com###mainmenu

! 11.2.2017, 05:07:44 http://www.universetoday.com/133348/time-build-venus-rover/
www.universetoday.com##.navbar-fixed-top.navbar-inverse.navbar

! 29.3.2017, 18:47:54 https://www.welt.de/politik/deutschland/article163240385/Erdogan-riskiert-einen-Buergerkrieg-in-Deutschland.html
www.welt.de##.c-sticky-video__body--is-fixed.c-sticky-video__body

! 9.4.2017, 23:44:18 https://electrek.co/2017/04/09/tesla-solar-panel-panasonic/
electrek.co##.scroll-to-fixed-fixed.header-wrap

! 9.4.2017, 23:44:27 https://electrek.co/2017/04/09/tesla-solar-panel-panasonic/
electrek.co##.scroll-to-fixed-fixed.news-feed-header

! 21.4.2017, 03:02:05 http://www.daytondailynews.com/business/growing-firm-lands-work-with-spacex/xKWul5vJh99TdELxfkFKUO/
www.daytondailynews.com##.hidden-md-down.sub-header-nav

! 21.4.2017, 03:04:03 http://www.daytondailynews.com/business/growing-firm-lands-work-with-spacex/xKWul5vJh99TdELxfkFKUO/
www.daytondailynews.com##.hidden-md-down.sub-header-nav

! 20.6.2017, 22:20:02 https://www.wired.com/story/this-dark-matter-theory-could-solve-a-celestial-conundrum/
www.wired.com###logo-bar

! 24.6.2017, 02:45:29 http://www.businessinsider.com/spacex-reusable-rocket-launch-costs-profits-2017-6?r=US&IR=T&IR=T
www.businessinsider.com##.condensed.masthead

! 25.6.2017, 13:26:08 http://www.planetary.org/blogs/guest-blogs/2017/20170623-starshade-helping-space-telescopes.html
www.planetary.org##.scrolledmenu.topheader

! 29.6.2017, 04:07:11 https://www.inverse.com/article/33532-dimensions-gravity-waves-physics
www.inverse.com##.app-header.consumer-header

! 8.7.2017, 01:16:44 http://www.huffingtonpost.com/entry/npr-declaration-of-independence_us_595c6525e4b0da2c7325bd50?ncid=inblnkushpmg00000009
www.huffingtonpost.com##.nav-sticky--b-page.nav-sticky.js-nav-sticky.bn-nav-sticky

! 8.7.2017, 01:27:11 https://www.aol.com/article/news/2017/07/05/trump-supporters-mistake-npr-tweeting-declaration-independence-calling-for-revolution/23017129/
www.aol.com##.zip-not-set.btest-accessible-test-2-g-article.light-weather-form.m-side-nav.l-side-nav

! 8.7.2017, 01:27:23 https://www.aol.com/article/news/2017/07/05/trump-supporters-mistake-npr-tweeting-declaration-independence-calling-for-revolution/23017129/
www.aol.com##.m-navbar--hasSubnav.m-navbar--hasLogo.m-navbar.l-navbar--fixed.l-navbar

! 8.7.2017, 02:59:23 https://3dprint.com/53642/solder-paste-extruder/
3dprint.com###main-header

! 8.7.2017, 02:59:37 https://3dprint.com/53642/solder-paste-extruder/
3dprint.com###top-header

! 9.7.2017, 17:03:13 http://www.sueddeutsche.de/politik/protestforscher-ueber-g-chaos-die-strategie-der-polizei-ist-kolossal-gescheitert-1.3579457?utm_content=bufferb7b13&utm_medium=social&utm_source=twitter.com&utm_campaign=buffer
www.sueddeutsche.de###header-navigation

**Comment by yourduskquibbles** [comment]
Thank you, I will test and add these in.

**Comment by yourduskquibbles** [comment]
Closed via [8e08715ce576750a353415853cfceb311c06414e](https://github.com/yourduskquibbles/webannoyances/commit/8e08715ce576750a353415853cfceb311c06414e)
