### ISSUE TITLE
artstation.com/ericgeusz

### ISSUE THREAD

**Issue by KonoromiHimaries** [yourduskquibbles/webannoyances#106]
![2018-11-23-window](https://user-images.githubusercontent.com/5884000/48955114-a46d9c80-ef4c-11e8-9fc2-6c892da9030c.png)

**Comment by krystian3w** [comment]
`artstation.com##.navbar-artist-user, .navbar-artist-profile.stuck:style(position: static !important;)`

**Comment by krystian3w** [comment]
`artstation.com##.fixed-main-nav:style(padding-top: 0 !important;)`
