### ISSUE TITLE
postimg.cc

### ISSUE THREAD

**Issue by KonoromiHimaries** [yourduskquibbles/webannoyances#110]
### URL(s) where the issue occurs

`https://postimg.cc/2L5PVS42`

### Describe the issue

share it button do not work

### Versions

- Browser/version: latest, stable
- uBlock Origin version: latest, stable

**Comment by yourduskquibbles** [comment]
Thanks.

Just FYI - I hate share elements (they're normally social media spam sites trying to take over a site and interrupt content) but this one is more useful since it provides the URL shortcuts and markdown so made an exception filter for it.
