### ISSUE TITLE
Reddit 2 Scrolls

### ISSUE THREAD

**Issue by ArmynC** [yourduskquibbles/webannoyances#117]
### URL(s) where the issue occurs

`https://www.reddit.com/r/uBlockOrigin/comments/a147uc/psa_if_youre_using_opera_and_wondering_why_the/`

### Describe the issue

I think that Web Annoyances Ultralist - Modal Overlay Filters is adding another scroll bar to the reddit posts.

### Screenshot(s)
![2_scrolls](https://user-images.githubusercontent.com/16375271/50528354-81f41380-0af6-11e9-9c1c-df9680c3fbee.png)

### Versions

- Browser/version: Version 72.0.3626.28 (Official Build) beta (64-bit)
- uBlock Origin version: 1.17.4

### Settings

https://arminc.tk/uBlock0%20%E2%96%B6%20Settings%20(with%20Filters)/ArminC_uBlock0_Settings.txt

### Notes

Disabling that filter and refreshing the reddit tab, makes the second scroll disappear.

**Comment by yourduskquibbles** [comment]
@ArmynC Thanks for the additional details. I was able to finally reproduce your issue not by going directly to your link but by navigating to a topic via the subreddit post listing, e.g. by clicking on a topic via [this link](https://www.reddit.com/r/uBlockOrigin/). Direct link to a reddit post apparently loads differently than just clicking on a post through the subreddit listing of posts on the new reddit redesign.


Does adding the following filter to 'My Filters' fix the issue for you? 

`www.reddit.com#@#body:style(overflow-x: hidden !important; overflow-y: scroll !important;)`

**Comment by ArmynC** [comment]
From a short test it solve the bug.

**Comment by yourduskquibbles** [comment]
Thanks I will remove the overflow filter from the modal list for now. 

I have tested a bit and don't believe reddit is serving a modal that takes away the scrollbar currently so I don't believe the filter is currently needed.
