### ISSUE TITLE
mixcloud.com

### ISSUE THREAD

**Issue by KonoromiHimaries** [yourduskquibbles/webannoyances#118]
### Describe the issue

https://github.com/uBlockOrigin/uAssets/issues/4554

popup if i try to close this card

### Screenshot(s)

![2019-01-06-window](https://user-images.githubusercontent.com/5884000/50735893-e463a880-11b5-11e9-93b8-89aa38ee090a.png)

sugested rule
`mixcloud.com##+js(addEventListener-defuser.js, beforeunload)`

### Details

- Browser/version: latest, stable
- uBlock Origin version: latest, stable

https://gist.github.com/KonoromiHimaries/9bc55fcafd3fab612f1f8dfa59f8f572

**Comment by yourduskquibbles** [comment]
@KonoromiHimaries Sorry never saw this before you closed it, I just added the filter.
