### ISSUE TITLE
another list of sites

### ISSUE THREAD

**Issue by elypter** [yourduskquibbles/webannoyances#12]
! 17.1.2018, 17:02:51 https://www.jetbrains.com/youtrack/
www.jetbrains.com##._fixed.header-secondary.js-header-secondary > .g-container

! 17.1.2018, 17:02:58 https://www.jetbrains.com/youtrack/
www.jetbrains.com##._fixed.header-secondary.js-header-secondary

! 21.1.2018, 16:59:59 https://www.netzwelt.de/news/148824-freemail-serverliste-pop-imap-adressen.html
www.netzwelt.de##.nav-filler

! 21.1.2018, 17:00:08 https://www.netzwelt.de/news/148824-freemail-serverliste-pop-imap-adressen.html
www.netzwelt.de###main-menu > .menu

! 21.1.2018, 17:00:13 https://www.netzwelt.de/news/148824-freemail-serverliste-pop-imap-adressen.html
www.netzwelt.de###topnav

! 23.1.2018, 12:16:31 https://mailfence.com/
mailfence.com##form

! 23.1.2018, 12:16:41 https://mailfence.com/
mailfence.com###header > .container

! 23.1.2018, 12:16:48 https://mailfence.com/
mailfence.com###header

! 27.1.2018, 12:48:54 https://www.linuxboot.org/
www.linuxboot.org##.navbar-custom.navbar-fixed-top.navbar-default.navbar

! 29.1.2018, 20:51:30 https://www.vrnerds.de/kickstarterkampagne-fuer-pimax-8-k-5-k-vr-brillen-veroeffentlicht/
www.vrnerds.de##.all-services

! 30.1.2018, 18:32:45 https://pineapplefund.org/
pineapplefund.org###mainNav

! 31.1.2018, 15:09:05 https://sourceforge.net/projects/startup-manager/
sourceforge.net##.l-header-nav-collapse.sandiego.sticky.l-header-nav

! 31.1.2018, 16:56:08 https://www.ixquick.com/do/search
||www.ixquick.com/graphics/air-theme-header-bg-right.png$image

! 31.1.2018, 16:56:18 https://www.ixquick.com/do/search
www.ixquick.com##.navbar-header

! 31.1.2018, 16:56:26 https://www.ixquick.com/do/search
www.ixquick.com##.stick-header.navbar-default.navbar

! 31.1.2018, 16:56:39 https://www.ixquick.com/do/search
www.ixquick.com##.inner-pages.settings_cont

! 31.1.2018, 18:34:38 https://apkcreative.com/apk/com.arjavgupta.ugandanknucklesmemesoundboard/
apkcreative.com##.zik-header-container

! 31.1.2018, 19:06:14 https://wize.life/themen/kategorie/politik/artikel/43033/komiker-boehmermann-laestert-ueber-nazi-opa-der-afd-sirene-beatrix-von-storch
wize.life##.noprint.headerWrapper > header

! 31.1.2018, 19:06:22 https://wize.life/themen/kategorie/politik/artikel/43033/komiker-boehmermann-laestert-ueber-nazi-opa-der-afd-sirene-beatrix-von-storch
wize.life##nav

! 31.1.2018, 21:18:40 http://forum.pimaxvr.com/t/support-for-linux/298
forum.pimaxvr.com##.clearfix.d-header

! 31.1.2018, 22:10:01 https://www.cio.com/article/3145960/virtual-reality/6-reasons-to-buy-sony-playstation-vr-over-oculus-and-htc-vive.html
www.cio.com###sticky-head

! 31.1.2018, 22:33:40 http://www.gamona.de/
www.gamona.de##.fixed.navi

! 31.1.2018, 22:50:23 http://www.instructables.com/id/The-NovaA-DIY-Oculus-Rift/
www.instructables.com##.affix.sticky-header

! 31.1.2018, 23:01:16 http://www.messynessychic.com/2013/01/29/the-fake-townhouses-hiding-mystery-underground-portals/
www.messynessychic.com###sticky-menu

! 1.2.2018, 03:16:49 http://www.maxconsole.com/threads/playstation-vr-hacking-psvr-on-pc-an-step-by-step-guide-tutorial.43808/
www.maxconsole.com##.navTabs

! 1.2.2018, 14:21:16 https://matrix.org/blog/2018/01/29/status-partners-up-with-new-vector-fueling-decentralised-comms-and-the-matrix-ecosystem/
matrix.org###main-header

! 3.2.2018, 21:59:39 https://forums.hololens.com/discussion/8146/openvr-support-for-microsoft-headsets
forums.hololens.com##.scroll-to-fixed-fixed.navbar

! 3.2.2018, 22:00:06 https://vr-world.com/direct-reality-windows-mr-soll-alle-vr-brillen-unterstuetzen/
vr-world.com###gp-sub-header

! 12.2.2018, 03:09:32 https://forums.ubports.com/topic/973/unity8-for-desktop/2
forums.ubports.com###header-menu

! 13.2.2018, 01:23:32 https://hackernoon.com/chroot-the-magical-healing-powers-of-the-original-linux-virtualization-tool-9aa4c3928711
hackernoon.com##.u-tintSpectrum.u-tintBgColor.u-xs-sizeFullViewportWidth.u-backgroundTransparentWhiteDarkest.u-fixed.u-textColorDarker.js-metabar.u-clearfix.metabar

---------------------------------------------------
more older sites from ublock in another browser following
---------------------------------------------------

! 22.10.2017, 20:59:07 https://fossbytes.com/windows-mixed-reality-headset/
fossbytes.com##.td-affix.td-header-main-menu.td-header-row

! 23.10.2017, 04:10:46 https://bios-pw.org/
bios-pw.org##.fill

! 23.10.2017, 08:10:00 http://blog.puppylinux.com/?viewDetailed=00028
blog.puppylinux.com###header

! 23.10.2017, 08:11:03 http://slacko.eezy.xyz/notes.php
slacko.eezy.xyz###stuff0

! 23.10.2017, 08:11:12 http://slacko.eezy.xyz/notes.php
slacko.eezy.xyz##header

! 24.10.2017, 05:28:23 https://www.computerwoche.de/a/python-lernen-leicht-gemacht,3331244,2
www.computerwoche.de##.inner

! 24.10.2017, 05:28:36 https://www.computerwoche.de/a/python-lernen-leicht-gemacht,3331244,2
www.computerwoche.de###lepBanner

! 24.10.2017, 05:30:47 http://noeticforce.com/best-python-ide-for-programmers-windows-and-mac
noeticforce.com###header-top

! 24.10.2017, 05:36:18 http://www.jetbrains.com/pycharm/
www.jetbrains.com##._fixed.header-secondary.js-header-secondary

! 24.10.2017, 06:47:14 https://gracefo.jpl.nasa.gov/mission/overview/
gracefo.jpl.nasa.gov##.site_nav

! 24.10.2017, 06:48:40 https://gracefo.jpl.nasa.gov/mission/overview/
gracefo.jpl.nasa.gov##.site_header_area

! 24.10.2017, 07:53:01 https://www.endthebackdoor.com/
www.endthebackdoor.com##.top-nav-collapse.navbar-fixed-top.navbar-custom.navbar > .container

! 24.10.2017, 07:53:11 https://www.endthebackdoor.com/
www.endthebackdoor.com##.top-nav-collapse.navbar-fixed-top.navbar-custom.navbar

! 25.10.2017, 06:22:43 http://usb.userbenchmark.com/
usb.userbenchmark.com###navForm

! 25.10.2017, 06:23:24 http://usb.userbenchmark.com/
usb.userbenchmark.com##.categoryStickyHeaderWrapper

! 25.10.2017, 06:27:54 https://thewirecutter.com/reviews/the-best-usb-3-0-thumb-drive/
thewirecutter.com##.active.hok-container > .main-row

! 27.10.2017, 23:53:57 https://www.spaceintelreport.com/ses-tells-satellite-builders-prepare-total-rethink-business/
www.spaceintelreport.com###main-header

! 27.10.2017, 23:54:07 https://www.spaceintelreport.com/ses-tells-satellite-builders-prepare-total-rethink-business/
www.spaceintelreport.com###top-header

! 30.10.2017, 02:07:11 https://www.reddit.com/r/PoliticalHumor/comments/79grd6/im_sure_trumps_administration_wont_add_to_this/?depth=99
www.reddit.com###header

! 30.10.2017, 02:31:32 https://research.adobe.com/project/scribbler-controlling-deep-image-synthesis-with-sketch-and-color/
research.adobe.com###header

! 30.10.2017, 06:01:33 http://www.pcgameshardware.de/Virtual-Reality-Hardware-258542/News/Windows-Mixed-Reality-Systemanforderungen-SteamVR-Vorbestellungen-1240358/
www.pcgameshardware.de##.header1 > .headerInner

! 30.10.2017, 10:25:17 https://www.motor-talk.de/forum/tuev-zwei-unterschiedliche-reifen-auf-einer-achse-erlaubt-t1870856.html
www.motor-talk.de###StickyHeader

! 30.10.2017, 11:08:32 http://www.focus.de/auto/ratgeber/kosten/worauf-pruefer-bei-der-hu-besonders-achten-das-sollten-sie-vor-dem-tuev-termin-selbst-checken_id_3872240.html
www.focus.de##.ressort-wrapper

! 30.10.2017, 11:11:42 https://www.tuev-sued.de/hauptuntersuchung/3-richtig-vorbereiten
www.tuev-sued.de##.navbar-fixed-top.navbar-default.navbar

! 30.10.2017, 12:36:30 https://www.ebay.de/fdbk/leave_feedback?
www.ebay.de###wc0

! 30.10.2017, 13:09:45 https://wasserhelden.net/unser-trinkwasser/lokale-auskuenfte/erlangen/
wasserhelden.net##.main-menu-wrap

! 30.10.2017, 17:10:42 https://savvytime.com/converter/utc-to-mez
savvytime.com##.no-padding.header-shadow.header

! 30.10.2017, 17:11:13 https://savvytime.com/converter/utc-to-mez
savvytime.com##.navbar-fixed-top.sub-nav

! 1.11.2017, 07:45:28 https://research.csiro.au/tsblog/sel4-raspberry-pi-3/
research.csiro.au##.sticky.hidden-print.flex--v-center.navbar--action.navbar--sticky

! 1.11.2017, 16:04:48 https://bmcbiol.biomedcentral.com/articles/10.1186/s12915-017-0352-z
bmcbiol.biomedcentral.com###ArticleNavigation

! 3.11.2017, 21:06:04 https://www.watchbox.de/serien/rage-of-bahamut-12261/staffel-1/begegnung-in-wytearp-331702.html
www.watchbox.de##.header_shrink.header_shrink_for_video.js-header.header

! 4.11.2017, 10:49:47 http://www.theitstuff.com/laptops-vs-desktops-final-answer
www.theitstuff.com##.visible.menu-wrap

! 5.11.2017, 04:36:24 https://otakustream.tv/anime/mahoujin-guru-guru-2017/
otakustream.tv##.top-header

! 5.11.2017, 04:36:40 https://otakustream.tv/anime/mahoujin-guru-guru-2017/
otakustream.tv##.menu-top

! 5.11.2017, 19:52:03 http://ofthebox.org/wifi-experiment-done-group-9th-grade-students-got-serious-international-attention/
ofthebox.org##.nav-in

! 5.11.2017, 19:52:12 http://ofthebox.org/wifi-experiment-done-group-9th-grade-students-got-serious-international-attention/
ofthebox.org###main-nav-wrap

! 7.11.2017, 05:19:14 http://www.nebelung.de/wissenswertes/kulturprobleme-schaedlinge/probleme-kulturpflanzen/kopfkohl/
www.nebelung.de###top-header

! 7.11.2017, 05:19:26 http://www.nebelung.de/wissenswertes/kulturprobleme-schaedlinge/probleme-kulturpflanzen/kopfkohl/
www.nebelung.de###main-header

! 7.11.2017, 19:39:55 https://www.smartdraw.com/floor-plan/floor-plan-designer.htm
www.smartdraw.com##.siteNavRow.row-fluid

! 7.11.2017, 19:40:02 https://www.smartdraw.com/floor-plan/floor-plan-designer.htm
www.smartdraw.com##.grayTopBar.navbar > .navbar-inner > .grayNav.nav

! 7.11.2017, 19:47:54 http://praxistipps.chip.de/grundriss-zeichnen-mit-dieser-freeware-gelingts_12422
praxistipps.chip.de##.Header--Sticky.Header

! 7.11.2017, 21:31:47 http://praxistipps.chip.de/grundriss-zeichnen-mit-dieser-freeware-gelingts_12422
praxistipps.chip.de##.Header--Sticky.Header

! 11.11.2017, 16:28:33 https://whatcoulditmeme.com/elon-musk-digital-age-snake-oil-salesman/
whatcoulditmeme.com##.floating-active.floating-header

! 13.11.2017, 08:19:50 https://rictusempra.github.io/uMatrix-Rules/
rictusempra.github.io##header

! 13.11.2017, 08:20:04 https://rictusempra.github.io/uMatrix-Rules/
rictusempra.github.io###banner

! 14.11.2017, 12:04:25 http://www.climatechangenews.com/2017/11/13/trumps-climate-official-i-actually-dont-know-2c-means/
www.climatechangenews.com###subscribe

! 14.11.2017, 12:04:33 http://www.climatechangenews.com/2017/11/13/trumps-climate-official-i-actually-dont-know-2c-means/
www.climatechangenews.com##.in.fade.modal-backdrop

! 17.11.2017, 11:09:06 https://about.gitlab.com/2017/11/01/gitlab-switches-to-dco-license/
about.gitlab.com##.navbar-default

! 17.11.2017, 11:10:43 https://about.gitlab.com/2017/11/01/gitlab-switches-to-dco-license/
about.gitlab.com##.sticky-banner

! 20.11.2017, 10:27:48 https://haydenjames.io/best-linux-distro/
haydenjames.io##.primary-navigation

! 23.11.2017, 10:02:24 https://www.f169bbs.com/bbs/news/517236-nude-photo-rep-goes-viral-social-media-gross-barton-poster-boy-term-limits
www.f169bbs.com###topbox

! 24.11.2017, 13:05:14 https://discourse.mozilla.org/t/support-umatrix/5131
discourse.mozilla.org##.d-header

! 8.12.2017, 17:48:51 https://microg.org/
microg.org##.navbar-fixed-top.navbar-default.navbar

! 8.12.2017, 20:48:34 https://www.chromebeat.com/ext/zapfixed/jgiflpbkoefoepgmeifoglafkomgjbge
www.chromebeat.com##.cloudHeader

**Comment by yourduskquibbles** [comment]
thanks!
