### ISSUE TITLE
picodi.com

### ISSUE THREAD

**Issue by krystian3w** [yourduskquibbles/webannoyances#121]
### URL(s) where the issue occurs

`https://www.picodi.com/uk/`

### Describe the issue

title modificator after change opened tab or clicked outside of the page:

<table><tr><td>

```html
<title>
Voucher Codes, 
Offers and Deals 
for the UK online stores
 - Picodi United Kingdom
</title>
````

</td><td>

:repeat: 

</td><td>

```html
<title>

Back to Picodi


</title>
```

</td></tr></table>

### Screenshot(s)

N/A

### Versions

- Browser/version: Firefox 65
- uBlock Origin version: uBO 1.18.4

### Settings

- Web Annoyances Ultralist

### Notes

Possible safe disable this?

**Comment by yourduskquibbles** [comment]
I will look into it, but my guess is that it will require a javascript injection `+js(abort-on-property-read.js foo)` filter so thinking [uAssets](https://github.com/uBlockOrigin/uAssets) may be the right place to ask for this since I don't really focus on those with my list.

**Comment by yourduskquibbles** [comment]
Related [uAssets](https://github.com/uBlockOrigin/uAssets/issues/4869) issue

Will add the suggested filter to Web Annoyances Ultralist `picodi.com##+js(abort-on-property-write.js, titleBack)` if they don't want to add to uBO Annoyances List

**Comment by krystian3w** [comment]
Still break website.

**Comment by krystian3w** [comment]
This should works better: `picodi.com##+js(abort-on-property-read.js, titleBack)`

Now no block copy sale code mechanism by JavaScript.

**Comment by yourduskquibbles** [comment]
OK I'll wait to see what they do in uAssets

**Comment by yourduskquibbles** [comment]
@krystian3w do you want me to add `picodi.com##+js(abort-on-property-read.js, titleBack)` since they won't add to uAssets? Does this filter have no breakage?

**Comment by krystian3w** [comment]
For my we can add, website do not have register from, "My picdodi" open only "Newsletter" pop-up.

I do not found any other breakge when I use `abort-on-property-read.js, titleBack`.

**Comment by yourduskquibbles** [comment]
Thanks, added to the main filterlist.
