### ISSUE TITLE
Misaligned header title at mnn.com

### ISSUE THREAD

**Issue by Jap2-0** [yourduskquibbles/webannoyances#122]
### URL(s) where the issue occurs

`mnn.com`

### Describe the issue

The header text is too far to the right when this list is enabled.  This also makes the page slightly wider than the screen, as the text hangs off the edge of the page.

### Screenshot(s)

Correct (all other lists I'm using enabled):
![image](https://user-images.githubusercontent.com/40511669/52819781-3a125700-3078-11e9-92db-e5ff7e9fccc8.png)

With this enabled:
![image](https://user-images.githubusercontent.com/40511669/52820264-87db8f00-3079-11e9-9f61-ed74dd12e3c9.png)

### Versions

- Browser/version: Chrome 71 (unfortunately)
- uBlock Origin version: uBO 1.18.5b0

### Settings

- A few extra filter lists, for the most part; a few other minor changes here and there, ask if you need anything more specific.

### Notes

Appears to be a side effect of `www.mnn.com##.site-header__nav:style(position: absolute !important;)`, which doesn't appear to be doing much of anything other than this.

**Comment by yourduskquibbles** [comment]
Thanks for reporting!
