### ISSUE TITLE
Nature article broken (in several ways)

### ISSUE THREAD

**Issue by Jap2-0** [yourduskquibbles/webannoyances#123]
### URL(s) where the issue occurs

`https://www.nature.com/articles/307634a0`

### Describe the issue

I'll let the screenshot speak for this one.  Two small notes on the screenshot is that the section titled "sections" scrolls once with the page, as well as the the section with "Nature" and "ISSN" (part of this is visible because I scrolled the page for the screenshot).  The rest is just the footer overlaying other elements.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/40511669/52820870-30d6b980-307b-11e9-9928-f83d2c8429bb.png)

### Versions

- Browser/version: Chrome 71 (unfortunately)
- uBlock Origin version: 1.18.5b1

### Settings

- A few extra filter lists, for the most part; a few other minor changes here and there, ask if you need anything more specific.

### Notes

Nothing yet, I'll let you know if I find anything (but what I'm seeing just looks like a complete mess).
Edit: I may be getting somewhere, I'll let you know within a couple minutes.

**Comment by Jap2-0** [comment]
Okay, the major issue is a result of `www.nature.com##.inner-banner, .main-column:style(block-size: 80px !important;)`.  The right column still isn't quite static, but that's not a huge issue compared to the article being legible.

**Comment by yourduskquibbles** [comment]
>  The right column still isn't quite static, but that's not a huge issue compared to the article being legible.

Agree 100% with that, article I must have used to create that filter must have been based on a longer article so the breakage wasn't apparent.

Thanks for reporting and investigating cause of the issue.

**Comment by yourduskquibbles** [comment]
@Jap2-0 I think if I add this filter `nature.com##[data-component^="reading-companion-sticky"]:style(margin-top: 0 !important;)` it should also fix the right column jumpiness issue. Will test on a few other articles to make sure I'm not inadvertently breaking anything else though.
