### ISSUE TITLE
List disappeared/removed from uBlock

### ISSUE THREAD

**Issue by prech** [yourduskquibbles/webannoyances#125]
Noticed this filter list disappeared from my uBlock Origins filter lists a few days ago during the Chrome 72 update. Really enjoy the list, and noticed lots of floating banners had mysteriously returned, so I went to dig around my UO settings, where I discovered this filter list was gone completely, not even disabled, or a "network error".

I tried re-installing via the one click method, as well as manually adding with the githubusercontent.com link, but neither were accepted. 

I noticed both alternate static links work well, however!

Just a minor issue, but if there could be some digging around to see why this occurred to avoid the list disappearing on its own, I'd really appreciate it :-) If it was just an issue with the githubusercontent.com host, I'm surprised UO would just remove it altogether, rather than show a temporary inability to connect...

**Comment by yourduskquibbles** [comment]
Interesting, I'm not sure what would cause that to be honest. Were all your other extensions and uBO filter lists migrated over properly?

**Comment by yourduskquibbles** [comment]
Any chance the Custom filter list got unselected and the list view was collapsed?

See example gif below:
![hiddenlist](https://user-images.githubusercontent.com/22258847/52968011-f706fb00-3379-11e9-9319-f81de8af171a.gif)

**Comment by prech** [comment]
> Interesting, I'm not sure what would cause that to be honest. Were all your other extensions and uBO filter lists migrated over properly?

Thanks for responding and the uncollapsed view GIF. 

It looks like my other filter lists (just the three associated with Nano Defender) were not affected, nor "My filters" or my whitelist. I just tried to reproduce the list add/subscription and, unfortunately, it's the same misbehavior, neither one click method nor manual githubusercontent.com link worked in my Chrome Version 72.0.3626.109. But both static links work.

I also have Chrome dev channel installed, so gave that a try. Interestingly, both the one click method and manual githubusercontent.com link worked. This is Chrome Version 74.0.3702.0

As another test, I added another githubusercontent.com filter list, [this hosts filter](https://github.com/StevenBlack/hosts), and uBlock added it without issue.

Not sure if it's Chrome 72 or something else misbehaving.

**Comment by yourduskquibbles** [comment]
Very weird behavior, I can't reproduce in Chrome Version 72.0.3626.109 but will leave the issue open for awhile in case others experience the same issue.

One last thought, Is there any error or blocked content being reported by your logger under the 'All' view when you try to add the list in Chrome Version 72.0.3626.109? The only other thing I can think of is a filter list blocking this repository for some reason with a network filter.

**Comment by prech** [comment]
Thanks for your help.

> One last thought, Is there any error or blocked content being reported by your logger under the 'All' view when you try to add the list in Chrome Version 72.0.3626.109? The only other thing I can think of is a filter list blocking this repository for some reason with a network filter.

I removed the filter from my list and just tried re-adding with the logger on.

I first tried the one click subscribe method, then manual githubusercontent.com link via the Wiki page. Per previously, neither succeeded. Then, I added the list via the staticaly.com address.

Please find the full log below, and as [a screen shot](https://i.imgur.com/l2c79Kc.jpg):

<details><summary>Logger output</summary>

| | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +298 |  |  | cjpalhdlnbpafiamejdnhcphjbkeiagm.chrome-extension-scheme | 0,3 | xhr | `https://cdn.staticaly.com/gh/yourduskquibbles/webannoyances/master/filters/social_filters.txt?_=215361` |
| +298 |  |  | cjpalhdlnbpafiamejdnhcphjbkeiagm.chrome-extension-scheme | 0,3 | xhr | `https://cdn.staticaly.com/gh/yourduskquibbles/webannoyances/master/filters/newsletter_filters.txt?_=215361` |
| +298 |  |  | cjpalhdlnbpafiamejdnhcphjbkeiagm.chrome-extension-scheme | 0,3 | xhr | `https://cdn.staticaly.com/gh/yourduskquibbles/webannoyances/master/filters/modal_filters.txt?_=215361` |
| +298 |  |  | cjpalhdlnbpafiamejdnhcphjbkeiagm.chrome-extension-scheme | 0,3 | xhr | `https://cdn.staticaly.com/gh/yourduskquibbles/webannoyances/master/filters/generic_filters.txt?_=215361` |
| +298 |  |  | cjpalhdlnbpafiamejdnhcphjbkeiagm.chrome-extension-scheme | 0,3 | xhr | `https://cdn.staticaly.com/gh/yourduskquibbles/webannoyances/master/filters/css_style_filters.txt?_=215361` |
| +297 |  |  | cjpalhdlnbpafiamejdnhcphjbkeiagm.chrome-extension-scheme | 0,3 | xhr | `https://cdn.staticaly.com/gh/yourduskquibbles/webannoyances/master/ultralist.txt?_=215361` |
| +108 | \|\|github.com/_private/browser/stats | -- | github.com | 1 | beacon | `https://api.github.com/_private/browser/stats` |
| +108 |  |  | github.com | 1 | other | `https://github.com/manifest.json` |
| +107 | \|\|collector.githubapp.com^ | -- | github.com | 3 | image | `https://collector.githubapp.com/github/page_view?dimensions[page]=https%3A%2F%2Fgithub.com%2Fyourduskquibbles%2Fwebannoyances&dimensions[title]=yourduskquibbles%2Fwebannoyances%3A%20Fix%20and%20remove%20annoying%20web%20elements%20such%20as%20sticky%20headers%2C%20floating%20boxes%2C%20dickbars%2C%20social%20share%20bars%20and%20other%20distracting%20elements.&dimensions[referrer]=&dimensions[user_agent]=Mozilla%2F5.0%20(Windows%20NT%2010.0%3B%20Win64%3B%20x64)%20AppleWebKit%2F537.36%20(KHTML%2C%20like%20Gecko)%20Chrome%2F72.0.3626.109%20Safari%2F537.36&dimensions[screen_resolution]=1920x1080&dimensions[pixel_ratio]=1.25&dimensions[browser_resolution]=1536x742&dimensions[tz_seconds]=-28800&dimensions[timestamp]=1550606171927&dimensions[request_id]=E4C0%3A966E%3A2D21A%3A44B29%3A5C6C5EF0&dimensions[region_edge]=sea&dimensions[region_render]=iad&dimensions[user_id]=22258847&dimensions[user_login]=yourduskquibbles&dimensions[repository_id]=68458634&dimensions[repository_nwo]=yourduskquibbles%2Fwebannoyances&dimensions[repository_public]=true&dimensions[repository_is_fork]=false&dimensions[repository_network_root_id]=68458634&dimensions[repository_network_root_nwo]=yourduskquibbles%2Fwebannoyances&dimensions[repository_explore_github_marketplace_ci_cta_shown]=false&&measures[performance_timing]=1-4-4-7513-3410-3280-3273-82-4-4-4--7513-0---17-35-21--65-63&&dimensions[actor_id]=8314103&dimensions[actor_login]=prech&dimensions[actor_hash]=45488adc5684b30e595d8ddfc4aba9e23cd3c07fc0c551183b6d9b8cad2d8789&dimensions[cid]=1048755312.1510291463` |
| +105 |  |  | github.com | 1 | xhr | `https://api.github.com/_private/browser/errors` |
| +104 |  |  | github.com | 1 | websocket | wss://live.github.com/_sockets/VjI6MzY5OTQ0NzA1OjhmNGM0ZDkzOGJkZmIzYmM3NjA1YTg5ZmFiMDhjNWIyYzc3M2NhZDVjODlmYzM5ZTEzMDdiYTYxNTE3MGJlMzc=--767e5f3cf063bc6f0608a83771f117899cd41880 |
| +103 |  |  | github.com | 1 | xhr | `https://github.com/yourduskquibbles/webannoyances/show_partial?partial=tree%2Frecently_touched_branches_list` |
| +103 |  |  | github.com | 3 | image | `https://avatars2.githubusercontent.com/u/8314103?s=40&v=4` |
| +103 |  |  | github.com | 3 | image | `https://github.githubassets.com/images/spinners/octocat-spinner-128.gif` |
| +103 |  |  | github.com | 3 | image | `https://github.githubassets.com/images/search-key-slash.svg` |
| +102 |  |  | github.com | 3 | script | `https://github.githubassets.com/assets/github-baf2061180e737799047f63fb9ed115e.js` |
| +102 |  |  | github.com | 3 | image | `https://user-images.githubusercontent.com/22258847/40389548-42ecaf5e-5e02-11e8-8d16-1d7e08c805b6.PNG` |
| +102 |  |  | github.com | 3 | image | `https://user-images.githubusercontent.com/22258847/40389620-73bc68ae-5e02-11e8-94ac-30bf769bdf70.PNG` |
| +102 |  |  | github.com | 3 | image | `https://user-images.githubusercontent.com/22258847/51348138-e8be7a00-1a6f-11e9-9b0c-5fac61a83f8f.png` |
| +102 |  |  | github.com | 3 | image | `https://user-images.githubusercontent.com/22258847/51348578-16f08980-1a71-11e9-80b8-0f2ad5379bcd.png` |
| +102 |  |  | github.com | 3 | script | `https://github.githubassets.com/assets/frameworks-e7386fe0dfb42605619f7a70aed3204f.js` |
| +102 |  |  | github.com | 3 | image | `https://github.githubassets.com/images/spinners/octocat-spinner-32.gif` |
| +102 |  |  | github.com | 3 | image | `https://avatars2.githubusercontent.com/u/22258847?s=60&v=4` |
| +100 |  |  | github.com | 3 | css | `https://github.githubassets.com/assets/github-0d139b56f7fdba32feb4dfab70407a06.css` |
| +100 |  |  | github.com | 3 | css | `https://github.githubassets.com/assets/frameworks-a70126cbff30372f13f599b76353080b.css` |
| +100 |  |  | github.com | 1 | doc | `https://github.com/yourduskquibbles/webannoyances` |
| +32 | \|\|github.com/_private/browser/stats | -- | github.com | 1 | beacon | `https://api.github.com/_private/browser/stats` |
| +31 | \|\|github.com/_private/browser/stats | -- | github.com | 1 | beacon | `https://api.github.com/_private/browser/stats` |
| +31 |  |  | github.com | 1 | other | `https://github.com/manifest.json` |
| +31 | \|\|collector.githubapp.com^ | -- | github.com | 3 | image | `https://collector.githubapp.com/github/page_view?dimensions[page]=https%3A%2F%2Fgithub.com%2Fyourduskquibbles%2Fwebannoyances%2Fwiki%2FInstallation-Instructions%23install-method-2---step-by-step-installation&dimensions[title]=Installation%20Instructions%20%C2%B7%20yourduskquibbles%2Fwebannoyances%20Wiki&dimensions[referrer]=https%3A%2F%2Fgithub.com%2Fyourduskquibbles%2Fwebannoyances&dimensions[user_agent]=Mozilla%2F5.0%20(Windows%20NT%2010.0%3B%20Win64%3B%20x64)%20AppleWebKit%2F537.36%20(KHTML%2C%20like%20Gecko)%20Chrome%2F72.0.3626.109%20Safari%2F537.36&dimensions[screen_resolution]=1920x1080&dimensions[pixel_ratio]=1.25&dimensions[browser_resolution]=1536x742&dimensions[tz_seconds]=-28800&dimensions[timestamp]=1550606095704&dimensions[request_id]=E4C0%3A966E%3A2D4B8%3A44BAD%3A5C6C5EF3&dimensions[region_edge]=sea&dimensions[region_render]=iad&dimensions[user_id]=22258847&dimensions[user_login]=yourduskquibbles&dimensions[repository_id]=68458634&dimensions[repository_nwo]=yourduskquibbles%2Fwebannoyances&dimensions[repository_public]=true&dimensions[repository_is_fork]=false&dimensions[repository_network_root_id]=68458634&dimensions[repository_network_root_nwo]=yourduskquibbles%2Fwebannoyances&dimensions[repository_explore_github_marketplace_ci_cta_shown]=false&&measures[performance_timing]=1-15-15-7828-2846-2715-2710-598-15-15-15--7828-0---39-567-543--588-587&&dimensions[actor_id]=8314103&dimensions[actor_login]=prech&dimensions[actor_hash]=45488adc5684b30e595d8ddfc4aba9e23cd3c07fc0c551183b6d9b8cad2d8789&dimensions[cid]=1048755312.1510291463` |
| +28 |  |  | github.com | 1 | xhr | `https://api.github.com/_private/browser/errors` |
| +27 |  |  | github.com | 1 | websocket | wss://live.github.com/_sockets/VjI6MzY5OTQ0NzA1OmQ4ZDAyMTBkMGI1OTAwNjEzNjJmNjAyMzAyYWY3Y2I0ZTFhM2IyZGJhNmU4ZDU3NGRhZjUzZjgzOWVlNTc1YjI=--6664d4ebad1c925b0cded85b931b82fec7367b59 |
| +25 |  |  | github.com | 3 | script | `https://github.githubassets.com/assets/wiki-d986eaa4dd007a3f9a67d1f6a6c30320.js` |
| +25 |  |  | github.com | 3 | script | `https://github.githubassets.com/assets/github-baf2061180e737799047f63fb9ed115e.js` |
| +25 |  |  | github.com | 3 | image | `https://user-images.githubusercontent.com/22258847/39935902-25add6be-553a-11e8-82b0-badc73f44ed3.gif` |
| +25 |  |  | github.com | 3 | script | `https://github.githubassets.com/assets/frameworks-e7386fe0dfb42605619f7a70aed3204f.js` |
| +25 |  |  | github.com | 3 | image | `https://user-images.githubusercontent.com/22258847/39938114-5dc5cf00-5541-11e8-996d-5d583611f76f.png` |
| +25 |  |  | github.com | 3 | image | `https://user-images.githubusercontent.com/22258847/39936895-7ca7a8fc-553d-11e8-9496-45a96b623614.png` |
| +24 |  |  | github.com | 3 | css | `https://github.githubassets.com/assets/github-0d139b56f7fdba32feb4dfab70407a06.css` |
| +24 |  |  | github.com | 3 | css | `https://github.githubassets.com/assets/frameworks-a70126cbff30372f13f599b76353080b.css` |
| +23 |  |  | github.com | 1 | doc | `https://github.com/yourduskquibbles/webannoyances/wiki/Installation-Instructions#install-method-2---step-by-step-installation` |
| +5 | \|\|github.com/_private/browser/stats | -- | github.com | 1 | beacon | `https://api.github.com/_private/browser/stats` |
| +5 | \|\|github.com/_private/browser/stats | -- | github.com | 1 | beacon | `https://api.github.com/_private/browser/stats` |
| +4 |  |  | github.com | 3 | image | `https://github.githubassets.com/favicon.ico` |
| +4 |  |  | github.com | 1 | other | `https://github.com/manifest.json` |
| +4 |  |  | github.com | 1 | xhr | `https://api.github.com/_private/browser/errors` |
| +4 | \|\|collector.githubapp.com^ | -- | github.com | 3 | image | `https://collector.githubapp.com/github/page_view?dimensions[page]=https%3A%2F%2Fgithub.com%2Fyourduskquibbles%2Fwebannoyances&dimensions[title]=yourduskquibbles%2Fwebannoyances%3A%20Fix%20and%20remove%20annoying%20web%20elements%20such%20as%20sticky%20headers%2C%20floating%20boxes%2C%20dickbars%2C%20social%20share%20bars%20and%20other%20distracting%20elements.&dimensions[referrer]=&dimensions[user_agent]=Mozilla%2F5.0%20(Windows%20NT%2010.0%3B%20Win64%3B%20x64)%20AppleWebKit%2F537.36%20(KHTML%2C%20like%20Gecko)%20Chrome%2F72.0.3626.109%20Safari%2F537.36&dimensions[screen_resolution]=1920x1080&dimensions[pixel_ratio]=1.25&dimensions[browser_resolution]=1536x742&dimensions[tz_seconds]=-28800&dimensions[timestamp]=1550606068473&dimensions[request_id]=E4C0%3A966E%3A2D21A%3A44B29%3A5C6C5EF0&dimensions[region_edge]=sea&dimensions[region_render]=iad&dimensions[user_id]=22258847&dimensions[user_login]=yourduskquibbles&dimensions[repository_id]=68458634&dimensions[repository_nwo]=yourduskquibbles%2Fwebannoyances&dimensions[repository_public]=true&dimensions[repository_is_fork]=false&dimensions[repository_network_root_id]=68458634&dimensions[repository_network_root_nwo]=yourduskquibbles%2Fwebannoyances&dimensions[repository_explore_github_marketplace_ci_cta_shown]=false&&measures[performance_timing]=1-115-40-4012-2811-2639-2639-566-40-22-6--4012-0---115-557-525-73-553-552&&dimensions[actor_id]=8314103&dimensions[actor_login]=prech&dimensions[actor_hash]=45488adc5684b30e595d8ddfc4aba9e23cd3c07fc0c551183b6d9b8cad2d8789&dimensions[cid]=1048755312.1510291463` |
| +3 |  |  | github.com | 1 | websocket | wss://live.github.com/_sockets/VjI6MzY5OTQ0NzA1OjhmNGM0ZDkzOGJkZmIzYmM3NjA1YTg5ZmFiMDhjNWIyYzc3M2NhZDVjODlmYzM5ZTEzMDdiYTYxNTE3MGJlMzc=--767e5f3cf063bc6f0608a83771f117899cd41880 |
| +3 |  |  | github.com | 1 | xhr | `https://github.com/yourduskquibbles/webannoyances/show_partial?partial=tree%2Frecently_touched_branches_list` |
| +2 |  |  | github.com | 3 | script | `https://github.githubassets.com/assets/github-baf2061180e737799047f63fb9ed115e.js` |
| +2 |  |  | github.com | 3 | image | `https://user-images.githubusercontent.com/22258847/40389620-73bc68ae-5e02-11e8-94ac-30bf769bdf70.PNG` |
| +2 |  |  | github.com | 3 | script | `https://github.githubassets.com/assets/frameworks-e7386fe0dfb42605619f7a70aed3204f.js` |
| +2 |  |  | github.com | 3 | image | `https://avatars2.githubusercontent.com/u/22258847?s=60&v=4` |
| +1 |  |  | github.com | 3 | image | `https://avatars2.githubusercontent.com/u/8314103?s=40&v=4` |
| +1 |  |  | github.com | 3 | css | `https://github.githubassets.com/assets/github-0d139b56f7fdba32feb4dfab70407a06.css` |
| +1 |  |  | github.com | 3 | css | `https://github.githubassets.com/assets/frameworks-a70126cbff30372f13f599b76353080b.css` |
| +0 |  |  | github.com | 1 | doc | `https://github.com/yourduskquibbles/webannoyances` |
</details>

**Comment by yourduskquibbles** [comment]
It's weird I don't see anything in the logger that would be blocking the request to the githubusercontent.com host, pretty stumped on this one. 

I'm glad the mirror link at least worked!
