### ISSUE TITLE
Google Docs

### ISSUE THREAD

**Issue by Jap2-0** [yourduskquibbles/webannoyances#126]
I didn't really want to bother filling all of this out, I believe I have the filter issue figured out (see bottom).

### URL(s) where the issue occurs

Any Google doc with multiple pages (I don't have any public ones)

### Describe the issue

Every page after the first page shows as blank.

### Screenshot(s)

Nothing really to show.

### Versions

- Browser/version: Chrome 71 (unfortunately)
- uBlock Origin version: 1.18.5b3

### Settings

- A few filter lists and stuff, probably not especially relevant

### Notes

Caused by `docs.google.com##+js(addEventListener-defuser.js, scroll)`

**Comment by yourduskquibbles** [comment]
Thanks, will need to further investigate to see if I can target this filter only on the main docs homepage which keeps the header in place. Breaking every other page but fixing the main page is obviously not worth doing.

**Comment by Jap2-0** [comment]
Is it for the homepage when signed in or signed out?

**Comment by yourduskquibbles** [comment]
> 
> 
> Is it for the homepage when signed in or signed out?

It was for when signed in but obviously was too broad in scope. I'll see if I can find a better filter today when I have some time to take a look and test properly.

**Comment by yourduskquibbles** [comment]
@Jap2-0 do you mind testing these filters below for `docs.google.com` by temporarily unsubsubscribing to the Web Annoyances Ultralist and adding the filters below to your 'My Filters' section?

```
docs.google.com###docs-homescreen-add:style(opacity: 1 !important;)
docs.google.com##.docs-homescreen-fcc-pinnedcontainer-pinned.docs-homescreen-fcc-pinnedcontainer, .docs-homescreen-floater-header-shadow.docs-homescreen-floater-grid-header.goog-scrollfloater, .gb_sc.gb_Id.gb_tb.gb_Xa:style(position: absolute !important;)
docs.google.com##.docs-homescreen-floater-grid-header.goog-scrollfloater:style(position: absolute !important; top: 64px !important;)
docs.google.com##.docs-homescreen-floater-header-title:style(line-height: 44px !important;)
docs.google.com##.docs-homescreen-homescreenmain > div:nth-child(4):style(opacity: 1 !important; display: block !important;)
docs.google.com##.docs-homescreen-item-container > div:nth-of-type(1):style(position: relative !important; visibility: visible !important;)
docs.google.com##.docs-homescreen-sftc.goog-scrollfloater:style(position: absolute !important;)
docs.google.com##.docs-hs-tmp-sch:style(position: relative !important; padding-top: 32px !important;)
docs.google.com##.gb_8d:style(position: absolute !important; visibility: visible !important; opacity: 1 !important;)
docs.google.com##.gb_qc.gb_Fd.gb_tb.gb_Xa:style(position: absolute !important; visibility: visible !important; opacity: 1 !important;)
```

I've added a new filter and changed an existing one, I think I have it working on the homepage and test docs I have opened up but want to make sure I'm not missing a user use case.

**Comment by Jap2-0** [comment]
They work fine for me for the most part (everything loads and sticks), but there is a small issue of spacing for me on the docs home page.  The first screenshot is what it's like without lists, with the current (neutered) list, and with the old list, the second screenshot is with the new filters.  The bottom part is cropped out because that's fine (and you guys don't need to see my documents :P)

![image](https://user-images.githubusercontent.com/40511669/53044722-c72f2480-3459-11e9-98bc-a14d72528faa.png)

![image](https://user-images.githubusercontent.com/40511669/53044731-cd250580-3459-11e9-84af-e0569831c7d8.png)


I'll look into this and see what I can do.

**Comment by yourduskquibbles** [comment]
Does updating 
From:
`docs.google.com##.docs-hs-tmp-sch:style(position: relative !important; padding-top: 32px !important;)` 

to:
`docs.google.com##.docs-hs-tmp-sch:style(position: relative !important; top: 32px !important;)` fix the issue for you? 


Padding at the top seems to be screen size dependent so isn't a great fix, maybe the updated filter works though.

**Comment by Jap2-0** [comment]
Yeah, that does it.

**Comment by yourduskquibbles** [comment]
Cool thanks, will post updated filters then.

**Comment by Jap2-0** [comment]
Yeah, I was playing around in chrome's dev tools and I couldn't break it by simulating different screen sizes... but for some reason it redirected to `https://www.google.com/docs/about/` if I tried to reload the page with dev tools open.  Either way, it looks good.
