### ISSUE TITLE
NYTimes.com bottom "subscribe" floating bar

### ISSUE THREAD

**Issue by prech** [yourduskquibbles/webannoyances#128]
### URL(s) where the issue occurs

https://www.nytimes.com/2019/02/25/us/politics/national-emergency-republicans.html
https://www.nytimes.com/2019/02/24/world/europe/britain-austerity-socialism.html

### Describe the issue

Bottom "subscribe" floating bar has re-appeared.

### Screenshot(s)

https://i.imgur.com/8pneqKO.jpg
https://i.imgur.com/3EkhoBy.jpg

### Versions

- Browser/version: Google Chrome Version 72.0.3626.119
- uBlock Origin version: uBlock Origin v1.18.4

### Notes

The "subscribe" floating bar was previously blocked/recognized by the ultralist, so perhaps they've made some changes? 

Any ideas appreciated

**Comment by yourduskquibbles** [comment]
Does adding `nytimes.com##.meter_default` to your 'My Filters' fix the issue for you?

**Comment by prech** [comment]
> Does adding `nytimes.com##.meter_default` to your 'My Filters' fix the issue for you?

Thanks much, this did the trick!

**Comment by yourduskquibbles** [comment]
Awesome -  Thanks for reporting!
