### ISSUE TITLE
Scrolling header when creating a set on quizlet

### ISSUE THREAD

**Issue by Jap2-0** [yourduskquibbles/webannoyances#129]
### URL(s) where the issue occurs

`https://quizlet.com/create-set`

### Describe the issue

The header shown in the screenshot scrolls with the page, taking a significant amount of screen real estate.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/40511669/53521920-50240c80-3aa7-11e9-902f-ff70c99edd85.png)

### Notes

This probably requires an account.
The filter `quizlet.com##.CreateSetHeader-sticky:style(position: absolute !important;)` is working nicely for me; if you want something more specific, I believe something targeting `quizlet.com/create-set`, `quizlet.com/*/autosaved`, and `quizlet.com/*/edit` should cover every page this pops up on that I know of.

**Comment by yourduskquibbles** [comment]
Thanks for reporting. I scrolled around the site a bit and added a few more filters for other sticky elements I found as well.
