### ISSUE TITLE
Update list problem

### ISSUE THREAD

**Issue by happysurf** [yourduskquibbles/webannoyances#13]
I have added your list but with Ublock Origin is impossible to update.

**Comment by yourduskquibbles** [comment]
Can you provide screenshot? And potentially a screenshot of the logger? Did you click on the force update icon (circled in red) next to the list 
![forceupdate](https://user-images.githubusercontent.com/22258847/36168252-57635bea-10f0-11e8-8c7b-001996388c79.png)


or click the 'Purge all caches' button from the 3rd Party Filters pane before clicking 'Update now'?

![purge](https://user-images.githubusercontent.com/22258847/36168314-8d2efc02-10f0-11e8-8991-a6b12232defe.png)

**Comment by yourduskquibbles** [comment]
Closing this issue - @happysurf Please provide updated reproduction steps if the issue still persists for you.
