### ISSUE TITLE
Dropdown autofill box on youtube scrolls

### ISSUE THREAD

**Issue by Jap2-0** [yourduskquibbles/webannoyances#131]
### URL(s) where the issue occurs

`youtube.com`

### Describe the issue

The dropdown box of suggestions from the search bar scrolls, though the search bar does not.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/40511669/53602676-7b792b00-3b7d-11e9-83d5-1325d1f4340d.png)

### Notes

It looks like `youtube.com##.gstl_50.sbdd_a:style(position: absolute !important;)` will do it.

**Comment by yourduskquibbles** [comment]
Nice catch, thanks.
