### ISSUE TITLE
Chrome Unboxed header

### ISSUE THREAD

**Issue by Jap2-0** [yourduskquibbles/webannoyances#132]
### URL(s) where the issue occurs

`https://chromeunboxed.com/`

### Describe the issue

Standard scrolling header.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/40511669/53608679-c00ec180-3b91-11e9-8915-61a2f32ac952.png)

### Notes

The header appears to be the same on all pages; After spending a few minutes forgetting how to spell, it looks like `chromeunboxed.com##.site-header:style(position: absolute !important;)` works nicely.

**Comment by yourduskquibbles** [comment]
Thx
