### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by 3j9fkyahunqoxwqu** [yourduskquibbles/webannoyances#134]
Hello

Excuse me for creating an issue for this but your filterlist is one of most great filterlist i have.
i wanted to thank you

what is ridiculous about web design is that all screens become wider and wider and webpages use the static bars in top and bottom and this is really annoying.

All websites are going to become more and more bloated

Your filterlist is really a haven in this web design :/

Also please if may keep the aggressiveness of your filterlist to a balanced mode because the web isn't livable if we get forced to disable your list in future because it is this much a must have and great filterlist that can't live without it :D

**Comment by yourduskquibbles** [comment]
@3j9fkyahunqoxwqu Thank you for the kind words and am happy to hear user feedback that it is useful for others! :)
