### ISSUE TITLE
AWS docs footer bar rendering

### ISSUE THREAD

**Issue by joshka** [yourduskquibbles/webannoyances#135]
### URL(s) where the issue occurs

`https://docs.aws.amazon.com/athena/latest/ug/work-with-data.html`

### Describe the issue

Footer bar hovers over the table of contents.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/381361/55988593-1ffc8b80-5c59-11e9-9fed-b9c146a2e077.png)

### Versions

- Browser/version: FF - 66
- uBlock Origin version: uBlock Origin v1.18.16

### Settings

- none

### Notes

Affects any AWS docs page where the amount of content is smaller than a full monitor height.
Fine without uBlock running. Not sure which CSS rule is affecting this (body related or footer)

**Comment by yourduskquibbles** [comment]
Thanks for reporting. Please let me know if you are still having issues.

**Comment by joshka** [comment]
Thanks, this seems to have fixed it.
