### ISSUE TITLE
Headers on smugmug.com

### ISSUE THREAD

**Issue by Jap2-0** [yourduskquibbles/webannoyances#136]
The filter that keeps the header on `smugmug.com` from moving breaks headers on pages/albums hosted at `examplename.smugmug.com`.

Picture of issue:

![image](https://user-images.githubusercontent.com/40511669/56003437-8652cf80-5c94-11e9-9fe5-46d2f5fda6b2.png)

The solution is to replace `smugmug.com###sm-page-header:style(position: absolute !important;)` with `smugmug.com##.sm-marketing-header:style(position: absolute !important;)` (as the latter only appears on the the main page).

I can try to find you a link to a page where it occurs if you want one (let me know), but it'll probably be something random I pull of google (because I try to maintain some semblance of privacy online).

**Comment by yourduskquibbles** [comment]
Thanks for reporting. I will try to find my own test domain and verify this update works properly but wanted to provide the fix as suggested first.

**Comment by Jap2-0** [comment]
Try googling `inurl:smugmug.com -inurl:www.smugmug.com -inurl:news.smugmug.com -inurl:help.smugmug.com`.

**Comment by yourduskquibbles** [comment]
> inurl:smugmug.com -inurl:www.smugmug.com -inurl:news.smugmug.com -inurl:help.smugmug.com

Looks good to me! 

Tested on
```
https://ferrisphotos.smugmug.com/
https://internationalgymnastics.smugmug.com/
https://davewilson.smugmug.com/
```

and all seem fine to me.
