### ISSUE TITLE
mothership.sg scrolling header

### ISSUE THREAD

**Issue by gtotog** [yourduskquibbles/webannoyances#137]
### URL(s) where the issue occurs

`mothership.sg`

### Describe the issue

scrolling sticky header

![](https://i.imgur.com/FQa8xya.jpg)
---

Played around in Firefox developer tool and got it working with these filters:

```
mothership.sg##.top-nav:style(position: absolute !important;)
mothership.sg##.search-bar:style(position: absolute !important;)
mothership.sg##.categories, .more-categories:style(position: absolute !important;)
```

**Comment by gtotog** [comment]
Is this the channel to suggest additions to list?  

Also your discord server is error 404.

**Comment by yourduskquibbles** [comment]
@ gtotog Thanks for reporting! 

This is best place to report additions to list and will look into what is going on with the discord server.
