### ISSUE TITLE
section headers missing from lawfareblog.com article

### ISSUE THREAD

**Issue by fjarlq** [yourduskquibbles/webannoyances#138]
### URL(s) where the issue occurs

`https://www.lawfareblog.com/notes-mueller-report-reading-diary`

### Describe the issue

When the ultralist is enabled, the section headers in this Lawfare article are missing.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/441483/56846222-ee570780-6889-11e9-96ed-8bd3917b45a2.png)

### Versions

- Browser/version: Chrome/74.0.3729.108
- uBlock Origin version: 1.18.16

### Notes

I suspect this is because the sections are tagged with:

`<p class="rtecenter">`

while this rule is in the ultralist:

`lawfareblog.com##.rtecenter`

**Comment by yourduskquibbles** [comment]
Thanks for reporting.
