### ISSUE TITLE
Tickets button on EventBrite

### ISSUE THREAD

**Issue by identigral** [yourduskquibbles/webannoyances#139]
### URL(s) where the issue occurs

https://www.eventbrite.com/e/internet-identity-workshop-iiwxxviii-28-2019a-tickets-53106507995

### Describe the issue

The Tickets button is filtered out

### Versions

- Browser/version: Chrome 74.0.3729.108
- uBlock Origin version: 1.18.16

### Notes

From uBO logger, the Tickets button is filtered out by this rule

eventbrite.com##.clrfix.sticky.sticky-listing-panel.js-sticky-panel.listing-panel

**Comment by yourduskquibbles** [comment]
Thanks for reporting! 

Please let me know if you encounter any other issues after purging cache and updating your filters.

**Comment by identigral** [comment]
Validated, looks good. Thank you for a quick fix!
