### ISSUE TITLE
channelnewsasia.com - scrolling headers

### ISSUE THREAD

**Issue by gtotog** [yourduskquibbles/webannoyances#140]
### URL(s) where the issue occurs

`[www.channelnewsasia.com]`

### Describe the issue

scrolling sticky header

### Screenshot(s)

![Channelnewsasia](https://i.imgur.com/Zziz43v.jpg)

### Versions

- Browser/version: Firefox for Windows 66.0.3
- uBlock Origin version: v1.18.17rc4

### Settings

Below are my filters to fix this:
```
www.channelnewsasia.com##.header__inner:style(position: unset !important;)
www.channelnewsasia.com##.header__outer:style(position: unset !important;)
```

**Comment by yourduskquibbles** [comment]
Thanks for reporting! Please let me know if issue persists after purging cache and updating filters.
