### ISSUE TITLE
Is there a way to use this with 1blocker (and safari on MacOS)

### ISSUE THREAD

**Issue by bruno-** [yourduskquibbles/webannoyances#142]
Hi,

I used this list with "uBlock origin" extension with Safari and I loved it! "uBlock origin" for Safari is unfortunately broken and I switched to [1blocker](https://1blocker.com) for Safari.

Question: is there a way to use this list with 1blocker and Safari?
Thanks

**Comment by yourduskquibbles** [comment]
Hi @bruno- 

I don't know the answer to that... and don't have a Mac to test on. In 1blocker options is there a place to import custom filter lists? Even if there is, I'm not sure what filter list parsing syntax they use, but I believe [adguard](https://adguard.com/en/adguard-mac/overview.html) does convert uBO extended filter syntax into its own syntax format and may work for your purposes so I would recommend trying adguard for Mac OS and let me know if it is working for you? I can add to the readme if you find the list works on adguard.

@ameshkov any chance you can confirm what I said above is correct?

**Comment by ameshkov** [comment]
Yeah, AG for Mac does support extended syntax.

Also, the new beta version of [AG for Safari](https://github.com/AdguardTeam/AdGuardForSafari) app also partly supports extended syntax. [Beta link](https://github.com/AdguardTeam/AdGuardForSafari/releases/download/v1.3.0-beta/AdGuard.for.Safari.app.zip). Unfortunately, we won't be able to port this to iOS.

> Edit: Adding install instructions for adguard safari extension in case you don't want system wide Mac OS blocker

Well, legacy extensions [will be removed](https://adguard.com/en/blog/legacy-safari-extensions.html) in the new Safari version.

**Comment by yourduskquibbles** [comment]
Thanks for confirming @ameshkov!

@bruno- Based on the above, I would recommend installing AG for Mac and seeing if that works for you after importing the [raw filter list](https://raw.githubusercontent.com/yourduskquibbles/webannoyances/master/ultralist.txt)[1] as a custom list.

[1] https://raw.githubusercontent.com/yourduskquibbles/webannoyances/master/ultralist.txt

**Comment by bruno-** [comment]
Thank you. I confirm it works great with AdGuard for Mac 👍

**Comment by yourduskquibbles** [comment]
Great to hear, and thanks for letting me know it works for you. 

I'll update the [README](https://github.com/yourduskquibbles/webannoyances/blob/master/README.md) soon with that information so others can benefit.
