### ISSUE TITLE
www.fairprice.com.sg -- Sticky scrolling header only appears when showing search results

### ISSUE THREAD

**Issue by gtotog** [yourduskquibbles/webannoyances#143]
### URL(s) where the issue occurs

`https://www.fairprice.com.sg/searchterm/milk`

### Describe the issue

Sticky scrolling header only appears when showing search results.

### Screenshot(s)
![](https://i.imgur.com/jwg184K.jpg)

### Fix

`www.fairprice.com.sg##.top_header_section:style(position: unset !important;)`

**Comment by yourduskquibbles** [comment]
Thanks for reporting.

I added some additional filters to get rid of the jumpiness but only tested on one screen width - please let me know if the filters are not working for you after updating your filter list.

**Comment by gtotog** [comment]
Thanks, it looks fine.
