### ISSUE TITLE
Filter list blocking Youtube Logo

### ISSUE THREAD

**Issue by COMMANDERWONG** [yourduskquibbles/webannoyances#147]
### URL(s) where the issue occurs
https://www.youtube.com/
### Describe the issue
When I go to youtube.com, the upper left Youtube logo is blocked by the filter.
### Screenshot(s)

[Screenshot(s) for difficult to describe visual issues are **mandatory**. Post links instead of **Inline Images** for Screenshots containing **Adult material**.]

### Versions

- Browser/version: Google Chrome
- uBlock Origin version:v1.20.0

### Settings

- [List here all the changes you made to uBO's default settings]

### Notes

<div id="logo-icon-container" class="yt-icon-container style-scope ytd-topbar-logo-renderer"><svg viewBox="0 0 200 60" preserveAspectRatio="xMidYMid meet" focusable="false" class="style-scope ytd-topbar-logo-renderer" style="pointer-events: none; display: block; width: 100%; height: 100%;"><g viewBox="0 0 200 60" preserveAspectRatio="xMidYMid meet" class="style-scope ytd-topbar-logo-renderer">

This seems to be the element that the filter list has blocked.

**Comment by yourduskquibbles** [comment]
Thanks for reporting, https://github.com/yourduskquibbles/webannoyances/commit/91ac7e8b067bc1e9da3a641e26c4222e2154219f broke this. It should be fixed now if you purge cache and update your filters.

I still need to figure out a fix for fullscreen scroll up flashing masthead but will test whatever fix I can come up with more thoroughly when I find it.
