### ISSUE TITLE
.top-link Filter Seems Overly Broad

### ISSUE THREAD

**Issue by caffeinewriter** [yourduskquibbles/webannoyances#150]
### URL(s) where the issue occurs

`https://represent.io/dashboard`

### Describe the issue

The [`.top-link`](https://github.com/yourduskquibbles/webannoyances/blob/77936719467f5c2c386e5b3f6a8fed16898dc3df/filters/generic_filters.txt#L2046) filter is incredibly broad. While that could mean a scroll-to-top button, it is more than conceivable that developers might use that as a class to denote links that are included in a top bar, or at the top of a container/page. 

### Screenshot(s)

**Without uBlock Enabled**
![Without uBlock Enabled](https://i.haz.science/19/07/firefox-1562966033-XEOgJot.png)

**With uBlock Enabled**
![With uBlock Enabled](https://i.haz.science/19/07/firefox-1562967108-KJ9ab7w.png)

### Versions

- Browser/version: Firefox Quantum 68.0
- uBlock Origin version: 1.20.2

### Settings

- Added this filterlist
- Added [DontPushMe](https://github.com/caffeinewriter/DontPushMe)
- Enabled all built-in filterlists except experimental
- Enabled EasyList
- Enabled EasyPrivacy
- Enabled Malvertising filter list by Disconnect​​​​​
- Enabled Malware Domain List​​​​​
- Enabled Malware domains
- Enabled Peter Lowe’s Ad and tracking server list

### Notes

While most of the filters in the generic filters list seem fine, [`.top-link`](https://github.com/yourduskquibbles/webannoyances/blob/77936719467f5c2c386e5b3f6a8fed16898dc3df/filters/generic_filters.txt#L2046) seems incredibly likely to produce false positives, moreso than [`#top-link`](https://github.com/yourduskquibbles/webannoyances/blob/77936719467f5c2c386e5b3f6a8fed16898dc3df/filters/generic_filters.txt#L544). It may be worth limiting this to sites that are known to use `.top-link` as a scroll-to-top button.

**Comment by yourduskquibbles** [comment]
Thanks for reporting - I will remove `##.top-link` for now, as I agree that it could cause too many false positives.
