### ISSUE TITLE
Incorrect blocking.

### ISSUE THREAD

**Issue by lancelot-moon** [yourduskquibbles/webannoyances#151]
https://github.com/AdguardTeam/AdguardFilters/issues/36926

This is a hospital's page.
http://www.bc.cch.org.tw/BCRG/opd/opd_5.aspx

Normally, it will have the pop-up for showing the progress of sick man's number when clicking any categories of Outpatient department.
But `Web Annoyances Ultralist` incorrectly blocks the pop-up.

**Comment by yourduskquibbles** [comment]
Thanks for reporting @lancelot-moon, this should be fixed now if you purge your cache and update filters.

**Comment by lancelot-moon** [comment]
Hi,
http://www1.cch.org.tw/opd/opd_5.aspx
It's better to modify `bc.cch.org.tw#@##sb-container` to `cch.org.tw#@##sb-container`.
Thanks.

**Comment by yourduskquibbles** [comment]
@lancelot-moon Thanks, I have updated as suggested.
