### ISSUE TITLE
antergos.com

### ISSUE THREAD

**Issue by KonoromiHimaries** [yourduskquibbles/webannoyances#153]
### URL(s) where the issue occurs

`https://antergos.com/donate`

### Describe the issue

broken page

### Screenshot(s)

![2019-07-25-Donate _ Antergos Linux - Iron](https://user-images.githubusercontent.com/5884000/61904404-16a4df80-af27-11e9-94dc-45d73a90846c.png)

### Versions

- Browser/version: chr 74
- uBlock Origin version: latest

**Comment by yourduskquibbles** [comment]
Thanks!
