### ISSUE TITLE
channelnewsasia.com [mobile version]

### ISSUE THREAD

**Issue by Alex-302** [yourduskquibbles/webannoyances#155]
### URL(s) where the issue occurs

`https://www.channelnewsasia.com/news/international` - mobile version.

### Describe the issue

Blank page. BODY is hidden by the rule `##.scroll-top` I think it is not a good rule. Better make it domain specific.

### Screenshot(s)

<details>
  <summary>Screenshot</summary>

  ![Screenshot 1](https://reports-img.adguard.com/qsKMc81.png)
</details>

### Versions

- Browser/version: mobile Chrome and iOS
- uBlock Origin version: any ad blocker

### Settings

`Easylist` + `Web Annoyances Ultralist`

Related issue: https://github.com/AdguardTeam/AdguardFilters/issues/37223

**Comment by yourduskquibbles** [comment]
Thanks, I have removed the rule as overly generic.
