### ISSUE TITLE
newyorker.com inline article has irrelevant video being autoplayed without sound

### ISSUE THREAD

**Issue by chazanov** [yourduskquibbles/webannoyances#156]
The discord channel appears offline to me. Can you confirm this?

I would like to ask for inclusion of
`www.newyorker.com##.cne-interlude-container`
but without the hassle of creating screenshots

**Comment by yourduskquibbles** [comment]
What does that filter remove? I can add it but don't know what list to add it to the list but can't tell what it removes when I go to `newyorker.com`. Is it something I can see if I go to a specific page you can provide?


Not sure how to fix the discord, I will need to check on it.

**Comment by yourduskquibbles** [comment]
Is the video in the middle of article at `https://www.newyorker.com/culture/cultural-comment/the-star-spangled-banner-controversy-that-altered-the-course-of-american-music` what you want to remove entirely? 

![cne](https://user-images.githubusercontent.com/22258847/62246119-f5be0d80-b3b0-11e9-9747-7e4864540d4b.png)


It looks like it is not a floating video, just autoplay that is annoyance?

**Comment by chazanov** [comment]
Sorry for my laziness.

In [any](https://www.newyorker.com/news/dispatch/how-legalization-changed-humboldt-county-weed) New Yorker article there are unrelated videos:

![Screenshot](https://user-images.githubusercontent.com/39840300/62330948-93e9ca80-b4ba-11e9-8ffd-dc7ab466cd77.png)

**Comment by yourduskquibbles** [comment]
Thanks for the write-up and after thinking about it a bit and looking at the example article link I agree with you that these interlude videos are annoying and distracting since they have no relation at all to the article being read.

I will add the filter as suggested but am open to hearing others thoughts if they think this is too aggressive of blocking.
