### ISSUE TITLE
Youtube.com issue?

### ISSUE THREAD

**Issue by hl2guide** [yourduskquibbles/webannoyances#16]
This list seems to have an issue with youtube.com. The watch later, notifications and profile menus do not appear when activated.

3 purple highlighted areas below:

![yt issue](https://user-images.githubusercontent.com/17044982/38137955-a611e620-3473-11e8-9bc8-c74a23eec9a0.png)

**Comment by yourduskquibbles** [comment]
Which page URL are you viewing when seeing these missing icons?

I can't reproduce from search page or home page (both logged in and logged out) so hoping to better understand your workflow so I can fix the issue.

**Comment by yourduskquibbles** [comment]
Further testing I can reproduce now. I will work on coming up with a fix. Thanks for reporting!

**Comment by yourduskquibbles** [comment]
Should be fixed now, please force an update of the list and let me know if there is still an issue for you.

**Comment by hl2guide** [comment]
Thanks for the quick fix. Works for me now.
