### ISSUE TITLE
Reddit Black Top

### ISSUE THREAD

**Issue by ArmynC** [yourduskquibbles/webannoyances#161]
### URL(s) where the issue occurs

`Anywhere (posts) on https://www.reddit.com`

### Describe the issue

Inside a reddit post, the top black bars are longer than usual

### Screenshot(s)

**With the filter**
![Capture](https://user-images.githubusercontent.com/16375271/62831712-7809c580-bc2c-11e9-85fe-821919c19322.PNG)

**Without a filter (normal)**
![Capture2](https://user-images.githubusercontent.com/16375271/62831733-8bb52c00-bc2c-11e9-96c6-0bfc448e17d3.PNG)

### Versions

- Browser/version: Version 77.0.3865.19 (Official Build) beta (64-bit)
- uBlock Origin version:  1.21.7b5

### Settings

`https://raw.githubusercontent.com/ArmynC/ArminC-uBlock-Settings/master/arminc-ublock-backup.txt`

### Notes

Sometimes it appears immediately but at other times it will be triggered at a page scroll (down).
-> Using the logger and other uBlock tools could deactivate (hide) temporary the issue.

**Comment by yourduskquibbles** [comment]
Thanks, please let me know if the issue reappears the class names are so random and they sometimes change so filters don't always last long on the reddit redesign. :/

**Comment by ArmynC** [comment]
I 'purged all cache' and 'updated now'. The issue is still there.. I miss something?

**Comment by yourduskquibbles** [comment]
Are you able to share an example post link? I just went to a random one on Politics to come up with the filter, maybe it changes depending on the subreddit you are on or logged-in/logged-out state?

**Comment by ArmynC** [comment]
First random post: `https://www.reddit.com/r/science/comments/covfi5/the_bacteria_in_our_gut_the_human_microbiome/`

~ No account (logged-out)

**Comment by yourduskquibbles** [comment]
> First random post: `https://www.reddit.com/r/science/comments/covfi5/the_bacteria_in_our_gut_the_human_microbiome/`
> 
> ~ No account (logged-out)
> 
> **EDIT**
> 
> If I enter using 'Open in a new tab' or by copying the link, the issue is gone.
> To see it, I need to click a post directly from the Reddit main (or subreddit) page.

Thanks I can reproduce now but am having issues coming up with a filter solution that is reliable on various test links from different subreddits.

Can you try testing adding the following 2 filters to My Filters and see if the issue still presents on random subreddits for you? This seems to fix it for me most of the time, but have seen some examples (but can't recreate now) where it doesn't.

`www.reddit.com##div[id="SHORTCUT_FOCUSABLE_DIV"] > div[class^="SubredditVars"] > div[style^="--comments-overlay-background"]:style(top: unset !important;)`
`www.reddit.com##div[id="SHORTCUT_FOCUSABLE_DIV"] > div[class^="SubredditVars"] > div[style^="--comments-overlay-background"] > div > div[id="overlayScrollContainer"] > div[tabindex="-1"]:style(margin-top: 24px !important;)`

**Comment by ArmynC** [comment]
The issue is still here. It just removes the top bar (search, login, singup etc.) and lengthens the black barof the respective post.. I should do something? Like restoring to default settings the browser? Or it already applied but didn't work?

**Comment by yourduskquibbles** [comment]
Thats what I found too, some subreddits the filters suggested above works but others it doesn't work. I will just remove the redesign reddit filters for now. Not worth fixing a shitty site design, I just use `old.reddit.com` :)
