### ISSUE TITLE
catalog.lib.vt.edu

### ISSUE THREAD

**Issue by ZaphodBeebblebrox** [yourduskquibbles/webannoyances#162]
### URL(s) where the issue occurs

`catalog.lib.vt.edu/cgi-bin/koha/opac-user.pl`

### Describe the issue

The filter `##.scrollto` ([found here](https://github.com/yourduskquibbles/webannoyances/blob/58ad90a4d8efb9bd38afae11bf0c2e700f9e7ed5/filters/generic_filters.txt#L1453)), blocks the entire site.

### Versions

- Browser/version: Vivaldi 2.4.1488.36 (chromium based)
- uBlock Origin version: 1.21.7b7

### Settings

All filters under built in, all but adguard mobile under ads, all under privacy, all under annoynaces, Nano Defender Integration lists.

### Notes

Perhaps `catalog.lib.vt.edu#@#.scrollto`

**Comment by yourduskquibbles** [comment]
Thanks for reporting, let me know if still having issues after updating your filters.
