### ISSUE TITLE
Hides the "save" element on Twitter profile pages 

### ISSUE THREAD

**Issue by 07416** [yourduskquibbles/webannoyances#165]
### URL(s) where the issue occurs

https://twitter.com/settings/profile

### Describe the issue

Hides the "save" element on Twitter profile pages (an account required).

### Screenshot(s)

![Twitter](https://user-images.githubusercontent.com/14923168/63935945-45066500-ca67-11e9-96ab-7507d41b6794.png)

### Versions

- Browser/version: Firefox 68.0.2 (64-bit)
- uBlock Origin version: uBlock Origin 1.21.2

### Notes
Again, a Twitter account is mandatory.

**Comment by yourduskquibbles** [comment]
Thanks for reporting! 

Please let me know if not working after you purge cache and update your filters.

Side note: The twitter DOM tree with completely random class names sure is great 🙄
