### ISSUE TITLE
facebook.com - navbar vanishes after scrolling

### ISSUE THREAD

**Issue by BlazDT** [yourduskquibbles/webannoyances#166]
facebook.com

When scrolling down in newsfeed, the navbar at the top is vanishing and is only displayed when you are at the top of the site.

Problematic rule:
facebook.com,facebookcorewwwi.onion#$#div[aria-label="Facebook"][role="banner"] { position: relative !important; }

**Comment by yourduskquibbles** [comment]
> When scrolling down in newsfeed, the navbar at the top is vanishing and is only displayed when you are at the top of the site.

@BlazDT This is intentional behavior and in fact the main purpose of Web Annoyances Ultralist - disabling sticky headers & sticky elements that steal screen real estate. 

From the [Intro in README.me](https://github.com/yourduskquibbles/webannoyances#intro)

> Are you tired of not being able to use all of your screen real estate for the text that matters on a website because floating headers and other distracting elements are blocking your view? Reclaim your screen real estate with Web Annoyances Ultralist!
>
> Block annoying web elements such as sticky headers, dickbars, floating headers, scrolling headers, fixed headers, scrolling videos, stickynavs, social icons, social share bars, smartphone app banners, app download prompts, cookie notices, GDPR warnings, scroll to top buttons, modal overlays, interstitial site overlays, removed or hidden overflow scroll bars, subscription nags, and generally distracting elements that have increasingly been turning the web into a user-hostile environment.
>
> When possible, sticky headers, stickynavs, floating elements, scrolling videos and more will be pinned in place to prevent site breakage.


The information below is intended to help the user who reported https://github.com/AdguardTeam/AdguardFilters/issues/34975#issuecomment-526190233

Please tell the user to try adding one of the following sets of filters to their Personal Filters to override this behavior caused by Web Annoyances Ultralist.

### Facebook Exception Filter Set 1
**Disable _ALL_ CSS Style Modifications for Facebook used in Web Annoyances Ultralist**
```
facebook.com,facebookcorewwwi.onion#@##browse_lhc_container, #entity_sidebar, #leftCol > div > div, #u_fetchstream_1_3, #js_l, div[id^="u_jsonp"][class^="_2pie"], div[id^="u_0"][class^="_2pie"], #leftCol div[id^="u_jsonp"], #rightCol div[id^="u_jsonp"][style*="position: fixed"]:style(position: relative !important; top: 0 !important;)
facebook.com,facebookcorewwwi.onion#@##content > div > ._lwx:style(position: absolute !important; padding-bottom: 10px !important;)
facebook.com,facebookcorewwwi.onion#@##u_0_u > ._5vx4._5vx2 > .clearfix._5vx7 > .lfloat._ohe > ._4470._43o4:style(background-color: #fff !important;)
facebook.com,facebookcorewwwi.onion#@#._1n-x._8k-._3m9, .fixed_always, ._7gbh:style(position: absolute !important;)
facebook.com,facebookcorewwwi.onion#@#._2yq ._4-u2:before:style(border: none !important;)
facebook.com,facebookcorewwwi.onion#@#._4k-p:style(margin-top: 0 !important;)
facebook.com,facebookcorewwwi.onion#@#._4oes:style(position: relative !important; border-bottom: 1px solid #ccc !important;)
facebook.com,facebookcorewwwi.onion#@#._5ss8:style(left: auto !important; top: 0 !important;)
facebook.com,facebookcorewwwi.onion#@#._5vx2:style(border: none !important; box-shadow: none !important;)
facebook.com,facebookcorewwwi.onion#@#._ky-:style(margin: 0 !important;)
facebook.com,facebookcorewwwi.onion#@#.fbChatSidebar:style(position: absolute !important; height: 100% !important; border-bottom: 1px solid #ccc !important;)
facebook.com,facebookcorewwwi.onion#@#.fixed_elem, ._2yq ._5sqx._5sqx:style(position: absolute !important; top: 0 !important;)
facebook.com,facebookcorewwwi.onion#@#.pbm.clearfix:style(padding-top: 53px !important;)
facebook.com,facebookcorewwwi.onion#@#div[aria-label="Facebook"][role="banner"]:style(position: relative !important;)
facebook.com,facebookcorewwwi.onion#@#div[id^="u_0"][style*="position: fixed;"]:style(position: absolute !important; top: 0 !important;)
```

### Facebook Exception Filter Set 2
**Disable _ONLY_ `position: fixed` CSS Style Modifications for Facebook used in Web Annoyances Ultralist**
```
facebook.com,facebookcorewwwi.onion#@##browse_lhc_container, #entity_sidebar, #leftCol > div > div, #u_fetchstream_1_3, #js_l, div[id^="u_jsonp"][class^="_2pie"], div[id^="u_0"][class^="_2pie"], #leftCol div[id^="u_jsonp"], #rightCol div[id^="u_jsonp"][style*="position: fixed"]:style(position: relative !important; top: 0 !important;)
facebook.com,facebookcorewwwi.onion#@##content > div > ._lwx:style(position: absolute !important; padding-bottom: 10px !important;)
facebook.com,facebookcorewwwi.onion#@#._1n-x._8k-._3m9, .fixed_always, ._7gbh:style(position: absolute !important;)
facebook.com,facebookcorewwwi.onion#@#._4oes:style(position: relative !important; border-bottom: 1px solid #ccc !important;)
facebook.com,facebookcorewwwi.onion#@#.fbChatSidebar:style(position: absolute !important; height: 100% !important; border-bottom: 1px solid #ccc !important;)
facebook.com,facebookcorewwwi.onion#@#.fixed_elem, ._2yq ._5sqx._5sqx:style(position: absolute !important; top: 0 !important;)
facebook.com,facebookcorewwwi.onion#@#div[aria-label="Facebook"][role="banner"]:style(position: relative !important;)
facebook.com,facebookcorewwwi.onion#@#div[id^="u_0"][style*="position: fixed;"]:style(position: absolute !important; top: 0 !important;)
```

**Comment by yourduskquibbles** [comment]
Leaving open for discussion in case I misinterpreted the issue from the user.
