### ISSUE TITLE
Reddit Navigation Bar Misaligned

### ISSUE THREAD

**Issue by exela** [yourduskquibbles/webannoyances#169]
### URL(s) where the issue occurs

`https://old.reddit.com/r/nba/comments/cxd5sn/steve_nash_throws_a_behindtheback_wraparound_pass/`

### Describe the issue

The top navigation bar on old.reddit.com is brought down and overlaps the links for 'Comments, Show Images, Other Discussions'.

### Screenshot(s)

![Enabled](https://i.imgur.com/oOerPmK.png "Enabled")

![Disabled](https://i.imgur.com/Ekgsuw9.png "Disabled")

https://imgur.com/a/DdnYdYv for gallery.

### Versions

- Browser/version: Google Chrome Version 76.0.3809.100 (Official Build) (64-bit)
- uBlock Origin version: uBlock Origin v1.21.6

### Settings

- Default Settings being Used

### Notes

I just enabled and re-enabled the filter list and refreshed the page to see this behavior.

Reddit Enhancement Suite (Addon) is enabled.

**Comment by yourduskquibbles** [comment]
Thanks for reporting. 

I think this is probably related to the update I made for #168 but please let me know if you experience issues elsewhere on reddit because finding the correct filter approach for reddit can be tricky because it allows custom CSS on their `old` subdomain so different subreddit pages can break depending on what subreddit you are in and the filter style applied.

**Comment by mondocane80** [comment]
I too am having the same issues with the old reddit toolbar.  Currently I have the list disabled so I can use it.

**Comment by yourduskquibbles** [comment]
@mondocane80 What specific subreddits are giving display issues for you?

**Comment by yourduskquibbles** [comment]
dfhddgfdfdgfgd




dfhddgfdfdgfgd



dfhddgfdfdgfgd


asd

**Comment by yourduskquibbles** [comment]
@exela @mondocane80 Hoping this is fixed now and one of you are able to confirm the issues are gone after purging cache & updating your filter lists. 

Posting excerpt of my reply from [Related discussion on reddit](https://old.reddit.com/r/uBlockOrigin/comments/cyzzxe/web_annoyances_ultralist_breaks_websites/) here as well. 

> I've removed a few problem reddit filters with commit 02a9cad that caused problems after filter updates in #168
> 
> I was unaware of the issues with reddit style because the brokenness was minimized by the RES extension I was running.
> 
> I've tested the updates on new and old reddit and hoping this fixes the brokenness but reddit can be difficult to chase issues with because of subreddits being able to set their own custom CSS so feedback would be helpful.

**Comment by yourduskquibbles** [comment]
Closing as fixed based on user feedback in [reddit thread.](https://old.reddit.com/r/uBlockOrigin/comments/cyzzxe/web_annoyances_ultralist_breaks_websites/ez4xajz/)
