### ISSUE TITLE
youtube.com - Channel Page Affected

### ISSUE THREAD

**Issue by hl2guide** [yourduskquibbles/webannoyances#17]
E.g. https://www.youtube.com/channel/UC0fDG3byEcMtbOqPMymDNbw

The YouTube Channel page is missing the ability to search, filter etc when the ultralist is enabled.

![screenshot](https://user-images.githubusercontent.com/17044982/38163698-0bcafe2c-3544-11e8-9f81-6914ddea9afa.jpg)

Highlighted in purple.

**Comment by yourduskquibbles** [comment]
Thanks for reporting! I don't have much time to test today but I think I fixed it, please let me know if you encounter issues on other channels with this fix.
