### ISSUE TITLE
Burgerking Website not Functional

### ISSUE THREAD

**Issue by eldervamp** [yourduskquibbles/webannoyances#170]
### URL(s) where the issue occurs

https://www.bk.com/

### Describe the issue

Website homepage not functional, greyed out.

### Screenshot(s)

Web Annoyance Ultralist Enabled
![Untitled](https://user-images.githubusercontent.com/37281419/64091142-62288580-cd3e-11e9-90bf-f73c718724eb.jpg)

Web Annoyance Ultralist Disabled
![Untitled2](https://user-images.githubusercontent.com/37281419/64091407-7f118880-cd3f-11e9-9d69-3c0dcb0dfe26.jpg)

### Versions

- Browser/version: Firefox 68.0.2
- uBlock Origin version: [1.21.2]

### Settings

uBlock filters
uBlock filters – Badware risks​
uBlock filters – Privacy
​​uBlock filters – Resource abuse​​​​​
​​uBlock filters – Unbreak​​​​​
EasyList​
EasyPrivacy​
Web Annoyances Ultralist​​

### Notes

Web Annoyances Ultra has a entry:  [###cookie-popup] that is preventing a cookie warning message which after accepting allows user to click on picture items

**Comment by yourduskquibbles** [comment]
Thanks for reporting, think this should be fixed now. Please purge cache and update your filters.

**Comment by eldervamp** [comment]
Thank You. Its fixed :)
