### ISSUE TITLE
Arris.com Website not Functional

### ISSUE THREAD

**Issue by eldervamp** [yourduskquibbles/webannoyances#171]
### URL(s) where the issue occurs

https://www.arris.com/surfboard/

### Describe the issue

Website homepage not functional, greyed out.

### Screenshot(s)

Web Annoyance Ultralist Enabled

![Untitled](https://user-images.githubusercontent.com/37281419/64392256-753b9e00-d03b-11e9-8991-c9b046f53a77.jpg)

Web Annoyance Ultralist Disabled

![Untitled2](https://user-images.githubusercontent.com/37281419/64392275-81bff680-d03b-11e9-9a70-17b8fa8cbc9f.jpg)

### Versions

- Browser/version: Firefox 69.0
- uBlock Origin version: 1.22

### Settings

uBlock filters
uBlock filters – Badware risks​
uBlock filters – Privacy
​​uBlock filters – Resource abuse​​​​​
​​uBlock filters – Unbreak​​​​​
EasyList​
EasyPrivacy​
Web Annoyances Ultralist​​

### Notes

Web Annoyances Ultra has a entry: [##.optanon-alert-box-wrapper] that is preventing a cookie warning message.

**Comment by yourduskquibbles** [comment]
Thanks for reporting, should be fixed now.
