### ISSUE TITLE
Britannica.com

### ISSUE THREAD

**Issue by Jap2-0** [yourduskquibbles/webannoyances#172]
### URL(s) where the issue occurs

`https://www.britannica.com/biography/Saint-Justin-Martyr`

### Describe the issue

Floating header

### Screenshot(s)

Can be provided if needed

### Versions

- Browser/version: Chrome 75
- uBlock Origin version: 1.22.1b2

### Settings

- Several additional lists, can be provided if needed

### Notes

The filter `britannica.com##.topic-toolbar:style(position: absolute !important;)` fixes it for me.

Also to note is that the page jumps a bit at one point.  This is partially fixed by the filter `britannica.com##.md-header:style(height: 70px !important;)`, but if you stop scrolling at the right spot the the goes crazy and shifts up and down ad infinitum.

**Comment by yourduskquibbles** [comment]
Thanks for reporting - I believe I solved the jumpy up and down ad infinitum issue with the additional filters[1] I added in  5fafe51, do you mind double checking that the site works properly for you now with an update of filters?

[1] `britannica.com##body.md-header-collapsed .md-header .md-header-top-row:style(display: flex !important;)` seems to stop the jumpy behavior for me

**Comment by Jap2-0** [comment]
Yes, that does it.  Thanks!
