### ISSUE TITLE
christianitytoday.com

### ISSUE THREAD

**Issue by Jap2-0** [yourduskquibbles/webannoyances#173]
### URL(s) where the issue occurs

`https://www.christianitytoday.com/history/people/evangelistsandapologists/justin-martyr.html`

### Describe the issue

After scrolling down a bit, the entire page becomes covered by a blank white element.

### Screenshot(s)

Can be provided if needed.

### Versions

- Browser/version: Chrome 75
- uBlock Origin version: 1.22.1b2

### Settings

- Mostly more lists, can be provided if needed.

### Notes

Occurs as a result of the filter `christianitytoday.com###fix-header:style(position: relative !important; top: 0 !important;)`; the filter`christianitytoday.com###fix-header` looks like it does what you want.

**Comment by yourduskquibbles** [comment]
Thanks for reporting!
