### ISSUE TITLE
bitchute.com

### ISSUE THREAD

**Issue by KonoromiHimaries** [yourduskquibbles/webannoyances#176]
broken page

**Comment by yourduskquibbles** [comment]
How broken? Seems ok to me on firefox?

**Comment by KonoromiHimaries** [comment]
@yourduskquibbles try it on `1366 x 768`

**Comment by yourduskquibbles** [comment]
I think this should be better now, tested on multiple resolutions and everything seems to be working well for me and sidebar is usable as intended by the site now...

Let me know if other issue though that I am not seeing.

**Comment by KonoromiHimaries** [comment]
@yourduskquibbles still broken on my end
![2019-09-21](https://user-images.githubusercontent.com/5884000/65373137-8e6a5e80-dc79-11e9-984e-0ff82ce16ecb.png)
