### ISSUE TITLE
tumblr.com [Incorrect blocking]

### ISSUE THREAD

**Issue by Alex-302** [yourduskquibbles/webannoyances#178]
### URL(s) where the issue occurs

`https://www.tumblr.com/dashboard`

### Describe the issue

Useful buttons are blocked by 
`tumblr.com##.is-visible.navbar, .l-header-container--refresh.l-header-container, .nav-fixed.nav-responsive.nav-wrapper, .navbar-inner:style(position: relative !important; top: 0 !important;)`

### Screenshot(s)

<details><summary>Screenshot:</summary> 

![image](https://user-images.githubusercontent.com/8361299/65607003-7c0f5e00-dfb4-11e9-9079-f40fbb28fb4d.png)

 </details>

### Versions

- Browser/version: Chrome 76
- uBlock Origin version: 1.22.2

### Settings

EasyList, Web Annoyances Ultralist

**Comment by yourduskquibbles** [comment]
@Alex-302 I just created a tumblr account to test and I don't think they are blocked, just pinned to top?

**Comment by yourduskquibbles** [comment]
@Alex-302 User should add exception filter `tumblr.com#@#.l-header-container--refresh:style(position: absolute !important;)` if they don't want the nav bar to be pinned at top.
