### ISSUE TITLE
trakt.tv

### ISSUE THREAD

**Issue by jpsqq** [yourduskquibbles/webannoyances#180]
### URL(s) where the issue occurs

`https://trakt.tv/dashboard` and all other sites on trakt.tv

### Describe the issue

Website logo gets removed when the floating nav bar gets (correctly) removed. Therefore there is no way to return to the homepage/"dashboard".

### Screenshot(s)

Without Web Annoyances Ultralist
![Bildschirmfoto 2019-10-05 um 14 00 33](https://user-images.githubusercontent.com/24903546/66254747-0e64ee00-e77b-11e9-967d-f1e7e8e0b43a.png)

With Web Annoyances Ultralist
![Bildschirmfoto 2019-10-05 um 14 03 48](https://user-images.githubusercontent.com/24903546/66254746-0e64ee00-e77b-11e9-9759-d228aaef8d2c.png)

### Versions

- Browser/version: Chrome 77.0.3865.90
- uBlock Origin version: 1.22.4

### Notes

Disabling the webannoyances filter in uBlock brings the floating header and the logo back. Enabling the filter removes the floating header and with it the clickable logo.

**Comment by yourduskquibbles** [comment]
@jpsqq I'm not familiar with the site and other parts of the website - does enabling Web Annoyances Ultralist **plus** adding the following filters to 'My Filters' fix the problem for you?

```
trakt.tv##header#top-nav #top-brand:style(opacity: 1 !important;)
trakt.tv##header#top-nav .navbar-nav.brand-left:style(margin-right: 40px !important;)
trakt.tv##header#top-nav .navbar-nav.brand-right:style(margin-left: 40px !important;)
trakt.tv##body.main.home header#top-nav, body.main.index header#top-nav:style(background: 0 0 !important;)
```

**Comment by jpsqq** [comment]
@yourduskquibbles Yep, logo returned and works. Thank you!

**Comment by yourduskquibbles** [comment]
> 
> 
> @yourduskquibbles Yep, logo returned and works. Thank you!

Thanks for reporting & confirming! I will update the filters for `trakt.tv`

**Comment by yourduskquibbles** [comment]
@jpsqq This should be fixed now - you should be able to remove those filters from 'My Filters' and then purge cache and update your filter list on 'Filter Lists' tab.

Please let me know if you encounter any residual issues!
