### ISSUE TITLE
nitter.net

### ISSUE THREAD

**Issue by KonoromiHimaries** [yourduskquibbles/webannoyances#181]
test link
`https://nitter.net/jonathansampson/status/1165493206441779200`

header

**Comment by yourduskquibbles** [comment]
Thanks!

**Comment by KonoromiHimaries** [comment]
@yourduskquibbles floating elements

https://nitter.net/getadblock

and on other instances

https://github.com/zedeus/nitter/wiki/Instances

**Comment by yourduskquibbles** [comment]
Thanks, updated filters
