### ISSUE TITLE
/vadmin/index.php?route=common/

### ISSUE THREAD

**Issue by vavavr00m** [yourduskquibbles/webannoyances#184]
### URL(s) 

- OpenCart 1.5.6 backend
[domain name]/vadmin/index.php?route=common/

### Describe the issue

Social Club tab is missing

### Screenshot(s)

![with Web Annoyances Filter](https://user-images.githubusercontent.com/4675132/67057412-faf65180-f182-11e9-8260-a42b0721682b.png)

![without Web Annoyances Filter](https://user-images.githubusercontent.com/4675132/67057479-3e50c000-f183-11e9-997f-71408c2ca115.png)

### Versions

- Browser/version: Google Chrome Version 77.0.3865.120 (Official Build) (64-bit)
- uBlock Origin version: N/A (Nano Adblocker v1.0.0.128)

### Settings

![Screenshot](https://user-images.githubusercontent.com/4675132/67057282-7f94a000-f182-11e9-84e0-e12bcf1c7a14.png)

### Notes

Nano Adblocker is reporting nothing is being filtered yet Social Club tab is missing when Web Annoyances Ultralist is enabled.

**Comment by yourduskquibbles** [comment]
Are you able to right click `Social Club` button and inspect element when Web Annoyances Ultralist is disabled and then take a screenshot of the inspector? I don't know what generic cosmetic filter is causing this issue without that.

**Comment by vavavr00m** [comment]
![Social Club inspect element](https://user-images.githubusercontent.com/4675132/67111535-b6f96000-f207-11e9-9f30-3915d9a42358.png)

**Comment by yourduskquibbles** [comment]
Thank you - One last request, can you let me know if adding `#@##social` to your `My Filters` while Web Annoyances Ultralist is enabled fixes the issue?

**Comment by vavavr00m** [comment]
It does! Thank you.

**Comment by yourduskquibbles** [comment]
OK thank you, I'll also update the Web Annoyances Ultralist to remove this overly generic filter since this isn't possible to whitelist just one domain to fix the issue.
