### ISSUE TITLE
startpage.com

### ISSUE THREAD

**Issue by p4t44** [yourduskquibbles/webannoyances#185]
### URL(s) where the issue occurs

`https://www.startpage.com/do/metasearch.pl?query=example`

### Describe the issue

Floating header

### Screenshot(s)

![](https://i.imgur.com/9We3tHy.png)

### Versions

- Browser/version: Occurs on both Chromium 75 and Firefox 69
- uBlock Origin version: 1.22.4 and Nano Adblocker 1.0.0.127

### Settings

On default settings, with no changes other then the web annoyances ultrallist added it occurs.

### Notes

I have found that the filter `www.startpage.com##.layout__header:style(position: relative !important)` solves this.

I'm not sure wether this is applicable to be included in the list or not, but there is also an annoying "make default search engine" banner in the top right corner, ![](https://i.imgur.com/iULi1P1.png) The filter `www.startpage.com##.fade-in.addon__popup-bg__blue.addon__popup` stops this.

**Comment by yourduskquibbles** [comment]
Added the filters as suggested, Thanks!
