### ISSUE TITLE
torrentfreak.com

### ISSUE THREAD

**Issue by p4t44** [yourduskquibbles/webannoyances#186]
`https://torrentfreak.com`

### 

<img width="1440" alt="Screen Shot 2019-10-25 at 1 55 52 PM" src="https://user-images.githubusercontent.com/53424460/67535449-29e66780-f72f-11e9-9dea-7760d12e10cf.png">

### Versions

- Browser/version: Chromium v75
- uBlock Origin version: 1.22.4

### Settings

Nothing, only Web Annoyances Ultralist added

### Notes

Filter to fix: `torrentfreak.com##.header__fixed:style(position: absolute!important)`

**Comment by yourduskquibbles** [comment]
Thanks for reporting!
