### ISSUE TITLE
Google Search summary at the right side appears at the left side instead and overlaps with the search results

### ISSUE THREAD

**Issue by AmperAndSand** [yourduskquibbles/webannoyances#188]
### URL(s) where the issue occurs

`https://www.google.com/search?q=hawaii`

### Describe the issue

The Google Search summary which normally appears at the right side appears at the left side instead and overlaps with the search results. Does not happen if Web Annoyances Ultralist​​​​​ is disabled.

### Screenshot(s)
![googlesearch](https://user-images.githubusercontent.com/1404745/69147076-2d8dc400-0b0c-11ea-8d86-51123ac96c4c.png)

### Versions

- Browser/version: Brave Version 1.0.0 Chromium: 78.0.3904.97 (Official Build) (64-bit) and Chrome Version 78.0.3904.108 (Official Build) (64-bit)
- uBlock Origin version: 1.23.0

### Settings

In uBO, all options under 'Privacy' are enabled. Nothing under 'Default behavior' is enabled. In Filter Lists, all the filters in the Built-in, Ads, Privacy, Malware Domains, Annoyances and Multipurpose sections are enabled, except for Fanboy’s Social Blocking List and Fanboy's Cookie List​​​​​​​​​​​. Nothing in the Regions, languages section is enabled.

### Notes

Adding this exception filter: `www.google.com#@#.mw #rhs:style(margin-left: 0 !important;)` to My Filters seems to resolve the issue. This will cancel out this filter in Web Annoyances Ultralist: `www.google.com##.mw #rhs:style(margin-left: 0 !important;)`.

**Comment by yourduskquibbles** [comment]
Thanks for report, this should be fixed now.

Apologies to any affected users - That filter breaking google was [added yesterday](https://github.com/yourduskquibbles/webannoyances/commit/4eee299e752986672f1015a4d0d2051d09c9dcb3) to fix a useless horizontal overflow on `https://www.google.com/finance` that is present even without `Web Annoyances Ultralist` or any user injected style filters, but breaking main google search is obviously not a good solution to that bad site design on google finance. 

For anyone interested, pasting a screenshot below of google finance with a default no extension chrome setup to show attempted issue was trying to solve for with `www.google.com##.mw #rhs:style(margin-left: 0 !important;)` but resulted in unintentionally breaking main google search in the process.

![googfinance](https://user-images.githubusercontent.com/22258847/69206453-b4e23400-0b1a-11ea-85b1-ba37da885185.png)
