### ISSUE TITLE
Bitwarden Vault

### ISSUE THREAD

**Issue by ArmynC** [yourduskquibbles/webannoyances#189]
### URL(s) where the issue occurs

`https://vault.bitwarden.com/#/vault`

### Describe the issue

The top bar and overall the layout is broken.

### Screenshot(s)

![Capture](https://user-images.githubusercontent.com/16375271/69484718-38fc2a80-0e3f-11ea-8f9e-cadb12f7fc6b.PNG)

### Versions

- Browser/version: Version 79.0.3945.45 (Official Build) beta (64-bit)
- uBlock Origin version: uBlock Origin development build v1.23.1b19

### Settings

CSS Filter

### Notes

Maybe this is affecting: bitwarden.com##.is-dockedTop, .js-metabar, nav:not(.collectionHeader-nav):style(position: absolute !important; transform: translateY(0) !important;)

**Comment by yourduskquibbles** [comment]
I don't have an account I can test with so can only remove that filter.

If you are able to do some debugging/screenshot sharing I can try to figure out how to solve the issue without removing all of `bitwarden.com` filters.

**Comment by yourduskquibbles** [comment]
Actually it looks like the existing filters should only be applied to their `blog.bitwarden.com` subdomain because these are medium blog filters. 

Updated the existing filters to no longer apply to `bitwarden.com` domain, only more targeted `blog.bitwarden.com` domain.

Thanks for reporting.
