### ISSUE TITLE
Demo page URL - espn.com filters don't work when redirected to regional espn domain(s)

### ISSUE THREAD

**Issue by simonrob** [yourduskquibbles/webannoyances#190]
### URL(s) where the issue occurs

`https://www.espn.co.uk/`

### Describe the issue

The [webannoyances demonstration page](https://github.com/yourduskquibbles/webannoyances/wiki/Demonstration-of-Web-Annoyances-Ultralist) uses espn.com as an example. The list's filters for that site are .com only, so if you are redirected to a regional version (e.g., espn.co.uk) then the filters aren't applied, and it doesn't provide a demonstration.

### Versions

- Browser/version: 78.0.3904.108
- uBlock Origin version: 1.23.0

### Settings

- N/A

**Comment by yourduskquibbles** [comment]
I updated the `espn.com` entries to end with wildcard `espn.*` and believe this should be fixed now assuming all of the regional versions use the same site template.

@simonrob are you able to update your filters and let me know if the page now works for you with the updates from https://github.com/yourduskquibbles/webannoyances/commit/3cf86534e5890339b4abb687d9dd71de266c666f ?

**Comment by yourduskquibbles** [comment]
I've tested the updates on `espn.co.uk` and `espn.com.mx` and both appear to be working now with the updated wildcard filter - I'm not sure of what other regional versions of `espn.com` would get served after detecting user location by current IP so think this should be fixed now but will wait for confirmation before closing.

**Comment by simonrob** [comment]
I just updated and it works now. Thanks!
