### ISSUE TITLE
Twitter filter breaking Tweetdeck

### ISSUE THREAD

**Issue by data-enabler** [yourduskquibbles/webannoyances#192]
### URL(s) where the issue occurs

`https://tweetdeck.twitter.com/`

### Describe the issue

Looks like one of the twitter.com filters breaks the sidebar layout in Tweetdeck.

### Screenshot(s)

![2019-12-23_16-39-40_firefox](https://user-images.githubusercontent.com/1616815/71381860-64d81080-25a3-11ea-9185-f9045af90a87.png)

### Versions

- Browser/version: Firefox 71.0
- uBlock Origin version: 1.24.2

### Settings

- default

### Notes

I think it's the `header > div` filter in this line:
https://github.com/yourduskquibbles/webannoyances/blob/2bec799f1b2916c3f720ff03c717ded2e76b25f9/filters/css_style_filters.txt#L6543

**Comment by yourduskquibbles** [comment]
Thanks for reporting! Please purge cache and update filters and let me know if the issue is still happening!
