### ISSUE TITLE
gameplay.tips

### ISSUE THREAD

**Issue by krystian3w** [yourduskquibbles/webannoyances#193]
### URL(s) where the issue occurs

`https://gameplay.tips/guides/5389-noita.html`

### Describe the issue

floating player - no contain with related to the article.

### Screenshot(s)

N/A

### Versions

- Browser/version:  Firefox 72
- uBlock Origin version: 1.24.2

### Settings

- Default + `webannoyances`

### Notes

```
gameplay.tips##.ac-floated-player.ac-player-wrapper
```

or remove all: `gameplay.tips##.ac-lre-player-ph:has-text(Recommend)`

**Comment by yourduskquibbles** [comment]
Seems like its ads, why not network filter `||anyclip.com^$domain=gameplay.tips` ?

Are there any articles the video is related?

**Comment by krystian3w** [comment]
> Are there any articles the video is related?

IMO no.

**Comment by yourduskquibbles** [comment]
@krystian3w thanks for tagging me, removed this based on https://github.com/uBlockOrigin/uAssets/issues/7327#issuecomment-625795859
