### ISSUE TITLE
DailyFX Sticky Header

### ISSUE THREAD

**Issue by hjstephens09** [yourduskquibbles/webannoyances#196]
### URL(s) where the issue occurs

https://www.dailyfx.com/sentiment-report

### Describe the issue

DailyFX's top website navigation / sticky header blocks your view as you scroll.

### Screenshot(s)

https://postimg.cc/VS3h78Hn

### Versions

- Browser & Version: Firefox Beta 74.01b + Safari + Chrome clones
- Adblocker (uBlock Origin) & Version: uBlock Origin v1.24.5b5

### Settings

- Default lists

### Notes

Long-standing annoyance on DailyFX. Not recent.

**Comment by yourduskquibbles** [comment]
Thanks for reporting, I think this should be fixed now but please let me know if issue still persists.

**Comment by hjstephens09** [comment]
Superb. A polished fix. Much better than the response I got [elsewhere](https://www.reddit.com/r/uBlockOrigin/comments/f3ftei/dailyfxs_top_website_navigation_sticky_header/).

Thanks for making this awesome filter list!
