### ISSUE TITLE
github.com

### ISSUE THREAD

**Issue by krystian3w** [yourduskquibbles/webannoyances#197]
https://github.com/notifications/beta

---

https://github.com/yourduskquibbles/webannoyances/issues/112

---

New github notification bar:

![obraz](https://user-images.githubusercontent.com/35370833/74575843-d40d2800-4f88-11ea-86e5-0073ddbbc500.png)

as long no marked `done` or closed by ❌.
```
##.js-notification-top-shelf.notifications-v2.is-stuck
```

or maybe better:

```
##.js-position-sticky.is-stuck
```

**Comment by yourduskquibbles** [comment]
I think `github.com##.notifications-v2:style(position: static !important;)` is best option

**Comment by krystian3w** [comment]
IMO no needed CSS...

**Comment by yourduskquibbles** [comment]
without CSS won't it entirely hide the bar which serves some purpose and changes intended site functionality?

**Comment by krystian3w** [comment]
In beta mobile possible generate glitch with positon static:

![obraz](https://user-images.githubusercontent.com/35370833/74680449-ee314b00-51c0-11ea-940a-aaaa39f3b4c9.png)

**Comment by krystian3w** [comment]
![obraz](https://user-images.githubusercontent.com/35370833/74680618-7a437280-51c1-11ea-8b3d-c0bd8a1bc4eb.png)

**Comment by yourduskquibbles** [comment]
@krystian3w glitch being space between header bar and notification bar on mobile?

**Comment by yourduskquibbles** [comment]
> 
> 
> @krystian3w glitch being space between header bar and notification bar on mobile?

I think if this is the issue you are talking about adding 
```
github.com##.pagehead:style(position: static !important; margin-bottom: 0 !important;)
github.com##.repository-content:style(margin-top: 24px !important;)
``` 

effectively fixes this display difference between mobile & desktop. I will add this nonetheless but hoping that is what you are talking about and there is not some other issue I am not seeing.

**Comment by krystian3w** [comment]
Or `visiblility hidden` (and ignore white space when slow scroll - better as gray 'box').

**Comment by yourduskquibbles** [comment]
@krystian3w Thx for report and feedback for mobile

**Comment by krystian3w** [comment]
Similar work latest:

`||github.com/*?notification_referrer_id=$removeparam=notification_referrer_id`
