### ISSUE TITLE
Sticky Header: YourDictionary.com

### ISSUE THREAD

**Issue by hjstephens09** [yourduskquibbles/webannoyances#199]
### URL(s) where the issue occurs
https://www.yourdictionary.com/about.html

### Describe the issue

Header doesn't stick to top of page as you scroll.

### Screenshot(s)

https://postimg.cc/MMDNNht3

### Versions

- Browser & Version: Firefox 73.0.1 (stable release)
- Adblockers: uBlock Origin 1.25.1b7; Nano Defender 15.0.0.185

### Settings

https://postimg.cc/BPJs1T7k

### Notes

Tested on other browsers without any adblocking on: Microsoft Edgium Dev and Safari stable.

**Comment by yourduskquibbles** [comment]
@hjstephens09 Thanks for reporting! This should be fixed now, please let me know if you see any other issues.
