### ISSUE TITLE
This filter breaks StackExchange websites

### ISSUE THREAD

**Issue by Fabian42** [yourduskquibbles/webannoyances#201]
### URL(s) where the issue occurs

`https://stackoverflow.com/`
`https://superuser.com/`
`https://meta.stackexchange.com/`
…

### Describe the issue

The StackExchange websites get completely broken by this filter. It blocks its CSS and even when those are manually unblocked, the own profile picture, inbox, reputation and other icons are missing, as well as the site logo, the JavaScript to open the inbox and other popups (it opens a new website instead, like it does in a new tab when Ctrl-clicking on them), images embedded into posts are blocked, the site indicator icons for links in the sidebar are gone, the number of people currently in a chat apparently can't be retrieved (it shows "visit chat" instead) and so on.

### Screenshot(s)

![adguard_se](https://user-images.githubusercontent.com/10481506/75843647-e930e600-5dd3-11ea-8ffb-a93f76b14a02.png)

### Versions

- Browser & Version: Firefox 73.0.1
- Adblocker (uBlock Origin, Adguard, Nano Adblocker, etc.) & Version: AdGuard browser extension 3.3.8

### Settings

- "all the changes you made to your Adblocker's default settings": Many, but none should really matter for this case.

### Notes

Getting the website to work or not work after disabling/enabling the filter seems to require waiting a few seconds and then usually also reloading with Ctrl+F5.

**Comment by yourduskquibbles** [comment]
Sorry @Fabian42! That was a bad typo, and it should be fixed now. 

Please update your filterlist - please note it may take some time for it to be pushed in the background to the Adguard server cache of `Web Annoyances Ultralist` so you can temporarily add `@@t` to `User Rules` (see screenshot below) to create an exception filter to override the badfilter if just updating your filters does nothing to fix the problem.

![image](https://user-images.githubusercontent.com/22258847/75847147-60528400-5dac-11ea-88da-0a9ee82986ad.png)

**Comment by Fabian42** [comment]
Confirmed fixed.
