### ISSUE TITLE
Blocking Quote and Reply buttons on nodeBB forum posts

### ISSUE THREAD

**Issue by levicki** [yourduskquibbles/webannoyances#202]
### URL(s) where the issue occurs

`https://what.thedailywtf.com/topic/20319/wtf-bites/26325`

### Describe the issue

This list blocks Quote and Reply buttons on individual posts making it impossible to quote or reply directly.

### Screenshot(s)

With list:
![image](https://user-images.githubusercontent.com/16415478/76325639-d6dd0d80-62e7-11ea-90cc-ef33087e4274.png)

Without list:
![image](https://user-images.githubusercontent.com/16415478/76325692-e6f4ed00-62e7-11ea-8bb7-e946b3913f18.png)

### Versions

- Browser & Version: Safari iOS
- Adblocker (uBlock Origin, Adguard, Nano Adblocker, etc.) & Version: AdGuard 3.1.4

### Settings

Filters in use.

Ad Blocking:
AdGuard Base,
AdGuard Mobile Ads,
EasyList,
Peter Lowe's Blocklist

Privacy:
AdGuard Tracking Protection,
EasyPrivacy,
Fanboy's Enhanced Tracking List

Social Widgets:
AdGuard Social Media,
Fanboy's Social Blocking List

Annoyances:
AdGuard Annoyances,
Fanboy's Annoyances,
Web Annoyances Ultralist,
Adblock Warning Removal List,
I don't care about cookies,
EasyList Cookie List

### Notes

I initially reported this issue to AdGuard and they determined it is your list:
https://github.com/AdguardTeam/AdguardFilters/issues/51171

**Comment by yourduskquibbles** [comment]
Thanks for reporting, this should be fixed now, please let me know if issue still happening for you after Adguard rules are updated.

**Comment by levicki** [comment]
It is fixed, thanks!

Sent from my iPhone

> On 10 Mar 2020, at 16:10, yourduskquibbles <notifications@github.com> wrote:
> 

﻿
Thanks for reporting, this should be fixed now, please let me know if issue still happening for you after Adguard rules are updated.
