### ISSUE TITLE
Scroll.in not displaying articles

### ISSUE THREAD

**Issue by shscs911** [yourduskquibbles/webannoyances#203]
### Scroll.in

https://scroll.in/

### Describe the issue

Scroll.in not displaying any articles, when Web Annoyances Ultralist is enabled. Works normally, when its disabled.

### Screenshot(s)
![With Web Annoyances Ultralist enabled](https://user-images.githubusercontent.com/44034402/76400844-f8e99500-63a6-11ea-8101-09ed27d23092.png)
With Web Annoyances Ultralist enabled

![With Web Annoyances Ultralist disabled](https://user-images.githubusercontent.com/44034402/76400892-0e5ebf00-63a7-11ea-8451-35c26c78846f.png)
With Web Annoyances Ultralist disabled

### Versions

- Browser: Firefox Developer Edition 74.0b9 (64-bit)
- Adblocker: uBlock Origin 1.25.1rc3

### Notes

I think these filters are the problem:
- `scroll.in##.scroll-navigation-container:style(position: relative !important;)`
- `##.scroll-box`

**Comment by yourduskquibbles** [comment]
@shscs911 Thanks for reporting and investigating! This should be fixed now. please let me know if you still see issues.

**Comment by shscs911** [comment]
Thanks @yourduskquibbles, its perfect now.
