### ISSUE TITLE
The Atlantic

### ISSUE THREAD

**Issue by hjstephens09** [yourduskquibbles/webannoyances#204]
### URL(s) where the issue occurs

https://www.theatlantic.com/

### Describe the issue

Subscription banner occurs at the bottom of the page. This does not occur when you click on an article to read. I am using [Bypass Paywalls Clean](https://github.com/magnolia1234/bypass-paywalls-firefox-clean) and uBlock Origin.

### Screenshot(s)

https://postimg.cc/vghmsDp2

### Versions

- Browser & Version: Firefox Stable 74.0
- Adblocker (uBlock Origin, Adguard, Nano Adblocker, etc.) & Version: uBlock Developer

### Settings

https://postimg.cc/ZBshH3km

**Comment by yourduskquibbles** [comment]
Thanks for reporting! This should be fixed now. Please let me know if you see any other issues.
