### ISSUE TITLE
9to5 sites

### ISSUE THREAD

**Issue by hjstephens09** [yourduskquibbles/webannoyances#205]
`https://9to5toys.com/2020/03/17/self-distancing-apple-movie-sale`but affects all _9to5_ sites: `https://9to5google.com, https://9to5mac.com/, https://9to5toys.com`

### Describe the issue

Social media icons.

### Screenshot(s)

https://postimg.cc/jnr7JdQd

### Versions

- Browser & Version: Firefox ESR / Waterfox Current
- Adblocker & Version: uBlock Origin Developer

### Settings

https://postimg.cc/KRWgnN5H
Does uBlock Annoyances need to be active with Ultralist?

**Comment by yourduskquibbles** [comment]
I recommend to use uBlock Annoyances with Web Annoyances Ultralist but I don't use any other Annoyance filterlists. That being said, I can't reproduce your issue unless I ignore generic filters on the sites so it could also be another list disabling generic filters on these domains, perhaps one of easylist annoyance lists? Or do you have generic filters disabled?

![ubo](https://user-images.githubusercontent.com/22258847/76871879-03da7480-6842-11ea-9c63-76e879795b61.png)

I will add site specific filters in any case for the reported sites.

**Comment by yourduskquibbles** [comment]
Thanks for reporting - I added social filters for the ones I saw on your test link, I may go back and add some more site specific if I find any on other domains.

**Comment by hjstephens09** [comment]
Thanks!

Also, for your testing purposes, I did not have `Ignore generic cosmetic filters` on.
