### ISSUE TITLE
"X-Ray" blocked for Amazon Prime Video

### ISSUE THREAD

**Issue by neognomic** [yourduskquibbles/webannoyances#207]
### URL(s) where the issue occurs
`https://smile.amazon.com/gp/video/detail/B07FYV4ZC5/ref=atv_wl_hom_c_unkc_1_5`
`https://smile.amazon.com/gp/video/detail/B01DUQQ5N6/ref=atv_wl_hom_c_unkc_1_13`
A couple of other videos were tested but don't have those URLs.
However, AFAICT, it is any Amazon Prime video that has "X-Ray" available for it, which is, guesstimate, 99% of their "Prime" Videos. 

### Describe the issue

The "X-Ray" function in Amazon Prime Video is blocked(removed) when Web Annoyances Ultralist  is used(ON) with AdGuard in MS Edge-beta. When Web Annoyances Ultralist is OFF, X-Ray is available to be used.
- FYI
A brief explanation and functions of "X-Ray" in Prime Video is available here: `https://smile.amazon.com/primeinsider/video/pv-xray-tips.html`
Briefly, it provides synopsis about each actor on the screen when X-Ray is selected. 
X-Ray is only displayed upon activation by movement of on screen pointer and only activated when selected with pointer. 

IOW, the issue is that it is not an annoyance but is treated as one by Web Annoyances Ultralist.

### Screenshot(s)
[Screenshots? We don't need no stinkin' screenshots, 😁.]

### Versions
Web Annoyances Ultralist version: 1.0.4.59 (updated: march 24, 2020 12:01 am)
AFAIK there has been no other version active here.
- Browser & Version: 
Microsoft Edge is up to date: Version 81.0.416.34 (Official build) beta (64-bit)
I do not use AdGuard or Web Annoyances Ultralist for the other browsers, yet, so cannot say if this is unique to MS Edge/Edge-beta or not.
- Adblocker (uBlock Origin, Adguard, Nano Adblocker, etc.) & Version: 
AdGuard  Version 3.3.8
AVAST (anti-virus) Program Version: 20.1.2397 (build 20.1.5069.562)

### Settings
- [List here all the changes you made to your Adblocker's default settings]
Not even a small chance I know those details.  I can say that I turned on every filter that was applicable for a desktop computer running MS Edge-beta and not a duplicate of another filter, primarily to avoid being beat to death with videos that load and start without specific authorization(none work for that).

### Notes
I did not notice an issue until I watched a video with Web Annoyances Ultralist ON and AdGuard Annoyances filter ON, which were the last two "Annoyances filters" that were activated. 
I turned those two OFF and X-Ray became available (after a refresh of course). 

[Add here the result of whatever investigation work you have done: please investigate the issues you report -- this prevents burdening other volunteers. This is especially true for issues arising from settings which are very different from default ones.]
I ran some tests with one "Annoyances filter" ON and the other OFF using several different videos.

It is definitely the "Web Annoyances Ultralist" causing the problem here.

I realize this might be difficult to fix but felt it important to report because it breaks a useful function.

**Comment by yourduskquibbles** [comment]
That's an intentional filter as I personally think the xray function is horrible and extremely distracting as any minor mouse movement means the video gets blocked 😁 If you disagree with me and want to override this behaviour add the following filters below to your personal set of `User rules` to override the filter being loaded in Web Annoyances Ultralist.

```
amazon.co.uk,amazon.com#@#.actor.xrayQuickViewListItem, .show.xrayQuickView, .xrayHeaderLink, .xrayQuickViewList.collectionView
amazon.co.uk,amazon.com#@#.actor.xrayQuickViewListItem
amazon.co.uk,amazon.com#@#.show.xrayQuickView
amazon.co.uk,amazon.com#@#.xrayHeaderLink
amazon.co.uk,amazon.com#@#.xrayQuickViewList.collectionView
```


In 24 hours, you should be able to just use the first filter as I[ just combined all the xray filters](https://github.com/yourduskquibbles/webannoyances/commit/c1f6893e6885a57baa0b8d5abe572d1efc22032d) into 1 filter line but adguard will not have this cached yet so as temporary measure, providing the 4 filters not combined and the 1 line filter that combines them all.

Screenshot of where to add the above filters: 
![image](https://user-images.githubusercontent.com/22258847/77446823-47def380-6dc5-11ea-99e3-301e37772451.png)

**Comment by neognomic** [comment]
Wow. FAST! Thank you very much and will try that.

The X-Ray must be different for Amazon.UK because in USA it sits on the same line as the audio, fullscreen, bandwidth, audio, ...etc. controls/functions and NEVER auto-blocks any video until it is manually activated by selecting it. 
NB:  the small "v" next to "X-Ray"changes to a "^" 'arrow' when X-Ray is activated. Maybe yours is set as "^" to always display X-Ray(the Amazon Prime player default setup).  
I, too, found that (extremely) annoying. The active/inactive switch takes care of that, unless, of course, your Amazon player does not have it for some reason.

Frankly, I find all of Amazon player's controls to be badly done("annoying") but there's nothing to do about that. They do not care and will not change them to make them less obtrusive. I have asked but after other experiences will say it is better than what it could be. E.g., NBC News video controls are worse.

So far, Web Annoyances Ultralist 'OFF' has worked, with AdGuard Annoyances filter 'ON' and am going to go with that setup for a few days.

Anyway, thanks for the User Rule!

**Comment by yourduskquibbles** [comment]
> The X-Ray must be different for Amazon.UK because in USA it sits on the same line as the audio, fullscreen, bandwidth, audio, ...etc. controls/functions and NEVER auto-blocks any video until it is manually activated by selecting it.

My default behaviour (fully expanded x-ray menu) is below.. 
![xray](https://user-images.githubusercontent.com/22258847/77540331-43741280-6e79-11ea-9e6b-87469f7051eb.png)



I still think this information is annoying info but you're right about there being a dropdown menu. My guess is they must have changed the feature and allowed user to collapse the info like what you describe, that didn't used to be an option which was awful user experience and reason why I added the filter in the first place. There were threads on Amazon support forums with 100's of posts of people complaining about this in the past...
 
Do you know if you can set default behaviour to collapse x-ray and have that preference saved between sessions? For me it seems it doesn't and the default behaviour is to block video (fully expanded x-ray) If that is the case I will keep the filter in Web Annoyances Ultralist but if its an option that can be user set to always be collapsed between sessions and saves that state permanently I could see removing the filters from the Web Annoyances Ultralist.

**Comment by neognomic** [comment]
First I will say that I think you should keep it in your WAU filter. There are people who have no interest in the information that is available from X-Ray and would like it removed, completely. Your very nice! Web Annoyances Ultralist accomplishes that and without breaking the browser. 
AND, so far, the combined User Rule seems to be working to stop that effect. Thank you, again, for that.

Perhaps consider adding the User Rule(s) to the Web Annoyances Ultralist information? A section of "Helpful User Rules" might be a solution to have the best of both worlds, 💡.

I'm 'hooked' on X-Ray info. At first it was an (extreme) annoyance but now I miss it when I use a local video player(e.g., VLC). It truly does enrich my experience with many videos. I use it for actor information, photos and access to other Amazon videos for an actor that I would like to see perform again.  The "Trivia" are usually interesting but the "Goofs" are, generally, goofs themselves and I ignore them.
Of course that is because I can turn the X-Ray drop-down synopses display off. If the X-Ray drop-down was on all the time the controls are on, there's not even a small chance I would use Amazon Prime Video.

> Do you know if you can set default behaviour to collapse x-ray and have that preference saved between sessions?

• No. And I do not remember if I set it, somehow, years ago. I did search for it way back when but IIRC the solution was the v|^ switch and the player remembers the choice for that video.

That's the short answer. Here's more.
On my PC browser(s), hidden _is_ the default behavior for all the browsers I have used, for years, on Linux and Win XPx64, 8 and 10. Most recently I started using Edge-beta because it is the only browser that could handle 4k display properly(and 'hate' Internet Exploder) but have used Firefox, Chrome and more recently Opera on MS windoz 10 OS.  All of those are Chromium, more or less. I have used many others ...mostly on Linux.  For all that will run Amazon Prime Video player, they all have the same behavior: X-Ray synopsis is not displayed until the "v" (or "X-Ray") is clicked(activated).  As you mentioned it will disappear when the controls do and (re)display upon pointer activation. (Notably, that does not necessarily mean moving the pointer as some of those devices will just activate|refresh on their own. Shouldn't but they do.)  If the, now, "^" is clicked the switch sets X-Ray synopsis as off, "^" becomes "v" and the drop-down disappears. It stays off/hidden until X-Ray or "v" is activated/clicked again.

The behavior may be different depending on the device.  I do not know what it does on any not-so-smartphone, tablet, FireTV, ...or any other device than the PC platform. The very brief time I attempted to watch video on a not-so-smartphone, years ago, I do not recall the X-Ray being an issue.

The active/inactive setting is per video.  Stop a video with it on(displaying the X-Ray drop-down synopses) and when the video is started again, the drop-down synopses will display. If it is off, then when that video is started again, X-Ray drop-down does not display.
That video's X-Ray's display state does not change any other video display state. I.e., X-Ray drop-down is off by default on all newly started videos.

It has been years since I started using Amazon Prime Video. I do remember that, like you, I found the drop down info' to be extremely annoying when I started any video and did search for a solution. As best as I recall, the only solution I found was to use the v|^ switch. 
I use a PC so cannot speak to other devices but, AFAIK, there is no Amazon Video Player setting for that on the PC device/platform. 
However, it's been quite a few years so maybe there is an Amazon player setting for it at Amazon and I just forgot about setting it. There are player settings accessible at Amazon: Select/click the "Accounts & Lists" in the Amazon banner then scroll to and select "Your Prime Video". The "Settings is at top of the new page on the right side. There are also "Help" and a "Getting Started" selections.

X-Ray does not always display the v or ^ because it is not available for some videos. Very old videos (60-year+ old) rarely have X-Ray at all and many videos do not have the v|^ switch even if X-Ray is available.

The "session" does not matter AFAIK.  Whether a video session, browser session or OS session, the setting remains the same, independent upon one's last choice for a video. It does not display here until activated(*except as mentioned above on a per video choice).

I have empathy for your situation but do not know why it does display on your device and browser of choice, 😕. 
I have had great success with Amazon Customer Service chat and would definitely try that if all else fails. Getting to chat with a real person is a bit harder these days but if the AI does not have a satisfactory answer, one can get a live chat session, 😉.
/.

**Comment by yourduskquibbles** [comment]
Thanks for the followup, I will leave the filter in place for now and will add to my to-do list to add some common site overrides in the wiki.
