### ISSUE TITLE
nytimes.com bottom "subscribe" floating bar has re-appeared

### ISSUE THREAD

**Issue by prech** [yourduskquibbles/webannoyances#208]
### URL(s) where the issue occurs

https://www.nytimes.com/2020/03/27/health/a-heart-attack-no-it-was-the-coronavirus.html
https://www.nytimes.com/2020/03/27/business/stock-market-pandemic-coronavirus.html

### Describe the issue

Bottom "subscribe" floating bar has re-appeared.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/8314103/77807511-47549000-7045-11ea-9b94-815c0dbada51.png)

### Versions

- Browser/version: Google Chrome Version 80.0.3987.149
- uBlock Origin version: uBlock Origin v1.24.4

### Notes

The "subscribe" floating bar was previously blocked/recognized by the ultralist, so perhaps they've made some changes? 

Any ideas appreciated

**Comment by yourduskquibbles** [comment]
I can't always reproduce on my setup for some reason but I think I may have solution.

Does adding either of the 2 filters to your `My Filters` remove the floating bar for you?
`nytimes.com##[data-testid="expanded-dock"]`
or 
`nytimes.com##.expanded-dock`

**Comment by prech** [comment]
Thanks much, @yourduskquibbles 

Either filter works well. I tried with 5+ pages and never saw the bar

**Comment by yourduskquibbles** [comment]
@prech thanks for confirming! I will add it to the modal filter sublist that is part of `[ultralist.txt](https://raw.githubusercontent.com/yourduskquibbles/webannoyances/master/ultralist.txt)`

**Comment by prech** [comment]
Greetings,

It appears NYTimes.com has re-implemented this floating bar:

https://www.nytimes.com/2021/02/08/travel/mississippi-river.html
https://www.nytimes.com/2021/02/05/business/accessory-dwelling-units-parents.html

I amended the existing filter and either seemed to work well. Perhaps it can be added to the Ultralist?

```
nytimes.com##.standard-dock
nytimes.com##[data-testid="standard-dock"]
```

Thanks

**Comment by yourduskquibbles** [comment]
Sure I will add `nytimes.com##[data-testid="standard-dock"]`.

Thank you!
