### ISSUE TITLE
The Verge (theverge.com)

### ISSUE THREAD

**Issue by rdsu-pt** [yourduskquibbles/webannoyances#210]
### URL(s) where the issue occurs

https://www.theverge.com

### Describe the issue

Remove the use of cookies and other tracking technologies acceptance.

### Screenshot(s)

![2020-04-04_18h06_55](https://user-images.githubusercontent.com/10651797/78457007-1f95a580-769f-11ea-8e52-8a608cf0223f.png)

### Versions

- Vivaldi 2.11.1811.52 (Stable channel) (64-bit)
- uBlock Origin 1.24.4

### Settings

Defaults, plus:
- Web Annoyances Ultralist - Ad Placeholder Filters
- Web Annoyances Ultralist - Modal Overlay Filters
- Web Annoyances Ultralist - Newsletter Subscription Filters​​​​​

### Notes

Thanks!

**Comment by yourduskquibbles** [comment]
@rdsu-pt Thanks for reporting! This should be fixed now in `modal list`. This only seems to show up for me when connected to EU VPN.

**Comment by rdsu-pt** [comment]
@yourduskquibbles , It still have it, after update the lists, and yes I'm connected in Europe :)

! Title: Web Annoyances Ultralist - Modal Overlay Filters
! Last Modified: 11:08 2020-04-06

**Comment by yourduskquibbles** [comment]
I added only `theverge.com###privacy-consent` earlier, does also adding `theverge.com##.m-privacy-consent` to `My Filters` remove it for you?

The message div I see when connected to EU VPN is screnshot below

![image](https://user-images.githubusercontent.com/22258847/78578601-bd9f8200-77fd-11ea-954b-8d66ba21bf6d.png)


![image](https://user-images.githubusercontent.com/22258847/78578521-a8c2ee80-77fd-11ea-8ba7-7cf7fc1a99d8.png)

Or is your cosmetic filter disabled perhaps on theverge.com from your testing earlier?

**Comment by rdsu-pt** [comment]
After restart the browser, now seems to works, as it should...

Thanks!

**Comment by yourduskquibbles** [comment]
Great, thanks for double checking, I added some more items to modal list as well just in case first filter only wasn't removing for you or others.
