### ISSUE TITLE
instagram.com

### ISSUE THREAD

**Issue by krystian3w** [yourduskquibbles/webannoyances#211]
`https://www.instagram.com/instagram/`

https://github.com/yourduskquibbles/webannoyances/blob/663cbca5fe35bd6677d89ff20ab28ee56e64b202/filters/modal_filters.txt#L531

Instagram now active logon pop-up after click with left mouse button on published photos (on profile).

maybe possible detect ❌ in right corner:

> ```html
> <button class="wpO6b " type="button">
>    <svg aria-label="Close" class="_8-yf5 " fill="#ffffff" height="18" viewBox="0 0 48 48" width="18">
>       <path clip-rule="evenodd" 
>            d="M41.8 9.8L27.5 24l14.2 14.2c.6.6.6 1.5 0 2.1l-1.4 1.4c-.6.6-1.5.6-2.1 0L24 27.5 9.8 41.8c-.6.6-1.5.6-2.1 0l-1.4-1.4c-.6-.6-.6-1.5 0-2.1L20.5 24 6.2 9.8c-.6-.6-.6-1.5 0-2.1l1.4-1.4c.6-.6 1.5-.6 2.1 0L24 20.5 38.3 6.2c.6-.6 1.5-.6 2.1 0l1.4 1.4c.6.6.6 1.6 0 2.2z"
>          fill-rule="evenodd">
>       </path>
>    </svg>
> </button>
> ```

> `instagram.com###react-root ~ div[class*=" "][class$=" "][role="presentation"]:has(a[href^="/accounts/"][href*="signup/"]):not(:has(button[type="button"] > svg[aria-label][width="18"][height="18"][viewBox*="48"]))`

if no - need language specific:

`instagram.com###react-root ~ div[class*=" "][class$=" "][role="presentation"]:has(a[href^="/accounts/"][href*="signup/"]):not(:has-text(Log in to view posts from))`

**Comment by yourduskquibbles** [comment]
> instagram.com###react-root ~ div[class*=" "][class$=" "][role="presentation"]:has(a[href^="/accounts/"][href*="signup/"]):not(:has(button[type="button"] > svg[aria-label][width="18"][height="18"][viewBox*="48"]))

This seems to work for me to still show login when clicking an image, thank you for testing @krystian3w! I've also added this filter back into `uBlock Filters - Annoyances` in https://github.com/uBlockOrigin/uAssets/commit/44419a3de284ad1802740b9d007bfa401290996f

Thanks facebook for continuing to find new ways ruin the open web. 🙄

**Comment by krystian3w** [comment]
![Imgur](https://imgur.com/a3iHNeW.png) |
--- |

`instagram.com##+js(aeld, click, Ge)`

but may break after logon if event is same. Or name is randomized.
