### ISSUE TITLE
doublegames.com

### ISSUE THREAD

**Issue by vavavr00m** [yourduskquibbles/webannoyances#212]
### URL(s) where the issue occurs

`https://www.doublegames.com/`

### Describe the issue

The top banner and the social media icons at the left side of the webpage.

### Screenshot(s)

-

### Versions

- Browser & Version: Google Chrome Version 81.0.4044.113 (Official Build) (64-bit)
- Adblocker: Nano Adblocker Version: 1.0.0.142

### Settings

-

### Notes

Element picker removes the ads and social media icons:
www.doublegames.com##.top_content_adds
www.doublegames.com##.buttons

**Comment by yourduskquibbles** [comment]
@vavavr00m  Thanks for reporting! This should be fixed now

**Comment by vavavr00m** [comment]
Please add to the following as well: https://www.doublegames.de, https://www.doublegames.ru, https://www.doublegames.net, https://www.doublegames.org, https://www.doublegames.jp, https://www.doublegames.pl, https://www.doublegames.cn, https://www.doublegames.biz, https://www.doublegames.us, https://www.doublegames.info, https://no.doublegames.com, https://www.doublegames.mobi, https://www.doublegames.asia, https://gr.doublegames.com, https://www.doublegames.bz, https://bg.doublegames.com, https://www.doublegames.tv, https://www.doublegames.cc, https://www.doublegames.su, https://se.doublegames.com, https://www.doublegames.name, https://lv.doublegames.com, https://lt.doublegames.com, https://ua.doublegames.com, https://ee.doublegames.com, https://da.doublegames.com, https://he.doublegames.com, https://id.doublegames.com, https://hr.doublegames.com, https://mn.doublegames.com, https://sl.doublegames.com, https://th.doublegames.com

**Comment by yourduskquibbles** [comment]
@vavavr00m this has been updated to match as a wildcard for all of the reported domains in https://github.com/yourduskquibbles/webannoyances/issues/212#issuecomment-620285892
