### ISSUE TITLE
System76 Blog not displaying content

### ISSUE THREAD

**Issue by shscs911** [yourduskquibbles/webannoyances#213]
### System76 Blog

https://blog.system76.com/

### Describe the issue

`blog.system76.com` is displaying a blank page, when Web Annoyances Ultralist is enabled. Works normally, when the list is disabled.

### Screenshot(s)
![2020-05-01_10-50](https://user-images.githubusercontent.com/44034402/80784169-bf106000-8b99-11ea-8285-c52aeebf8d02.png)
With Web Annoyances Ultralist enabled

![2020-05-01_10-52](https://user-images.githubusercontent.com/44034402/80784220-e6672d00-8b99-11ea-9b56-411a53915a4c.png)
With Web Annoyances Ultralist disabled

### Versions

- Browser: Firefox Developer Edition 75.0b11 (64-bit)
- Adblocker: uBlock Origin v1.26.3b14

### Notes

I think one of these filters might be the problem:
- `##[href*="facebook.com/sharer.php?"]`
- `##[href*="twitter.com/intent/tweet"]`
- `##.share-item`
- `##.tumblr`

**Comment by yourduskquibbles** [comment]
@shscs911 Thanks for reporting! This should be fixed now, please let me know if still having issues. 

The generic filter `##.tumblr` was causing the issue so I've removed it from generic list since it is pretty generic class name that will probably cause other issues in future as well.

**Comment by shscs911** [comment]
Its working now. Thanks for the prompt fix.
