### ISSUE TITLE
Clean repo

### ISSUE THREAD

**Issue by KonoromiHimaries** [yourduskquibbles/webannoyances#215]
### Describe the issue
```
https://rtyley.github.io/bfg-repo-cleaner/
```

**Comment by yourduskquibbles** [comment]
Hmm, I'm not sure I understand the benefits of this... does this wipe out all commit history or somehow offer big improvement to someone cloning/mirroring the repo?

**Comment by krystian3w** [comment]
https://hub.filterlists.com/t/energized-protection-github-repo-is-down/80 If the limit is below 100 GB.
