### ISSUE TITLE
twitter.com - 'Save' button disappears when attempting to Add/remove from list

### ISSUE THREAD

**Issue by AmperAndSand** [yourduskquibbles/webannoyances#216]
### URL(s) where the issue occurs

While logged-in on Twitter → https://twitter.com/twitter → Add/remove from list

### Describe the issue

In Twitter, attempting to add/remove a Twitter account to your Lists, will make the 'Save' button disappear. To reproduce, while logged-in, go to any Twitter profile page, e.g., https://twitter.com/twitter then click on the 'three dots' button near the 'Follow' button and then click on 'Add/remove from Lists'. Attempting to check any of the existing lists will make the 'Save' button disappear.

### Screenshot(s)

Web Annoyances Ultralist​​​​​ disabled:
![](https://user-images.githubusercontent.com/1404745/82137831-f5163b00-984d-11ea-820d-fb6b352e2878.png)

Web Annoyances Ultralist​​​​​ enabled:
![](https://user-images.githubusercontent.com/1404745/82137828-f182b400-984d-11ea-8902-af6535b206a3.png)

### Versions

- Brave 1.8.96 Chromium: 81.0.4044.138 (Official Build) (64-bit)
- uBlock Origin 1.26.0

### Settings

In uBO, all options under 'Privacy' are enabled. Nothing under 'Default behavior' is enabled. In Filter Lists, all the filters in the Built-in, Ads, Privacy, Malware Domains, Annoyances and Multipurpose sections are enabled, except for Fanboy’s Social Blocking List and Fanboy's Cookie List​​​​​​​​​​​. Nothing in the Regions, languages section is enabled.

### Notes

Save button appears if Web Annoyances Ultralist is​​​​​ disabled.

**Comment by yourduskquibbles** [comment]
@AmperAndSand Thanks for reporting! I think this should be fixed now. Do you mind updating filters and letting me know if the issue is fixed for you?

**Comment by AmperAndSand** [comment]
@yourduskquibbles The issue is now fixed. Thanks!
