### ISSUE TITLE
#include directive issue

### ISSUE THREAD

**Issue by Alex-302** [yourduskquibbles/webannoyances#217]
It seems wrong path in 
`https://raw.githubusercontent.com/yourduskquibbles/webannoyances/master/filters/css_style_filters.txt`:
`!#include filters/css_companion_filters.txt`
instead of
`!#include css_companion_filters.txt`
Currently this section cannot be loaded by AdGuard and uBO. They trying to download
`https://raw.githubusercontent.com/yourduskquibbles/webannoyances/master/` **filters/filters/** `css_companion_filters.txt`

**Comment by yourduskquibbles** [comment]
@Alex-302 Yep, thanks for letting me know. I think the requirement of new syntax is a bug in the latest ubo dev build on firefox, doing a temporary workaround to cover all cases until this is fixed by including both syntaxes for now.

I had just opened an internal ticket on uBO discussion related to this
, see below

> Hi I've been away from computer mostly for last month or so due to personal reasons so haven't followed all of the latest updates with uBO closely but I noticed my [CSS_Companion_Filters](https://github.com/yourduskquibbles/webannoyances/blob/master/filters/css_companion_filters.txt) nested sublist that loads through the sublist [CSS_Style_Filters.txt](https://github.com/yourduskquibbles/webannoyances/blob/master/filters/css_style_filters.txt) included in [Ultralist.txt](https://github.com/yourduskquibbles/webannoyances/blob/master/ultralist.txt) was not loading in the latest uBO dev build [1.27.5b1](https://github.com/gorhill/uBlock/releases/tag/1.27.5b1) on firefox nightly so I changed the syntax yesterday in https://github.com/yourduskquibbles/webannoyances/commit/0b38ee26057c705da30919b8c23d2f1621b787eb but then an error is occurring in latest dev build [1.27.1b0](https://chrome.google.com/webstore/detail/ublock-origin-development/cgbcahbpdhpcegmbfconppldiemgcoii) on chrome beta because the syntax update on that version doesn't like the addition of the `filters` folder (tries to load from filters/filters now on chrome.)
> 
> Not sure if this syntax change for nested sublists was intentional or if it is a bug in `1.27.5b1`
> 
> If you need testing versions of the two different syntaxes here are raw links
> 
> 1. [updated nested sublist syntax](https://raw.githubusercontent.com/yourduskquibbles/webannoyances/4c0316a91d604ab7fb31510d38baea61a3e0495b/ultralist.txt) - This should fail to load the `css_companion_filters.txt` nested sublist on latest dev build in chrome
> 2. [Old list with previous nested sublist syntax](https://raw.githubusercontent.com/yourduskquibbles/webannoyances/0b38ee26057c705da30919b8c23d2f1621b787eb/ultralist.txt) - This should fail to load the `css_companion_filters.txt` nested sublist on latest dev build in firefox
>

**Comment by Alex-302** [comment]
Ok, thanks. We will temporary disable this filter, because our filters compiler fails on `!#include filters/css_companion_filters.txt` (this is correct behafior for our filters compiler)

**Comment by yourduskquibbles** [comment]
Update: fix for the broken behavior in ubo beta is on the radar 

See: https://github.com/uBlockOrigin/uBlock-issues/issues/1034#issuecomment-631580536

When this is fixed in latest uBO beta I will remove the extra `!include` and flag you @Alex-302

**Comment by yourduskquibbles** [comment]
@Alex-302 the nested include syntax has been reverted back to working as it was as the bug should be fixed now in latest uBO dev build [1.27.5b2](https://github.com/gorhill/uBlock/releases/tag/1.27.5b2) and

**Comment by yourduskquibbles** [comment]
> 
> 
> Ok, thanks. We will temporary disable this filter(it is still available, but will not be updated some time), because our filters compiler fails on `!#include filters/css_companion_filters.txt` (this is correct behafior for our filters compiler)

@Alex-302 This should be fixed now so you should be able to re-enable so latest updates can be fetched.

**Comment by Alex-302** [comment]
@yourduskquibbles thanks)
