### ISSUE TITLE
GitHub profile issues

### ISSUE THREAD

**Issue by chocolateboy** [yourduskquibbles/webannoyances#218]
### URL(s) where the issue occurs

GitHub profiles, e.g.:

- `https://github.com/torvalds`

### Describe the issue

A new GitHub filter (2020-05-18) and an old one (2019-02-20) mangle the GitHub profile page.

[This rule](https://github.com/yourduskquibbles/webannoyances/commit/93256dc6bf892c234ede4a658ce7171ea1ac7c8c#diff-1a1e714985b8ed05f395515ae98b2d03R3022) causes the navbar at the top of the page to float over to the right of the screen when you scroll down and back up:

```
github.com##.js-sticky.js-sticky-offset-scroll...
```

[This rule](https://github.com/yourduskquibbles/webannoyances/commit/f588b28ccbf07be3aba03763a381ba83db08e0ab#diff-1a1e714985b8ed05f395515ae98b2d03R2024) breaks the year display when there's a long contribution activity list with many years, and the screen width is greater than ~1000 px, leading to a blank block with just the years on the rhs when you scroll down:

```
github.com##.profile-timeline-year-list...
```

#### Nav Bar

![github-profile-navbar-float-right](https://user-images.githubusercontent.com/31533/82570845-aa5c3200-9b71-11ea-99a5-d80e28da49f1.png)

#### Year List

![github-profile-contribution-years-glitch](https://user-images.githubusercontent.com/31533/82569433-c5c63d80-9b6f-11ea-8ee4-e9250f298327.png)

### Versions

- Browser: Firefox 76.0.1
- Ad blocker: uBlock Origin 1.27.4

### Notes

Thanks for maintaining this list! :+1:

**Comment by yourduskquibbles** [comment]
Thanks for reporting. I am unable to reproduce what you showed in your screenshot currently with my setup..... Before I try debug a bunch of different ways to reproduce, are you able to confirm you have latest filters and/or update your filters, and make sure the version is dated `! Last Modified: 10:37 2020-05-21`? 

There was a uBO bug related to the double nested sublist `CSS_companion_filters.txt` not being loaded and I also happened to notice when `CSS_companion_filters.txt` wasn't loading the profiles were also messed up. See: https://github.com/yourduskquibbles/webannoyances/issues/217 so if your list version is during that time period it may not be using the sublist. If it is that bug, there is an [emergency release v1.27.6 of uBO stable](https://github.com/gorhill/uBlock/releases/tag/1.27.6) incoming to fix this regression.

Alternatively, you can also test if this is your issue by adding the following filter from that list to your `My Filters`? 


`github.com##.gh-header .gh-header-shadow.box-shadow, .gh-header .sticky-content, .is-placeholder, .is-stuck + .toolbar-shadow, .is-stuck .diffbar .show-if-stuck, .is-stuck.gh-header-sticky.top-0.js-sticky-offset-scroll.js-sticky, .pr-toolbar-shadow, .toolbar-shadow, .user-profile-sticky-bar`

**Comment by yourduskquibbles** [comment]
If this regression is causing the issue and you are stuck on uBO 1.27.4 you could temporarily _also_ subscribe to the [`css_companion_filters.txt`](https://github.com/yourduskquibbles/webannoyances/blob/master/filters/css_companion_filters.txt) list as custom list until 1.27.6 is rolled out. Paste the following URL `https://raw.githubusercontent.com/yourduskquibbles/webannoyances/master/filters/css_companion_filters.txt` under `Import` of `Filter Lists` tab

![image](https://user-images.githubusercontent.com/22258847/82573907-5a22a700-9b54-11ea-9fd7-ae3913b6e62c.png)

Then click yellow `Apply Changes` button at top of `Filter Lists` page.

**Comment by chocolateboy** [comment]
> Before I try debug a bunch of different ways to reproduce, are you able to confirm you have latest filters and/or update your filters, and make sure the version is dated `! Last Modified: 10:37 2020-05-21`?

I am now, yes. I last updated an hour ago, so I was using the latest version from yesterday.

> Alternatively, you can also test if this is your issue by adding the following filter from that list to your `My Filters`?

Yes, that fixes both issues. Thanks!

> If this regression is causing the issue and you are stuck on uBO 1.27.4

Thanks, I'm happy to use a workaround (I was previously disabling those rules by copying them into `My filters` and prefixing `~`) until the next release of uBO.

**Comment by chocolateboy** [comment]
FYI: just upgraded to uBO 1.27.6 (and restarted the browser) and I still see both of these issues if I uncomment the workaround. However, the issue goes away again if I subscribe to your [`css_companion_filters.txt`](https://github.com/yourduskquibbles/webannoyances/blob/master/filters/css_companion_filters.txt) list.

**Comment by yourduskquibbles** [comment]
> 
> 
> FYI: just upgraded to uBO 1.27.6 (and restarted the browser) and I still see both of these issues if I disable the workaround. However, the issue goes away again if I subscribe to your [`css_companion_filters.txt`](https://github.com/yourduskquibbles/webannoyances/blob/master/filters/css_companion_filters.txt) list.

Weird, I'm unable to reproduce on a clean chrome profile and [uBO 1.27.6 loaded through Chrome extension store](https://chrome.google.com/webstore/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm/related?hl=en)

Are you able to open the uBO logger and then go to Filter Lists tab and purge cache of Web Annoyances and update the list [1] while you have the uBO logger open and filtered to all[2] and paste a screenshot or output?


[1] purge cache and update: 
![step1](https://user-images.githubusercontent.com/22258847/82581575-c4d8e000-9b5e-11ea-826a-51e8a0f57c99.png)


[2] Logger should look like this after filter update list (hopefully no error messages): 
![logger](https://user-images.githubusercontent.com/22258847/82581521-ad99f280-9b5e-11ea-9b29-4e96f949a0fd.png)

**Comment by chocolateboy** [comment]
Thanks! I was only seeing the main list loading until I did one of the following (not sure which since I did both):

- Purged the cache and reloaded all lists
- Uninstalled this list and re-imported it

This has fixed the issue Sorry for the noise.

**Comment by yourduskquibbles** [comment]
Awesome, thanks for confirming! Not a problem as I am sure others are experiencing same issues so it is helpful to have all the steps written out anyways.
