### ISSUE TITLE
geeksforgeeks.org has 2 vertical scroll bars

### ISSUE THREAD

**Issue by GeneralKenobi1** [yourduskquibbles/webannoyances#219]
### URL(s) where the issue occurs

`https://www.geeksforgeeks.org/dynamic-programming/` and similar articles

### Describe the issue

There are two vertical scroll bars instead of 1. This messes up my mouse wheeling. I think it is being caused by this filter: `geeksforgeeks.org##body:style(overflow-x: hidden !important; overflow-y: scroll !important; padding-right: 0 !important;)`

### Screenshot(s)

![2020-06-12_063816](https://user-images.githubusercontent.com/43397938/84508638-714a4580-ac77-11ea-931f-0a27ef09a706.png)

### Versions

- Browser & Version: Google Chrome 81.0.4044.92 (64-bit)
- Adblocker (uBlock Origin, Adguard, Nano Adblocker, etc.) & Version: uBlock Origin v1.26.0

**Comment by yourduskquibbles** [comment]
Thanks for reporting and investigating! This should be fixed now, please update your filters and let me know if you are still having any issues.

**Comment by GeneralKenobi1** [comment]
Confirmed working. Wow, that was like a 5 minute turnaround time. Thanks for the quick response!
