### ISSUE TITLE
radiopoznan.fm

### ISSUE THREAD

**Issue by WowDude** [yourduskquibbles/webannoyances#22]
Scrolling header

### Zrzut ekranu

![capture_057_06042018_162421](https://user-images.githubusercontent.com/37474031/38426457-fc3093ba-39b6-11e8-979d-123a8b4f0c4b.jpg)

### Link bezpośredni

http://radiopoznan.fm/

### Co trzeba zrobić, aby pojawił się element, reklama albo błąd?

1. Visit the page

### Moja konfiguracja
Win 7 SP1 [64bit]
Firefox 59.0.2 [64bit]
uBlock Origin 1.15.24

### Filtry:

<details>
  <summary>Click to expand</summary>

Nano Defender 13.48
Nano Defender filter
Nano Base filter
Nano Whitelist filter
uBlock filters
uBlock filters – Annoyances
uBlock filters – Badware risks
uBlock filters – Privacy
uBlock filters – Resource abuse​​​​​
uBlock filters – Unbreak
Adguard’s Annoyance List
Adguard Base Filters
Adguard Spyware Filters
Adblock & uBlock polish filter - AdGuard supplement
Adblock Warning Removal List
EasyList
EasyList Polish
EasyPrivacy
Fanboy’s Annoyance List
Fanboy’s Anti-Thirdparty Social (see warning inside list)
Fanboy’s Cookiemonster List
Fanboy’s Enhanced Tracking List
Fanboy's Polish
Fanboy’s Social Blocking List
I'm OK with cookies​
I don't care about cookies
hpHosts’ Ad and tracking servers
Peter Lowe’s Ad and tracking server list
POL: polskie filtry do Adblocka i uBlocka
Polish Privacy Filters
Polskie Filtry Anty-Donacyjne
Polskie Filtry Ciasteczkowe​
Polskie Filtry Elementów Irytujących
Polskie Filtry RSS​
Polskie Filtry Społecznościowe​
Polskie Filtry Wewnętrzne
AlleBlock​
KAD - Przekręty

</details>

**Comment by yourduskquibbles** [comment]
Thanks for reporting! I'm not sure yet how to fix this one because the content loads within an iframe. I will need to investigate when I have more time to see if it is possible for uBlock Origin to see inside the iframe and apply a cosmetic filter.

**Comment by yourduskquibbles** [comment]
I think the filter in [a88d995](https://github.com/yourduskquibbles/webannoyances/commit/a88d9952182dc9787a277236b30c209c349173e8) works, please update your filterlist and test and make sure.

**Comment by yourduskquibbles** [comment]
Agreed, please update filters again and validate this works for you. Thanks!

**Comment by WowDude** [comment]
Yes, it's fixed.
