### ISSUE TITLE
Kubernetes Documentation page shows garbled banner

### ISSUE THREAD

**Issue by shscs911** [yourduskquibbles/webannoyances#221]
### Kubernetes Docs

https://kubernetes.io/docs/home/

### Describe the issue

`https://kubernetes.io/docs/home/` is displaying a garbled `Black Lives Matter` banner, when Web Annoyances Ultralist is enabled. Works normally, when the list is disabled. Weird thing is that Kubernetes homepage has the same banner, but works normally when Web Annoyances Ultralist is enabled.

### Screenshot(s)

With Web Annoyances Ultralist enabled
![Screenshot_20200620_001037](https://user-images.githubusercontent.com/44034402/85170573-35bd0600-b28b-11ea-9f0d-d9ee44cb28d9.png)

With Web Annoyances Ultralist disabled
![Screenshot_20200620_001111](https://user-images.githubusercontent.com/44034402/85170586-3bb2e700-b28b-11ea-83cf-16b2ba6acb22.png)

### Versions

- Browser: Firefox Developer Edition 75.0b11 (64-bit)
- Adblocker: uBlock Origin v1.27.11b8

### Notes

I think this filter might be the problem:
- `##header:style(position: absolute !important; transform: none !important;)`

**Comment by yourduskquibbles** [comment]
@shscs911 Thanks for reporting, I think this should be fixed now but please let me know if you still have issues after a filter update.

**Comment by shscs911** [comment]
Its fixed now. Thanks.
