### ISSUE TITLE
unsplash.com search box blocked

### ISSUE THREAD

**Issue by GeneralKenobi1** [yourduskquibbles/webannoyances#222]
### URL(s) where the issue occurs

https://unsplash.com/s/photos/computer

### Describe the issue

Free stock image website. The search box is essential for searching the website for images. The search box appears to be permanently blocked by this filter: `unsplash.com##.mV0BM._2jvJJ`

### Screenshot(s)

uBlock Origin for Chrome off:

![2020-06-23_051538](https://user-images.githubusercontent.com/43397938/85402484-a163d500-b510-11ea-90de-c80ce2fe0ff3.png)

uBlock Origin for Chrome on:

![2020-06-23_051551](https://user-images.githubusercontent.com/43397938/85402528-b04a8780-b510-11ea-86b2-fbf09c3d1aca.png)

### Versions

- Browser & Version: Google Chrome 83.0.4103.106
- Adblocker (uBlock Origin, Adguard, Nano Adblocker, etc.) & Version: uBlock Origin Chrome 1.27.10
- Windows 7

### Notes

Consider deleting `unsplash.com##.mV0BM._2jvJJ`

**Comment by yourduskquibbles** [comment]
@GeneralKenobi1 Thanks for reporting! This should be fixed now after a filter update - please let me know if you are still having issues though.
