### ISSUE TITLE
soundcloud.com

### ISSUE THREAD

**Issue by epic-account** [yourduskquibbles/webannoyances#223]
### URL(s) where the issue occurs

`https://soundcloud.com/wombcorps/rip-fotze-response-to-breakforce-one-baby-demo-viju-send-for-amen-tal-jungle-syndicate/recommended`

### Describe the issue

Scroll down a bit and the box overlaps the relevant tracks

### Screenshot(s)

![2020-06-23 19-47-59](https://user-images.githubusercontent.com/58827198/85421385-cd716b80-b58d-11ea-8c6f-397ffa561a37.png)

### Versions

- Browser & Version: Firefox Nightly 79.0a1 (2020-06-23)
- Adblocker (uBlock Origin, Adguard, Nano Adblocker, etc.) & Version: uBlock Origin 1.27.10

### Notes

```
soundcloud.com##.l-fixed-top-one-column > .l-top:style(position: absolute !important;top: 89px !important;)
soundcloud.com##.relatedList__explanation
soundcloud.com##.userNetwork__subheadlineWrapper
```
this seems to have fixed this

**Comment by yourduskquibbles** [comment]
@epic-account Thanks for reporting and investigating! Should be fixed now after you update your filters, please let me know if you are still having issues.
