### ISSUE TITLE
GitHub profile header

### ISSUE THREAD

**Issue by epic-account** [yourduskquibbles/webannoyances#224]
### URL(s) where the issue occurs

`https://github.com/gorhill`

### Describe the issue

Header always stays on screen

### Screenshot(s)

![2020-06-23 23-02-04](https://user-images.githubusercontent.com/58827198/85442509-b3de1d00-b5a9-11ea-9d03-c14c3453ec5f.png)

### Versions

- Browser & Version: Firefox Nightly 79.0a1 (2020-06-23)
- Adblocker (uBlock Origin, Adguard, Nano Adblocker, etc.) & Version: uBlock Origin 1.27.10

**Comment by yourduskquibbles** [comment]
@epic-account Thanks for reporting, this should be fixed now. github loves to update their site design 😀
