### ISSUE TITLE
github.com

### ISSUE THREAD

**Issue by epic-account** [yourduskquibbles/webannoyances#226]
### URL(s) where the issue occurs

`https://github.com/uBlockOrigin`

### Describe the issue

There should be a space between the search bar and the header

### Screenshot(s)

![2020-06-25 15-05-47](https://user-images.githubusercontent.com/58827198/85699879-4dfeac00-b6f5-11ea-9397-65f8bb869d8d.png)

### Versions

- Browser & Version: Firefox Nightly 79.0a1 (2020-06-24)
- Adblocker (uBlock Origin, Adguard, Nano Adblocker, etc.) & Version: 1.27.10

**Comment by yourduskquibbles** [comment]
@epic-account Thanks for reporting! This should be fixed now after a filter update but please let me know if you find other issues.
