### ISSUE TITLE
citi.com :style filter misbehaving

### ISSUE THREAD

**Issue by RedDragonWebDesign** [yourduskquibbles/webannoyances#233]
### URL(s) where the issue occurs

`https://online.citi.com/US/ag/accountdetails`

### Describe the issue

Definitely the style filter:
- Feedback button plants itself in the middle of the screen (position absolute).
- Live Chat button at first plants itself by the feedback button, then as you move around the screen it floats with you as the page scrolls to random places.

May be unrelated or a different filter:
- Clicking on either button currently creates a modal on the bottom right, that gets stuck and shows infinite loading screen, then shows "Please refresh the page and start a new conversation."

### Screenshot(s)

![2020-07-17_011741](https://user-images.githubusercontent.com/43397938/87765990-5cf4ed80-c7cd-11ea-8dde-41b0934a5137.png)

![2020-07-17_011808](https://user-images.githubusercontent.com/43397938/87765998-61b9a180-c7cd-11ea-96f3-0d73c696367b.png)

![2020-07-17_013132](https://user-images.githubusercontent.com/43397938/87766008-667e5580-c7cd-11ea-9a9d-7ef8779d0f6e.png)

![2020-07-17_012242](https://user-images.githubusercontent.com/43397938/87766014-68481900-c7cd-11ea-8962-9eb6b0928d61.png)

### Notes

- :style filter in question is `citi.com###nebula_div_btn, .olUpNewIcon.feedbackDesktop:style(position: absolute !important;)`. Turning this off temporarily fixed the first 2 bullets.
- There is a feedback link in the footer, so we can probably just nuke the floating feedback button all together if that's easier.
- I think this only occurs for logged in users, so may be hard to test.
- The buttons aren't super intrusive. Removing the filter may be easier than fixing it.
- Careful. This may be an entire bottom footer of some kind, also containing open chat windows, similar to the one used on Facebook and LinkedIn for instant messages.

**Comment by yourduskquibbles** [comment]
I will remove the position filters for this one, agree it is not obtrusive. 

The live chat not working is because of `*$websocket,3p,domain=citi.com` filter in EasyPrivacy. 

Adding `@@||va.msg.liveperson.net^$websocket,domain=online.citi.com` fixes this issue but I think that filter should be added to EasyPrivacy. I can open an issue on EasyList or maybe tagging @ryanbr he will see this. In the mean time I'll add that filter to `uBlock filters - Unbreak` list.

**Comment by yourduskquibbles** [comment]
@RedDragonWebDesign The live chat should be fix now in `uBlock - Unbreak List` now, thanks for reporting and let me know if other issues please!
