### ISSUE TITLE
Error on the page https://disconnect.me/trackerprotection

### ISSUE THREAD

**Issue by Jose1971AB** [yourduskquibbles/webannoyances#236]
Hey, buddy, good night.

I don't know if my problem is to post on this forum. If not, I'd appreciate it if you'd point me in the right direction.
### URL(s) where the issue occurs
`[https://disconnect.me/trackerprotection]`

### Describe the issue
The page presents an error when the filter Web Annoyances Ultralist is activated. See the screenshots and you will understand it much better.

### Screenshot(s)
**Faults (2 images)**
![1](https://user-images.githubusercontent.com/44229110/88339040-a0091080-cd39-11ea-8944-6ed579267ce5.jpg)

![2](https://user-images.githubusercontent.com/44229110/88339100-be6f0c00-cd39-11ea-9596-0b63f103e06b.jpg)

**My custom uBlock Origins settings**
![AA](https://user-images.githubusercontent.com/44229110/88339366-350c0980-cd3a-11ea-8200-074cce5965d5.jpg)

### Versions

- Browser & Version: [firefox 64-bit v78.0.2]
- Adblocker (uBlock Origin, Adguard, Nano Adblocker, etc.) & Version: [uBlock Origins v1.28.4]

### Settings

- [List here all the changes you made to your Adblocker's default settings]
Please see the Screenshot(s) section for the custom uBlock Origins settings

### Notes

Well, I have been deactivating the filters one by one and reloading the page until I have found the one that causes the failure, in this case Web Annoyances Ultralist.

If you need any further information, please do not hesitate to ask me.

A greeting and thank you very much in advance, good night

**Comment by yourduskquibbles** [comment]
@Jose1971AB Thank you for reporting and showing screenshots, this should be fixed now. Please let me know if any other issues.

**Comment by Jose1971AB** [comment]
Hello @yourduskquibbles, good morning...

**Thank you very much for everything, it's working.**

I'm preparing another incident for you.

Thank you, my friend, a greeting.
