### ISSUE TITLE
www.cbc.ca/news

### ISSUE THREAD

**Issue by WorldIRC** [yourduskquibbles/webannoyances#242]
### URL(s) where the issue occurs

`www.cbc.ca`

### Describe the issue

CBC News header in left corner is broken.

### Screenshot(s)

![AdGuard Off](https://user-images.githubusercontent.com/69649971/90179339-4d8ca400-dd7b-11ea-92a2-c5bd9d1fad09.png)

![AdGuard On](https://user-images.githubusercontent.com/69649971/90179372-59786600-dd7b-11ea-9422-21041c8bc2b3.png)

### Versions

- Browser & Version: Firefox, Chrome, Safari, all latest versions
- Adblocker (uBlock Origin, Adguard, Nano Adblocker, etc.) & Version: AdGuard latest version on all platforms

### Settings

- Disabling cbc.ca#$##section-link-title > .icon { display: inline-block !important; opacity: 1 !important; } from your filter resolves the issue

### Notes

See above. Disabling one line from filter resolves issue

**Comment by yourduskquibbles** [comment]
@WorldIRC Thanks for the detailed report! I was able to reproduce on a random news article `https://www.cbc.ca/news/world/israel-uae-reach-historic-deal-diplomatic-relations-1.5684905`

This should be fixed now. Please let me know if other issues.

**Comment by yourduskquibbles** [comment]
> 
> 
> Will there be an update that is pushed to the filter? If so, I will let you know once it reaches AdGuard!

Yes, AdGuard seems to push filter updates about once every 24 hours so this should be fixed in the hosted AdGuard version within the next 24 hours.

**Comment by WorldIRC** [comment]
Updated and all good. Thanks again!
