### ISSUE TITLE
github.com - Year list gets cut off

### ISSUE THREAD

**Issue by epic-account** [yourduskquibbles/webannoyances#248]
### URL(s) where the issue occurs

`https://github.com/dylanaraps`

### Describe the issue

title

### Screenshot(s)

![firefox_2020-09-12_21-42-34](https://user-images.githubusercontent.com/58827198/93000460-12c88800-f542-11ea-925f-f44423c0150c.png)

### Versions

- Browser & Version: Firefox Nightly 82.0a1
- Adblocker (uBlock Origin, Adguard, Nano Adblocker, etc.) & Version: uBlock Origin 1.29.2

**Comment by yourduskquibbles** [comment]
@epic-account thanks for reporting! I believe this should be fixed now; please let me know if still having issues after purge cache and update filter lists.
