### ISSUE TITLE
github.com logged in homepage - scrolling down messes up left aside

### ISSUE THREAD

**Issue by RedDragonWebDesign** [yourduskquibbles/webannoyances#251]
### URL(s) where the issue occurs

https://www.github.com/ - must be logged in

### Describe the issue

Steps to reproduce

1) Log into github
2) Go to https://www.github.com/
3) Scroll down a little bit. Screen may look like screenshot

### Screenshot(s)

![2020-09-24_154419](https://user-images.githubusercontent.com/43397938/94207815-462ddf80-fe7d-11ea-8b9b-bb19d7a20e8c.png)

### Versions

- Browser & Version: Chrome 85
- Adblocker (uBlock Origin, Adguard, Nano Adblocker, etc.) & Version: ubo dev 1.29.3b6

...

- Browser & Version: Edge 84
- Adblocker (uBlock Origin, Adguard, Nano Adblocker, etc.) & Version: ubo 1.29.2

### Settings

- all annoyances lists
- web annoyances ultralist
- block everything

**Comment by yourduskquibbles** [comment]
@RedDragonWebDesign I can't recreate, can you confirm you are still having this issue after updating your filter list to include the change from https://github.com/yourduskquibbles/webannoyances/commit/5d05895f68a1a76102b461ee975ecb2b0da2b5e8 ?

I noticed that and thought I fixed that with https://github.com/yourduskquibbles/webannoyances/commit/5d05895f68a1a76102b461ee975ecb2b0da2b5e8 but maybe it is still happening under certain viewport settings

**Comment by RedDragonWebDesign** [comment]
It's fixed for me now in both browsers. Maybe that commit fixed it.

Thanks for your help. Closing for now.
