### ISSUE TITLE
w3resource.com - floating header

### ISSUE THREAD

**Issue by RedDragonWebDesign** [yourduskquibbles/webannoyances#253]
https://www.w3resource.com/php/data-types/integer-floating-point-number.php

This webpage has a floating header on desktop. I tried writing a filter but I couldn't get it working. If you have time, can you assist? I tried...

````
w3resource.com##.mdl-layout__content:style(height: unset !important; overflow-y: none !important;)
w3resource.com##body:style(overflow-y: overflow !important; height: unset !important;)
````

Thanks for your help.

**Comment by yourduskquibbles** [comment]
I think only one filter is needed: `w3resource.com##.mdl-layout__content:style(overflow: unset !important;)`

This one is relatively easy sometimes there are a lot of hacky solutions needed for sites like this to remove the scroll bar from the lower level DOM element (e.g. `main` and add it back to the higher level DOM element e.g. `html` or `body`.

For example:
```
messages.google.com##.container:style(overflow-y: auto !important;)
messages.google.com##.content-container:style(overflow: unset !important;)
messages.google.com##.h-c-header--product-marketing-one-tier.h-is-wholly-scrolled .h-c-header__bar, .h-c-header__bar:style(position: absolute !important; transform: translate3d(0,0,0) !important;)
```
