### ISSUE TITLE
buzzfeed.com

### ISSUE THREAD

**Issue by RedDragonWebDesign** [yourduskquibbles/webannoyances#255]
Can you help me write a filter for this floating header? I tried this and expected it to work, but it's not working for some reason.

    buzzfeed.com##[class^="trendingNavWrapper__"]:style(position: static !important;)

    <nav class="wrapper__3B1Hn trendingNavWrapper__1povE trendingNavSticky__7pV2n collapsedTrending__HUms3" aria-hidden="true">

![image](https://user-images.githubusercontent.com/43397938/95788187-e5314480-0c8f-11eb-8a32-7e5843cd4ec5.png)

**Comment by yourduskquibbles** [comment]
I think `buzzfeed.com##[class*="trendingNavWrapper"]:style(position: static !important; transform: translateY(0) !important;)` should work.

Also going to add `buzzfeed.com##[class*="topicNav"]:style(opacity: 1 !important;)`
