### ISSUE TITLE
drakorindofilms.cc

### ISSUE THREAD

**Issue by vavavr00m** [yourduskquibbles/webannoyances#256]
### URL(s) where the issue occurs

`[https://drakorindofilms.cc/]`

### Describe the issue

Banners & other stuff (not sure how they are called. Probably modal?)

### Screenshot(s)

None

### Versions

- Browser & Version: 
Google Chrome 86.0.4240.75 (Official Build) (64-bit)

- Adblockers:
Adguard 7.5 nightly 33 (build 3407, CL 1.7.114) for Windows
Nano Adblocker Version: 1.0.0.153

### Settings

- A bunch of settings were modified.

### Notes

I believe it's just not blocked by any filters that are installed.

**Comment by RedDragonWebDesign** [comment]
That site hurts my eyes a bit ; )

Here's the filters you need.

    ! floating bottom banner
    drakorindofilms.cc###fixedban

    ! inline homepage top ad banners
    drakorindofilms.cc##li:has(.iklan)

    ! inline article bottom ad banners
    drakorindofilms.cc##center:has([width="500"][height="80"])
    
The list owner will see this ticket and can decide if he wants to add these to the official list. In the meantime, you can put these in your "My filters" section of your Ad Blocker.

**Comment by vavavr00m** [comment]
@RedDragonWebDesign My eyes hurt too. Your filters worked. Thank you! However, in @yourduskquibbles's fix, only the modal is being filtered.

![image](https://user-images.githubusercontent.com/4675132/96339354-dbac4000-10c6-11eb-88b3-03f540af38ea.png)

**Comment by RedDragonWebDesign** [comment]
Interesting! Looks like he added `drakorindofilms.cc###fixedban, .iklan, center:has([width="500"][height="80"])`.

My guess is that this is equivalent to `drakorindofilms.cc###fixedban:has([width="500"][height="80"]), .iklan:has([width="500"][height="80"]), center:has([width="500"][height="80"])`

We probably need to split that into multiple filters.

**Comment by vavavr00m** [comment]
@RedDragonWebDesign that doesn't work for me.

**Comment by RedDragonWebDesign** [comment]
I edited my last post to be more clear. TLDR: yourduskquibbles will fix it when he sees this : )

**Comment by yourduskquibbles** [comment]
Oops, @RedDragonWebDesign is correct, there is a typo in the filter, the procedural filters should always be on their own line in order to work properly. 

Filters will be updated to 
```
drakorindofilms.cc###fixedban, .iklan
drakorindofilms.cc##center:has([width="500"][height="80"])
```

Will fix this, thanks for reporting back about the issue @vavavr00m!

**Comment by vavavr00m** [comment]
I confirm it's fixed. Thanks to both of you.

Note: Since Nano Adblocker was sold recently, I switched back to uBlock Origin.
