### ISSUE TITLE
marketingplatform.google.com floating topbar

### ISSUE THREAD

**Issue by RedDragonWebDesign** [yourduskquibbles/webannoyances#259]
https://marketingplatform.google.com/info?authuser=0

Probably need some `:style(overflow` type filters for this one, but I wasn't able to get it. If you get some time, can you assist? Here's what I tried.

````
marketingplatform.google.com##gap-app:style(overflow: auto !important;)
marketingplatform.google.com###suite-top-nav, .portal-page-container:style(overflow: hidden !important;)
````

![image](https://user-images.githubusercontent.com/43397938/98168480-76669600-1e9f-11eb-98f6-8d476237b907.png)

**Comment by yourduskquibbles** [comment]
@RedDragonWebDesign I think these three below fix it for me, weird combination but seems to work... not sure if it will break display or other pages if you start navigating off the main page though, if you are familiar with the site and could test it would be good.

```
marketingplatform.google.com##.flex.app-container:style(overflow: auto !important;)
marketingplatform.google.com##.layout-column:style(display: block !important;)
marketingplatform.google.com##md-content[role="main"]:style(overflow: hidden !important;)
```

**Comment by RedDragonWebDesign** [comment]
Thanks for writing those. I guess going from `display: flex` to `display: block` was the key here.

I clicked around. I wasn't able to break anything.

I think filter #1 can be deleted. I think `.flex.app-container` is set to `overflow: auto` by the page already.

**Comment by yourduskquibbles** [comment]
> I think filter #1 can be deleted. I think `.flex.app-container` is set to `overflow: auto` by the page already.

With it commented out I get no scrollbar, so going to keep it for now. Thanks for confirming.
