### ISSUE TITLE
dropbox.com

### ISSUE THREAD

**Issue by RedDragonWebDesign** [yourduskquibbles/webannoyances#263]
## Problem

missing y scroll bar

## Steps to reproduce

- Log into https://www.dropbox.com/
- Right click a file with a lot of version history, go to Version History
- Try to scroll down, y scroll bar is missing

## Problem filter

`dropbox.com##html.maestro.maestro--responsive:style(overflow-y: hidden !important;)`

**Comment by yourduskquibbles** [comment]
Do I need to have a synced dropbox folder to PC in order to test this? Do you know if I can use a random `txt` file and make edits to it a bunch of times (saving after each edit) to increase the version history in order to reproduce?

**Comment by yourduskquibbles** [comment]
@RedDragonWebDesign I think I found a way to test - does adding the following two filters fix the issue for you and not cause issues elsewhere?

```
dropbox.com#@#html.maestro.maestro--responsive:style(overflow-y: hidden !important;)
dropbox.com##html.maestro.maestro--responsive:not(.js-focus-visible):style(overflow-y: hidden !important;)
```

**Comment by RedDragonWebDesign** [comment]
Tested and working well on my end. Thanks for your time on this.

**Comment by yourduskquibbles** [comment]
Thanks for confirming
