### ISSUE TITLE
[self-promotions] centrumxp.pl, onexstore.pl

### ISSUE THREAD

**Issue by krystian3w** [yourduskquibbles/webannoyances#264]
> _Who detect self-promotion:_
> 
> _@seba2282_

### URL(s) where the issue occurs

* on top slider:
`https://www.centrumxp.pl` 

* right column ads about buy office:
`https://www.centrumxp.pl/Publikacja/PC-guy-powraca-Apple-kreuje-sie-na-pioniera-laptopow-ARM-spozniony-o-kilka-lat` 

### Describe the issue

Centrum XP have self-promotion ads with own online Shop `onexstore.pl`

### Screenshot(s)

![obraz](https://user-images.githubusercontent.com/35370833/99146322-42495d00-2677-11eb-9a89-4ded115d58b5.png) |
--- |
one slide in slider on homepage |

![obraz](https://user-images.githubusercontent.com/35370833/99146304-162ddc00-2677-11eb-93f8-a0bd93c00628.png) |
--- |
right column when read articles |
`##section.sidebar-news-grid:nth-of-type(1)` |

### Versions

- Browser & Version: FX `82.0.2`
- Adblocker (uBlock Origin, Adguard, Nano Adblocker, etc.) & Version: uBO `1.30.9rc0`

### Settings

- stock and `ultralist`.

### Notes

Slide may need use `:remove()` ~~or html filtering (Firefox only).~~

```
centrumxp.pl##a[href*="OnexStore" i] > img[src*="OnexStore" i]:upward(p.slick-slide):remove()
centrumxp.pl##.slick-dots li:nth-of-type(4) .no-focus:upward(li):remove()

centrumxp.pl##section.sidebar-news-grid:nth-of-type(1)
```

PS. AdGuard **may** still no support combination `:upward(foo):remove()`

**Comment by seba2282** [comment]
@yourduskquibbles @KonoromiHimaries what about that issue? Me and @krystian3w haven't any information what about it.

**Comment by yourduskquibbles** [comment]
@krystian3w @seba2282 On `https://www.centrumxp.pl` this filter doesn't work for me to remove anything `centrumxp.pl##.slick-dots li:nth-of-type(4) .no-focus:upward(li):remove()` 

This filter should be used in place of it?
`centrumxp.pl##.slick-dots li:nth-of-type(4) [data-role="none"]:upward(li):remove()`

**Comment by yourduskquibbles** [comment]
Please test:

```
! filters to add?
! https://www.centrumxp.pl/Publikacja/PC-guy-powraca-Apple-kreuje-sie-na-pioniera-laptopow-ARM-spozniony-o-kilka-lat
centrumxp.pl##section.sidebar-news-grid:nth-of-type(1)

! https://www.centrumxp.pl/
centrumxp.pl##a[href*="OnexStore" i] > img[src*="OnexStore" i]:upward(p.slick-slide):remove()
centrumxp.pl##.slick-dots li:nth-of-type(4) [data-role="none"]:upward(li):remove()
```

**Comment by seba2282** [comment]
centrumxp.pl##a[href*="OnexStore" i] > img[src*="OnexStore" i]:upward(p.slick-slide):remove()
centrumxp.pl##.slick-dots li:nth-of-type(4) .no-focus:upward(li):remove()

centrumxp.pl##section.sidebar-news-grid:nth-of-type(1)

That rule @yourduskquibbles try test. For me on Edge Chromium remove make white place after onexstore on centrumxp (banner top on site).

**Comment by krystian3w** [comment]
I see, maybe `.no-focus` is dynamically added after show 4th slide.

---

Now also see bug with empty 4th slide (also reported by @seba2282) - similar to use on 1st slide:

`centrumxp.pl##a[href*="OnexStore" i] > img[src*="OnexStore" i]:upward(p.slick-slide):style(visibility: hidden !important;)`

IMO website is protected to use html filtering or HTML filtering no support `[attr="foo" i]` in uBO.

**Comment by seba2282** [comment]
I will check that after few moments. Only back in home. But that slides are important on site? I tried hidden all that banner slides on top but after few was cutting first tittles names articles. @krystian3w remember that? I think was better turn off that all top banner slides + made few down articles names under. If @krystian3w know what i tell. But i don't know how make that.

**Comment by krystian3w** [comment]
> after few was cutting first tittles names articles. 

Because page lose margin, based on this added into Slider.

try:

`##.main-banner--images.main-banner > *`

or

`centrumxp.pl##.main-banner--images.main-banner:style(visibility: hidden !important; height: 0px !important; width: 0px !important; margin: 85px !important;)`

**Comment by seba2282** [comment]
@krystian3w Now site look good and promotions gone. :)

@yourduskquibbles, add that rules:

centrumxp.pl##section.sidebar-news-grid:nth-of-type(1)
centrumxp.pl##.main-banner--images.main-banner:style(visibility: hidden !important; height: 0 !important; width: 0 !important; margin: 85px !important;)

**Comment by seba2282** [comment]
@krystian3w look now if all is good. If can :) 
![centrumxp1](https://user-images.githubusercontent.com/16944478/99686555-fbe36c00-2a83-11eb-8d3c-93836cecc6fd.png)
![centrumxp2](https://user-images.githubusercontent.com/16944478/99686559-fd149900-2a83-11eb-96fb-2512ce8e2cfa.png)

**Comment by yourduskquibbles** [comment]
Can one of you two post full filters you are using and I will add them to `ad_placeholders.txt` sublist

**Comment by seba2282** [comment]
> Can one of you two post full filters you are using and I will add them to `ad_placeholders.txt` sublist

@yourduskquibbles that about banner on top you can add? @krystian3w Gave that rule to hide top banner slides on top centrumxp.pl 
About second rule on that ad with office, they made update on site and see some ads as news without tagged ad (reklama on PL). I showed that on screens.

**Comment by seba2282** [comment]
@krystian3w 
centrumxp.pl##section.sidebar-news-grid:nth-of-type(1)  (not work - update site) 
Note:  look on my screens about where are ads actually between news without tagget "reklama"

centrumxp.pl##.main-banner--images.main-banner:style(visibility: hidden !important; height: 0 !important; width: 0 !important; margin: 85px !important;)  (that look o work good still)

@yourduskquibbles here are details about rules for information. About that you asked to add?

**Comment by seba2282** [comment]
@krystian3w In code you will see: 
home-news__title Microsoft 365 Business Basic od 19.90 zł/m-c
home-news__title Microsoft 365 Family na 6 komputerów za 349 zł
I don't know, how block that two self - promotion which after connect with onexstore. Have idea?

**Comment by seba2282** [comment]
centrumxp.pl##a[href*="OnexStore" i]:remove() 

centrumxp.pl##.main-banner--images.main-banner:style(visibility: hidden !important; height: 0 !important; width: 0 !important; margin: 85px !important;)

@yourduskquibbles @krystian3w can look on that? 

Actually look good that rules.

**Comment by seba2282** [comment]
@krystian3w @yourduskquibbles I haven't any informations. Are added rules or what? Long time that issue stay and I don't know what more about.

**Comment by yourduskquibbles** [comment]
I will add 

```
centrumxp.pl##a[href*="OnexStore" i]:remove()
centrumxp.pl##.main-banner--images.main-banner:style(visibility: hidden !important; height: 0 !important; width: 0 !important; margin: 85px !important;)
centrumxp.pl##section.sidebar-news-grid:nth-of-type(1)
````

**Comment by seba2282** [comment]
@yourduskquibbles thank you. If i will see some problems in future I will give suggest fixes if I will can know how. Because i am amateur and I don't know to much in making rules. ☺️

**Comment by yourduskquibbles** [comment]
Thank you for suggestions!

**Comment by seba2282** [comment]
@yourduskquibbles centrumxp.pl need update. Remove all old rules and add that: 

`centrumxp.pl##.main-banner--images.main-banner:style(visibility: hidden !important; height: 0 !important; width: 0 !important; margin: 85px !important;)`
`centrumxp.pl##.badge-partner` 
`centrumxp.pl##a[href="http://www.qa.centrumxp.pl/"]` 
`centrumxp.pl##a[href*="onexstore"]` 
`centrumxp.pl##a[href*="onexgroup"]` 
`centrumxp.pl##a[href="http://www.microsoft-azure.pl/"]` 
`centrumxp.pl##a[href="https://www.microsoft.com/pl-PL/solution-providers/partnerdetails/OnexGroup_87a525c3-c178-40d1-9259-48841bb49941/31b16157-aca3-43dc-8ede-17cd1c32cc58"]` 
`centrumxp.pl##a[href="https://www.youtube.com/user/CentrumXPpl"]`
`centrumxp.pl##div.wrap:nth-of-type(2)`

**Comment by yourduskquibbles** [comment]
> 
> 
> @yourduskquibbles centrumxp.pl need update. Remove all old rules and add that:
> 
> `centrumxp.pl##.main-banner--images.main-banner:style(visibility: hidden !important; height: 0 !important; width: 0 !important; margin: 85px !important;)`
> `centrumxp.pl##.badge-partner`
> `centrumxp.pl##a[href="http://www.qa.centrumxp.pl/"]`
> `centrumxp.pl##a[href*="onexstore"]`
> `centrumxp.pl##a[href*="onexgroup"]`
> `centrumxp.pl##a[href="http://www.microsoft-azure.pl/"]`
> `centrumxp.pl##a[href="https://www.microsoft.com/pl-PL/solution-providers/partnerdetails/OnexGroup_87a525c3-c178-40d1-9259-48841bb49941/31b16157-aca3-43dc-8ede-17cd1c32cc58"]`
> `centrumxp.pl##a[href="https://www.youtube.com/user/CentrumXPpl"]`
> `centrumxp.pl##div.wrap:nth-of-type(2)`

@seba2282 I've added updates per your suggestion... plz let me know if need any updates after filter refresh

**Comment by seba2282** [comment]
> > 
> > 
> > @yourduskquibbles centrumxp.pl need update. Remove all old rules and add that:
> > 
> > `centrumxp.pl##.main-banner--images.main-banner:style(visibility: hidden !important; height: 0 !important; width: 0 !important; margin: 85px !important;)`
> > `centrumxp.pl##.badge-partner`
> > `centrumxp.pl##a[href="http://www.qa.centrumxp.pl/"]`
> > `centrumxp.pl##a[href*="onexstore"]`
> > `centrumxp.pl##a[href*="onexgroup"]`
> > `centrumxp.pl##a[href="http://www.microsoft-azure.pl/"]`
> > `centrumxp.pl##a[href="https://www.microsoft.com/pl-PL/solution-providers/partnerdetails/OnexGroup_87a525c3-c178-40d1-9259-48841bb49941/31b16157-aca3-43dc-8ede-17cd1c32cc58"]`
> > `centrumxp.pl##a[href="https://www.youtube.com/user/CentrumXPpl"]`
> > `centrumxp.pl##div.wrap:nth-of-type(2)`
> 
> @seba2282 I've added updates per your suggestion... plz let me know if need any updates after filter refresh



I look when I will be on PC. I made few rules as testing and work. Are two sites general subdomain for all centrumxp.pl
I make copy that rules and if you will accept to add them. 🙂

**Comment by yourduskquibbles** [comment]
Sure just let me know and I will add

**Comment by seba2282** [comment]
`centrumxp.pl##.main-banner--images.main-banner:style(visibility: hidden !important; height: 0 !important; width: 0 !important; margin: 85px !important;)`
`centrumxp.pl##.badge-partner` 
`centrumxp.pl##a[href="http://www.qa.centrumxp.pl/"]`
`centrumxp.pl##a[href*="onexstore"]` 
`centrumxp.pl##a[href*="onexgroup"]` 
`centrumxp.pl##a[href="http://www.microsoft-azure.pl/"]` 
`centrumxp.pl##a[href="https://www.microsoft.com/pl-PL/solution-providers/partnerdetails/OnexGroup_87a525c3-c178-40d1-9259-48841bb49941/31b16157-aca3-43dc-8ede-17cd1c32cc58"]` 
`centrumxp.pl##a[href="https://www.youtube.com/user/CentrumXPpl"]` 
`centrumxp.pl##div.wrap:nth-of-type(2)`
`akademia.centrumxp.pl##a[href*="sklep.centrumxp.pl"]`
`akademia.centrumxp.pl##a[href="https://partnercenter.microsoft.com/pl-pl/pcv/solution-providers/OnexGroup_87a525c3-c178-40d1-9259-48841bb49941/31b16157-aca3-43dc-8ede-17cd1c32cc58"]`
`akademia.centrumxp.pl##a[href*="OnexGroup"]`
`akademia.centrumxp.pl##.new-section--white.new-section--lg-margin.new-section`


For centrumxp.pl and akademia.centrumxp.pl

**Comment by yourduskquibbles** [comment]
@seba2282 added your filters as suggested.

I consolidated them into less lines and made some of the URL's not include the unique identifiers. Hope this helps!

**Comment by seba2282** [comment]
We will see. Thanks for helping :)

**Comment by seba2282** [comment]
Actually work all good. Thank you :)
