### ISSUE TITLE
pan.baidu.com(a cloud disk) can't share file

### ISSUE THREAD

**Issue by Lxeon** [yourduskquibbles/webannoyances#267]
### URL(s) where the issue occurs

`[https://pan.baidu.com/disk/home?#/all?path=%2F&vmode=list]`

### Describe the issue

[can't show the share file page, its cause by '###share' filter]

### Screenshot(s)

[ after filter:

![图片](https://user-images.githubusercontent.com/28784869/100382225-d216e000-3055-11eb-9bb7-72318f54e174.png)

 normal should be:
![图片](https://user-images.githubusercontent.com/28784869/100382143-9d0a8d80-3055-11eb-9784-3b55a28f4a39.png)

]

### Versions

- Browser & Version: [windows firefox 83.0 x64]
- Adblocker (uBlock Origin, Adguard, Nano Adblocker, etc.) & Version: [Adguard 7.5.3]

### Notes

[Add here the result of whatever investigation work you have done: please investigate the issues you report -- this prevents burdening other volunteers. This is especially true for issues arising from settings which are very different from default ones.]

**Comment by yourduskquibbles** [comment]
@Lxeon Thanks for reporting! I have posted a fix per your suggestion of the bad filter as the link you provided just routes me back to the home page. Please let me know if you still have any issues!
