### ISSUE TITLE
Bartaman Patrika Navbar

### ISSUE THREAD

**Issue by pidus** [yourduskquibbles/webannoyances#268]
### URL(s) where the issue occurs

https://bartamanpatrika.com/

### Describe the issue

Navbar is sticky. Reduces screen space to read content.

### Screenshot(s)

https://postimg.cc/56q1N5jg
![Screenshot_20201202_113424-1](https://user-images.githubusercontent.com/11857051/100835746-1a8a2f80-3494-11eb-98ec-9f41e3331d98.jpg)

### Versions

- Google Chrome Version 87.0.4280.66 (Official Build) (64-bit)
- Adblocker - uBlock Origin v1.31.0

### Settings

uBlock Origin Medium mode

### Notes

[Add here the result of whatever investigation work you have done: please investigate the issues you report -- this prevents burdening other volunteers. This is especially true for issues arising from settings which are very different from default ones.]

**Comment by yourduskquibbles** [comment]
@pidus Thanks for reporting! This should be fixed in `Web Annoyances Ultralist` now after you update your filter list, please let me know if you see any other issues.
