### ISSUE TITLE
broken services menu on google.com

### ISSUE THREAD

**Issue by Sergey-Lyapin** [yourduskquibbles/webannoyances#269]
Marked button don't work because of rule: 
`google.com##iframe[role="presentation"][style="height: 100%; width: 100%;"]:upward(1)`

![Screenshot 2020-12-04 at 15 52 30](https://user-images.githubusercontent.com/18536328/101166169-e86dfe80-3648-11eb-994b-cfc4eeeaafe2.png)

**Comment by Sergey-Lyapin** [comment]
@yourduskquibbles please take a look

**Comment by yourduskquibbles** [comment]
@Sergey-Lyapin Thanks for reporting, this should be fixed now by updating the filter to only target the domain `ogs.google.com`.

Related discussion: https://github.com/yourduskquibbles/webannoyances/issues/258#issuecomment-722461307
