### ISSUE TITLE
The top of the 9to5mac website overlaps with the blue navigation bar.

### ISSUE THREAD

**Issue by w6511** [yourduskquibbles/webannoyances#270]
### URL(s) where the issue occurs
https://9to5mac.com/2020/12/15/strong-iphone-12-demand/

### Describe the issue
The top of the 9to5mac website overlaps with the blue navigation bar.

### Screenshot(s)
![7C400389-865B-4FF6-BB5B-10983C000FBC](https://user-images.githubusercontent.com/65994118/102228613-daac5900-3f25-11eb-801b-e98710f3f2f0.gif)

### Versions

- Safari, iOS 14.3
- Adguard iOS Version: [4.0.4]

### Settings

- Adguard Settings - Safari protection - Filters - Annoyances - Web Annoyances Ultralist (Turn On)

**Comment by yourduskquibbles** [comment]
@w6511 Thanks for video showing issue, I think adding `9to5google.com,9to5mac.com,9to5toys.com,dronedj.com,electrek.co,spaceexplored.com#@#.site-header-placeholder, .site-header.js-header-sticky .primary-menu` will fix this, I will test and push override filter for Safari exception filter if this is the case.

**Comment by yourduskquibbles** [comment]
@w6511 Confirmed this is fixed now on my side but adguard will normally only update the cached filter list once per day so may take until tomorrow to see the fix on your side unless you add `9to5google.com,9to5mac.com,9to5toys.com,dronedj.com,electrek.co,spaceexplored.com#@#.site-header-placeholder, .site-header.js-header-sticky .primary-menu` to adguard `user rules`.


![unnamed](https://user-images.githubusercontent.com/22258847/102231267-c895d080-3ebb-11eb-991e-8d22a07a61e7.png)

**Comment by w6511** [comment]
It works. Thank you so much for your quick reply.
