### ISSUE TITLE
Cookie Notice

### ISSUE THREAD

**Issue by pidus** [yourduskquibbles/webannoyances#272]
### URL(s) where the issue occurs
https://www.timeslive.co.za/sunday-times/books/news/2020-11-29-the-kiss-of-death/
`[At least one URL for a web page where the clearly described issue occurs is **mandatory**. The backticks surrounding the URLs is important, it prevents the URL from being clickable. Warn with "NSFW" where applicable.]`

### Describe the issue
GDPR cookie notice
[Be as clear as possible: nobody can read your mind, and nobody is looking at your issue over your shoulder.]

### Screenshot(s)
![Screenshot_2020-12-31-08-20-33-292_org mozilla fenix](https://user-images.githubusercontent.com/11857051/103391797-21629b80-4b41-11eb-8264-d5151c12b096.jpg)

[Screenshot(s) for difficult to describe visual issues are **mandatory**. Post links instead of **Inline Images** for Screenshots containing **Adult material**.]

### Versions

- Browser & Version: [here] Firefox Nightly
- Adblocker (uBlock Origin, Adguard, Nano Adblocker, etc.) & Version: [here] uBlock Origin

### Settings

- [List here all the changes you made to your Adblocker's default settings]

### Notes
It can be fixed with a generic filter: `###gdpr-overlay`
[Add here the result of whatever investigation work you have done: please investigate the issues you report -- this prevents burdening other volunteers. This is especially true for issues arising from settings which are very different from default ones.]

**Comment by yourduskquibbles** [comment]
@pidus Thanks for reporting! This should be fixed now.
