### ISSUE TITLE
Fandom Wiki Pages

### ISSUE THREAD

**Issue by GeQi** [yourduskquibbles/webannoyances#274]
### URL(s) where the issue occurs

`[At least one URL for a web page where the clearly described issue occurs is **mandatory**. The backticks surrounding the URLs is important, it prevents the URL from being clickable. Warn with "NSFW" where applicable.]`

*.fandom.com
e.x.
https://elderscrolls.fandom.com/wiki/The_Elder_Scrolls_Wiki

### Describe the issue

[Be as clear as possible: nobody can read your mind, and nobody is looking at your issue over your shoulder.]

Scroll to bottom, the "Fan Feed" section is enirely unrelated to the content of the page, taking huge screen space.

Also the footer is totally unnecessary and irrelevant.

The header is more subjective, is it mostly useless but has a search bar that might be useful to some.

### Screenshot(s)

[Screenshot(s) for difficult to describe visual issues are **mandatory**. Post links instead of **Inline Images** for Screenshots containing **Adult material**.]

Fan Feed:
![image](https://user-images.githubusercontent.com/4011632/104143995-e0f3f080-537e-11eb-8865-71d3aad172ff.png)

Footer:
![image](https://user-images.githubusercontent.com/4011632/104144084-2ca69a00-537f-11eb-9aa2-964fd1318826.png)

Header:
![image](https://user-images.githubusercontent.com/4011632/104144159-5e1f6580-537f-11eb-9f89-6cf8d23de666.png)

### Versions

- Browser & Version: [Brave Version 1.18.78 Chromium: 87.0.4280.141 (Official Build) (x86_64)]
- Adblocker (uBlock Origin, Adguard, Nano Adblocker, etc.) & Version: [uBlock Origin]

### Settings

- [List here all the changes you made to your Adblocker's default settings]

### Notes

[Add here the result of whatever investigation work you have done: please investigate the issues you report -- this prevents burdening other volunteers. This is especially true for issues arising from settings which are very different from default ones.]

I propose the following filters:

```
fandom.com##.wds-global-navigation-wrapper

fandom.com##.wds-global-footer

fandom.com##.mcf-en

fandom.com###WikiaBar
```

**Comment by yourduskquibbles** [comment]
@GeQi I looked through the example page and I don't think any of these belong in `Web Annoyances Ultralist`. I suggest just adding these filters to your own Personal Filters list as they are changing the intended site design that someone else may find helpful or useful.
