### ISSUE TITLE
Nexus Mods Adblock Reminder

### ISSUE THREAD

**Issue by GeQi** [yourduskquibbles/webannoyances#275]
### URL(s) where the issue occurs

`[At least one URL for a web page where the clearly described issue occurs is **mandatory**. The backticks surrounding the URLs is important, it prevents the URL from being clickable. Warn with "NSFW" where applicable.]`

https://www.nexusmods.com/

### Describe the issue

[Be as clear as possible: nobody can read your mind, and nobody is looking at your issue over your shoulder.]

Adblock Reminder

### Screenshot(s)

[Screenshot(s) for difficult to describe visual issues are **mandatory**. Post links instead of **Inline Images** for Screenshots containing **Adult material**.]

![image](https://user-images.githubusercontent.com/4011632/104144372-2cf36500-5380-11eb-9771-fc55a5276fed.png)

### Versions

- Browser & Version: [Brave Version 1.18.78 Chromium: 87.0.4280.141 (Official Build) (x86_64)]
- Adblocker (uBlock Origin, Adguard, Nano Adblocker, etc.) & Version: [uBlock Origin]

### Settings

- [List here all the changes you made to your Adblocker's default settings]

### Notes

[Add here the result of whatever investigation work you have done: please investigate the issues you report -- this prevents burdening other volunteers. This is especially true for issues arising from settings which are very different from default ones.]

I propose:
`www.nexusmods.com##div.clearfix.agroup`

**Comment by yourduskquibbles** [comment]
@GeQi Thanks for reporting, this should be fixed now.
