### ISSUE TITLE
Slickdeals Login Page Missing Login Fields

### ISSUE THREAD

**Issue by LanikSJ** [yourduskquibbles/webannoyances#277]
### URL(s) where the issue occurs

https://slickdeals.net/forums/login.php?action_source=Log%20In%20Button

### Describe the issue

The login fields are missing

### Screenshot(s)

Broken:
![image](https://user-images.githubusercontent.com/12159404/104641875-31a96900-565f-11eb-8fa5-0f408631912d.png)
Working:
![image](https://user-images.githubusercontent.com/12159404/104641997-4b4ab080-565f-11eb-9062-0c8562f2b441.png)

### Versions

- Browser & Version: Brave Beta 1.20.78
- Adblocker: uBlock Origin & Version: 1.32.4

### Settings

Filter lists in use:
![image](https://user-images.githubusercontent.com/12159404/104642271-91a00f80-565f-11eb-8022-a6b39b0be4c0.png)

### Notes

Disabling Web Annoyances Ultralist solves the problem.

**Comment by yourduskquibbles** [comment]
@LanikSJ Thanks for reporting! Should be fixed now, let me know if you encounter any other issues please
