### ISSUE TITLE
mobalytics.gg

### ISSUE THREAD

**Issue by GeQi** [yourduskquibbles/webannoyances#281]
### URL(s) where the issue occurs

`[At least one URL for a web page where the clearly described issue occurs is **mandatory**. The backticks surrounding the URLs is important, it prevents the URL from being clickable. Warn with "NSFW" where applicable.]`

https://mobalytics.gg/blog/lor-fundamentals-mastering-mana-advantage/

### Describe the issue

[Be as clear as possible: nobody can read your mind, and nobody is looking at your issue over your shoulder.]

Header ads that persists when scrolling

### Screenshot(s)

[Screenshot(s) for difficult to describe visual issues are **mandatory**. Post links instead of **Inline Images** for Screenshots containing **Adult material**.]

![image](https://user-images.githubusercontent.com/4011632/104973748-ed95cb80-59b2-11eb-8e01-654561f051b0.png)

### Versions

- Browser & Version: [here]
- Adblocker (uBlock Origin, Adguard, Nano Adblocker, etc.) & Version: [here]

### Settings

- [List here all the changes you made to your Adblocker's default settings]

### Notes

[Add here the result of whatever investigation work you have done: please investigate the issues you report -- this prevents burdening other volunteers. This is especially true for issues arising from settings which are very different from default ones.]

`##.live-comp-wrap`

**Comment by yourduskquibbles** [comment]
@GeQi Thanks for reporting! This should be fixed now
