### ISSUE TITLE
imore.com

### ISSUE THREAD

**Issue by GeQi** [yourduskquibbles/webannoyances#282]
### URL(s) where the issue occurs

`[At least one URL for a web page where the clearly described issue occurs is **mandatory**. The backticks surrounding the URLs is important, it prevents the URL from being clickable. Warn with "NSFW" where applicable.]`

https://www.imore.com/editors-desk-another-ces-has-come-and-gone

### Describe the issue

[Be as clear as possible: nobody can read your mind, and nobody is looking at your issue over your shoulder.]

When blocking 3-rd party script and frames, this ad seems to get spawn.

### Screenshot(s)

[Screenshot(s) for difficult to describe visual issues are **mandatory**. Post links instead of **Inline Images** for Screenshots containing **Adult material**.]
![image](https://user-images.githubusercontent.com/4011632/104975842-099c6b80-59b9-11eb-92c7-ac16a73a08fb.png)

### Versions

- Browser & Version: [here]
- Adblocker (uBlock Origin, Adguard, Nano Adblocker, etc.) & Version: [here]

### Settings

- [List here all the changes you made to your Adblocker's default settings]

### Notes

[Add here the result of whatever investigation work you have done: please investigate the issues you report -- this prevents burdening other volunteers. This is especially true for issues arising from settings which are very different from default ones.]

I propose `##.no-amazon`

**Comment by yourduskquibbles** [comment]
@GeQi Thanks for reporting! This should be fixed now
