### ISSUE TITLE
journals.sagepub.com

### ISSUE THREAD

**Issue by RedDragonWebDesign** [yourduskquibbles/webannoyances#283]
https://journals.sagepub.com/doi/10.1177/1536504211399050

### Describe the issue

I'm having trouble writing filters for this one. It's got a couple of problems:

- double vertical scroll bars on the right
- unnecessary horizontal scroll bar on the bottom
- a floating PDF link that is too essential to just outright block. My attempts to make it static put it in weird positions off the screen, and JavaScript changes its position as the user scrolls.

### Screenshot(s)

![2021-01-27_161407](https://user-images.githubusercontent.com/43397938/106071263-e2315700-60ba-11eb-829b-da2086714312.png)

### Versions

- Browser & Version: Chrome, Win7, 1080p
- Adblocker (uBlock Origin, Adguard, Nano Adblocker, etc.) & Version: ubo dev

### Settings

- all annoyances lists, ubo, block everything

**Comment by yourduskquibbles** [comment]
@RedDragonWebDesign This should be fixed now. You're right this site was a mess, took a long time to figure out for the two different site widths... I could never see that floating PDF button, so hopefully its fixed for you, just let me know if these updates don't work or it's missing something

**Comment by yourduskquibbles** [comment]
PDF Print button is actually only on Chrome, need to test this further will hopefully get to it today. Everything except the pdf button should be fixed for now though.

**Comment by yourduskquibbles** [comment]
@RedDragonWebDesign I think the floating pdf button is fixed with 
```
journals.sagepub.com###gs-casa-c:style(position: absolute !important; bottom: 0 !important;)
journals.sagepub.com###gs-casa-r:style(position: unset !important; top: 0 !important;)
```

Can you test and confirm?

**Comment by RedDragonWebDesign** [comment]
Works beautiful. I looked at that commit. What a beast of a page. Thanks for taking the time.

**Comment by yourduskquibbles** [comment]
Thanks for confirming, I added those filters for the print button that shows up on chrome as well
