### ISSUE TITLE
Webpage https://apps.facebook.com/mobaheroes does not show anything

### ISSUE THREAD

**Issue by stdedos** [yourduskquibbles/webannoyances#284]
### URL(s) where the issue occurs

https://apps.facebook.com/mobaheroes

### Describe the issue

Does not show anything

### Screenshot(s)

[Screenshot(s) for difficult to describe visual issues are **mandatory**. Post links instead of **Inline Images** for Screenshots containing **Adult material**.]

### Versions

- Browser & Version: Version 87.0.4280.88 (Official Build) (64-bit)
- Adblocker (uBlock Origin, Adguard, Nano Adblocker, etc.) & Version: uBlock Origin v1.32.4

### Settings

- [List here all the changes you made to your Adblocker's default settings]

### Notes

[Add here the result of whatever investigation work you have done: please investigate the issues you report -- this prevents burdening other volunteers. This is especially true for issues arising from settings which are very different from default ones.]

**Comment by yourduskquibbles** [comment]
@stdedos The page appears to load for me but then I get a wall I can't get past. Is this what you are seeing? 

![fb](https://user-images.githubusercontent.com/22258847/107125959-dc85ff00-687a-11eb-8151-63907b44d961.png)



I get this message even with uBO fully disabled.

**Comment by yourduskquibbles** [comment]
I now can get the game to load fine by enabling `Apps, Websites and Games` setting in my Facebook profile settings but don't see the issue reported using latest filter list.
![fb2](https://user-images.githubusercontent.com/22258847/107126253-ab0e3300-687c-11eb-81b8-b68b51425a0f.png)

**Comment by stdedos** [comment]
This is what it looks like for me 😕
![image](https://user-images.githubusercontent.com/133706/107132446-da0dbe80-68e7-11eb-86e8-2ab4802fedf9.png)

Ofc I have other lists, and filters, and rules etc etc, but *just* disabling this one; it "clears" everything.

Here be dragons:
<details><summary>Logger output</summary>

| | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +6 | ##[role="tablist"]:upward(4):style(transform: translateY(0) !important;) |  | apps.facebook.com |  | dom | `https://apps.facebook.com/mobaheroes/?gift_id=412e120abcfe661e0190355153ad1838` |
| +6 | ##[role="tablist"]:upward(3):style(opacity: 1 !important; visibility: visible !important;) |  | apps.facebook.com |  | dom | `https://apps.facebook.com/mobaheroes/?gift_id=412e120abcfe661e0190355153ad1838` |
| +6 | ##._5vx2:style(border: none !important; box-shadow: none !important;) |  | apps.facebook.com |  | dom | `https://apps.facebook.com/mobaheroes/?gift_id=412e120abcfe661e0190355153ad1838` |
| +5 | ##html:style(overflow-x: hidden !important; height: unset !important;) |  | apps.facebook.com |  | dom | `https://apps.facebook.com/common/referer_frame.php` |
| +4 | ##html:style(overflow-x: hidden !important; height: unset !important;) |  | apps.facebook.com |  | dom | `https://apps.facebook.com/common/referer_frame.php` |
| +4 | /logos/facebook_ | -- | apps.facebook.com | 1 | image | `https://static.facebook.com/images/logos/facebook_2x.png` |
| +4 | ##html:style(overflow-x: hidden !important; height: unset !important;) |  | apps.facebook.com |  | dom | `https://apps.facebook.com/common/referer_frame.php` |
| +4 | ##html:style(overflow-x: hidden !important; height: unset !important;) |  | apps.facebook.com |  | dom | `https://apps.facebook.com/common/referer_frame.php` |
| +4 | /logos/facebook_ | -- | apps.facebook.com | 1 | image | `https://static.facebook.com/images/logos/facebook_2x.png` |
| +4 | \|\|facebook.com/*/plugins/$domain=~facebook.com | -- | i-heroes-fb.nextersglobal.com | 1,3 | frame | `https://www.facebook.com/v3.3/plugins/like_box.php?app_id=1701433570146040&channel=https%3A%2F%2Fstaticxx.facebook.com%2Fx%2Fconnect%2Fxd_arbiter%2F%3Fversion%3D46%23cb%3Df29b353bec7c448%26domain%3Di-heroes-fb.nextersglobal.com%26origin%3Dhttps%253A%252F%252Fi-heroes-fb.nextersglobal.com%252Ff2cb2ac2cb8a1%26relation%3Dparent.parent&color_scheme=light&container_width=0&header=false&height=400&href=https%3A%2F%2Ffacebook.com%2Fherowarsgame&locale=en_US&sdk=joey&show_border=false&show_faces=true&stream=false&width=500` |
| +4 | ##+js(remove-class, _31e, body > ._li) |  | apps.facebook.com |  | dom | `https://apps.facebook.com/common/referer_frame.php` |
| +4 | \|\|facebook.com*/impression.php | -- | i-heroes-fb.nextersglobal.com | 1,3 | image | `https://www.facebook.com/impression.php/f3cb63dedab6a98/?api_key=1701433570146040&payload=%7B%22ae%22%3A1%2C%22ev%22%3A%22fb_mobile_activate_app%22%2C%22canvas%22%3A1%7D` |
| +4 | /logos/facebook_ | -- | apps.facebook.com | 1 | image | `https://static.facebook.com/images/logos/facebook_2x.png` |
| +4 | google-analytics.com/analytics.js | << | i-heroes-fb.nextersglobal.com | 3,3 | script | `https://www.google-analytics.com/analytics.js` |
| +4 | \|\|google-analytics.com/analytics.js$script,redirect-rule=google-analytics.com/analytics.js | -- | i-heroes-fb.nextersglobal.com | 3,3 | script | `https://www.google-analytics.com/analytics.js` |
| +4 | \|\|google-analytics.com^ | -- | i-heroes-fb.nextersglobal.com | 3,3 | script | `https://www.google-analytics.com/analytics.js` |
| +4 | /fbevents.js | -- | i-heroes-fb.nextersglobal.com | 3,3 | script | `https://connect.facebook.net/en_US/fbevents.js` |
| +4 | /logos/facebook_ | -- | apps.facebook.com | 1 | image | `https://static.facebook.com/images/logos/facebook_2x.png` |
| +4 | ##+js(remove-class, _31e, body > ._li) |  | apps.facebook.com |  | dom | `https://apps.facebook.com/common/referer_frame.php` |
| +4 | ##+js(remove-class, _31e, body > ._li) |  | apps.facebook.com |  | dom | `https://apps.facebook.com/common/referer_frame.php` |
| +4 | ##+js(remove-class, _31e, body > ._li) |  | apps.facebook.com |  | dom | `https://apps.facebook.com/common/referer_frame.php` |
| +3 | ##html:style(overflow-x: hidden !important; height: unset !important;) |  | apps.facebook.com |  | dom | `https://apps.facebook.com/mobaheroes/?gift_id=412e120abcfe661e0190355153ad1838` |
| +3 | ##div[role="banner"] > div:nth-of-type(-n+4):style(position: absolute !important;) |  | apps.facebook.com |  | dom | `https://apps.facebook.com/mobaheroes/?gift_id=412e120abcfe661e0190355153ad1838` |
| +3 | ##div[aria-label="Facebook"][role="banner"]:style(position: relative !important;) |  | apps.facebook.com |  | dom | `https://apps.facebook.com/mobaheroes/?gift_id=412e120abcfe661e0190355153ad1838` |
| +3 | ##[role="complementary"]:style(position: relative !important; top: 0 !important; max-height: unset !important;) |  | apps.facebook.com |  | dom | `https://apps.facebook.com/mobaheroes/?gift_id=412e120abcfe661e0190355153ad1838` |
| +3 | ###u_0_13:style(position: absolute !important;) |  | apps.facebook.com |  | dom | `https://apps.facebook.com/mobaheroes/?gift_id=412e120abcfe661e0190355153ad1838` |
| +3 | ###rightCol |  | apps.facebook.com |  | dom | `https://apps.facebook.com/mobaheroes/?gift_id=412e120abcfe661e0190355153ad1838` |
| +3 | ###fbDockChatBuddylistNub > .fbNubButton |  | apps.facebook.com |  | dom | `https://apps.facebook.com/mobaheroes/?gift_id=412e120abcfe661e0190355153ad1838` |
| +2 | ##+js(remove-class, _31e, body > ._li) |  | apps.facebook.com |  | dom | `https://apps.facebook.com/mobaheroes/?gift_id=412e120abcfe661e0190355153ad1838` |
| +2 | ##+js(remove-class, _31e, body > ._li) |  | apps.facebook.com |  | dom | `https://apps.facebook.com/mobaheroes/?gift_id=412e120abcfe661e0190355153ad1838` |
| +2 | ##+js(remove-class, _31e, body > ._li) |  | apps.facebook.com |  | dom | `https://apps.facebook.com/mobaheroes/?gift_id=412e120abcfe661e0190355153ad1838` |
| +2 | ##+js(remove-class, _31e, body > ._li) |  | apps.facebook.com |  | dom | `https://apps.facebook.com/mobaheroes/?gift_id=412e120abcfe661e0190355153ad1838` |
| +1 | ##+js(remove-class, _31e, body > ._li) |  | apps.facebook.com |  | dom | `https://apps.facebook.com/mobaheroes/?gift_id=412e120abcfe661e0190355153ad1838` |
</details>

**Comment by yourduskquibbles** [comment]
Can you try disabling the filter `##+js(remove-class, _31e, body > ._li)` or the list that is using this?

You can disable this specific filter in your `My Filters` (Not sure where this filter is coming from but it looks really aggressive.... `body > ._li` is essentially the entire page in the DOM tree that is getting removed by some other filter list.

You can try adding to `My Filters` to disable this filter. 

Either 
`facebook.com#@#+js(remove-class, _31e, body > ._li)`
or 
`apps.facebook.com#@#+js(remove-class, _31e, body > ._li)`

**Comment by stdedos** [comment]
Filter in question: https://github.com/AdguardTeam/AdGuardFilters
![image](https://user-images.githubusercontent.com/133706/107140890-fe8c8980-692d-11eb-8b49-0e2a13d87fe1.png)

No, it doesn't help. Your list - AdGuardFilters == White page still

**Comment by yourduskquibbles** [comment]
> 
> 
> Filter in question: https://github.com/AdguardTeam/AdGuardFilters
> ![image](https://user-images.githubusercontent.com/133706/107140890-fe8c8980-692d-11eb-8b49-0e2a13d87fe1.png)
> 
> No, it doesn't help. Your list - AdGuardFilters == White page still

Thanks I will test with this on my end. In the mean time, my next best guess is it could be one of the `upwards(n)` filters from `Web Annoyances Ultralist` that is too aggressive possibly because Facebook could be loading a somewhat different DOM Tree depending on the users/region so the filter could be over removing something for you but everything works great with me. If you are willing I'm hoping I could have you test the following filters (ONLY one at a time initially) that will disable the `upward` filters that are part of `Web Annoyances Ultralist`. I'm hoping that if you test only one filter disabled at a time, we can narrow down what filter could be causing the issue and I can just remove this filter and try to come up with a better one in its place.

Please test adding **ONLY one filter** at a time to `My Filters`
1. `facebook.com,facebookcorewwwi.onion#@#[data-pagelet="page"] [role="complementary"] [data-pagelet="RightRail"] > div:not([data-visualcompletion="ignore-dynamic"]) span[aria-label="Advertiser link"]:upward(11)`

2. `facebook.com,facebookcorewwwi.onion#@#[role="main"] div[style*="top: 56px;"] > div > div > div > div > div > div > div:nth-of-type(1) [role="tablist"]:upward(5):style(opacity: 1 !important; visibility: visible !important;)`

3. `facebook.com,facebookcorewwwi.onion#@#[role="main"] div[style*="top: 56px;"] > div > div > div > div > div > div > div:nth-of-type(1) [role="tablist"]:upward(6):style(transform: translateY(0) !important;)`

**Comment by stdedos** [comment]
No dice. I have tried all 3 of them (in combinations, including individually).

1. Reset to my configuration
2. Add one line
3. Apply Changes
4. Refresh page
5. Repeat

until I finished all of the permutations.

**Comment by yourduskquibbles** [comment]
Bummer, I still can't recreate on either Chrome or Firefox with `Adguard Annoyances` or even with ALL annoyance lists offered in the Filter List Section + `Web Annoyances Ultralist`.

Do you have any regional specific lists also enabled or any other custom lists?

Next step for me would be to try region based IP but `facebook` doesn't like you jumping around IP's/regions and could lock my account so want to try doing that one last :)

**Comment by stdedos** [comment]
Forgive my lack of understanding, but: What do having other lists interfere with your list maybe being a little too eager since 3 days ago? 😕 

![image](https://user-images.githubusercontent.com/133706/107241103-5660e880-6a33-11eb-8aa0-d20180cd490c.png)

**Comment by yourduskquibbles** [comment]
I'm not sure, I've never had something like that happen but I can't recreate what you are getting with my setup so hoping to remove as many variables from the possible causes of why you're experiencing that.

**Comment by stdedos** [comment]
uBlock logger unfortunately does not list or log (or export) which filters belong to which list.

If I could have that, and a way to evaluate filters on a loaded page, I could then manually tell which rule is responsible for this.

**Comment by yourduskquibbles** [comment]
I think it does - you can set uBO `advanced setting`[1] `filter author mode:`[2] `true` and then also go one-by-one disabling DOM filters through the logger and testing reloading the page after each time you disable a filter.

See: 
[1] https://github.com/gorhill/uBlock/wiki/Advanced-settings
[2] https://github.com/gorhill/uBlock/wiki/Advanced-settings#filterauthormode

**Comment by stdedos** [comment]
Apologies for the delay; now it seems that this version:

```
! Title: Web Annoyances Ultralist
! Last Modified: 11:19 2021-02-13
```
Fixes my problem! Thank you 😀

**Comment by yourduskquibbles** [comment]
OK thanks for reporting back the issue is resolved. I had updated a few filters around the time when you reported this originally wondering if maybe you were on an old cache of the list so getting filters I had already removed or updated. Whatever the case, glad to hear it is resolved!
