### ISSUE TITLE
m.news.naver.com

### ISSUE THREAD

**Issue by piquark6046** [yourduskquibbles/webannoyances#286]
https://github.com/AdguardTeam/AdguardFilters/issues/74702#issuecomment-778210544 ( AdguardTeam/AdguardFilters#74702 )

Note: Please enable Responsive Design Mode (Mobile Mode).

**Comment by yourduskquibbles** [comment]
This is an item I normally intentionally remove from sites, but will add exception for this domain since it is not high traffic and is requested by a user.
