### ISSUE TITLE
Youtube Channels Page

### ISSUE THREAD

**Issue by freelyskycloud** [yourduskquibbles/webannoyances#287]
### URL(s) where the issue occurs
https://www.youtube.com/c/LugnutsK/videos (Or any other channel)

### Describe the issue
Enabling this filter makes the youtube channels banner picture disappear. This then moves everything on the page up. Making the first row of videos unclickable.

### Versions

- Browser & Version: Firefox 85.0.2
- Adblocker (uBlock Origin, Adguard, Nano Adblocker, etc.) & Version: uBlock Origin 1.33.2

### Notes
In `filters/floating_filters.txt` line 9346; `youtube.com###contentContainer:style(padding-top: 0 !important;)` breaks youtube channel pages.

**Comment by Snipe76** [comment]
Sidebar is unsuable too.
The first 3 buttons (Home, Trending and Subs) are not visible.

**Comment by Pietryszak** [comment]
I agree with @Snipe76 Sidebar is unusable. Home, Trending, and Subscriptions are not visible after the last update.

**Comment by yourduskquibbles** [comment]
@freelyskycloud @Snipe76 @Pietryszak Thanks for reporting and sorry for the delay on being able to address. 

After purging cache and updating `Web Annoyances Ultralist` and reloading `https://www.youtube.com/c/LugnutsK/videos` do the new filters work? looks like Youtube redesigned their site a bit.

**Comment by freelyskycloud** [comment]
@yourduskquibbles I can confirm that the youtube channels page works again. Thanks for fixing it.

**Comment by yourduskquibbles** [comment]
@freelyskycloud Thank you for confirming!
