### ISSUE TITLE
malwaretips.com dark mode issue

### ISSUE THREAD

**Issue by SergeyTverye** [yourduskquibbles/webannoyances#288]
Hey! Unexpectedly met such a problem with your filter. 
### URL(s) where the issue occurs
https://malwaretips.com/
### Describe the issue
If turn on dark mode after logging into account, the side sidebar goes beyond the border of the table, and the buttons for managing the website design become inaccessible. 
### Screenshot(s)
https://i.comss.pics/2021/02/21/SNIMOK-EKRANA-2021-02-21-002923.jpg
### Versions
- Firefox 86 Beta x64
- Edge 88.0.705.74
- uBlock Origin v1.33.2
### Settings
Only Web Annoyances Ultralis filter enabled

**Comment by yourduskquibbles** [comment]
@SergeyTverye Thanks for reporting, I think this is solved now, but can you try updating your filter list and see if that solves the issue for you?
