### ISSUE TITLE
computerworld.com

### ISSUE THREAD

**Issue by pintassilgo** [yourduskquibbles/webannoyances#289]
### URL(s) where the issue occurs

`https://www.computerworld.com/article/3584908/chrome-note-taking-tool.html`

### Describe the issue

Images don't load.

### Notes

Caused by
`||computerworld.com/*/insider_reg_api.js$script,domain=computerworld.com`

**Comment by yourduskquibbles** [comment]
@pintassilgo Thanks for reporting, this should be fixed now!
