### ISSUE TITLE
.signup-wrapper generic filter breaks researchgate.net

### ISSUE THREAD

**Issue by notevenaperson** [yourduskquibbles/webannoyances#291]
### URL(s) where the issue occurs

`https://www.researchgate.net/signup.SignUpAccountBasics.html`
Any other signup widgets on the site
### Describe the issue
Signup boxes are filtered when they shouldn't.
### Versions

- Browser & Version: Firefox 86
- Adblocker: uBlock Origin v1.33.2

### Settings
none that should interfere with this

**Comment by yourduskquibbles** [comment]
@notevenaperson Thx for reporting! This should be fixed now
