### ISSUE TITLE
app.jobvite.com

### ISSUE THREAD

**Issue by LanikSJ** [yourduskquibbles/webannoyances#292]
### URL(s) where the issue occurs

`https://app.jobvite.com/jhire/modules/candidates/add.html?&rt=https://app.jobvite.com/admin/myaccount/dashboard.html&formType=refer`

### Describe the issue

"Add to Requisition" (screenshot below) will have cancel and add buttons hidden.  Allowing `.postActions` for app.jobvite.com solves the problem.  FWIW the site is behind a login and password which is tied to my companies SSO.  I can provide any additional information you need to debug this.  Just let me know.

### Screenshot(s)
![image](https://user-images.githubusercontent.com/12159404/110562613-b57f4f00-80fe-11eb-8a33-f21c058a680f.png)

### Versions

- Browser & Version: Brave Browser 1.21.74
- Adblocker (uBlock Origin, Adguard, Nano Adblocker, etc.) & Version: uBO 1.33.2

### Settings
![image](https://user-images.githubusercontent.com/12159404/110562701-dba4ef00-80fe-11eb-881e-db1200d495ff.png)

### Notes

I added `app.jobvite.com#@#.postActions` to my personal filters list and the site loads correctly.

**Comment by yourduskquibbles** [comment]
@LanikSJ Thanks for reporting! I have added filter that should fix this based on your suggestion.
