### ISSUE TITLE
False positive: cookieconsentspeed.run

### ISSUE THREAD

**Issue by shreyasminocha** [yourduskquibbles/webannoyances#295]
### URL(s) where the issue occurs

`https://cookieconsentspeed.run/`

### Describe the issue

The filter `/cookieconsent` breaks this innocent site.

### Screenshot(s)

All but the fathom script are innocent:

![Screenshot of the uBO logger where several innocent first-party scripts, images, and stylesheets are blocked by the filter `/cookieconsent`](https://user-images.githubusercontent.com/11537232/111856485-ee9b9880-8922-11eb-992e-bbc905b568fe.png)

### Versions

- LibreWolf (Firefox) 85.0.2
- uBlock Origin 1.33.2

### Settings

Nothing relevant here.

**Comment by yourduskquibbles** [comment]
@shreyasminocha Thanks for reporting, this should be fixed now!
