### ISSUE TITLE
wykop.pl navbar no longer scrolling with website

### ISSUE THREAD

**Issue by Acrivec** [yourduskquibbles/webannoyances#296]
### URL(s) where the issue occurs

`[https://wykop.pl/moj]`

### Describe the issue

The top navbar is supposed to scroll with the website, staying constantly on top of screen.
It can be turned off in user settings - making it appear only on top of website, without scrolling with screen.
Disabling 'cosmetic filtering' fixes the problem.

### Screenshot(s)

https://i.imgur.com/JCwcMeC.png
https://i.imgur.com/eXQLCVD.png

### Versions

- Browser & Version: Firefox 87.0
- Adblocker (uBlock Origin, Adguard, Nano Adblocker, etc.) & Version: uBlock Origin v1.34.0

### Settings

Dunno how to list them, and won't compare one by one.

**Comment by krystian3w** [comment]
This is feautre. List block sticky navigations: https://raw.githubusercontent.com/yourduskquibbles/webannoyances/master/filters/floating_filters.txt

**Comment by Acrivec** [comment]
Unsubscribing the list then. Too bad that because of one filter I have to remove all others.

**Comment by krystian3w** [comment]
LMAO, possible add few exeptions to "Moje filtry" and works again:
```css
wykop.pl#@##nav:style(position: absolute !important;)
wykop.pl#@##footer:style(position: relative !important; height: auto !important; padding: 0 10px !important; bottom: 0 !important;)
wykop.pl#@##rightFooterBox:style(position: relative !important; display: block !important; opacity: 1 !important;)
wykop.pl#@##site:style(margin-bottom: 0 !important;)
```

**Comment by Acrivec** [comment]
Closing issue, not going to communicate with you, as of you're just plain rude.
