### ISSUE TITLE
yelp.com login broken

### ISSUE THREAD

**Issue by LanikSJ** [yourduskquibbles/webannoyances#297]
### URL(s) where the issue occurs
https://www.yelp.com/login

### Describe the issue
The login container that has all the social networks logins as well as username and password is hidden.

### Screenshot(s)
Offending filter enabled:
![image](https://user-images.githubusercontent.com/12159404/114630059-967c5b80-9c6e-11eb-829d-faca1c193995.png)

Offending filter disabled:
![image](https://user-images.githubusercontent.com/12159404/114630000-78aef680-9c6e-11eb-85b5-5c0fda9dfa3f.png)

### Versions

- Browser & Version: Brave Browser 1.22.71
- Adblocker (uBlock Origin, Adguard, Nano Adblocker, etc.) & Version: uBO 1.34.0

### Settings
![image](https://user-images.githubusercontent.com/12159404/114630135-c0ce1900-9c6e-11eb-8b64-55d238636ac2.png)

### Notes
Adding the below filter fixes the problem:
```
yelp.com#@#.signup-wrapper
```

**Comment by yourduskquibbles** [comment]
@LanikSJ Thank you for reporting and sorry for delay in fixing this but I have added your exception filter as suggested.
