### ISSUE TITLE
powiatkamienski.pl

### ISSUE THREAD

**Issue by strict-block** [yourduskquibbles/webannoyances#298]
### URL(s) where the issue occurs

`https://www.powiatkamienski.pl/#block-danestopka`

### Describe the issue

Page gets blank after scroll to top.

### Screenshot(s)

N/A

### Versions

- Browser & Version: Chrome 89
- Adblocker & Version: AdGuard addon v3.5.34

### Settings
```
Ad Blocking:
AdGuard Base,
AdGuard Mobile Ads

Privacy:
AdGuard Tracking Protection,
EasyPrivacy

Social Widgets:
AdGuard Social Media,
Fanboy's Social Blocking List

Annoyances:
AdGuard Annoyances,
Web Annoyances Ultralist,
I don't care about cookies

Security:
Online Malicious URL Blocklist,
Spam404,
NoCoin Filter List

Language-specific:
Official Polish filters for AdBlock, uBlock Origin & AdGuard,
Polish Social Filters,
KAD - Anti-Scam,
Polish Annoyances Filters,
Polish Anti Adblock Filters,
Polish Anti-Annoying Special Supplement
```

### Notes

Hardly reproduce with uBlock Origin on Firefox (glitch then you tried hide `<body>`).

https://github.com/yourduskquibbles/webannoyances/blob/9844e52a62fb651a9385db12c13b721266175719/filters/generic_filters.txt#L1271

**Comment by yourduskquibbles** [comment]
@strict-block Thanks for reporting, I believe this should be fixed now with https://github.com/yourduskquibbles/webannoyances/commit/c7f3f94d285ee7d617cd2ca859d8de9fe7be5be4

Please let me know if still issues
