### ISSUE TITLE
Unknown error text in YouTube title bar

### ISSUE THREAD

**Issue by harusakura924** [yourduskquibbles/webannoyances#299]
# Comment

當我開啟Web Annoyances Ultralisk,而且在Youtube播放影音頁面,左上角會出現不明錯誤，經查證確定是Web Annoyances Ultralisk套件導致。

**可能要開啟後多刷新幾次才會看到

When I turn on Web Annoyances Ultralisk and play the video page on Youtube, an unknown error appears in the upper left corner. It is verified that it is caused by the Web Annoyances Ultralisk package.

** You may need to refresh a few more times after opening it to see.

# Screenshots

![f65d1dd3-0006-4785-adae-f28d0b56e218](https://user-images.githubusercontent.com/60030937/115148425-19981a00-a092-11eb-953d-4506cd591106.png)

The same question was posted on
https://github.com/AdguardTeam/AdguardFilters/issues/80461#issuecomment-821995288

**Comment by krystian3w** [comment]
Seemingly only with AdGuard technology the error occurs.

In their issue repository you can find for example: https://github.com/AdguardTeam/AdguardBrowserExtension/issues/1486

**Comment by yourduskquibbles** [comment]
I don't know how to reproduce this, if someone can provide repro steps or show it is caused by Web Annoyances Ultralist will reopen.

**Comment by krystian3w** [comment]
Needed is endable tracking what "AG rules" (~ uBO filter 1 line) is used (& how often).

Maybe you disbled tracking usage AG rules so problem gone. AG don't closed this issue as fixed:

https://github.com/AdguardTeam/AdguardBrowserExtension/issues/1486
