### ISSUE TITLE
Help for the rule

### ISSUE THREAD

**Issue by fhjyx3** [yourduskquibbles/webannoyances#300]
### URL(s) where the issue occurs

`https://www.kadinlarkulubu.com/konu/cok-arada-kaldim-ne-yapmaliyim.1230836/`

### Describe the issue

Is it possible to hide the space on the right with a rule? I do not know how to hide it.
Thanks for help
(Don't add the rule to the filter because I want it for my own user filter.)

### Screenshot(s)

<details>
 <summary>Screenshot</summary>

![kklb](https://user-images.githubusercontent.com/83103695/115949003-66d51b00-a4da-11eb-9f92-80d70dc1f813.png)

 
</details>

### Versions

- Browser & Version: Chrome 90
- Adblocker (uBlock Origin, Adguard, Nano Adblocker, etc.) & Version: AdGuard 3.5.34

### Settings

- Stealth Mode is active
Active filters: 
AdGuard Base filter, Annoyances filter, Tracking Protection filter, Social Media filter, AdGuard Turkish filter

### Notes

[Add here the result of whatever investigation work you have done: please investigate the issues you report -- this prevents burdening other volunteers. This is especially true for issues arising from settings which are very different from default ones.]

**Comment by spirillen** [comment]
I'll think not, as it to me appears to be a fixed width.

But here is one to @ryanbr cookie :cookie:  list
```
##.notice--cookie
```

**Comment by krystian3w** [comment]
`##body:style(max-width: unset !important;)` may works in element picker.
