### ISSUE TITLE
Erroneously removes buttons generated by streamlit.io python web GUI library

### ISSUE THREAD

**Issue by fiendish** [yourduskquibbles/webannoyances#301]
### URL(s) where the issue occurs

https://share.streamlit.io/arielcedola/kmeans/main/kmeans_app.py

### Describe the issue

I'm working on a project using the streamlit.io python web GUI library, and if I have this filter enabled in AdGuard for Safari then my generated buttons don't appear.

### Screenshot(s)

<img width="738" alt="Screen Shot 2021-05-14 at 7 42 48 PM" src="https://user-images.githubusercontent.com/201996/118344683-ce382680-b4ec-11eb-8586-8425102a9a25.png">

<img width="556" alt="Screen Shot 2021-05-14 at 7 41 30 PM" src="https://user-images.githubusercontent.com/201996/118344686-d2644400-b4ec-11eb-8284-321aaec63f16.png">

### Versions

- Browser & Version: Safari 14.0.3 (15610.4.3.1.7, 15610)
- Adblocker (uBlock Origin, Adguard, Nano Adblocker, etc.) & Version: AdGuard for Safari 1.9.13

### Settings

- Enabled "Web Annoyances Ultralist" filter.

**Comment by fiendish** [comment]
It appears that the problem could be with https://github.com/yourduskquibbles/webannoyances/blob/36d36ac169a32e89baf6de9216cf7a5d9007556b/filters/generic_filters.txt#L1796

**Comment by krystian3w** [comment]
IMO the best rethink why was added and remove the line.

**Comment by yourduskquibbles** [comment]
@fiendish This should be fixed now. Thank you for reporting and apologies for the delay on fixing this.
