### ISSUE TITLE
Block video boxes from floating on Postmedia sites (Canada)

### ISSUE THREAD

**Issue by 8restcoop8** [yourduskquibbles/webannoyances#302]
### URL(s) where the issue occurs

calgaryherald.com,calgarysun.com,edmontonjournal.com,edmontonsun.com,leaderpost.com,lfpress.com,montrealgazette.com,nationalpost.com,ottawacitizen.com,ottawasun.com,theprovince.com,thestarphoenix.com,torontosun.com,vancouversun.com,windsorstar.com,winnipegsun.com

### Describe the issue

Floating video boxes (YouTube embeds and others) continue to float down page and aren't blocked by floating rules.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/40674398/118699677-0bdbce80-b7cf-11eb-8a2c-e0725de78305.png)

### Versions

- Browser/version: Firefox 89.0b13
- uBlock Origin version: 1.35.2

### Settings

n/a

**Comment by yourduskquibbles** [comment]
@8restcoop8 Thank you for reporting! This should be fixed now, please let me know if other issues.
