### ISSUE TITLE
Top Twitter posts cut off with list enabled in AdGuard on Android

### ISSUE THREAD

**Issue by wefalltomorrow** [yourduskquibbles/webannoyances#303]
### URL(s) where the issue occurs

`https://mobile.twitter.com/LukeSmithF1/status/1401539328606715910?s=19`

### Describe the issue

On the mobile Twitter website, with this filter enabled in AdGuard, all top posts are either partially or completely cut off making them impossible to see/read.

### Screenshot(s)

Link to Imgur album showing problem: https://imgur.com/a/q9P59js

### Versions

- Browser & Version: Kiwi Browser and latest filter update at the time of writing this.
- Adblocker (uBlock Origin, Adguard, Nano Adblocker, etc.) & Version: AdGuard Android (stable v3.6.2)

### Settings

- Enabled "Web Annoyances Ultralist" filter.

### Notes

Nothing more to add.

**Comment by yourduskquibbles** [comment]
@wefalltomorrow Thx for reporting... I don't have ability to test on physical android device but does adding the following filters to `My Filters` fix the issue for you?

```
mobile.twitter.com###react-root > .rn-ipm5af.rn-zchlnj.rn-u8s1d.rn-1d2f490, ._3f2NsD-H.W1P7mM7E, ._3f2NsD-H._1363jyKz, ._3f2NsD-H._22omdtNH._8qpj9SE2._3xujJ3kq, ._3f2NsD-H._2qq9pBP0, header > .css-1dbjc4n[style^="height: calc(106px);"]
mobile.twitter.com#@##react-root > .rn-ipm5af.rn-zchlnj.rn-u8s1d.rn-1d2f490, ._3f2NsD-H.W1P7mM7E, ._3f2NsD-H._1363jyKz, ._3f2NsD-H._22omdtNH._8qpj9SE2._3xujJ3kq, ._3f2NsD-H._2qq9pBP0, header > .css-1dbjc4n[style^="height: calc(106px);"], header[role="banner"] > div[style*="height"], header[role="banner"] > div[style]
mobile.twitter.com#@#header[role="banner"] > div[style*="height"]
mobile.twitter.com#@#header[role="banner"] > div[style]
```

I tested in chrome emulating android device and it seems to fix the issue for me so I will add these to the adguard android exclusion list.
