### ISSUE TITLE
Broken style in aliexpress.com

### ISSUE THREAD

**Issue by pintassilgo** [yourduskquibbles/webannoyances#304]
### URL(s) where the issue occurs

`https://pt.aliexpress.com/item/32711891166.html`

### Describe the issue

These two cosmetic rules from `floating_filters.txt` are breaking the layout:
`aliexpress.com##.hm-left:style(width: 256px !important; height: 96px !important;)`
`aliexpress.com###header:style(height: auto !important;)`

The first rule is the primary issue. The second rule causes a minor issue of incoherent vertical padding (see Screenshots).

### Screenshot(s)

Broken:
![image](https://user-images.githubusercontent.com/5483864/122948486-5366f480-d351-11eb-9268-d6885beba456.png)

Fixed after skipping the two rules (`aliexpress.com#@#`...):
![image](https://user-images.githubusercontent.com/5483864/122948748-86a98380-d351-11eb-9947-2f983b0f9e95.png)

With the second rule only (`height: auto`), ugly:
![image](https://user-images.githubusercontent.com/5483864/122949346-f61f7300-d351-11eb-973f-98a1ca595005.png)

Without defining `height: auto`, correct:
![image](https://user-images.githubusercontent.com/5483864/122949387-ffa8db00-d351-11eb-8b01-cdb435da95e2.png)

### Versions

- Firefox 90
- uBO 1.35.2

**Comment by yourduskquibbles** [comment]
@pintassilgo Thank you for detailed report. This should be fixed now. Please let me know if other issues
