### ISSUE TITLE
Whirlpool forums buttons are blocked

### ISSUE THREAD

**Issue by lianthar** [yourduskquibbles/webannoyances#307]
https://forums.whirlpool.net.au/thread/3w8y8py7

The header/footer buttons on any threads in this forum are removed when WebAnnoyances filter is enabled in AdGuard.
eg. Watch, Reply, Archive Version buttons.

- Chrome 92.0.4515.107 (Official Build) (64-bit)
- AdGuard Version 3.6.6

**Comment by yourduskquibbles** [comment]
@lianthar Thanks for reporting, this should be fixed now. Please let me know if you still having issues
