### ISSUE TITLE
ProPublica glitch

### ISSUE THREAD

**Issue by sweetcashew** [yourduskquibbles/webannoyances#308]
### URL(s) where the issue occurs

`https://www.propublica.org/article/commercial-aviation-is-essential-to-life-here-its-also-home-to-a-growing-share-of-the-countrys-deadly-crashes`

### Describe the issue

If you scroll down to the point where the header would normally be stickied to the top of the page, the entire page seizes. If you scroll past that point, the page stops seizing.

### Video

https://user-images.githubusercontent.com/88003315/127051755-d370338a-3760-477e-a383-7f72e5658803.mov

### Versions

- Browser & Version: Firefox 90.0.2
- Adblocker (uBlock Origin, Adguard, Nano Adblocker, etc.) & Version: uBlock Origin 1.36.2

### Notes

Seems to be related to `.site-header`?

**Comment by yourduskquibbles** [comment]
@sweetcashew thanks for reporting and the video, that is very helpful!

This took a bit of testing but I think this should be fixed now, please let me know if still having issues on your side.
