### ISSUE TITLE
The Intercept logo bugs

### ISSUE THREAD

**Issue by sweetcashew** [yourduskquibbles/webannoyances#309]
### URL(s) where the issue occurs

`https://theintercept.com/2021/07/05/barrett-moore-brad-thor-doomsday-prepper-the-haven/`

### Describe the issue

The logo is duplicated, and that region is treated differently while scrolling (it stays static) compared to fixed on category pages (e.g. `https://theintercept.com/politics/`).

### Screenshot(s)

<img width="1280" alt="screenshot" src="https://user-images.githubusercontent.com/88003315/127052854-e7e42e14-aea8-45c1-b395-30b31fa74020.png">

### Versions

- Browser & Version: 90.0.2
- Adblocker (uBlock Origin, Adguard, Nano Adblocker, etc.) & Version: uBlock Origin 1.36.2

**Comment by yourduskquibbles** [comment]
@sweetcashew Thx for reporting, this should be fixed now
