### ISSUE TITLE
Filters to block annoyances on Williams-Sonoma websites

### ISSUE THREAD

**Issue by sweetcashew** [yourduskquibbles/webannoyances#310]
### URL(s) where the issue occurs

`williams-sonoma.com`
`potterybarn.com`
`pbteen.com`
`potterybarnkids.com`
`westelm.com`
`markandgraham.com`

### Describe the issue

These Williams-Sonoma websites have email subscription overlays (some which prevent scrolling) which I've blocked:
- `.overlayScroll`
- `.overlayMask`
- `.overlayThrobber`

There is also a script that I enabled on some of these sites `customer-service/show-join-email.jsonp` because if it is blocked (which Fanboy's Annoyances filter list does) then after a couple minutes the page times out and a browser alert appears saying that the script couldn't be found (there might be a better way to prevent that timeout error without allowing the script, but I couldn't figure out how).

There is also a sticky chat call-to-action at the bottom of the page, `.design-chat`, that I blocked.

And finally, inner pages have another email subscription overlay, `#join-email-campaign`, which I blocked.

### Versions

- Browser & Version: Firefox 90.0.2
- Adblocker (uBlock Origin, Adguard, Nano Adblocker, etc.) & Version: uBlock Origin 1.36.2

### Notes

Here are the filters:

```
! Williams Sonoma annoyances
@@||williams-sonoma.com/customer-service/show-join-email.jsonp$script
williams-sonoma.com##.overlayScroll
williams-sonoma.com##.overlayMask
williams-sonoma.com##.overlayThrobber
williams-sonoma.com##.design-chat
williams-sonoma.com###join-email-campaign

! Pottery Barn annoyances
@@||potterybarn.com/customer-service/show-join-email.jsonp$script
potterybarn.com##.overlayScroll
potterybarn.com##.overlayMask
potterybarn.com##.overlayThrobber
potterybarn.com##.design-chat
potterybarn.com###join-email-campaign

! Pottery Barn Teen annoyances
@@||pbteen.com/customer-service/show-join-email.jsonp$script
pbteen.com##body:style(overflow: auto !important)
pbteen.com##.overlayScroll
pbteen.com##.overlayMask
pbteen.com##.overlayThrobber
pbteen.com##.design-chat
pbteen.com###join-email-campaign

! Pottery Barn Kids annoyances
@@||potterybarnkids.com/customer-service/show-join-email.jsonp$script
potterybarnkids.com##body:style(overflow: auto !important)
potterybarnkids.com##.overlayScroll
potterybarnkids.com##.overlayMask
potterybarnkids.com##.overlayThrobber
potterybarnkids.com##.design-chat
potterybarnkids.com###join-email-campaign

! West Elm annoyances
@@||westelm.com/customer-service/show-join-email.jsonp$script
westelm.com##body:style(overflow: auto !important)
westelm.com##.overlayScroll
westelm.com##.overlayMask
westelm.com##.overlayThrobber
westelm.com##.design-chat
westelm.com###join-email-campaign

! Mark and Graham annoyances
@@||markandgraham.com/customer-service/show-join-email.jsonp$script
markandgraham.com##body:style(overflow: auto !important)
markandgraham.com##.overlayScroll
markandgraham.com##.overlayMask
markandgraham.com##.overlayThrobber
markandgraham.com###join-email-campaign
```

**Comment by teddybradford** [comment]
Also, some of these sites have sticky headers that may be able to be made static, but I didn't look into that.

**Comment by sweetcashew** [comment]
These extra filters remove sticky headers:

```
pbteen.com##.fixed-header.headroom-not-top:style(position: static !important)
pbteen.com##.fixed-header.headroom-not-top + .fixed-header-spacer:style(margin-top: 0 !important)

markandgraham.com###default.fixed-header.headroom-not-top.headroom-pinned:style(position: relative !important)
markandgraham.com###default.fixed-header.headroom-not-top.headroom-pinned + .fixed-header-spacer:style(margin-top: 0 !important)
```

**Comment by yourduskquibbles** [comment]
@sweetcashew Thanks for reporting and providing filter suggestions. I think I got all of the items you found and tested around on all the domains a bit but if you get a chance, do you mind testing as well and let me know if I missed anything?

**Comment by sweetcashew** [comment]
Looks good! Thanks!
