### ISSUE TITLE
Imgur bug

### ISSUE THREAD

**Issue by sweetcashew** [yourduskquibbles/webannoyances#311]
### URL(s) where the issue occurs

`https://imgur.com/lVlPvCB`

### Describe the issue

If you scroll down, the page becomes blank.

### Screenshot(s)

<img width="1280" alt="screenshot" src="https://user-images.githubusercontent.com/88003315/127070633-639de768-445d-4651-bbc3-4adbf53bd169.png">

### Versions

- Browser & Version: 90.0.2
- Adblocker (uBlock Origin, Adguard, Nano Adblocker, etc.) & Version: uBlock Origin 1.36.2

**Comment by yourduskquibbles** [comment]
Related: #340 I have no idea what filter is causing this so I just remove them all and rewrote new filters. Seems to be working for me with testing so I am going to push filter and hope it works for both @RedDragonWebDesign and @sweetcashew  if you both can test  and confirm :)
