### ISSUE TITLE
Vanity Fair annoyances

### ISSUE THREAD

**Issue by sweetcashew** [yourduskquibbles/webannoyances#312]
### URL(s) where the issue occurs

`https://www.vanityfair.com/hollywood/2016/02/mystery-of-the-maltese-falcon`
`https://archive.vanityfair.com/article/2002/12/fort-braggs-deadly-summer`

### Describe the issue

Block sticky header, footers, ads, paywall modals, and CTAs.

### Versions

- Browser & Version: FF 90.0.2
- Adblocker (uBlock Origin, Adguard, Nano Adblocker, etc.) & Version: uBlock Origin 1.37.0

### Notes

```
! Vanity Fair annoyances
vanityfair.com##.paywall-modal
vanityfair.com##.consumer-marketing-unit--cm-footer

! Vanity Fair Archive annoyances
archive.vanityfair.com##.user_menu_wrapper:style(position: relative !important)
archive.vanityfair.com###issue_toc
archive.vanityfair.com##.shared_footer_cta_primary
archive.vanityfair.com##.shared_footer_cta_basic
archive.vanityfair.com##.shared_substory_cta
```

**Comment by yourduskquibbles** [comment]
@sweetcashew thx for reporting! This should be fixed now, please let me know if other issues.

**Comment by sweetcashew** [comment]
Thanks, but looks like it still needs to block: `.paywall-modal`

**Comment by sweetcashew** [comment]
I think maybe e0c87da was the wrong change?

**Comment by yourduskquibbles** [comment]
@sweetcashew Should be updated now

**Comment by sweetcashew** [comment]
Found one more overlay!

If you click on this image:
<img width="739" alt="image" src="https://user-images.githubusercontent.com/88003315/128260814-c3752ab9-43fa-4f90-9401-a84dda731fb7.png">

You get this overlay:
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/88003315/128260783-e68683d5-796e-4ff0-888e-84a30b06e49b.png">

Which can be blocked with:
`archive.vanityfair.com##.bnd_subscribe`

**Comment by yourduskquibbles** [comment]
Thanks for repro steps, should be updated now
