### ISSUE TITLE
.scroll-box false positive

### ISSUE THREAD

**Issue by sweetcashew** [yourduskquibbles/webannoyances#313]
### URL(s) where the issue occurs

`1password.com`

### Describe the issue

`.scroll-box` is used to display a UI box with items listed in it.

Should this element be removed as a generic blocking filter? Seems like there would be lots of false positives.

### Versions

- Browser & Version: FF 90.0.2
- Adblocker (uBlock Origin, Adguard, Nano Adblocker, etc.) & Version: uBO 1.37

**Comment by yourduskquibbles** [comment]
@sweetcashew Thx for reporting, I've remove this generic filter for now.
