### ISSUE TITLE
The Baffler subscription overlay

### ISSUE THREAD

**Issue by sweetcashew** [yourduskquibbles/webannoyances#314]
### URL(s) where the issue occurs

`https://thebaffler.com/salvos/the-scream-ali`

### Describe the issue

These filters get rid of the subscription overlay that appears when you scroll down through an article on `thebaffler.com`.

```
thebaffler.com##.boxzilla-overlay
thebaffler.com##.boxzilla-container
```

### Versions

- Browser & Version: FF 90.0.2
- Adblocker (uBlock Origin, Adguard, Nano Adblocker, etc.) & Version: uBO 1.37

**Comment by yourduskquibbles** [comment]
@sweetcashew Thanks for reporting! This should be fixed now.
