### ISSUE TITLE
WaPo sticky videos styling bug

### ISSUE THREAD

**Issue by sweetcashew** [yourduskquibbles/webannoyances#315]
### URL(s) where the issue occurs

`https://www.washingtonpost.com/local/education/mock-slave-trade-critical-race-theory/2021/07/23/b4372c36-e9a8-11eb-ba5d-55d3b5ffcaf1_story.html`

### Describe the issue

When scrolling halfway down a playing video, the video dimensions change due to floating filter styles that need adjusting.

To fix the bug:

In this existing filter: `washingtonpost.com##.powa-sticky-stick.powa-sticky:style(position: absolute !important; top: unset !important; right: unset !important; bottom: unset !important; max-width: 916px !important; width: 100% !important; z-index: unset !important; animation: none !important;)`

the `max-width: 916px !important` should be changed to `max-width: 100% !important;`

and then this filter should be added:

```
washingtonpost.com##.powa-sticky-stuck.powa-sticky:style(position: relative !important;)
```

### Screenshot(s)

![image](https://user-images.githubusercontent.com/88003315/127223839-3d5d9fec-b8a1-489e-b059-afef3059a211.png)
![image](https://user-images.githubusercontent.com/88003315/127223784-50a68e57-2d66-4eab-a2b9-e4a4f33bfb29.png)

### Versions

- Browser & Version: FF 90.0.2
- Adblocker (uBlock Origin, Adguard, Nano Adblocker, etc.) & Version: uBO 1.37

**Comment by yourduskquibbles** [comment]
@sweetcashew Thanks for reporting and providing suggested filters! This should be fixed now
