### ISSUE TITLE
TPM annoyances

### ISSUE THREAD

**Issue by sweetcashew** [yourduskquibbles/webannoyances#316]
### URL(s) where the issue occurs

`https://talkingpointsmemo.com/cafe/bob-moses-visionary-organizer-teacher-risked-his-life-for-voting-rights`

### Describe the issue

There are 3 annoyances on TPM articles:

1. ![image](https://user-images.githubusercontent.com/88003315/127226472-f9aef13b-a571-444a-8bf7-5cad82166ca8.png)
2. ![image](https://user-images.githubusercontent.com/88003315/127226502-d48ea16a-e667-4886-b9cf-b47eb1777929.png)
3. ![image](https://user-images.githubusercontent.com/88003315/127226518-95030ac4-63da-4a5b-8e27-ffe2b6fd9cc3.png)

### Versions

- Browser & Version: FF 90.0.2
- Adblocker (uBlock Origin, Adguard, Nano Adblocker, etc.) & Version: uBO 1.37

### Notes

I blocked them with these filters: 

```
talkingpointsmemo.com##.NewsletterForm
talkingpointsmemo.com##.CommentsNotice
talkingpointsmemo.com##.MeteredBumper
```

**Comment by yourduskquibbles** [comment]
@sweetcashew Thanks for reporting! Filters added as suggested 🙂
