### ISSUE TITLE
NYTimes subscribe ad

### ISSUE THREAD

**Issue by sweetcashew** [yourduskquibbles/webannoyances#317]
### URL(s) where the issue occurs

`https://www.nytimes.com/2013/05/12/magazine/who-would-kill-a-monk-seal.html`

### Describe the issue

This filter removes subscribe ad from content flow:

```
nytimes.com###NYT_MAIN_CONTENT_2_REGION
```

### Screenshot(s)

<img width="741" alt="image" src="https://user-images.githubusercontent.com/88003315/127243298-2c978208-e9c8-4daf-b3d2-60d80b66e59c.png">

**Comment by yourduskquibbles** [comment]
Thanks for reporting, should be fixed now
