### ISSUE TITLE
New England Today annoyances

### ISSUE THREAD

**Issue by sweetcashew** [yourduskquibbles/webannoyances#318]
### URL(s) where the issue occurs

`https://newengland.com/today/living/new-england-history/karenwood/`

### Describe the issue

1. Sticky header (needs to be set to absolute rather than static because otherwise it is shifted down)
```
newengland.com###mq-fixed-header:style(position: absolute !important)
```

2. Missing menu icon (.social-icons selector blocks it)
```
newengland.com#@#.social-icons
newengland.com##.social-icons:not(:has(.mq-menu-icon))
newengland.com##.contain-to-grid.eyebrow .social ul.menu:style(text-align: left !important)
```

3. Inline text ad
```
newengland.com##.inline-text-ad
```

### Screenshot(s)

<img width="710" alt="image" src="https://user-images.githubusercontent.com/88003315/127441702-cf15f526-864d-4cd0-a703-ff0b2fb89426.png">

### Versions

- Browser & Version: FF 90.0.2
- Adblocker (uBlock Origin, Adguard, Nano Adblocker, etc.) & Version: uBO 1.37

**Comment by yourduskquibbles** [comment]
@sweetcashew Thanks for reporting and providing filter suggestions, added all of your suggested filters and an additional one for a modal overlay that popped up for me upon page reload. Appreciate all of the detailed reports you have submitted
