### ISSUE TITLE
Oprah Daily sticky header

### ISSUE THREAD

**Issue by sweetcashew** [yourduskquibbles/webannoyances#319]
### URL(s) where the issue occurs

`https://www.oprahdaily.com/life/a36903905/bradley-sisters-dissapearance/`

### Describe the issue

These filters unstick the header:

```
oprahdaily.com##.nav.sticky:style(position: static !important)
oprahdaily.com##.nav-placeholder
```

**Comment by yourduskquibbles** [comment]
Thanks for reporting, should be fixed now
