### ISSUE TITLE
wnycstudios.org broken

### ISSUE THREAD

**Issue by prodan1234** [yourduskquibbles/webannoyances#32]
```
wnycstudios.org 
```

Header image broken. [This](https://imgur.com/a/MzCiM) is what it looks like with Web Annoyances Ultralist. [This](https://imgur.com/a/XNVEY) is what it should look like.

OS/version: macOS 10.13.4
Browser/version: Chrome 66.0.3359.117 
Adblock Extension/version: uBlock Origin 1.15.24

**Comment by yourduskquibbles** [comment]
Thanks for reporting! Please update your filter list, it should be fixed now.
