### ISSUE TITLE
Boston Magazine annoyances

### ISSUE THREAD

**Issue by sweetcashew** [yourduskquibbles/webannoyances#321]
### URL(s) where the issue occurs

`https://www.bostonmagazine.com/news/2016/02/07/brian-peixoto-final-appeal/`

### Describe the issue

Two issues:
1. Header is sticky
2. Header width doesn't adjust when browser is resized

Filters to fix this:
```
bostonmagazine.com##.header-navigation.is_stuck:style(position: absolute !important)
bostonmagazine.com##.header-navigation-placeholder:style(width: 100% !important)
```

**Comment by yourduskquibbles** [comment]
Thanks for reporting, should be fixed now
