### ISSUE TITLE
The Star sticky header

### ISSUE THREAD

**Issue by sweetcashew** [yourduskquibbles/webannoyances#322]
### URL(s) where the issue occurs

`https://www.thestar.com/`

### Describe the issue

This filter removes the sticky header:

```
thestar.com##.o-main-menu--sticky
```

**Comment by yourduskquibbles** [comment]
Thanks for reporting, fixed this and a floating video I found on `https://www.thestar.com/sports/olympics/opinion/2021/08/04/for-andre-de-grasse-olympic-gold-brings-tears-of-pure-joy-silver-and-bronze-were-never-enough.html`
