### ISSUE TITLE
Bellingcat annoyances

### ISSUE THREAD

**Issue by sweetcashew** [yourduskquibbles/webannoyances#323]
### URL(s) where the issue occurs

`https://www.bellingcat.com/news/uk-and-europe/2020/12/21/if-it-hadnt-been-for-the-prompt-work-of-the-medics-fsb-officer-inadvertently-confesses-murder-plot-to-navalny/`

### Describe the issue

Two filters:

1. Unsticky the heading
    `bellingcat.com##.site__header:style(position: static !important)`
2. Remove ad at bottom of page
    `bellingcat.com##.footer__mailing`

### Screenshot(s)

Ad
<img width="714" alt="image" src="https://user-images.githubusercontent.com/88003315/127259822-a0ac6320-95aa-48cb-937b-560fe1608582.png">

**Comment by yourduskquibbles** [comment]
Thanks this should be fixed now
