### ISSUE TITLE
MIT Press sticky header

### ISSUE THREAD

**Issue by sweetcashew** [yourduskquibbles/webannoyances#324]
### URL(s) where the issue occurs

`https://mitpress.mit.edu/blog/jessica-pellien-rejoins-mit-press-director-marketing-and-communications`

### Describe the issue

Disables sticky header:
```
mitpress.mit.edu##.header:style(position: relative !important)
mitpress.mit.edu##.page-main:style(margin-top: 0 !important)
```

**Comment by yourduskquibbles** [comment]
Thanks, this should be fixed now
