### ISSUE TITLE
The MIT Press Reader sticky header nav

### ISSUE THREAD

**Issue by sweetcashew** [yourduskquibbles/webannoyances#325]
### URL(s) where the issue occurs

`https://thereader.mitpress.mit.edu/recounting-cognitive-history-of-numerals/`

### Describe the issue

Filters to disable sticky header (and disable show/hide animation when scrolling back to top of page):
```
thereader.mitpress.mit.edu###top-bar:style(position: static !important)
thereader.mitpress.mit.edu##.headroom:style(transform: none !important; transition: none !important)
```

**Comment by yourduskquibbles** [comment]
Thanks, this should be fixed now
