### ISSUE TITLE
Psyche annoyances

### ISSUE THREAD

**Issue by sweetcashew** [yourduskquibbles/webannoyances#327]
### URL(s) where the issue occurs

`https://psyche.co/ideas/mental-disorders-are-brain-disorders-heres-why-that-matters`
`https://psyche.co/guides/how-to-cope-with-experiencing-feelings-of-unreality`

### Describe the issue

Block social links & block subscribe and social overlays

```
psyche.co##[class*="MainColumn"] > [class*="Wrapper"]:last-child
psyche.co##[class*="Content"] > [class*="Wrapper"]:last-child
psyche.co##[class*="SocialLinks"]
psyche.co##[class*="SocialShareBarWrapper"]
psyche.co##[class*="SocialShareWrapper"]
psyche.co##[class*="SocialButtonsWrapper"]
psyche.co##[class*="SocialMetaWrapper"]
```

Note: `psyche.co##[class*="MainColumn"] > [class*="Wrapper"]:last-child` and `psyche.co##[class*="Content"] > [class*="Wrapper"]:last-child` target the subscribe overlays, which sadly don't have very good class names to grab, but I did some testing and these selectors seem to work well without causing false positives as far as I can tell.

### Screenshot(s)

<img width="683" alt="image" src="https://user-images.githubusercontent.com/88003315/127267545-b29be22a-6b69-41b9-9b91-b5af48b56776.png">

<img width="306" alt="image" src="https://user-images.githubusercontent.com/88003315/127267534-038dc29f-73d3-4b2c-9c96-5067f3989dc8.png">

<img width="339" alt="image" src="https://user-images.githubusercontent.com/88003315/127267585-8ffea6d4-c013-4666-9970-d6f856120f1b.png">

<img width="518" alt="image" src="https://user-images.githubusercontent.com/88003315/127268219-d79795aa-d083-47f2-8411-35dc5cbe4717.png">

**Comment by yourduskquibbles** [comment]
This should be fixed now and thanks for the filter suggestions, expert mode CSS selector on the newsletter subscribe filter suggestions 😉

**Comment by sweetcashew** [comment]
Re: https://github.com/yourduskquibbles/webannoyances/issues/326#issuecomment-892993191

I made better filters for this site. I recommend replacing my previous suggestions with these ones (less chance for false positives with these updated filters):

```
! https://psyche.co
! mid-content newsletter form
psyche.co##.csfaUk

! newsletter overlay
psyche.co##.iCORpj

! https://psyche.co/guides/how-to-ease-the-pain-of-grief-following-a-romantic-breakup
! social media popups for (1) light- and (2) dark-themed pages
psyche.co##.dGAfAi
psyche.co##.jECSPw

! sidebar social share links
psyche.co##[class*="styled__SocialShareWrapper-"]

! more sidebar social share links (these ones appear in the sidebar when you scroll to the bottom of the article)
! https://psyche.co/ideas/mental-disorders-are-brain-disorders-heres-why-that-matters
psyche.co##[class*="ideas__SocialShareBarWrapper-"] > [class*="styled__Container"]
psyche.co##[class*="guides__SocialMetaWrapper-"] > [class*="styled__Container"]
psyche.co##[class*="films__SocialButtonsWrapper-"] > [class*="styled__Container"]

! newsletter form on film pages
psyche.co##.bFXxib
```

**Comment by yourduskquibbles** [comment]
@sweetcashew Updated :)
