### ISSUE TITLE
The Atlantic social share button

### ISSUE THREAD

**Issue by sweetcashew** [yourduskquibbles/webannoyances#331]
### URL(s) where the issue occurs

`https://www.theatlantic.com/politics/archive/2021/07/how-government-learned-waste-your-time-tax/619568/`

### Describe the issue

```
theatlantic.com##[class*="ArticleShare_root"]
```

### Screenshot(s)

<img width="450" alt="image" src="https://user-images.githubusercontent.com/88003315/127411693-f0f57d88-db91-4758-ad1a-098439632ccc.png">

**Comment by yourduskquibbles** [comment]
@sweetcashew thx for reporting, added as suggested :)
