### ISSUE TITLE
PCGamer.com bug

### ISSUE THREAD

**Issue by sweetcashew** [yourduskquibbles/webannoyances#332]
### URL(s) where the issue occurs

`https://www.pcgamer.com/`

### Describe the issue

The header is wonky.

### Screenshot(s)

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/88003315/127420522-e7676ff1-ec4a-4919-aa61-42ca8b5e0c33.png">

### Versions

- Browser & Version: FF 90.0.2
- Adblocker (uBlock Origin, Adguard, Nano Adblocker, etc.) & Version: uBO 1.37

**Comment by yourduskquibbles** [comment]
@sweetcashew Thx for reporting, should be fixed now
