### ISSUE TITLE
blog.feedspot.com annoyances

### ISSUE THREAD

**Issue by sweetcashew** [yourduskquibbles/webannoyances#333]
### URL(s) where the issue occurs

`https://blog.feedspot.com/video_game_news/`

### Describe the issue

If you scroll down about halfway, an overlay pops up. Another one appears when you scroll back to top. And the contents of the pop up also appears in the footer (#wp_subscribe_popup_clone).
Block it with:
```
blog.feedspot.com###instantpopup
blog.feedspot.com###exitpopup
blog.feedspot.com###wp_subscribe_popup_clone
```

On the right of the page are social icons.
Block with:
```
blog.feedspot.com##.share_mod_ul
```

Inline ads to block:
```
blog.feedspot.com###bloggersoutreach
blog.feedspot.com##.mkt-container
```

Block sidebar marketing and email alert form:
```
blog.feedspot.com###custom_html-3, #custom_html-3_clone
blog.feedspot.com###text-836, #text-836_clone
```

Block email follow form:
```
blog.feedspot.com##[id^="newsletterform"]
```

### Screenshot(s)

<img width="1099" alt="image" src="https://user-images.githubusercontent.com/88003315/127422922-3f62f8de-c2ea-44cd-8b35-fe472bb1f396.png">

<img width="444" alt="image" src="https://user-images.githubusercontent.com/88003315/127423090-4e44df36-f095-40eb-a6ac-63b588b7ff43.png">

<img width="876" alt="image" src="https://user-images.githubusercontent.com/88003315/127423458-b9a74152-5155-4817-8260-335cf87b0733.png">

<img width="842" alt="image" src="https://user-images.githubusercontent.com/88003315/127423526-d61f0540-fb72-4463-b869-6093f8df533d.png">

<img width="244" alt="image" src="https://user-images.githubusercontent.com/88003315/127424854-d6f01580-9b66-4baf-b04a-0e870146a148.png">

<img width="233" alt="image" src="https://user-images.githubusercontent.com/88003315/127423994-8fc2a9e3-f4c1-4372-a46a-ce04e23757de.png">

<img width="400" alt="image" src="https://user-images.githubusercontent.com/88003315/127424201-d9954a3e-1177-474c-9a97-3865f2e0c554.png">

**Comment by yourduskquibbles** [comment]
@sweetcashew thx for reporting, should be fixed now.
