### ISSUE TITLE
Buzzfeed News inline follow/feedback annoyance

### ISSUE THREAD

**Issue by sweetcashew** [yourduskquibbles/webannoyances#334]
### URL(s) where the issue occurs

`https://www.buzzfeednews.com/article/adeonibada/sundown-towns-racism-black-drivers-tiktok`

### Describe the issue

Block inline follow/feedback container:
```
buzzfeednews.com##.follow--container
```

### Screenshot(s)

<img width="884" alt="image" src="https://user-images.githubusercontent.com/88003315/127425605-049f449c-7f64-4629-9964-3bbe3e6cce86.png">

**Comment by yourduskquibbles** [comment]
Thx for reporting, should be fixed now.
