### ISSUE TITLE
GQ subscription ad

### ISSUE THREAD

**Issue by sweetcashew** [yourduskquibbles/webannoyances#335]
### URL(s) where the issue occurs

`https://www.gq.com/story/jerry-joseph-scandal-hs-basketball`

### Describe the issue

Block bottom-of-page subscription ad:
```
gq.com##[class*="ConsumerMarketingUnitThemedWrapper"]
```

### Screenshot(s)

<img width="1241" alt="image" src="https://user-images.githubusercontent.com/88003315/127425805-8bcd2322-5352-4c03-84e9-05b3811d966b.png">

**Comment by yourduskquibbles** [comment]
Thanks for reporting, fixed as suggested :)
