### ISSUE TITLE
newyorker.com

### ISSUE THREAD

**Issue by sweetcashew** [yourduskquibbles/webannoyances#336]
### URL(s) where the issue occurs

`https://www.newyorker.com/magazine/2021/08/09/the-seas-are-rising-could-oysters-protect-us`

### Describe the issue

The Ultralist has a filter that sets part of the header height to `7rem`, but it looks like it should be smaller (or maybe an auto height instead?)

### Screenshot(s)

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/88003315/128247992-8b31c140-3680-4f72-aad9-fc329f471d7a.png">

### Versions

- Browser & Version: FF 90.0.2
- Adblocker (uBlock Origin, Adguard, Nano Adblocker, etc.) & Version: uBO 1.37

**Comment by yourduskquibbles** [comment]
@sweetcashew Thx for reporting, I think this should be fixed now.

**Comment by IMayKnow** [comment]
@yourduskquibbles ![image](https://user-images.githubusercontent.com/89752791/131944425-7b941f04-aff6-4a9e-9db1-19c1216420b5.png)
