### ISSUE TITLE
washingtonpost.com

### ISSUE THREAD

**Issue by sweetcashew** [yourduskquibbles/webannoyances#339]
### URL(s) where the issue occurs

`https://www.washingtonpost.com/rolex-partnership-content/climate-solutions/the-penguin-protector/`

### Describe the issue

The header/navbar is broken.

### Screenshot(s)

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/88003315/128261784-a8c1cb22-22f5-4b90-b593-8830c380b599.png">

**Comment by yourduskquibbles** [comment]
Thanks for reporting, took a while to figure out the correct filter updates but think this fixes it.

If you see any other `washingtonpost.com` pages with breakage based on these filter updates please let me know.
