### ISSUE TITLE
imgur.com

### ISSUE THREAD

**Issue by RedDragonWebDesign** [yourduskquibbles/webannoyances#340]
### URL(s) where the issue occurs

Any image/gallery page on imgur.com. Example: https://imgur.com/gallery/31V6wAT

### Describe the issue

Only happens with Web Annoyances Ultralist installed. Load the page. After a couple seconds, page will go gray. I think some JavaScript is deleting a bunch of HTML elements.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/43397938/128492277-4be41170-f2b5-4f3e-8ca3-d139c6a54ca5.png)

### Versions

- Browser & Version: Edge
- Adblocker (uBlock Origin, Adguard, Nano Adblocker, etc.) & Version: ubo 1.36.2

### Settings

- ubo defaults + all annoyances lists + web annoyances ultralist

**Comment by yourduskquibbles** [comment]
Related: #311 I have no idea what filter is causing this so I just remove them all and rewrote new filters. Seems to be working for me with testing so I am going to push filter and hope it works for both @RedDragonWebDesign and @sweetcashew if you both can test  and confirm :)

**Comment by RedDragonWebDesign** [comment]
Looks good, thanks for fixing. Maybe look into a filter for the floating footer too.

**Comment by yourduskquibbles** [comment]
> 
> 
> Looks good, thanks for fixing. Maybe look into a filter for the floating footer too.

Thanks for confirming! Must have chopped that one out accidentally, will add `imgur.com##.Footer-wrapper:style(position: relative !important; bottom: 0 !important;)` back.

Although with infinite scroll, you never actually are able to see the footer for more than a flash before it shifts off page again. :/
