### ISSUE TITLE
Yahoo News Bottombar Gets Pinned to Middle of Screen

### ISSUE THREAD

**Issue by borealis999** [yourduskquibbles/webannoyances#341]
### URL(s) where the issue occurs

`news.yahoo com`

### Describe the issue

The bottom bar in a news article on Yahoo News that has the "view comments" button should be pinned to the bottom of the page, however, it is pinned near the start of the article, obstructing some text

### Screenshot(s)

![Screenshot_2021-08-08-15-44-46-862_com kiwibrowser browser](https://user-images.githubusercontent.com/66651428/128647931-7b553076-44d8-4eba-83d1-582ed8dd1f08.jpg)

### Versions

- Browser & Version: Kiwi Browser version 93.0.4577.25 (Android)
- Adblocker (uBlock Origin, Adguard, Nano Adblocker, etc.) & Version: Android app version 4.0.60

### Settings

- Allow QUIC connections to Kiwi
- Use Dandelion Sprout Annoyances List
- Add F***F***AdBlock list

### Notes

This issue persists even when using Kiwi Browser with no extensions except for uBlock Origin with no lists used other than Web Annoyances Ultralist

**Comment by yourduskquibbles** [comment]
@borealis999 Thanks for reporting, I think this should be fixed now. If you still see any issues, please let me know
