### ISSUE TITLE
NYTimes cooking subscription bar on all pages

### ISSUE THREAD

**Issue by prech** [yourduskquibbles/webannoyances#342]
### URL(s) where the issue occurs

https://www.nytimes.com
https://www.nytimes.com/2021/08/17/us/politics/afghanistan-biden-administration.html

### Describe the issue

"Get NYT Cooking for $1.25/week" atop all pages

### Screenshot(s)

![image](https://user-images.githubusercontent.com/8314103/129858016-5863144b-1959-49ba-a1c5-6e995588898f.png)

### Versions

- Browser/version: Google Chrome Version 92.0.4515.131
- uBlock Origin version: uBlock Origin 1.37.2

### Notes

I think adding this filter worked for me, but don't know if it's the most efficient method, or if the ID might change names to evade the filter

`www.nytimes.com##.css-1q6mid5`

Thanks!

**Comment by yourduskquibbles** [comment]
@prech I also added `nytimes.com##.css-1q6mid5[href*="/subscription?"]` which I was able to use on a different button that loaded for `$1 week subscription` with the same class element as you reported. hoping this also works for the Cooking subscription button, but please let me know if it doesn't!
