### ISSUE TITLE
bing.com

### ISSUE THREAD

**Issue by Mennaruuk** [yourduskquibbles/webannoyances#343]
### URL(s) where the issue occurs

`https://bing.com`

### Describe the issue

Bing homepage looks glitchy with WAU enabled. See screenshots below.

### Screenshot(s)
<p align="center"> WAU enabled </p>

![image](https://user-images.githubusercontent.com/52135169/131281870-ac5ab7d4-a959-496d-8c36-b40d56606845.png)

<p align="center"> WAU disabled </p>

![image](https://user-images.githubusercontent.com/52135169/131281928-a54f3a08-1a19-42a6-af18-84c6f55cda3d.png)

### Versions

- Browser & Version: Firefox 91.0.2
- Adblocker (uBlock Origin, Adguard, Nano Adblocker, etc.) & Version: uBlock Origin 1.37.2

### Settings

- N/A

### Notes

N/A

**Comment by yourduskquibbles** [comment]
@Mennaruuk Thanks for reporting! Believe this should be fixed now, please let me know if seeing any other issues though.
