### ISSUE TITLE
lightningmaps.org

### ISSUE THREAD

**Issue by WittyNameHere** [yourduskquibbles/webannoyances#344]
### URL(s) where the issue occurs
`https://www.lightningmaps.org`

### Describe the issue
Page content is not displaying as normal

### Screenshot(s)
What you should get: ![2iWPgKPo3P](https://user-images.githubusercontent.com/45863172/131586990-8a91b12c-1596-401d-8cc0-ccbb67a48dbc.png)
What I'm actually getting: ![msedge_YcQUCl0GYU](https://user-images.githubusercontent.com/45863172/131586992-cb806103-4bf7-41b7-9cde-570308115b48.png)

### Versions
- Browser & Version: Tested with Vivaldi 4.1 and Edge 92
- Adblocker (uBlock Origin, Adguard, Nano Adblocker, etc.) & Version: uBlock Origin 1.37.2

### Settings

No changes specific to this domain.

### Notes

Site loads normally when this blocklist is disabled.

**Comment by yourduskquibbles** [comment]
@WittyNameHere thx for reporting, this should be fixed now. Please let me know if you see other issues!
