### ISSUE TITLE
dictionary.com (floating header)

### ISSUE THREAD

**Issue by Mennaruuk** [yourduskquibbles/webannoyances#346]
### URL(s) where the issue occurs

`https://www.dictionary.com/e/new-dictionary-words-summer-2021`

### Describe the issue

Floating header.

### Screenshot(s)

![ezgif com-gif-maker](https://user-images.githubusercontent.com/52135169/131926826-ad6b5ac4-6819-41b0-8a58-1d8005ef48d9.gif)

### Versions

- Browser & Version: Firefox 91.0.2
- Adblocker (uBlock Origin, Adguard, Nano Adblocker, etc.) & Version: uBlock Origin 1.37.2

### Settings

N/A

### Notes

Thanks, dude.

**Comment by yourduskquibbles** [comment]
@Mennaruuk Thx for reporting, should be fixed now!
