### ISSUE TITLE
cityam.com

### ISSUE THREAD

**Issue by Mennaruuk** [yourduskquibbles/webannoyances#348]
### URL(s) where the issue occurs

`https://www.cityam.com`

### Describe the issue

Subscription nag.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/52135169/131929740-8b0a6bd1-432b-4666-8f44-e8c46db4d4e9.png)

### Versions

- Browser & Version: Firefox 91.0.2
- Adblocker (uBlock Origin, Adguard, Nano Adblocker, etc.) & Version: uBlock Origin 1.37.2

### Settings

N/A

### Notes

Thanks again!

**Comment by Mennaruuk** [comment]
`cityam.com###tpdPopupModal`

**Comment by yourduskquibbles** [comment]
@Mennaruuk Thx for reporting, should be fixed now & also floating header

**Comment by Mennaruuk** [comment]
### URL(s) where the issue occurs

`https://www.cityam.com/superyacht-sales-return-as-more-billionaires-splash-out`

### Describe the issue

Sticky header + subscription nag at bottom.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/52135169/140993086-ec7d6451-16ac-4fcb-9768-dbe2354c5257.png)



### Versions

- Browser & Version: Firefox 94.0.1
- Adblocker (uBlock Origin, Adguard, Nano Adblocker, etc.) & Version: uBlock Origin 1.38.6

### Settings

N/A

### Notes

Thanks a lot!

**Comment by yourduskquibbles** [comment]
@Mennaruuk Filters should be updated now to fix new report. Thx!
