### ISSUE TITLE
Sciencing.com

### ISSUE THREAD

**Issue by zaphodbeebblebrox** [yourduskquibbles/webannoyances#35]
Example: `https://sciencing.com/calculate-electroplating-7597391.html`

`sciencing.com##.header-container:style(position: absolute !important;)`

**Comment by yourduskquibbles** [comment]
Thanks @zaphodbeebblebrox - Just FYI I also added a CSS transition fix for the header height transition.

**Comment by Mennaruuk** [comment]
_Sciencing_ is back at it with sticky header and scrolling video. Yikes!

**Comment by yourduskquibbles** [comment]
@Mennaruuk Thx for reporting, should be fixed again.
