### ISSUE TITLE
yt5s.com

### ISSUE THREAD

**Issue by ghost** [yourduskquibbles/webannoyances#351]
### URL(s) where the issue occurs
`https://yt5s.com/en5/youtube-to-mp3`
`[At least one URL for a web page where the clearly described issue occurs is **mandatory**. The backticks surrounding the URLs is important, it prevents the URL from being clickable. Warn with "NSFW" where applicable.]`

### Describe the issue
Ad / Annoyance
[Be as clear as possible: nobody can read your mind, and nobody is looking at your issue over your shoulder.]

### Screenshot(s)

[Screenshot(s) for difficult to describe visual issues are **mandatory**. Post links instead of **Inline Images** for Screenshots containing **Adult material**.]

### Versions

- Browser & Version: Google Chrome 92.0.4515.159 (Official Build) (64-bit)
- Adblocker (uBlock Origin, Adguard, Nano Adblocker, etc.) & Version: uBlock Origin 1.37.2

### Settings

- ![image](https://user-images.githubusercontent.com/89752791/131943636-2830633c-b374-4182-988c-9e5a053656b4.png)
- ![image](https://user-images.githubusercontent.com/89752791/131943665-6deaff6b-5c08-41e3-a138-cbf7950fe99b.png)

### Notes

[Add here the result of whatever investigation work you have done: please investigate the issues you report -- this prevents burdening other volunteers. This is especially true for issues arising from settings which are very different from default ones.]

**Comment by yourduskquibbles** [comment]
Should be fixed now
