### ISSUE TITLE
mail.hostinger.com

### ISSUE THREAD

**Issue by pintassilgo** [yourduskquibbles/webannoyances#355]
### URL(s) where the issue occurs

`[https://mail.hostinger.com/]`

### Describe the issue

The filter
`hostinger.com##.menu:style(position: absolute !important;)`
in `floating_filters.txt` is breaking Hostinger webmail layout, with overlapping buttons and hidden search input.

### Screenshot(s)

With the filter:
![image](https://user-images.githubusercontent.com/5483864/133145091-e38b0fa4-5fa9-4193-bed6-160ab1874019.png)

Disabling cosmetic filters or adding the following exception rule:
`hostinger.com#@#.menu:style(position: absolute !important;)`
![image](https://user-images.githubusercontent.com/5483864/133145162-a6082368-fd5f-4ee2-9ae1-0648ff86affb.png)

### Versions

- Browser & Version: Firefox 92
- Adblocker (uBlock Origin, Adguard, Nano Adblocker, etc.) & Version: uBO 1.37.2

### Settings

- Medium mode.

**Comment by yourduskquibbles** [comment]
@pintassilgo thx for reporting, I changed the target domain on `hostinger.com` filters since it looks like mail uses subdomain `mail.hostinger.com` not `www.hostinger.com` please let me know if still having any issues!
