### ISSUE TITLE
time.com

### ISSUE THREAD

**Issue by Mennaruuk** [yourduskquibbles/webannoyances#356]
### URL(s) where the issue occurs

`https://time.com`

### Describe the issue

Text over text.

### Screenshot(s)

WAU Enabled
![image](https://user-images.githubusercontent.com/52135169/133527794-a9a51900-c67a-4ea0-b152-8ab1f4c0b449.png)

WAU Disabled
![image](https://user-images.githubusercontent.com/52135169/133528076-584a1174-b07c-4d2a-aaed-9cdea12a28ac.png)

### Versions

- Browser & Version: Firefox 92
- Adblocker (uBlock Origin, Adguard, Nano Adblocker, etc.) & Version: uBlock Origin 1.37.2

### Settings

N/A

### Notes
There's also a sticky header in this story:
`https://time.com/collection/next-generation-leaders`

![image](https://user-images.githubusercontent.com/52135169/133528323-06777223-0933-402e-b6fd-3f85485a8fb3.png)

Thanks again!

**Comment by yourduskquibbles** [comment]
@Mennaruuk Thx for reporting! Both reported issues should be fixed now. Please let me know if you find other problems!
