### ISSUE TITLE
cell.com

### ISSUE THREAD

**Issue by Mennaruuk** [yourduskquibbles/webannoyances#358]
### URL(s) where the issue occurs

`https://www.cell.com/cell/fulltext/S0092-8674(21)01057-6`

### Describe the issue

Floating header.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/52135169/133890880-9ab47fdc-1312-4077-9934-3ec3e639b2f3.png)

### Versions

- Browser & Version: Firefox 92
- Adblocker (uBlock Origin, Adguard, Nano Adblocker, etc.) & Version: uBlock Origin 1.37.2

### Settings

N/A

### Notes

Thanks, dude.

**Comment by yourduskquibbles** [comment]
@Mennaruuk Thanks for reporting, this should be fixed now!
