### ISSUE TITLE
theguardian.com

### ISSUE THREAD

**Issue by ExtremelyCool** [yourduskquibbles/webannoyances#359]
### URL(s) where the issue occurs

`[At least one URL for a web page where the clearly described issue occurs is **mandatory**. The backticks surrounding the URLs is important, it prevents the URL from being clickable. Warn with "NSFW" where applicable.]`

### Describe the issue
`https://www.theguardian.com/us`
[Be as clear as possible: nobody can read your mind, and nobody is looking at your issue over your shoulder.]

### Screenshot(s)
![image](https://user-images.githubusercontent.com/90566652/134750854-8ea7f95f-0482-4424-9799-e94147372670.png)

[Screenshot(s) for difficult to describe visual issues are **mandatory**. Post links instead of **Inline Images** for Screenshots containing **Adult material**.]

### Versions

- Browser & Version: Google Chrome
- Adblocker (uBlock Origin, Adguard, Nano Adblocker, etc.) & Version: uBlock Origin 1.38.0

### Settings

- [List here all the changes you made to your Adblocker's default settings]

### Notes

[Add here the result of whatever investigation work you have done: please investigate the issues you report -- this prevents burdening other volunteers. This is especially true for issues arising from settings which are very different from default ones.]

**Comment by ExtremelyCool** [comment]
Also, mailing button `https://www.theguardian.com/us-news/2021/sep/24/house-democrats-abortion-federal-right-vote`

**Comment by ExtremelyCool** [comment]
Also, mailing button(s) on `https://www.theguardian.com/us-news/2021/sep/24/house-democrats-abortion-federal-right-vote`

**Comment by yourduskquibbles** [comment]
@ExtremelyCool Thx for reporting, this should be fixed now.

Re: the mailing button(s), my policy on that is to leave them when they use the `mailto:` URI, see https://github.com/yourduskquibbles/webannoyances/issues/330#issuecomment-892995846 for more explanation
