### ISSUE TITLE
science.org

### ISSUE THREAD

**Issue by Mennaruuk** [yourduskquibbles/webannoyances#360]
### URL(s) where the issue occurs

`https://www.science.org/doi/10.1126/sciimmunol.abf1198`

### Describe the issue

Sticky header and back-to-top button.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/52135169/134751631-27df8bbc-7f60-4984-b359-891f8b0290e1.png)

### Versions

- Browser & Version: Firefox 92.0.1
- Adblocker (uBlock Origin, Adguard, Nano Adblocker, etc.) & Version: uBlock Origin 1.37.2

### Settings

N/A

### Notes

Thanks, dude.

**Comment by yourduskquibbles** [comment]
@Mennaruuk Thx for reporting! This should be fixed now, please let me know if you still see any issues.
