### ISSUE TITLE
pubs.acs.org

### ISSUE THREAD

**Issue by Mennaruuk** [yourduskquibbles/webannoyances#361]
### URL(s) where the issue occurs

`https://pubs.acs.org/doi/10.1021/acsbiomedchemau.1c00021`

### Describe the issue

Sticky header.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/52135169/134751708-cc9e3790-f72f-40c0-8633-34f16aca73ac.png)

### Versions

- Browser & Version: Firefox 92.0.1
- Adblocker (uBlock Origin, Adguard, Nano Adblocker, etc.) & Version: uBlock Origin 1.37.2

### Settings

N/A

### Notes

Thanks, dude.

**Comment by yourduskquibbles** [comment]
@Mennaruuk Thx for reporting, should be fixed but if you are able, can you confirm on another example article? There's a lot of css involved with this one because of how they display the secondary header after scrolling down so trying to neuter that with no side-effects.

**Comment by Mennaruuk** [comment]
It works well on other articles! Thank you.

Example: `https://pubs.acs.org/doi/10.1021/accountsmr.1c00147`

The only issue is that the title of articles is now partially hidden.

![image](https://user-images.githubusercontent.com/52135169/135171494-4e3be5ff-9c36-4c8b-8b9a-457a53c9a4c1.png)

Is there a way to make the header shorter so the title shows more fully? Thanks!

![image](https://user-images.githubusercontent.com/52135169/135171643-5c11d362-4b09-42d2-ba7f-6deebb3354fd.png)

**Comment by yourduskquibbles** [comment]
> https://pubs.acs.org/doi/10.1021/accountsmr.1c00147

Thanks for replying, looks like they are loading different CSS depending on screen resolution but using the same class names.

![acs org](https://user-images.githubusercontent.com/22258847/135302548-406a5aab-bb1b-4db0-bf81-109f93803b43.png)

 I will Probably need to remove some of the exact `px` widths and margins that I am setting since there is no class names I can use based on their site design to account for smaller resolution screen... This may make the header a little "flashy" or "jumpy" scrolling down and back up to the top, but that's less of an annoyance than what you have pointed out.

**Comment by Mennaruuk** [comment]
Dang. Why are they making it this hard?

If it’s too much work, you can leave the sticky header. I feel like this will cause a headache for you. Thank you so much for your help!

**Comment by yourduskquibbles** [comment]
> Dang. Why are they making it this hard?

It's just a non-standard site code design choice :) Every site is different, and to be honest, it can be a fun puzzle to try and figure out some of the more interesting ones.


I think I maybe found a decent workaround, but the header contents will flash a bit when you scroll down and scroll back up quickly now. I tested a bunch of different screen widths with these filters so hopefully this is "usable" for the vast majority of screen widths. Just let me know if you see something I may have missed after loading the new filters.

**Comment by Mennaruuk** [comment]
It works perfectly! Thank you so much, boss :)

**Comment by Mennaruuk** [comment]
Perfect! Thank you for fixing the filter, now ACS is web annoyances-free!
