### ISSUE TITLE
ebay.com

### ISSUE THREAD

**Issue by ExtremelyCool** [yourduskquibbles/webannoyances#364]
### URL(s) where the issue occurs

`[At least one URL for a web page where the clearly described issue occurs is **mandatory**. The backticks surrounding the URLs is important, it prevents the URL from being clickable. Warn with "NSFW" where applicable.]`

### Describe the issue
feedback button
[Be as clear as possible: nobody can read your mind, and nobody is looking at your issue over your shoulder.]

### Screenshot(s)

[Screenshot(s) for difficult to describe visual issues are **mandatory**. Post links instead of **Inline Images** for Screenshots containing **Adult material**.]

### Versions

- Browser & Version: Google Chrome 93.0.4577.82 (Official Build) (64-bit)
- Adblocker (uBlock Origin, Adguard, Nano Adblocker, etc.) & Version: uBlock Origin 1.38.0

### Settings
![image](https://user-images.githubusercontent.com/90566652/134752269-bf3a43df-dcd4-45c4-8eda-ced386d5f741.png)
![image](https://user-images.githubusercontent.com/90566652/134752279-3ae5085f-0d40-49ed-871c-d182f8020ad7.png)

### Notes

[Add here the result of whatever investigation work you have done: please investigate the issues you report -- this prevents burdening other volunteers. This is especially true for issues arising from settings which are very different from default ones.]

**Comment by yourduskquibbles** [comment]
@ExtremelyCool Can you provide screenshot or specific page on what you are requesting? Not sure what `feedback button` is referring to.

**Comment by agam3r** [comment]
![image](https://user-images.githubusercontent.com/93623745/140179201-dc071dbc-6115-4aa5-aaea-48420a0c13b5.png)

**Comment by yourduskquibbles** [comment]
The feedback button is fixed in place already so not sure what there is to address. Closing unless get more information on what should be changed.
