### ISSUE TITLE
kotaku.com

### ISSUE THREAD

**Issue by ExtremelyCool** [yourduskquibbles/webannoyances#365]
### URL(s) where the issue occurs
`https://kotaku.com/kirby-going-full-on-super-mario-odyssey-on-the-switch-i-1847739334`
`[At least one URL for a web page where the clearly described issue occurs is **mandatory**. The backticks surrounding the URLs is important, it prevents the URL from being clickable. Warn with "NSFW" where applicable.]`

### Describe the issue
sharing buttons
[Be as clear as possible: nobody can read your mind, and nobody is looking at your issue over your shoulder.]

### Screenshot(s)

[Screenshot(s) for difficult to describe visual issues are **mandatory**. Post links instead of **Inline Images** for Screenshots containing **Adult material**.]

### Versions

- Browser & Version: Google Chrome 93.0.4577.82 (Official Build) (64-bit)
- Adblocker (uBlock Origin, Adguard, Nano Adblocker, etc.) & Version: uBlock Origin 1.38.0

### Settings
![image](https://user-images.githubusercontent.com/90566652/134752269-bf3a43df-dcd4-45c4-8eda-ced386d5f741.png)
![image](https://user-images.githubusercontent.com/90566652/134752279-3ae5085f-0d40-49ed-871c-d182f8020ad7.png)
- [List here all the changes you made to your Adblocker's default settings]

### Notes

[Add here the result of whatever investigation work you have done: please investigate the issues you report -- this prevents burdening other volunteers. This is especially true for issues arising from settings which are very different from default ones.]

**Comment by Mennaruuk** [comment]
I propose:

`kotaku.com##.share-tools-buttons-inpost`
