### ISSUE TITLE
usnews.com

### ISSUE THREAD

**Issue by ExtremelyCool** [yourduskquibbles/webannoyances#368]
### URL(s) where the issue occurs
`https://www.usnews.com/news`
`[At least one URL for a web page where the clearly described issue occurs is **mandatory**. The backticks surrounding the URLs is important, it prevents the URL from being clickable. Warn with "NSFW" where applicable.]`

### Describe the issue
annoyance / newsletter subscription box
[Be as clear as possible: nobody can read your mind, and nobody is looking at your issue over your shoulder.]

### Screenshot(s)

[Screenshot(s) for difficult to describe visual issues are **mandatory**. Post links instead of **Inline Images** for Screenshots containing **Adult material**.]

### Versions

- Browser & Version: Google Chrome
- Adblocker (uBlock Origin, Adguard, Nano Adblocker, etc.) & Version: uBO 1.38.0

### Settings
![image](https://user-images.githubusercontent.com/90566652/134827273-298c6196-9a76-40c1-8ac4-de18a930589d.png)
![image](https://user-images.githubusercontent.com/90566652/134827266-b45705bf-2c83-427c-8486-546161154b68.png)
- [List here all the changes you made to your Adblocker's default settings]

### Notes

[Add here the result of whatever investigation work you have done: please investigate the issues you report -- this prevents burdening other volunteers. This is especially true for issues arising from settings which are very different from default ones.]

**Comment by Mennaruuk** [comment]
Do you have a specific link to a page that shows this newsletter box? I can't find one.
