### ISSUE TITLE
broken youtube site

### ISSUE THREAD

**Issue by KonoromiHimaries** [yourduskquibbles/webannoyances#37]
![2018-05-01- 3 na czasie - youtube](https://user-images.githubusercontent.com/5884000/39461239-a36aa232-4d09-11e8-883d-b3956c6c995a.png)

**Comment by KonoromiHimaries** [comment]
https://github.com/MajkiIT/polish-ads-filter/issues/7394

**Comment by yourduskquibbles** [comment]
Thanks, please refresh your filters and verify it is fixed.
