### ISSUE TITLE
brainly.com

### ISSUE THREAD

**Issue by ExtremelyCool** [yourduskquibbles/webannoyances#370]
### URL(s) where the issue occurs
`https://brainly.com/`
`[At least one URL for a web page where the clearly described issue occurs is **mandatory**. The backticks surrounding the URLs is important, it prevents the URL from being clickable. Warn with "NSFW" where applicable.]`

### Describe the issue
floating header
[Be as clear as possible: nobody can read your mind, and nobody is looking at your issue over your shoulder.]

### Screenshot(s)

[Screenshot(s) for difficult to describe visual issues are **mandatory**. Post links instead of **Inline Images** for Screenshots containing **Adult material**.]

### Versions

- Browser & Version: Tor
- Adblocker (uBlock Origin, Adguard, Nano Adblocker, etc.) & Version: uBlock Origin 1.37.2

### Settings
![image](https://user-images.githubusercontent.com/90566652/134993463-00625c78-b281-4d93-8436-0581d7d25bf4.png)
![image](https://user-images.githubusercontent.com/90566652/134993493-1f9648f7-7af9-4144-af9a-4e5c603ee031.png)

- [List here all the changes you made to your Adblocker's default settings]

### Notes

[Add here the result of whatever investigation work you have done: please investigate the issues you report -- this prevents burdening other volunteers. This is especially true for issues arising from settings which are very different from default ones.]

**Comment by yourduskquibbles** [comment]
@ExtremelyCool Thx for reporting, should be fixed now.
