### ISSUE TITLE
comicbook.com

### ISSUE THREAD

**Issue by zaphodbeebblebrox** [yourduskquibbles/webannoyances#39]
Example url: `http://comicbook.com/marvel/2018/05/01/avengers-infinity-war-hints-at-captain-marvel-kree-skrull-war/`

Not suggesting anything because everything I do looks kind-of ugly.

**Comment by yourduskquibbles** [comment]
@zaphodbeebblebrox Do you have filter list enabled? I have filters for this site already. Only thing that I see that could be improved is the sidebar and maybe the video transition animation. Is there something else you see?

**Comment by zaphodbeebblebrox** [comment]
Sorry, I'm an idiot.
