### ISSUE TITLE
forcescience.org

### ISSUE THREAD

**Issue by Mennaruuk** [yourduskquibbles/webannoyances#396]
### URL(s) where the issue occurs

`https://www.forcescience.org/2021/03/causing-suspects-to-attack-you`

### Describe the issue

Sticky header + back-to-top button.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/52135169/139595255-5809a1a3-59d8-4864-9ba5-dc4ce8f4c875.png)

### Versions

- Browser & Version: Firefox 93.0
- Adblocker (uBlock Origin, Adguard, Nano Adblocker, etc.) & Version: uBlock Origin 1.38.6

### Settings

N/A

### Notes

Thanks a lot!

**Comment by yourduskquibbles** [comment]
@Mennaruuk Thx for reporting, believe this should be fixed now although uses some non-standard ways to defeat the sticky header so please confirm if you are able! Thanks!

**Comment by Mennaruuk** [comment]
It works perfectly. You're a whiz!
