### ISSUE TITLE
3rbcafee.com

### ISSUE THREAD

**Issue by Mennaruuk** [yourduskquibbles/webannoyances#397]
### URL(s) where the issue occurs

`https://www.3rbcafee.com/2020/05/Alrayyan-TV-Live.html`

### Describe the issue

Sticky header and footer.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/52135169/139604386-15b935bb-6dc8-4092-abbe-e23f93b76333.png)

### Versions

- Browser & Version: Firefox 93.0
- Adblocker (uBlock Origin, Adguard, Nano Adblocker, etc.) & Version: uBlock Origin 1.38.6

### Settings

N/A

### Notes

Thanks a bunch!

**Comment by yourduskquibbles** [comment]
@Mennaruuk Thx for reporting, this should be fixed now!
