### ISSUE TITLE
corpuscoranicum.de

### ISSUE THREAD

**Issue by Mennaruuk** [yourduskquibbles/webannoyances#398]
### URL(s) where the issue occurs

`https://corpuscoranicum.de/handschriften/index/sure/7/vers/195/handschrift/323`

### Describe the issue

Super annoying sticky header. It gets in my way of working!

### Screenshot(s)

![image](https://user-images.githubusercontent.com/52135169/139965398-763566b8-b0ce-4500-9591-187156facfda.png)

### Versions

- Browser & Version: Firefox 93.0
- Adblocker (uBlock Origin, Adguard, Nano Adblocker, etc.) & Version: uBlock Origin 1.38.6

### Settings

N/A

### Notes

Thanks a lot!

**Comment by yourduskquibbles** [comment]
@Mennaruuk Thx for reporting, this should be fixed now!
