### ISSUE TITLE
moviefone.com

### ISSUE THREAD

**Issue by Mennaruuk** [yourduskquibbles/webannoyances#400]
### URL(s) where the issue occurs

`https://www.moviefone.com/movie/a-mouthful-of-air/KBhVpKFJGZRADeF84PgwV5/video/I4ANsTM0`

### Describe the issue

Sticky header.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/52135169/140259306-e47c0651-c8ec-47d9-a1b1-281d30a30296.png)

### Versions

- Browser & Version: Firefox 93.0
- Adblocker (uBlock Origin, Adguard, Nano Adblocker, etc.) & Version: uBlock Origin 1.38.6

### Settings

N/A

### Notes

Thanks a lot!

**Comment by yourduskquibbles** [comment]
@Mennaruuk Thx for reporting, should be fixed now!
