### ISSUE TITLE
realpython.com

### ISSUE THREAD

**Issue by Mennaruuk** [yourduskquibbles/webannoyances#401]
### URL(s) where the issue occurs

`https://realpython.com/python-speech-recognition`

### Describe the issue

Sticky header.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/52135169/140364459-7061a8c0-9915-4d7f-bbd2-8e1cc38e2ca4.png)

### Versions

- Browser & Version: Firefox 93.0
- Adblocker (uBlock Origin, Adguard, Nano Adblocker, etc.) & Version: uBlock Origin 1.38.6

### Settings

N/A

### Notes

Thanks a lot!

**Comment by yourduskquibbles** [comment]
@Mennaruuk Thx for reporting, should be fixed now!
