### ISSUE TITLE
mondoweiss.net

### ISSUE THREAD

**Issue by Mennaruuk** [yourduskquibbles/webannoyances#402]
### URL(s) where the issue occurs

`https://mondoweiss.net/2021/11/apartheids-spiritual-devastation-is-theme-of-nyt-israel-travelogue-that-uses-the-a-word-only-once`

### Describe the issue

Sticky header.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/52135169/140653870-bb35a51d-435f-49f0-94c2-02ad7e24d0aa.png)

### Versions

- Browser & Version: Firefox 93.0
- Adblocker (uBlock Origin, Adguard, Nano Adblocker, etc.) & Version: uBlock Origin 1.38.6

### Settings

N/A

### Notes

Thanks a lot!

**Comment by yourduskquibbles** [comment]
@Mennaruuk Thx for reporting, should be fixed now!
