### ISSUE TITLE
responsiblestatecraft.org

### ISSUE THREAD

**Issue by Mennaruuk** [yourduskquibbles/webannoyances#403]
### URL(s) where the issue occurs

`https://responsiblestatecraft.org/2021/11/05/new-marvel-film-puts-spotlight-on-hollywoods-military-ties`

### Describe the issue

Sticky header on homepage + articles.

### Screenshot(s)
![image](https://user-images.githubusercontent.com/52135169/140683152-c24368f1-6a2b-468e-8aeb-66f0fc947a4a.png)

![image](https://user-images.githubusercontent.com/52135169/140683071-9b7be36c-f3b8-4479-861b-7524d205d49b.png)

### Versions

- Browser & Version: Firefox 93.0
- Adblocker (uBlock Origin, Adguard, Nano Adblocker, etc.) & Version: uBlock Origin 1.38.6

### Settings

N/A

### Notes

Thanks a lot!

**Comment by yourduskquibbles** [comment]
@Mennaruuk Thx for reporting, should be fixed now!
