### ISSUE TITLE
haaretz.com

### ISSUE THREAD

**Issue by Mennaruuk** [yourduskquibbles/webannoyances#404]
### URL(s) where the issue occurs

`https://www.haaretz.com/israel-news/is-israel-really-a-settler-colonial-state-1.9970098`

### Describe the issue

Sticky header when scrolling up.

### Screenshot(s)
![image](https://user-images.githubusercontent.com/52135169/140685096-ffbcdcb8-77f1-4e23-8fd9-b7cdfdf5db17.png)

### Versions

- Browser & Version: Microsoft Edge 95.0.1020.44
- Adblocker (uBlock Origin, Adguard, Nano Adblocker, etc.) & Version: uBlock Origin 1.38.4

### Settings

N/A

### Notes

Thanks a lot!

**Comment by yourduskquibbles** [comment]
@Mennaruuk Thx for reporting, interesting site design on this one :) Should be fixed now
