### ISSUE TITLE
al-monitor.com

### ISSUE THREAD

**Issue by Mennaruuk** [yourduskquibbles/webannoyances#405]
### URL(s) where the issue occurs

`https://www.al-monitor.com/originals/2021/11/despite-failure-block-new-budget-netanyahu-not-ready-retire`

### Describe the issue

Sticky header.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/52135169/140685621-8e095ebc-2835-49cd-a609-a3765b220dd8.png)

### Versions

- Browser & Version: Microsoft Edge 95.0.1020.44
- Adblocker (uBlock Origin, Adguard, Nano Adblocker, etc.) & Version: uBlock Origin 1.38.4

### Settings

N/A

### Notes

Thanks a lot!

**Comment by yourduskquibbles** [comment]
@Mennaruuk Thx for reporting, should be fixed now!
