### ISSUE TITLE
goodrx.com

### ISSUE THREAD

**Issue by Mennaruuk** [yourduskquibbles/webannoyances#407]
### URL(s) where the issue occurs

`https://www.goodrx.com/conditions/depression/common-myths-and-misconceptions-about-antidepressants`

### Describe the issue

Sticky header + subscription nag.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/52135169/140981974-0c65332a-e55d-47ea-8f61-350ff9f5b7f9.png)

### Versions

- Browser & Version: Firefox 94.0.1
- Adblocker (uBlock Origin, Adguard, Nano Adblocker, etc.) & Version: uBlock Origin 1.38.6

### Settings

N/A

### Notes

Thanks a lot!

**Comment by yourduskquibbles** [comment]
@Mennaruuk Thx for reporting, should be fixed now!
