### ISSUE TITLE
nhsinform.scot

### ISSUE THREAD

**Issue by Mennaruuk** [yourduskquibbles/webannoyances#408]
### URL(s) where the issue occurs

`https://www.nhsinform.scot/illnesses-and-conditions/cancer/practical-issues/work`

### Describe the issue

Sticky header.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/52135169/140983221-21338f35-3ff0-4384-a54d-d8614ed5e4e7.png)

### Versions

- Browser & Version: Firefox 94.0.1
- Adblocker (uBlock Origin, Adguard, Nano Adblocker, etc.) & Version: uBlock Origin 1.38.6

### Settings

N/A

### Notes

Thanks a lot!

**Comment by yourduskquibbles** [comment]
Thx for reporting, should be fixed now!
