### ISSUE TITLE
dallasnews.com

### ISSUE THREAD

**Issue by Mennaruuk** [yourduskquibbles/webannoyances#409]
### URL(s) where the issue occurs

`https://www.dallasnews.com/news/courts/2021/11/08/trial-begins-in-killing-of-black-transgender-woman-whose-body-was-found-in-dallas-white-rock-lake`

### Describe the issue

Sticky header.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/52135169/140985850-f1c3451e-1490-48be-81bd-280922358d8e.png)

### Versions

- Browser & Version: Firefox 94.0.1
- Adblocker (uBlock Origin, Adguard, Nano Adblocker, etc.) & Version: uBlock Origin 1.38.6

### Settings

N/A

### Notes

Thanks a lot!

**Comment by yourduskquibbles** [comment]
@Mennaruuk Thx for reporting, should be fixed now!
