### ISSUE TITLE
weekendavisen.dk

### ISSUE THREAD

**Issue by Mennaruuk** [yourduskquibbles/webannoyances#410]
### URL(s) where the issue occurs

`https://www.weekendavisen.dk/2021-36/ideer/den-sidste-dag-med-aandenoed`

### Describe the issue

Sticky header when scrolling up.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/52135169/140986188-aa1d8ae3-1039-4f62-b57c-b5f40eed14c3.png)

### Versions

- Browser & Version: Firefox 94.0.1
- Adblocker (uBlock Origin, Adguard, Nano Adblocker, etc.) & Version: uBlock Origin 1.38.6

### Settings

N/A

### Notes

Thanks a lot!

**Comment by yourduskquibbles** [comment]
@Mennaruuk Thx for reporting, this should be fixed now!
