### ISSUE TITLE
information.dk

### ISSUE THREAD

**Issue by Mennaruuk** [yourduskquibbles/webannoyances#411]
### URL(s) where the issue occurs

`https://www.information.dk/udland/2021/11/nye-flygtningekrise-paa-graensen-polen-velplanlagt-storm-eus-pigtraad`

### Describe the issue

Sticky header.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/52135169/140986464-724fe7a7-cd52-4d14-861a-027c3aa26d91.png)

### Versions

- Browser & Version: Firefox 94.0.1
- Adblocker (uBlock Origin, Adguard, Nano Adblocker, etc.) & Version: uBlock Origin 1.38.6

### Settings

N/A

### Notes

Thanks a lot!

**Comment by yourduskquibbles** [comment]
@Mennaruuk thanks for reporting, should be fixed now!
