### ISSUE TITLE
jyllands-posten.dk

### ISSUE THREAD

**Issue by Mennaruuk** [yourduskquibbles/webannoyances#412]
### URL(s) where the issue occurs

`https://jyllands-posten.dk`

### Describe the issue

Sticky header.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/52135169/140988358-cd9a4c51-43b7-41bf-a9b0-a0ed6e7177f7.png)

### Versions

- Browser & Version: Firefox 94.0.1
- Adblocker (uBlock Origin, Adguard, Nano Adblocker, etc.) & Version: uBlock Origin 1.38.6

### Settings

N/A

### Notes

Thanks a lot!

**Comment by yourduskquibbles** [comment]
@Mennaruuk Thx for reporting, this should be fixed now. Working my way (slowly....) through all your reported sites. I didn't forget about them :)
