### ISSUE TITLE
arbejderen.dk

### ISSUE THREAD

**Issue by Mennaruuk** [yourduskquibbles/webannoyances#413]
### URL(s) where the issue occurs

`https://arbejderen.dk/udland/dansk-klimaaktivist-vi-kan-ikke-acceptere-at-politikerne-ikke-tager-ansvar`

### Describe the issue

Sticky header.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/52135169/140989625-24b5d720-e6cf-449d-bc25-8c50eab7791a.png)

### Versions

- Browser & Version: Firefox 94.0.1
- Adblocker (uBlock Origin, Adguard, Nano Adblocker, etc.) & Version: uBlock Origin 1.38.6

### Settings

N/A

### Notes

Thanks a lot!

**Comment by yourduskquibbles** [comment]
@Mennaruuk Should be fixed now!
