### ISSUE TITLE
berlingske.dk

### ISSUE THREAD

**Issue by Mennaruuk** [yourduskquibbles/webannoyances#414]
### URL(s) where the issue occurs

`https://www.berlingske.dk/globalt/who-var-imod-ideen-men-den-virkede-nu-har-israel-banket-fjerde`

### Describe the issue

Sticky header when scrolling up + progress bar.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/52135169/140990030-e60a7407-4109-4ada-a172-8253739614ce.png)

### Versions

- Browser & Version: Firefox 94.0.1
- Adblocker (uBlock Origin, Adguard, Nano Adblocker, etc.) & Version: uBlock Origin 1.38.6

### Settings

N/A

### Notes

Thanks a lot!

I propose:

`berlingske.dk###siteHeaderSticky:style(position: absolute !important;)`

**Comment by yourduskquibbles** [comment]
@Mennaruuk should be fixed now, please let me know if you still see issues!
