### ISSUE TITLE
kristeligt-dagblad.dk

### ISSUE THREAD

**Issue by Mennaruuk** [yourduskquibbles/webannoyances#416]
### URL(s) where the issue occurs

`https://www.kristeligt-dagblad.dk/debat/ikke-vaccinerede-kendisser-laegges-had-i-flere-lande`

### Describe the issue

Sticky header + progress bar.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/52135169/140991113-92a65225-2321-4837-8197-594402ef4439.png)

### Versions

- Browser & Version: Firefox 94.0.1
- Adblocker (uBlock Origin, Adguard, Nano Adblocker, etc.) & Version: uBlock Origin 1.38.6

### Settings

N/A

### Notes

Thanks a lot!

I propose:

`kristeligt-dagblad.dk##.site-header__top-bar:style(position: absolute !important;)`
`kristeligt-dagblad.dk##.progress-border`

**Comment by yourduskquibbles** [comment]
@Mennaruuk thx for reporting, should be fixed now!
