### ISSUE TITLE
inews.co.uk

### ISSUE THREAD

**Issue by Mennaruuk** [yourduskquibbles/webannoyances#417]
### URL(s) where the issue occurs

`https://inews.co.uk/news/politics/boris-johnson-second-jobs-mps-ban-benefit-commons-1291747`

### Describe the issue

Sticky header + back-to-top button.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/52135169/140991900-34d62a99-e2e9-45c0-8ae9-98def0c8af27.png)

### Versions

- Browser & Version: Firefox 94.0.1
- Adblocker (uBlock Origin, Adguard, Nano Adblocker, etc.) & Version: uBlock Origin 1.38.6

### Settings

N/A

### Notes

Thanks a lot!

I propose:

`inews.co.uk##.inews__header,.inews__post__category-banner:style(position: absolute !important;)`

`inews.co.uk##.inews__back-to-top`

**Comment by yourduskquibbles** [comment]
@Mennaruuk Thx for reporting, should be fixed now!
