### ISSUE TITLE
standard.co.uk

### ISSUE THREAD

**Issue by Mennaruuk** [yourduskquibbles/webannoyances#418]
### URL(s) where the issue occurs

`https://www.standard.co.uk/news/london/lady-gaga-house-of-gucci-world-premiere-london-b965268.html`

### Describe the issue

Sticky header + subscription nag.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/52135169/140993899-93eb9473-eae8-4975-b7ee-80f4c7177c24.png)

### Versions

- Browser & Version: Firefox 94.0.1
- Adblocker (uBlock Origin, Adguard, Nano Adblocker, etc.) & Version: uBlock Origin 1.38.6

### Settings

N/A

### Notes

Thanks a lot!

**Comment by yourduskquibbles** [comment]
@Mennaruuk Thx for reporting, this should be fixed now
