### ISSUE TITLE
morningstaronline.co.uk

### ISSUE THREAD

**Issue by Mennaruuk** [yourduskquibbles/webannoyances#419]
### URL(s) where the issue occurs

`https://www.morningstaronline.co.uk/article/b/food-delivery-workers-to-stage-motorcade-against-parking-fines-while-working`

### Describe the issue

Sticky header.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/52135169/140994679-54ae851e-e46a-4203-b813-d68064696412.png)

### Versions

- Browser & Version: Firefox 94.0.1
- Adblocker (uBlock Origin, Adguard, Nano Adblocker, etc.) & Version: uBlock Origin 1.38.6

### Settings

N/A

### Notes

Thanks a lot!

I propose:

`morningstaronline.co.uk###branding:style(position: absolute !important;)`

**Comment by yourduskquibbles** [comment]
@Mennaruuk Thx for reporting, should be fixed now!
