### ISSUE TITLE
tradebytrade.com

### ISSUE THREAD

**Issue by KonoromiHimaries** [yourduskquibbles/webannoyances#42]
![2018-05-15-trade by trade _ the perfect cryptocurrency trading platform](https://user-images.githubusercontent.com/5884000/40033324-366663e8-57f8-11e8-840b-bcaf98b65836.png)

broken site

<details><summary>my settings</summary>

my filters
https://gist.github.com/KonoromiHimaries/c05bf7f6dd6dcb2d3beb090871985baa

 uBO 1.16.4
 ND 14.24
 Chr 66.0.3359.139
</details>

**Comment by yourduskquibbles** [comment]
Thanks!

Another stupid redundancy removal....
