### ISSUE TITLE
navajotimes.com

### ISSUE THREAD

**Issue by Mennaruuk** [yourduskquibbles/webannoyances#420]
### URL(s) where the issue occurs

`https://navajotimes.com/reznews/hopi-leaders-attend-biden-restoration-of-bears-ears`

### Describe the issue

Sticky header.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/52135169/140995154-4a8637cc-b6d0-43fd-97ab-e0c17e24e329.png)

### Versions

- Browser & Version: Firefox 94.0.1
- Adblocker (uBlock Origin, Adguard, Nano Adblocker, etc.) & Version: uBlock Origin 1.38.6

### Settings

N/A

### Notes

Thanks a lot!

**Comment by yourduskquibbles** [comment]
@Mennaruuk Thx for reporting, should be fixed now!
