### ISSUE TITLE
aiptcomics.com

### ISSUE THREAD

**Issue by Mennaruuk** [yourduskquibbles/webannoyances#421]
### URL(s) where the issue occurs

`https://aiptcomics.com/2021/11/09/himawari-house-qa`

### Describe the issue

Sticky header when scrolling up.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/52135169/141012159-19ddcff0-90d4-40b3-9e09-a3fb49ef79c6.png)

### Versions

- Browser & Version: Firefox 94.0.1
- Adblocker (uBlock Origin, Adguard, Nano Adblocker, etc.) & Version: uBlock Origin 1.38.6

### Settings

N/A

### Notes

Thanks a lot!

I propose:

`aiptcomics.com##.mvp-main-head-grid:style(position: static !important;)`

**Comment by yourduskquibbles** [comment]
@Mennaruuk thx for reporting, this should be fixed now!
