### ISSUE TITLE
gab.com

### ISSUE THREAD

**Issue by Mennaruuk** [yourduskquibbles/webannoyances#422]
### URL(s) where the issue occurs

`https://gab.com/ColeThePony`

### Describe the issue

Sticky headers.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/52135169/141012560-a104d6ec-4ba1-487d-9fcc-6e52e12efc9c.png)

### Versions

- Browser & Version: Firefox 94.0.1
- Adblocker (uBlock Origin, Adguard, Nano Adblocker, etc.) & Version: uBlock Origin 1.38.6

### Settings

N/A

### Notes

Thanks a lot!

**Comment by Mennaruuk** [comment]
Yeah, I think this site is an exception, it looks worse. Closing!

**Comment by yourduskquibbles** [comment]
@Mennaruuk what do you think of these filters?  I dunno about leaving left panel sticky or not when scrolling down a user profile.

```
! scroll down mini profile avatar
gab.com##.VTBVd._2I3eh._3dGg1._UuSG > ._2mtbj.SslQJ._3dGg1._UuSG:has([src*="media.gab.com/system/accounts/avatars/"])

! always display user page timeline/comments/photos/videos
gab.com##.VTBVd._2I3eh._3dGg1._UuSG > ._UuSG:has([aria-current="page"]):style(display: block !important;)

! make user profile info not jump down
gab.com##.active.sticky-outer-wrapper > .sticky-inner-wrapper:style(position: relative !important; transform: translate3d(0, 0, 0) !important;)

! pin header (class used for all sticky elements)
gab.com##.Sg-9_:style(position: static !important;)

! make sidebar sticky again 
gab.com##header[role="banner"] .Sg-9_:style(position: fixed !important;)

```

**Comment by Mennaruuk** [comment]
FANTASTIC! Thank you so much @yourduskquibbles 😊

**Comment by yourduskquibbles** [comment]
Will add these, I think they are improvement from default and have fixed stuff on this site before as well.

**Comment by Mennaruuk** [comment]
@yourduskquibbles Good afternoon! I faced some new issues, mainly flashing of the left pane when scrolling up or down as well as images not expanding when clicked.
![J3899tRl4C](https://user-images.githubusercontent.com/52135169/146432046-310e24a6-e0e4-4504-980c-3193d2790abd.gif)

https://user-images.githubusercontent.com/52135169/146432054-84334c40-7249-4d60-ba9d-d310b08cf08f.mp4

**Comment by yourduskquibbles** [comment]
@Mennaruuk I can't reproduce that first janky behavior, but can reproduce the second one.

Try these filters in My Filters.. I think it should solve at least the second one you are seeing

```
! remove bad filter
gab.com#@#.Sg-9_, .tabs-bar, .ui .page__top:style(position: static !important;)

! update to less generic header bar filter
gab.com##.Sg-9_._2jrGl._369Nr.Df1jL._2fFIj._2mtbj._3zKwE._2wNvg._UuSG, .tabs-bar, .ui .page__top:style(position: static !important;)

```

**Comment by yourduskquibbles** [comment]
first one, based on class changes, may be fixed if you try these filters

```
! disable bad filter
gab.com#@#.active.sticky-outer-wrapper > .sticky-inner-wrapper:style(position: relative !important; transform: translate3d(0, 0, 0) !important;)

! update to always apply even without `.active` class
gab.com##.sticky-outer-wrapper > .sticky-inner-wrapper:style(position: relative !important; transform: translate3d(0, 0, 0) !important;)
```

**Comment by Mennaruuk** [comment]
All these filters work wonderfully! Thank you very much.

**Comment by yourduskquibbles** [comment]
Cool, thanks for letting me know, will push the updates out.
