### ISSUE TITLE
timesofisrael.com

### ISSUE THREAD

**Issue by Mennaruuk** [yourduskquibbles/webannoyances#423]
### URL(s) where the issue occurs

`https://www.timesofisrael.com/raam-party-chief-abbas-discusses-2-state-solution-with-jordans-king`

### Describe the issue

Floating element.

### Screenshot(s)

https://user-images.githubusercontent.com/52135169/141014136-730196a7-3e37-417c-9683-16fce1c444d4.mp4

### Versions

- Browser & Version: Firefox 94.0.1
- Adblocker (uBlock Origin, Adguard, Nano Adblocker, etc.) & Version: uBlock Origin 1.38.6

### Settings

N/A

### Notes

Thanks a lot!

**Comment by yourduskquibbles** [comment]
@Mennaruuk Thx for reporting, and repro video. This should be fixed now. It seems to be screen size dependent though so please confirm it looks OK for screen width you are using.
