### ISSUE TITLE
thepostmillennial.com

### ISSUE THREAD

**Issue by Mennaruuk** [yourduskquibbles/webannoyances#424]
### URL(s) where the issue occurs

`https://thepostmillennial.com/china-built-mock-ups-of-us-warships-satellite-images`

### Describe the issue

Unnecessary scrollbar at the top.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/52135169/141015323-1fee9a06-24df-473f-896b-587758222e1b.png)

### Versions

- Browser & Version: Firefox 94.0.1
- Adblocker (uBlock Origin, Adguard, Nano Adblocker, etc.) & Version: uBlock Origin 1.38.6

### Settings

N/A

### Notes

Thanks a bunch!

**Comment by yourduskquibbles** [comment]
@Mennaruuk Thx for reporting, this is the sites own dumb design choice but I fixed it :)
