### ISSUE TITLE
belfasttelegraph.co.uk

### ISSUE THREAD

**Issue by Mennaruuk** [yourduskquibbles/webannoyances#425]
### URL(s) where the issue occurs

`https://www.belfasttelegraph.co.uk/news/uk/duke-of-sussex-says-he-warned-twitter-ceo-ahead-of-january-6-riots-41036172.html`

### Describe the issue

Sticky header.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/52135169/141016126-a584daaf-b1e6-47f8-91ac-ff20cb3e9303.png)

### Versions

- Browser & Version: Firefox 94.0.1
- Adblocker (uBlock Origin, Adguard, Nano Adblocker, etc.) & Version: uBlock Origin 1.38.6

### Settings

N/A

### Notes

Thanks a bunch!

**Comment by yourduskquibbles** [comment]
@Mennaruuk Thx for reporting, should be fixed now
