### ISSUE TITLE
eastbourneherald.co.uk

### ISSUE THREAD

**Issue by Mennaruuk** [yourduskquibbles/webannoyances#426]
### URL(s) where the issue occurs

`https://www.eastbourneherald.co.uk/health/coronavirus/frontline-nhs-staff-given-deadline-to-get-covid-vaccine-to-continue-jobs-3450563`

### Describe the issue

Sticky header.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/52135169/141016679-c1d562a5-9563-4a75-aaf1-4fac1f5ae3ca.png)

### Versions

- Browser & Version: Firefox 94.0.1
- Adblocker (uBlock Origin, Adguard, Nano Adblocker, etc.) & Version: uBlock Origin 1.38.6

### Settings

N/A

### Notes

Thanks a many!

I propose:

`eastbourneherald.co.uk###header:style(position: static !important;)`

**Comment by yourduskquibbles** [comment]
@Mennaruuk Thx for reporting, should be fixed now
