### ISSUE TITLE
decolonizepalestine.com

### ISSUE THREAD

**Issue by Mennaruuk** [yourduskquibbles/webannoyances#427]
### URL(s) where the issue occurs

`https://decolonizepalestine.com`

### Describe the issue

Sticky header.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/52135169/141016904-8f15ee56-61bc-48a9-a22c-54093a08bcb6.png)

### Versions

- Browser & Version: Firefox 94.0.1
- Adblocker (uBlock Origin, Adguard, Nano Adblocker, etc.) & Version: uBlock Origin 1.38.6

### Settings

N/A

### Notes

Thanks a many!

**Comment by yourduskquibbles** [comment]
@Mennaruuk Thx for reporting, this should be fixed now
