### ISSUE TITLE
ardrossanherald.com,bucksfreepress.co.uk,burytimes.co.uk,countypress.co.uk,dunfermlinepress.com,eastlothiancourier.com,herefordtimes.com,stroudnewsandjournal.co.u

### ISSUE THREAD

**Issue by Mennaruuk** [yourduskquibbles/webannoyances#428]
### URL(s) where the issue occurs

`https://www.burytimes.co.uk/news/19705599.inquest-parents-seek-answers-death-bury-17-year-old`

### Describe the issue

Bottom subscription nag. Happens after scrolling down a bit.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/52135169/141017183-d33e3266-5b50-4544-927a-810c40c926a6.png)

### Versions

- Browser & Version: Firefox 94.0.1
- Adblocker (uBlock Origin, Adguard, Nano Adblocker, etc.) & Version: uBlock Origin 1.38.6

### Settings

N/A

### Notes

Also noticed the same issue with another site:

`https://www.stroudnewsandjournal.co.uk/news/19704084.siobhan-baillie-denies-claims-referred-ppe-suppliers-vip-lane`
`https://www.herefordtimes.com/news/19704121.herefordshire-picked-location-big-budget-film`
`https://www.countypress.co.uk/news/19701655.salvation-army-hostel-resident-smashed-furniture`
`https://www.bucksfreepress.co.uk/news/19705657.sir-steve-redgrave-blown-away-south-bucks-mental-health-hub-high-wycombe`
`https://www.dunfermlinepress.com/news/19704818.coronavirus-dunfermline-west-fifes-coronavirus-hotspots-revealed-public-health-scotland-map`
`https://www.eastlothiancourier.com/news/19705411.trial-hears-claims-music-instructor-repeatedly-touched-schoolgirl-piano-lessons`
`https://www.ardrossanherald.com/news/19698714.garnoch-valley-tourism-boost-hopes-plan-lochshore-paths`

**Comment by yourduskquibbles** [comment]
I couldn't get the subscription nag to appear but a sticky header did show up when scrolling down after a few seconds so fixed that one on all reported sites
