### ISSUE TITLE
portsmouth.co.uk

### ISSUE THREAD

**Issue by Mennaruuk** [yourduskquibbles/webannoyances#429]
### URL(s) where the issue occurs

`https://www.portsmouth.co.uk/news/people/revealed-meet-the-yarn-bomber-behind-the-spectacular-remembrance-post-box-topper-in-portsmouth-3451337`

### Describe the issue

Sticky header.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/52135169/141017375-9d3b0610-be94-48cc-9e0d-a80a91d0da3a.png)

### Versions

- Browser & Version: Firefox 94.0.1
- Adblocker (uBlock Origin, Adguard, Nano Adblocker, etc.) & Version: uBlock Origin 1.38.6

### Settings

N/A

### Notes

Thank you.

I propose:

`portsmouth.co.uk###header:style(position: static !important;)`

**Comment by yourduskquibbles** [comment]
@Mennaruuk Thx for reporting, this should be fixed now.

Related #426
