### ISSUE TITLE
rfi.fr

### ISSUE THREAD

**Issue by Mennaruuk** [yourduskquibbles/webannoyances#430]
### URL(s) where the issue occurs

`https://www.rfi.fr/en/business-and-tech/20211021-trump-announces-plans-to-launch-new-social-network-truth-social`

### Describe the issue

Sticky header.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/52135169/141018224-841f9270-a0b6-4806-9052-b13b42eddfdf.png)

### Versions

- Browser & Version: Firefox 94.0.1
- Adblocker (uBlock Origin, Adguard, Nano Adblocker, etc.) & Version: uBlock Origin 1.38.6

### Settings

N/A

### Notes

Thank you.

I propose:

`rfi.fr##.o-header:style(position: absolute !important;)`

**Comment by yourduskquibbles** [comment]
@Mennaruuk Thx for reporting, this should be fixed now!
