### ISSUE TITLE
wakefieldexpress.co.uk

### ISSUE THREAD

**Issue by Mennaruuk** [yourduskquibbles/webannoyances#431]
### URL(s) where the issue occurs

`https://www.wakefieldexpress.co.uk/news/people/here-is-where-you-can-see-all-the-christmas-lights-being-switched-on-in-wakefield-pontefract-and-castleford-and-other-light-up-events-3449313`

### Describe the issue

Sticky header.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/52135169/141018487-ce23f87c-5a47-441c-8d87-8a546fd181a2.png)

### Versions

- Browser & Version: Firefox 94.0.1
- Adblocker (uBlock Origin, Adguard, Nano Adblocker, etc.) & Version: uBlock Origin 1.38.6

### Settings

N/A

### Notes

Thank you.

I propose:

`wakefieldexpress.co.uk###header:style(position: static !important;)`

**Comment by yourduskquibbles** [comment]
@Mennaruuk Thx for reporting, this should be fixed now!
