### ISSUE TITLE
standard.co.uk

### ISSUE THREAD

**Issue by Mennaruuk** [yourduskquibbles/webannoyances#432]
### URL(s) where the issue occurs

`https://www.standard.co.uk/news/london/lady-gaga-house-of-gucci-world-premiere-london-b965268.html`

### Describe the issue
Bottom newsletter nag.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/52135169/141018920-1f63d22b-b8e4-46ee-9565-7c89c6c57530.png)

### Versions

- Browser & Version: Firefox 94.0.1
- Adblocker (uBlock Origin, Adguard, Nano Adblocker, etc.) & Version: uBlock Origin 1.38.6

### Settings

N/A

### Notes

Thank you.

**Comment by yourduskquibbles** [comment]
@Mennaruuk I don't get this anymore when loading link, maybe test they removed?

**Comment by Mennaruuk** [comment]
You're right, it's gone. Closing!
