### ISSUE TITLE
prospectmagazine.co.uk

### ISSUE THREAD

**Issue by Mennaruuk** [yourduskquibbles/webannoyances#433]
### URL(s) where the issue occurs

`https://www.prospectmagazine.co.uk/philosophy/boo-to-the-boo-hurrahs-how-four-oxford-women-transformed-philosophy`

### Describe the issue
Sticky header  + modal overlay.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/52135169/141020032-fb4f7434-008e-4727-9637-7e589e2e995b.png)

![image](https://user-images.githubusercontent.com/52135169/141019998-a1c0ec03-22f5-446a-8d72-c9211709f708.png)

### Versions

- Browser & Version: Firefox 94.0.1
- Adblocker (uBlock Origin, Adguard, Nano Adblocker, etc.) & Version: uBlock Origin 1.38.6

### Settings

N/A

### Notes

Thank you.

I propose:

`prospectmagazine.co.uk##.header:style(position: absolute !important;)`

**Comment by yourduskquibbles** [comment]
@Mennaruuk Thx for reporting, should be fixed now!
