### ISSUE TITLE
pilotonline.com

### ISSUE THREAD

**Issue by Mennaruuk** [yourduskquibbles/webannoyances#434]
### URL(s) where the issue occurs

`https://www.pilotonline.com/government/local/vp-nw-riddick-removal-norfolk-manager-police-chief-20211110-w63z6okj3ba3jkmhw566yebnlu-story.html`

### Describe the issue
Sticky header.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/52135169/141171059-2f8d421d-86d7-4102-ae47-be54e368c2e9.png)

### Versions

- Browser & Version: Firefox 94.0.1
- Adblocker (uBlock Origin, Adguard, Nano Adblocker, etc.) & Version: uBlock Origin 1.38.6

### Settings

N/A

### Notes

Thank you.

I propose:

`pilotonline.com###app-bar-sticky:style(position: static !important;)`

**Comment by yourduskquibbles** [comment]
@Mennaruuk Thx for reporting, should be fixed now!
