### ISSUE TITLE
saraacarter.com

### ISSUE THREAD

**Issue by Mennaruuk** [yourduskquibbles/webannoyances#435]
### URL(s) where the issue occurs

`https://saraacarter.com`
`https://saraacarter.com/developing-bidens-national-security-advisor-named-in-russia-investigation`

### Describe the issue
Sticky headers. One happens when scrolling up on an article.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/52135169/141171498-c0b2bf6d-ca4f-427c-aec7-c2e4abea95ac.png)
![image](https://user-images.githubusercontent.com/52135169/141171705-4300c9cc-3ec7-4fa4-91d0-12d6d12888bf.png)

### Versions

- Browser & Version: Firefox 94.0.1
- Adblocker (uBlock Origin, Adguard, Nano Adblocker, etc.) & Version: uBlock Origin 1.38.6

### Settings

N/A

### Notes

Thank you.

**Comment by yourduskquibbles** [comment]
@Mennaruuk Thx for reporting, should be fixed now!
