### ISSUE TITLE
politifact.com

### ISSUE THREAD

**Issue by Mennaruuk** [yourduskquibbles/webannoyances#436]
### URL(s) where the issue occurs

`https://www.politifact.com`

### Describe the issue
Subscription nag.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/52135169/141172321-f534f512-6be0-4a9c-804d-2f58d3e00600.png)

### Versions

- Browser & Version: Firefox 94.0.1
- Adblocker (uBlock Origin, Adguard, Nano Adblocker, etc.) & Version: uBlock Origin 1.38.6

### Settings

N/A

### Notes

Thank you.

I propose:

`politifact.com##.o-disruptor`

**Comment by yourduskquibbles** [comment]
@Mennaruuk Thx for reporting, should be fixed now as suggested!
