### ISSUE TITLE
uncoverdc.com

### ISSUE THREAD

**Issue by Mennaruuk** [yourduskquibbles/webannoyances#437]
### URL(s) where the issue occurs

`https://uncoverdc.com/2021/11/08/dark-to-light-theyre-crazy`

### Describe the issue
Sticky header + subscription nag modal overlay.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/52135169/141173170-baf82318-6587-41c2-8a8a-e3b2db16f2cf.png)

### Versions

- Browser & Version: Firefox 94.0.1
- Adblocker (uBlock Origin, Adguard, Nano Adblocker, etc.) & Version: uBlock Origin 1.38.6

### Settings

N/A

### Notes

Thank you.

I propose:
`uncoverdc.com##.td-affix:style(position: static !important;)`
`uncoverdc.com##.sgpb-popup-overlay`
`uncoverdc.com##.sgpb-popup-dialog-main-div-wrapper`

**Comment by yourduskquibbles** [comment]
@Mennaruuk thx for reporting, this should be fixed now!
