### ISSUE TITLE
washingtontimes.com

### ISSUE THREAD

**Issue by Mennaruuk** [yourduskquibbles/webannoyances#439]
### URL(s) where the issue occurs

`https://www.washingtontimes.com`

### Describe the issue
Bottom subscription nag.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/52135169/141187150-6cb3b558-b157-4239-b14e-489073cd2005.png)

### Versions

- Browser & Version: Firefox 94.0.1
- Adblocker (uBlock Origin, Adguard, Nano Adblocker, etc.) & Version: uBlock Origin 1.38.6

### Settings

N/A

### Notes

Thanks!

**Comment by yourduskquibbles** [comment]
@Mennaruuk This should be fixed now!
