### ISSUE TITLE
theverge.com

### ISSUE THREAD

**Issue by zaphodbeebblebrox** [yourduskquibbles/webannoyances#44]
New pinned header.

Example URL: `https://www.theverge.com/2018/5/17/17364004/nest-goes-offline-thermostats-locks-cameras-alarms`

`theverge.com##.tab-bar-fixed.c-tab-bar`

**Comment by yourduskquibbles** [comment]
This should be fixed with https://github.com/yourduskquibbles/webannoyances/commit/d014175ab4fe0f38ffbdf5ed168374dc1f42da8f from yesterday.

Please update filters and verify.

**Comment by zaphodbeebblebrox** [comment]
Sorry.

**Comment by yourduskquibbles** [comment]
No worries @zaphodbeebblebrox, I appreciate the reports!
