### ISSUE TITLE
bigleaguepolitics.com

### ISSUE THREAD

**Issue by Mennaruuk** [yourduskquibbles/webannoyances#440]
### URL(s) where the issue occurs

`https://bigleaguepolitics.com/european-union-turns-away-migrants-after-belarus-president-alexander-lukashenko-puts-them-on-their-doorstep`

### Describe the issue
Sticky header.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/52135169/141224055-3142a769-739b-4bb0-8877-c8782f3c0d16.png)

### Versions

- Browser & Version: Firefox 94.0.1
- Adblocker (uBlock Origin, Adguard, Nano Adblocker, etc.) & Version: uBlock Origin 1.38.6

### Settings

N/A

### Notes

Thanks!

I propose:

`bigleaguepolitics.com##.header:style(position: static !important;)`

**Comment by yourduskquibbles** [comment]
Thx for reporting, this should be fixed now!
