### ISSUE TITLE
babylonbee.com

### ISSUE THREAD

**Issue by Mennaruuk** [yourduskquibbles/webannoyances#441]
### URL(s) where the issue occurs

`https://babylonbee.com/news/new-game-call-of-duty-rittenhouse-lets-you-defend-your-home-from-a-horde-of-bloodthirsty-communists`

### Describe the issue
Modal overlay.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/52135169/141348467-91536cd6-58cf-4c04-b146-394d6753e27e.png)

### Versions

- Browser & Version: Firefox 94.0.1
- Adblocker (uBlock Origin, Adguard, Nano Adblocker, etc.) & Version: uBlock Origin 1.38.6

### Settings

N/A

### Notes

Thanks!

**Comment by yourduskquibbles** [comment]
@Mennaruuk Thx for reporting, this should be fixed now!
