### ISSUE TITLE
tv.gab.com

### ISSUE THREAD

**Issue by Mennaruuk** [yourduskquibbles/webannoyances#442]
### URL(s) where the issue occurs

`https://tv.gab.com/channel/vullo/view/100-photo-tray-scrapbook-618e4f65bd917b052e6c2f8b`

### Describe the issue
Scrolling video.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/52135169/141479191-d03fb7cf-7268-4b22-83a0-5267dd469228.png)

### Versions

- Browser & Version: Firefox 94.0.1
- Adblocker (uBlock Origin, Adguard, Nano Adblocker, etc.) & Version: uBlock Origin 1.38.6

### Settings

N/A

### Notes

Thanks!

**Comment by yourduskquibbles** [comment]
@Mennaruuk Thx for reporting, this should be fixed now!
