### ISSUE TITLE
lrb.co.uk

### ISSUE THREAD

**Issue by Mennaruuk** [yourduskquibbles/webannoyances#443]
### URL(s) where the issue occurs

`https://www.lrb.co.uk/the-paper/v43/n22/sophie-lewis/shebeen-queens`

### Describe the issue
Sticky header when scrolling up.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/52135169/141483015-6b4d61f2-6466-4096-82af-d6b5306efd09.png)

### Versions

- Browser & Version: Firefox 94.0.1
- Adblocker (uBlock Origin, Adguard, Nano Adblocker, etc.) & Version: uBlock Origin 1.38.6

### Settings

N/A

### Notes

Thanks!

**Comment by yourduskquibbles** [comment]
@Mennaruuk Thx for reporting! That was a fun one, lots of filters needed to keep sections in the header from flashing/shifting around/links clickable. Since there were so many needed, please let me know if you get a chance if everything seems to be working OK for you.

**Comment by yourduskquibbles** [comment]
Found issues when using site at phone size screen width...

**Comment by yourduskquibbles** [comment]
I think adding `##html:not(.toc-title-swapped)` to the start of a few filters will fix the issues found with small screen width. Please test if you are able :)

**Comment by Mennaruuk** [comment]
THANK YOU! I tested it on PC, and it works well! How would I test on my iPhone? I have AdGuard, and I enabled WAU there, but the header still shows up when I scroll up.

**Comment by yourduskquibbles** [comment]
AdGuard on iphone can't do CSS changes, limitation of iOS/Safari unfortunately.

I primarily use firefox on desktop and I just check for responsive design changes by making the desktop window as narrow as possible (~400px wide). I find this is a pretty good way to check for how a site will appear on mobile if they are using responsive design practices.

You can also emulate android phones by using the page inspector on Chrome and click the button I drew an arrow to in screenshot below:

![mobileemulate](https://user-images.githubusercontent.com/22258847/146260805-ed7389a6-5c07-4d84-a0a7-5015d43158ec.png)


You can't get iPhone Safari adguard experience with this method though, that I haven't found a great way to test other than on my phone.

**Comment by yourduskquibbles** [comment]
Closing as fixed since I think we're good on the actual issue at hand now :)
