### ISSUE TITLE
healthcentral.com

### ISSUE THREAD

**Issue by Mennaruuk** [yourduskquibbles/webannoyances#444]
### URL(s) where the issue occurs

`https://www.healthcentral.com/article/what-you-need-to-know-right-now-about-covid-19-antiviral-drugs`

### Describe the issue
Sticky header.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/52135169/141490318-2befe8a0-dd6b-4540-af46-43ecd751371a.png)

### Versions

- Browser & Version: Firefox 94.0.1
- Adblocker (uBlock Origin, Adguard, Nano Adblocker, etc.) & Version: uBlock Origin 1.38.6

### Settings

N/A

### Notes

Thanks!

**Comment by yourduskquibbles** [comment]
@Mennaruuk thx for reporting, this should be fixed now!
