### ISSUE TITLE
aegeanair.com web page issues

### ISSUE THREAD

**Issue by stdedos** [yourduskquibbles/webannoyances#447]
On the https://en.aegeanair.com/milesandbonus/my-account/claim-missing-miles/ page (needs login), filter `##.js-scroll-top:not(html):not(body)` hides two very necessary input boxes for the form in the site.

Exclusion `aegeanair.com#@#.js-scroll-top:not(html):not(body)` must be added.

**Comment by yourduskquibbles** [comment]
@stdedos Thx for reporting, and this should be fixed now! Since the site requires login, I will add your filter as suggested. Please let me know if you have any other issues!

**Comment by stdedos** [comment]
As far as your list is concerned, the filter is more than enough! Thanks :-D
