### ISSUE TITLE
zdf.de

### ISSUE THREAD

**Issue by Vekkq** [yourduskquibbles/webannoyances#449]
### URL(s) where the issue occurs

[zdf.de/nachrichten](https://www.zdf.de/nachrichten)
(entire site)

### Describe the issue

Shows a popup, blocking view and scrollbar. 

### Screenshot(s)
![](http://naivelabs.org/share/2021-12-06%2018.23.09%20www.zdf.de%209bb7bf4f6023.png)

### Versions

- Browser & Version: Vivaldi 5.0.2497.24
- Adblocker (uBlock Origin, Adguard, Nano Adblocker, etc.) & Version: uBlock Origin 1.39.2

### Notes

These filters solved the issue for me:
```
www.zdf.de##.m-opened.m-open.dialog-backdrop
www.zdf.de##html:style(overflow: auto !important)
```

**Comment by yourduskquibbles** [comment]
@Vekkq I couldnt get modal to appear, may be region IP based? But I've added your filters as suggested... Also fixed the header and removed the onetrust consent sdk filter so user can accept and get images to load. Not sure how to trigger images to load without clicking the consent, probably possible with a `+js()` filter but don't have time to investigate right now. Possible EasyList or some other cookie list has already figured it out though.

**Comment by Vekkq** [comment]
Sorry, I figured now that I had the EasyList cookie warning filter list on, which blocked the original modal and also solved the issue with images not loading without me knowing.
