### ISSUE TITLE
instapaper.com

### ISSUE THREAD

**Issue by RadicalNoise** [yourduskquibbles/webannoyances#450]
### URL(s) where the issue occurs

`https://www.instapaper.com/u`

### Describe the issue

The filter blocks the user settings link.

### Screenshot(s)

<details><summary>Image</summary>

 
![222](https://user-images.githubusercontent.com/74098460/145485751-ccfebd16-c3ec-4aed-a7e8-4854cf517139.png)

</details>

### Versions

- Chrome 96
- AdGuard 3.6.16

### Settings

- `Web Annoyances Ultralist`

**Comment by yourduskquibbles** [comment]
@RadicalNoise Thx for reporting, this should be fixed now as well as #451
