### ISSUE TITLE
instapaper.com

### ISSUE THREAD

**Issue by RadicalNoise** [yourduskquibbles/webannoyances#451]
### URL(s) where the issue occurs

`https://www.instapaper.com/u`

### Describe the issue

The filter blocks part of the article.

### Screenshot(s)

<details><summary>Image</summary>

 
![345](https://user-images.githubusercontent.com/74098460/145489941-3a9193fa-ace5-4219-9892-c23ce4fe36a9.png)

</details>

### Versions

- Chrome 96
- AdGuard 3.6.16

### Settings

- `Web Annoyances Ultralist`

### Steps to reproduce:

- Create an Instapaper account

- Install Instapaper extension
`https://chrome.google.com/webstore/detail/instapaper/ldjkgaaoikpmhmkelcgkgacicjfbofhh`

- Open the page below:
`https://playerbros.com/valorant-champions-2021-ceyrek-finalleri-belli-oldu/`

- Add the page to Instapaper using the browser extension.
<details><summary>Image</summary>

 
![s2222](https://user-images.githubusercontent.com/74098460/145490432-37421fc8-9096-4e45-a6dc-cf92417ed879.png)

</details>

- Click on the article and scroll down. You cannot see the other half of the article.

**Comment by yourduskquibbles** [comment]
@RadicalNoise Thx for detailed repro steps, this should be fixed now as well as #450. Please let me know if you find other issues!
