### ISSUE TITLE
epicgames.com

### ISSUE THREAD

**Issue by prettyv** [yourduskquibbles/webannoyances#452]
### URL(s) where the issue occurs

`https://www.epicgames.com/store/`

### Describe the issue

The layout of the header bar on at least front and game pages in the Epic Game Store is currently broken, spanning over 2 lines and totally missing the right half.

### Screenshot(s)
![Screenshot_20211210_002847](https://user-images.githubusercontent.com/1702205/145491776-d01ef444-04b4-4fae-acb7-42d3729e05eb.png)

### Versions

- Browser & Version: Firefox 95.0
- Adblocker:  uBlock Origin 1.39.2

### Notes

This filter in `filters/floating_filters.txt` is responsible for the broken positioning: `epicgames.com##header#egh:style(position: absolute !important;)`

**Comment by yourduskquibbles** [comment]
@prettyv Thx for reporting, this should be fixed now: https://github.com/yourduskquibbles/webannoyances/commit/db0cae7a8b6ec0526027ded6fa1b15f59c7ea8c4
