### ISSUE TITLE
twitter.com

### ISSUE THREAD

**Issue by ghost** [yourduskquibbles/webannoyances#453]
### URL(s) where the issue occurs

`https://twitter.com/libsoftiktok`
`https://twitter.com/libsoftiktok/status/1469462669765660673`

### Describe the issue
annoyances
[Be as clear as possible: nobody can read your mind, and nobody is looking at your issue over your shoulder.]

### Screenshot(s)
![image](https://user-images.githubusercontent.com/95556652/145656612-68130056-6c5f-4da6-b75a-8d3939f625b7.png)

[Screenshot(s) for difficult to describe visual issues are **mandatory**. Post links instead of **Inline Images** for Screenshots containing **Adult material**.]

### Versions

- Browser & Version: Google Chrome 96.0.4664.93 (Official Build) (64-bit)
- Adblocker (uBlock Origin, Adguard, Nano Adblocker, etc.) & Version: uBlock Origin 1.39.2

### Settings

- [List here all the changes you made to your Adblocker's default settings]

### Notes

[Add here the result of whatever investigation work you have done: please investigate the issues you report -- this prevents burdening other volunteers. This is especially true for issues arising from settings which are very different from default ones.]

**Comment by yourduskquibbles** [comment]
No steps to reproduce, no idea what is being asked for
