### ISSUE TITLE
cnet.com

### ISSUE THREAD

**Issue by ghost** [yourduskquibbles/webannoyances#454]
### URL(s) where the issue occurs
`https://www.cnet.com/news/`
`[At least one URL for a web page where the clearly described issue occurs is **mandatory**. The backticks surrounding the URLs is important, it prevents the URL from being clickable. Warn with "NSFW" where applicable.]`

### Describe the issue
video leftover I think
[Be as clear as possible: nobody can read your mind, and nobody is looking at your issue over your shoulder.]

### Screenshot(s)
![image](https://user-images.githubusercontent.com/95556652/145656810-8593d783-a472-4278-bce8-d05ed183b71c.png)

[Screenshot(s) for difficult to describe visual issues are **mandatory**. Post links instead of **Inline Images** for Screenshots containing **Adult material**.]

### Versions

- Browser & Version: Google Chrome 96.0.4664.93 (Official Build) (64-bit)
- Adblocker (uBlock Origin, Adguard, Nano Adblocker, etc.) & Version: uBlock Origin 1.39.2

### Settings

- [List here all the changes you made to your Adblocker's default settings]

### Notes

[Add here the result of whatever investigation work you have done: please investigate the issues you report -- this prevents burdening other volunteers. This is especially true for issues arising from settings which are very different from default ones.]

**Comment by yourduskquibbles** [comment]
Fixed in uAssets unbreak list
https://github.com/uBlockOrigin/uAssets/commit/fee260cf5e13b8b3c54358b96b11b5e0a54f00f5
