### ISSUE TITLE
Trying to get rid of annoying overlay 

### ISSUE THREAD

**Issue by Depj** [yourduskquibbles/webannoyances#459]
### URL(s) where the issue occurs

`[At least one URL for a web page where the clearly described issue occurs is **mandatory**. The backticks surrounding the URLs is important, it prevents the URL from being clickable. Warn with "NSFW" where applicable.]`

### Describe the issue

[Be as clear as possible: nobody can read your mind, and nobody is looking at your issue over your shoulder.]

### Screenshot(s)

[Screenshot(s) for difficult to describe visual issues are **mandatory**. Post links instead of **Inline Images** for Screenshots containing **Adult material**.]

### Versions

- Browser & Version: [here]
- Adblocker (uBlock Origin, Adguard, Nano Adblocker, etc.) & Version: [here]

### Settings

- [List here all the changes you made to your Adblocker's default settings]

### Notes

[Add here the result of whatever investigation work you have done: please investigate the issues you report -- this prevents burdening other volunteers. This is especially true for issues arising from settings which are very different from default ones.]

**Comment by yourduskquibbles** [comment]
@Depj what site? you submitted default template with no URL

**Comment by yourduskquibbles** [comment]
Closing as invalid. If @depj wants to let me know the site they were trying to report, happy to reopen and fix
