### ISSUE TITLE
ask.fm

### ISSUE THREAD

**Issue by Mennaruuk** [yourduskquibbles/webannoyances#460]
### URL(s) where the issue occurs

`https://ask.fm/FLAK2340`

### Describe the issue

Overlay prevents from browsing site.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/52135169/146438264-9b27228a-ebef-43b2-8c79-bc479ef5d220.png)

### Versions

- Browser & Version: Firefox 95.0
- Adblocker (uBlock Origin, Adguard, Nano Adblocker, etc.) & Version: uBlock Origin 1.39.2

### Settings

- Default settings

### Notes

Appreciate your help :)

EDIT: Sorry, not a bug, just a filter request.

**Comment by yourduskquibbles** [comment]
@Mennaruuk Thx for reporting, should be fixed now!
