### ISSUE TITLE
Google image search broken with last update on Android 

### ISSUE THREAD

**Issue by iskar-jarak** [yourduskquibbles/webannoyances#487]
### URL(s) where the issue occurs

`https://www.google.com/search?q=Google&tbm=isch&ved=2ahUKEwjd1d6ruuL7AhWj_TgGHYGqDCsQ2-cCegQIABAC&oq=Google&gs_lcp=ChJtb2JpbGUtZ3dzLXdpei1pbWcQAzIECCMQJzIECCMQJzIFCAAQgAQyBQgAEIAEMgUIABCABDoECAAQQzoHCCMQ6gIQJzoECAAQA1DnCljpEWC4E2gBcAB4AIABmAOIAeUOkgEJMC4xLjQuMS4xmAEAoAEBsAEFwAEB&sclient=mobile-gws-wiz-img&ei=7-CNY52iA6P74-EPgdWy2AI&client=ms-android-samsung-ss&prmd=ivsn`

### Describe the issue

Elements are misaligned and the second column of images in the search page are not shown fully. The Google floating bar is also not in the right place 

### Screenshot(s)
![Screenshot_20221205-004117_Chrome](https://user-images.githubusercontent.com/74290904/205636601-a61a7025-3549-406b-9ffb-c0174d209a0d.jpg)

### Versions

- Browser & Version: Chrome 107
- Adblocker (uBlock Origin, Adguard, Nano Adblocker, etc.) & Version: Adguard android v 3.6.9

### Settings

- all default settings

**Comment by vonDubenshire** [comment]
I can confirm. Same issue. Tracked to this filter. 

https://user-images.githubusercontent.com/40748193/206294410-c8e67362-3d1c-4cf8-8462-1e22ae16b7da.mp4

**Comment by yourduskquibbles** [comment]
@iskar-jarak @vonDubenshire Thanks for reporting, this should be fixed now, may also need to temporarily add the following exclusion filter until Adguard base lists get updated on their server within 24 hours or so.

You can test this works or not by temporarily adding the following exclusion filter to `User rules`.

`www.google.com#@#.Lj9fsd:style(position: absolute !important; top: 20px !important; padding: 6px 0 0 0 !important; box-shadow: none !important; )`
