### ISSUE TITLE
YouTube - Chapter navigation buttons are not visible

### ISSUE THREAD

**Issue by jed84** [yourduskquibbles/webannoyances#488]
URL(s) where the issue occurs
https://www.youtube.com/
Example of the video that contains chapters: https://www.youtube.com/watch?v=aoG8Iqq802U

Describe the issue
On YouTube, the buttons that allow to view prev/next chapters are incorrectly hidden if the filter Web Annoyances Ultralist is enabled.

![obraz](https://user-images.githubusercontent.com/47121522/208809297-b71985ff-fb98-4cc8-bff3-bb7f3aa9aa2d.png)

Versions
    Browser/version: Firefox 108
    uBlock Origin version: uBlock Origin 1.45.2

**Comment by notevenaperson** [comment]
#474
