### ISSUE TITLE
Floating filter blocks the Active Developer Badge page in the Discord developer portal

### ISSUE THREAD

**Issue by OIRNOIR** [yourduskquibbles/webannoyances#496]
### URL(s) where the issue occurs

`https://discord.com/developers/active-developer`

### Describe the issue

This line in the floating filters list: `discord.com##[class^="notice-"]` blocks the dialog on the Discord developer portal that allows claiming and removal of the Discord Active Developer badge.

### Screenshot(s)

Intended behavior: (Filter off)
<img width="1680" alt="Screenshot 2023-01-30 at 11 49 28 PM" src="https://user-images.githubusercontent.com/70721372/215698753-0a475ea7-f0af-40d0-9ea9-47b4d1517f21.png">

Actual behavior: (Filter on)
<img width="1680" alt="Screenshot 2023-01-30 at 11 49 49 PM" src="https://user-images.githubusercontent.com/70721372/215698902-46a487d7-0018-4ceb-9bdf-6f4c714dca70.png">

### Versions

- Browser & Version: Safari 16.3 on MacOS 13.2
- Adblocker (uBlock Origin, Adguard, Nano Adblocker, etc.) & Version: AdGuard 1.11.10, Web Annoyances Ultralist version 1.0.8.68.

### Settings

- Enabled this filter

### Notes

[Add here the result of whatever investigation work you have done: please investigate the issues you report -- this prevents burdening other volunteers. This is especially true for issues arising from settings which are very different from default ones.]

I have tracked the issue down to a single line in a single file: filters/floating_filters.txt. The line with `discord.com##[class^="notice-"]`.

With inspect element, it is clear that this rule is setting the entire dialog to display: none, despite it being the most important thing on the page.
<img width="154" alt="Screenshot 2023-01-30 at 11 52 25 PM" src="https://user-images.githubusercontent.com/70721372/215699229-3d689b65-1882-4212-81c4-6e295f5d138e.png">

I would have otherwise submitted a pull request to remove this line, but I don't know what kind of consequences that would have had. Why is this rule there? What's it for? What does it block?

**Comment by yourduskquibbles** [comment]
@OIRNOIR Thanks for reporting, this should be fixed now

**Comment by OIRNOIR** [comment]
Thank, it is fixed!

**Comment by OIRNOIR** [comment]
Thanks, it's fixed!
