### ISSUE TITLE
Spotify payment page is broken

### ISSUE THREAD

**Issue by SoftwareRat** [yourduskquibbles/webannoyances#497]
### URL(s) where the issue occurs

German payment page for example:
https://www.spotify.com/de/purchase/offer/eu-2mf-q1-2023-trial-2m/?marketing-campaign-id=2mft-europe-campaign-q1-2023

### Describe the issue
The place where the payment options should be is empty

### Screenshot(s)

![Screenshot from 2023-02-25 19-33-04](https://user-images.githubusercontent.com/40393784/221373835-30187814-0960-47d4-88f2-0e6351d2da8b.png)

### Versions

- Browser & Version: Firefox ESR, 102.8.0esr (64-bit)
- Adblocker (uBlock Origin, Adguard, Nano Adblocker, etc.) & Version: uBlock Origin 1.47.0

### Notes
I think
```
spotify.com##div[aria-live^="polite"]
spotify.com##.react-contextmenu, nav:style(pointer-events: all !important;)
```
are the problem

**Comment by krystian3w** [comment]
IMO not second, because it would require some effort on the part of the site to check that the items have unblocked clickability (and then boorishly hide an important part of the site_.

**Comment by yourduskquibbles** [comment]
@SoftwareRat Thanks for reporting, this should be fixed now.

@krystian3w Confirmed from my testing only `spotify.com##div[aria-live^="polite"]` was the badfilter here.
