### ISSUE TITLE
another few more sites

### ISSUE THREAD

**Issue by elypter** [yourduskquibbles/webannoyances#5]
thanks for making this list. here i have a few more candidates:

! 20.7.2017, 22:17:59 https://www.dein-web-design.de/responsive-webdesign/sticky-header-navigation.html
www.dein-web-design.de##.navbar-small.mega.navbar-fixed-top.navbar-default.navbar

! 21.7.2017, 16:41:02 https://forum.xda-developers.com/ace-3/development/gt-s7275r-b-t-cyanogenmod-14-samsung-t3468084
forum.xda-developers.com##body > .breadcrumbs.navbits

! 21.7.2017, 17:38:29 https://forum.xda-developers.com/ace-3/development/optimize-roms-recycling-factory-t3638513
forum.xda-developers.com##.nolinks > .breadcrumbs.navbits

! 27.7.2017, 04:33:08 http://ipolitics.ca/2017/07/26/canadian-forces-reply-to-trumps-transgender-ban-everyones-welcome-here/
ipolitics.ca##.header-sticky.desktop.header

! 27.7.2017, 21:48:53 http://money.cnn.com/2017/04/13/technology/tesla-semi-truck-september/index.html
money.cnn.com##.main-banner

! 28.7.2017, 02:45:21 http://mapio.net/expose/2118625/
mapio.net###minimap

! 29.7.2017, 14:27:13 https://www.dll-files.com/msvbvm60.dll.html
www.dll-files.com##.scroll-box.client-cta-box

! 1.8.2017, 18:16:52 http://www.comeaucomputing.com/
www.comeaucomputing.com###topmsg

! 2.8.2017, 00:45:09 http://bestride.com/news/video-the-mattel-spinwelder-was-the-coolest-christmas-gift-of-the-1970s
bestride.com##.navbar-fixed-top.navbar-default.navbar

! 2.8.2017, 03:43:02 http://www.spaceflight.watch/
www.spaceflight.watch##nav

! 2.8.2017, 03:53:15 https://www.nature.com/news/china-s-quest-to-become-a-space-science-superpower-1.22359?WT.ec_id=NATURE-20170727&spMailingID=54575327&spUserID=Njk3NjE5NzEwMzgS1&spJobID=1204202138&spReportId=MTIwNDIwMjEzOAS2
www.nature.com###top-story-section:nth-of-type(5) > .top-story.cleared.box

! 2.8.2017, 04:30:45 https://copenhagensuborbitals.com/
copenhagensuborbitals.com###donatebar

! 3.8.2017, 02:49:32 https://forum.vivaldi.net/
forum.vivaldi.net###header-menu

! 3.8.2017, 02:49:53 -------------------------------
login.vivaldi.net###header

! 3.8.2017, 02:50:31 https://vivaldi.com/
vivaldi.com###site-header

! 5.8.2017, 17:28:19 https://devuan.org/
devuan.org###sticky-bar

! 5.8.2017, 19:55:09 http://www.revelist.com/body-positive/ta-ta-towel-for-boob/8709/the-tata-towel-is-perfect-for-postshower-boob-drip/1
www.revelist.com##.pin-banner.header-article-sd.header-content

! 6.8.2017, 00:13:23 https://m.ebay-kleinanzeigen.de/s-anzeige/forsthaus-zu-vermieten/666250056-205-6801
m.ebay-kleinanzeigen.de###headerbar

! 6.8.2017, 00:13:36 ----------------------------
m.ebay-kleinanzeigen.de##.j-do-not-hide.ctacontainer

! 6.8.2017, 01:22:32 https://godotengine.org/article/we-should-all-use-gltf-20-export-3d-assets-game-engines
godotengine.org##nav

! 6.8.2017, 01:51:46 https://anbox.io/
anbox.io###mainNav

! 6.8.2017, 22:35:43 http://www.fortressofsolitude.co.za/peter-jackson-augmented-reality-demo/
www.fortressofsolitude.co.za###menu-main

! 6.8.2017, 22:36:03 http://www.fortressofsolitude.co.za/peter-jackson-augmented-reality-demo/
www.fortressofsolitude.co.za###hometabs-wrap

! 9.8.2017, 11:46:35 http://www.rootupdate.com/2017/02/install-lineage-os-rom-in-galaxy-note-4.html
www.rootupdate.com###sticky_header

! 11.8.2017, 12:59:28 https://www.dorkjournal.com/2017/04/04/best-samsung-galaxy-note-4-custom-roms/
www.dorkjournal.com##.header--slide.fixed.header > .cf.header_top

! 11.8.2017, 12:59:37 https://www.dorkjournal.com/2017/04/04/best-samsung-galaxy-note-4-custom-roms/
www.dorkjournal.com##.text-center.full-menu-container

! 12.8.2017, 03:50:27 http://www.worldatlas.com/webimage/countrys/europe/lgcolor/decolorlf.htm
www.worldatlas.com##.w-headerMain

! 12.8.2017, 03:57:48 https://www.mapsofworld.com/germany/germany-river-map.html
www.mapsofworld.com###short_from

! 13.8.2017, 23:14:07 http://www.businessinsider.de/anti-google-ads-pop-up-outside-office-criticizing-ceo-sundar-pichai-2017-8?r=UK&IR=T
www.businessinsider.de##.condensed.masthead > .container

! 13.8.2017, 23:14:19 http://www.businessinsider.de/anti-google-ads-pop-up-outside-office-criticizing-ceo-sundar-pichai-2017-8?r=UK&IR=T
www.businessinsider.de##.condensed.masthead

! 16.8.2017, 17:13:38 https://www.ebay.de/p/VENTURA-Fahrrad-Gep%C3%A4cktr%C3%A4ger-24-28-schwarz-Alu-Zuladung-25-Kg/513025531
www.ebay.de###ocs-inflow

! 16.8.2017, 21:48:48 https://www.bookscanner.de/videos/
www.bookscanner.de##.navigation-alignment.navigation-colors.jtpl-navigation__inner

! 17.8.2017, 13:50:41 http://www.nordbayern.de/region/erlangen/fahrradleichen-am-erlanger-bahnhof-werden-entsorgt-1.4343904
www.nordbayern.de###myslidemenu

! 17.8.2017, 15:21:58 https://www.internet-bikes.com/de/44626-tranzx-sattelstutze-feder-350-x-272-mm-aluminium-silber/
www.internet-bikes.com##.header

! 19.8.2017, 04:22:51 https://www.maketecheasier.com/use-nmap-check-linux-open-ports/
www.maketecheasier.com##.site-header-content

! 20.8.2017, 01:30:45 https://www.electricbike.com/mid-drive-kits/
www.electricbike.com##.sticky.navigation

! 20.8.2017, 02:19:12 https://www.sportlerfrage.net/frage/anfaengerritzel-beim-rennrad
www.sportlerfrage.net##.is-affixed.Masthead

! 20.8.2017, 02:38:39 https://www.radforum.de/threads/346322-nacken-vor-kaelte-schuetzen
www.radforum.de##.multibarcontainer

! 20.8.2017, 13:32:52 http://www.bike-magazin.de/service/schrauber_tipps/schaltung-und-umwerfer-richtig-einstellen/a564.html
www.bike-magazin.de##.stucked.top.set > .ribbon > .vertical.main > ul

! 20.8.2017, 14:13:59 https://www.openstreetmap.org/#map=13/54.2518/9.1968
||www.openstreetmap.org/assets/banners/banner-sotm-2017-833e622a26d1948090d2d17161900368823a535ee7ca84b6033e67a81017d5f2.png$image

! 21.8.2017, 04:05:06 https://wickwerks.com/products/mountain-bike-3824/
||wickwerks.com/wp-content/uploads/2015/09/WickWerks-Cycling.gif$image

! 21.8.2017, 04:05:16 https://wickwerks.com/products/mountain-bike-3824/
wickwerks.com###headerwrap

! 21.8.2017, 05:10:06 https://pedelec-elektro-fahrrad.de/news/e-bike-hinterrad-nabenmotor-mit-fuenf-gaengen-fuer-2013-angekuendigt/2897/
pedelec-elektro-fahrrad.de##.is_stuck.mm-fixed-top.stickyloaded.altcontainer

! 21.8.2017, 05:10:32 https://pedelec-elektro-fahrrad.de/news/e-bike-hinterrad-nabenmotor-mit-fuenf-gaengen-fuer-2013-angekuendigt/2897/
pedelec-elektro-fahrrad.de###wtr-progress

! 21.8.2017, 05:10:47 https://pedelec-elektro-fahrrad.de/news/e-bike-hinterrad-nabenmotor-mit-fuenf-gaengen-fuer-2013-angekuendigt/2897/
pedelec-elektro-fahrrad.de###wtr-progress

! 21.8.2017, 05:11:22 https://pedelec-elektro-fahrrad.de/news/e-bike-hinterrad-nabenmotor-mit-fuenf-gaengen-fuer-2013-angekuendigt/2897/
pedelec-elektro-fahrrad.de###wtr-progress

! 21.8.2017, 05:46:36 http://www.elektrobike-online.com/news/rad-szene-und-tourismus/pumptire-selbst-aufpumpender-reifen-kurz-vor-marktreife-mit-video.570854.410636.htm
www.elektrobike-online.com###main-menu

! 21.8.2017, 14:58:02 https://www.owler.com/iaApp/1080527/pumptire-company-profile
www.owler.com###pageless-onboarding-popup-overlay

! 21.8.2017, 14:58:12 https://www.owler.com/iaApp/1080527/pumptire-company-profile
www.owler.com###pageless-onboarding-popup-container

! 21.8.2017, 14:58:23 https://www.owler.com/iaApp/1080527/pumptire-company-profile
www.owler.com###header

! 21.8.2017, 14:58:54 https://index.co/company/pumptire
index.co##.trigger_fly--flying.u_propSticky.trigger_fly--ready.trigger_fly.c_headerCover > .c_layout

! 21.8.2017, 14:59:00 https://index.co/company/pumptire
||index.co/img/iconTile10.png$image

! 21.8.2017, 14:59:07 https://index.co/company/pumptire
index.co##.c_layout--keepsPadding.c_layout

! 21.8.2017, 14:59:16 https://index.co/company/pumptire
index.co##.c_header--flyAttached.c_header--ready.c_headerHeight.c_header

! 21.8.2017, 14:59:24 https://index.co/company/pumptire
index.co##.trigger_fly--flying.u_propSticky.trigger_fly--ready.trigger_fly.c_headerCover

! 21.8.2017, 16:07:37 https://www.mtb-news.de/forum/t/sattelstuetze-fetten.320719/
www.mtb-news.de##.navbar-inner

! 21.8.2017, 16:31:40 http://www.portlandbolt.com/technical/faqs/recommendation-on-thread-engagement/
www.portlandbolt.com##.noprint.header-fixed.site-header > .header-content.header-main

! 22.8.2017, 04:12:33 http://www.tour-magazin.de/service/werkstatt/richtig-schmieren-richtig-fetten--so-wird-es-gemacht/a607.html
www.tour-magazin.de##.stucked.top.set > .ribbon > .vertical.main > ul

! 22.8.2017, 04:13:22 http://forum.mountainbike-magazin.de/forum/mountainbike-bikes-parts-und-equipment-saettel-und-sattelstuetzen/28557-sattelstuetze-einfetten.html
forum.mountainbike-magazin.de###main-menu

! 22.8.2017, 18:34:11 https://www.teslarati.com/spacex-falcon-heavy-most-powerful-rocket-ready-launch/
www.teslarati.com###main-nav-cont

! 22.8.2017, 18:34:19 https://www.teslarati.com/spacex-falcon-heavy-most-powerful-rocket-ready-launch/
www.teslarati.com###main-nav-wrap

! 23.8.2017, 00:35:59 http://www.wer-weiss-was.de/t/prinzipielle-frage-flanschlager-axial-belastbar/7567507
www.wer-weiss-was.de###ember1659

! 23.8.2017, 04:40:15 https://community.netgear.com/t5/Home-Networking/ct-p/home-networking/page/3189
community.netgear.com##.top-bar

! 23.8.2017, 04:52:39 https://www.daniweb.com/hardware-and-software/hardware/threads/49463/computer-wont-turn-on-power-light-blinks
www.daniweb.com##body > header

! 23.8.2017, 05:21:11 https://picclick.com/Wire-Rounder-Tool-With-Wooden-Handle-Debur-Wire-332214311077.html
picclick.com##.navbar-fixed-top.navbar-default.navbar > .container-fluid

! 24.8.2017, 04:50:50 https://www.asus.com/Laptops/Eee_PC_1016P/
www.asus.com###overview-top-nav

! 24.8.2017, 16:21:51 http://www.wer-weiss-was.de/t/fahrrad-alte-kette-neuer-zahnkranz/8778845
www.wer-weiss-was.de###ember1662

! 25.8.2017, 03:10:50 http://www.gamerevolution.com/features/346091-h3h3productions-wins-17-month-copyright-lawsuit-expensive-legal-fees
www.gamerevolution.com###js-site-navigation

! 25.8.2017, 05:20:59 http://www.auctiva.com/edu/entry.aspx?id=eBays-Global-Shipping-Program-Puts-Sellers-on-the-Fence
||www.auctiva.com/images/textures/header-bg.png$image

! 25.8.2017, 05:21:10 http://www.auctiva.com/edu/entry.aspx?id=eBays-Global-Shipping-Program-Puts-Sellers-on-the-Fence
www.auctiva.com##.navbar-inner

! 25.8.2017, 14:26:57 https://www.tinkercad.com/
www.tinkercad.com##.navbar-wrapper

! 26.8.2017, 02:15:48 http://www.heute-show.de/zdf/
www.heute-show.de##.gradient

! 26.8.2017, 02:16:01 http://www.heute-show.de/zdf/
www.heute-show.de##.push.header

! 26.8.2017, 13:40:06 http://www.i-e-e.info/2436v-universalcontroller-der-alleskoenner/
www.i-e-e.info###main-header

! 27.8.2017, 21:47:09 https://gab.ai/weev/posts/11274990
gab.ai##.header

! 28.8.2017, 01:11:52 http://essayoutlinetemplate.org/tesla/tesla-battery-location
essayoutlinetemplate.org##.header

! 28.8.2017, 01:12:51 http://sw-kawasaki.com/wiring/tesla-battery-electric-wire-diagram.html
sw-kawasaki.com###my-modal

! 28.8.2017, 01:12:58 http://sw-kawasaki.com/wiring/tesla-battery-electric-wire-diagram.html
sw-kawasaki.com##.in.fade.modal-backdrop

! 28.8.2017, 01:23:55 https://teslamotorsclub.com/tmc/threads/pics-info-inside-the-battery-pack.34934/page-14#post-755546
teslamotorsclub.com##.fc-secondary-menu

! 28.8.2017, 01:29:11 https://teslamotorsclub.com/tmc/threads/pics-info-inside-the-battery-pack.34934/page-14#post-755546
teslamotorsclub.com##.fc-primary-menu

! 28.8.2017, 03:32:00 https://www.ivpn.net/privacy-guides/an-introduction-to-tor-vs-i2p
www.ivpn.net##header > .bg-white.tank

! 28.8.2017, 04:53:25 http://www.movie4k.ws/lavalantula/
www.movie4k.ws###header

! 28.8.2017, 04:55:35 https://www.streamcatcher.de/film/lavalantula---angriff-der-feuerspinnen-stream/776316
www.streamcatcher.de##.header.navbar-fixed-top.container-fluid

! 28.8.2017, 04:56:23 http://stream-online-hd.xyz/?z
stream-online-hd.xyz##.navbar-fixed-top.navbar-default.navbar

! 28.8.2017, 04:58:34 http://free-cinema21.streamingonline.desi/streaming/294562/lavalantula+full+movie+stream/
free-cinema21.streamingonline.desi###main-navigation

! 28.8.2017, 04:59:08 http://free-cinema21.streamingonline.desi/streaming/294562/lavalantula+full+movie+stream/
free-cinema21.streamingonline.desi###modal-watch

! 28.8.2017, 04:59:14 http://free-cinema21.streamingonline.desi/streaming/294562/lavalantula+full+movie+stream/
free-cinema21.streamingonline.desi##.in.fade.modal-backdrop

! 28.8.2017, 05:01:51 https://putlocker.rs/watch/lavalantula.my8/099y29
putlocker.rs###header

! 29.8.2017, 16:02:42 https://www.radforum.de/threads/182451-kette-saeubernoelen/page3?s=54b435e9a114f1f427d6ef84557cc607
www.radforum.de###LZ0N8qSLUJDCU3Gv > .old.postcontainer.postbitim.postbitlegacy

! 29.8.2017, 17:55:32 https://www.obi.de/baustahl-baugitter/estrichgitter-2-m-x-1-m/p/7176605
www.obi.de##.auto-init.js-show-overview-fixhdr.overview-sticky-header

! 29.8.2017, 17:56:25 https://www.obi.de/baustahl-baugitter/baustahlmatte-1-m-x-2-3-m/p/1309079
www.obi.de##.auto-init.js-show-overview-fixhdr.overview-sticky-header

! 29.8.2017, 20:55:32 https://electricbike.com/forum/forum/main-forum/general-discussions/12249-who-else-has-more-than-500-miles-on-their-bbshd
||electricbike.com/forum/images/css/sprite_gradients_vb.png$image

! 29.8.2017, 20:55:39 https://electricbike.com/forum/forum/main-forum/general-discussions/12249-who-else-has-more-than-500-miles-on-their-bbshd
electricbike.com##.js-shrink-event-parent.conversation-toolbar

! 29.8.2017, 23:09:34 http://www.elektroniknet.de/elektronik/power/kurzschlussstrom-bei-grossen-lithium-ionen-akkus-abschalten-103663.html
www.elektroniknet.de##.navbar-fixed-top.navigation > .container

! 30.8.2017, 00:21:15 https://www.youtube.com/watch?v=NQoJ4RQ6iCc
www.youtube.com###masthead

! 30.8.2017, 03:02:37 https://www.youtube.com/watch?v=lUPVnmxUPHY
www.youtube.com###masthead

! 30.8.2017, 03:05:58 https://www.youtube.com/user/DVDKritik/videos
www.youtube.com###channel-header

! 30.8.2017, 03:06:11 https://www.youtube.com/user/DVDKritik/videos
www.youtube.com###contentContainer

! 30.8.2017, 03:40:21 https://www.fahrrad-xxl.de/blog/mountainbike-oder-trekkingrad-welches-fahrrad-passt-eher-zu-mir/
www.fahrrad-xxl.de##.is_stuck.mm-fixed-top.stickyloaded.regular-nav.top-nav

! 30.8.2017, 03:52:05 https://pedelec-ebike-forum.de/
pedelec-ebike-forum.de##.topmenu

! 30.8.2017, 03:54:39 http://eczo.bike/
eczo.bike##.t228__maincontainer

! 30.8.2017, 04:07:22 http://eczo.bike/
eczo.bike###nav28963912

**Comment by yourduskquibbles** [comment]
Thanks I got all of them except for the `sw-kawasaki.com` filters because I can't resolve the domain name - will check again later to see if it is resolving.
