### ISSUE TITLE
all cryptocurrencies

### ISSUE THREAD

**Issue by KonoromiHimaries** [yourduskquibbles/webannoyances#57]
to reproduct

1. join to this site
https://coinmarketcap.com/all/views/all/

2. select any cryptocurrency

3. click website link
![2018-05-29-eos eos price charts market cap and other metrics _ coinmarketcap](https://user-images.githubusercontent.com/5884000/40679417-56e0679a-6383-11e8-88e7-0b63084c8b98.png)

**Comment by KonoromiHimaries** [comment]
maybe not because of popularity in the ranking, but the number of page views? what the bottom ceiling of 10,000k views?

**Comment by KonoromiHimaries** [comment]
@yourduskquibbles check this
https://www.similarweb.com/extension-welcome

**Comment by yourduskquibbles** [comment]
If you want to compile the list of sites with >10k views I am OK with that, I don't trust an extension like that though.
