### ISSUE TITLE
cookie warnings

### ISSUE THREAD

**Issue by elypter** [yourduskquibbles/webannoyances#6]
if you are lucky and do not live in the eu you might not have noticed them yet but since it is a law to inform users of tracking cookies those are usually implemented as banners that you have to click away once or every time if you do not save cookies. i do NOT want to ask to include those but just want to suggest to inform users in the readme that there are lists that remove those banners and that it is not part of this list because that would only cause dublicates.

**Comment by yourduskquibbles** [comment]
Are you able to provide links to other such filter lists that I can include?

As a general rule I tend to kill these warnings in my list when I come across them, but don't specifically target them with generic filters and only target specific sites I come across.

**Comment by elypter** [comment]
there is the prebake list that is included in ubo, the eu cookie shit list and the cookiemonster list
http://prebake.eu/
https://github.com/r4vi/block-the-eu-cookie-shit-list/
https://www.fanboy.co.nz/
there might be more but i think those are the most popular ones. there are also the cookiesok and the idontcareaboutcookies browser addons which maybe use different lists as well. there is a list thats probably the one of the second addon or based on it https://www.kiboke-studio.hr/i-dont-care-about-cookies/abp/

this also exists https://filters.adtidy.org/extension/chromium/filters/14.txt

i think it would be best if you report cookie warnings that are not part of any of those lists to the most actively developed one instead of mixing them with the floating element list.

**Comment by Atavic** [comment]
@elypter This uBlock discussion: https://github.com/gorhill/uBlock/issues/2997 ends with picking **Fanboy's Cookiemonster** and also there's a huge replacement for Prebake, see: https://github.com/gorhill/uBlock/issues/2997#issuecomment-329230611

**Comment by Ravizz** [comment]
I'm just testing if I can comment in this issue, hmm I can.

**Comment by yourduskquibbles** [comment]
I have finally added a project [wiki](https://github.com/yourduskquibbles/webannoyances/wiki) that includes an [entire section](https://github.com/yourduskquibbles/webannoyances/wiki/Additional-Annoyance-Filter-Lists) linking to additional filter lists that should now address this issue.
