### ISSUE TITLE
wykop.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [yourduskquibbles/webannoyances#63]
![2018-06-01-wykop pl - newsy aktualnosci gry wiadomosci muzyka ciekawostki filmiki](https://user-images.githubusercontent.com/5884000/40856419-1cb563ac-65d8-11e8-96d5-2336b909cb77.png)

broken message icon

<details><summary>my settings</summary>

my filters
https://gist.github.com/KonoromiHimaries/afab54402a6cc37a168c2e55a0ef6896

 uBO 1.16.8
 ND 14.42
 Chr 67.0.3396.62
</details>

**Comment by yourduskquibbles** [comment]
Can you post a screenshot of your logger? Need a login to see the three icons on the right.

**Comment by KonoromiHimaries** [comment]
@yourduskquibbles you have a discord and teamviewer?

**Comment by KonoromiHimaries** [comment]
https://gist.github.com/KonoromiHimaries/5972f1c725c708baed9e1267ac669a79
