### ISSUE TITLE
discord

### ISSUE THREAD

**Issue by KonoromiHimaries** [yourduskquibbles/webannoyances#66]
do you can create discord server or anything else to be able create multiple issues at once without creating a separate thread for each issue

what would it look like, an example. https://discord.me/polskiefiltry

**Comment by yourduskquibbles** [comment]
I will look into that, I doubt I would be able to manage it though if you'd like to maintain it I would be happy to advertise it in the readme/wiki.

**Comment by KonoromiHimaries** [comment]
@yourduskquibbles if you can create a discord server and be online it every 2/3 days for 10 minutes, then I can become an administrator and prepare everything

my actual id `KonoromiHimaries#2881`

**Comment by yourduskquibbles** [comment]
https://discord.gg/UsWBZgq

**Comment by yourduskquibbles** [comment]
I set it up, have to sign out for now though. Won't be able to be back online for a few hours at the earliest.

**Comment by yourduskquibbles** [comment]
Our [Discord server](https://discord.gg/UsWBZgq) details have been added to the [README](https://github.com/yourduskquibbles/webannoyances/blob/master/README.md). Feel free to join the server and report issues there.

**Comment by KonoromiHimaries** [comment]
@yourduskquibbles can you look on the discord server?
