### ISSUE TITLE
yet another list of sites

### ISSUE THREAD

**Issue by elypter** [yourduskquibbles/webannoyances#7]
i have collected a few more:

! 31.8.2017, 22:44:24 http://www.parktool.com/blog/repair-help/pedal-installation-and-removal
www.parktool.com##.header-content

! 31.8.2017, 22:45:01 http://www.parktool.com/blog/repair-help/pedal-installation-and-removal
www.parktool.com##.fixed-header.header

! 31.8.2017, 22:59:46 http://bike.shimano.com/content/sac-bike/en/home/road/drivetrain/bottom-brackets/bb-un26.html
bike.shimano.com###anchorlinks

! 31.8.2017, 23:08:46 https://duckduckgo.com/?q=kurbelgarnitur+wechseln&t=vivaldi&ia=videos&iax=1&iai=WjryieWF9D4
duckduckgo.com##.is-stuck.has-dropdowns.js-zcm-sticky.metabar--fixed.metabar

! 2.9.2017, 22:02:03 https://medium.freecodecamp.org/how-i-replicated-an-86-million-project-in-57-lines-of-code-277031330ee9?gi=8eb96d1ad333
medium.freecodecamp.org##.u-tintSpectrum.u-tintBgColor.u-xs-sizeFullViewportWidth.u-backgroundTransparentWhiteDarkest.u-fixed.u-textColorTransparentWhiteDarker.u-boxShadowBottomThinLighter.js-metabar.u-clearfix.metabar

! 2.9.2017, 23:22:05 https://resource.dopus.com/t/directory-opus-12-6-1-beta/26753
resource.dopus.com##.clearfix.d-header

! 3.9.2017, 03:36:16 https://www.revolvy.com/topic/Solid%20oxygen
www.revolvy.com###main_header

! 4.9.2017, 14:40:54 https://www.feinewerkzeuge.de/axt-einstielen.html
www.feinewerkzeuge.de##.navbar-fixed-top.navbar-default.navbar

! 5.9.2017, 13:28:40 https://blog.bolt.io/heres-why-juicero-s-press-is-so-expensive-6add74594e50
blog.bolt.io##.u-tintSpectrum.u-tintBgColor.u-xs-sizeFullViewportWidth.u-backgroundTransparentWhiteDarkest.u-fixed.u-textColorTransparentWhiteDarker.u-boxShadowBottomThinLighter.js-metabar.u-clearfix.metabar

! 7.9.2017, 18:23:59 http://www.ebikeschool.com/geared-hub-motors-vs-gearless-hub-motors/
www.ebikeschool.com##.site-header

! 8.9.2017, 14:31:00 http://asb-erlangen.de/de/unsere-angebote1/kleiderkaffee
asb-erlangen.de##.myasb.primarynav

! 8.9.2017, 14:31:16 http://asb-erlangen.de/de/unsere-angebote1/kleiderkaffee
asb-erlangen.de##.fixer.navigation

! 9.9.2017, 14:35:07 http://www.gkn.com/en/our-divisions/gkn-powder-metallurgy/our-markets/
www.gkn.com##.navbar-nav.nav

! 9.9.2017, 18:22:27 http://www.ecmweb.com/content/bad-bearings-cause-motor-failures
www.ecmweb.com##.js-header.header

! 9.9.2017, 18:25:40 http://www.pedelecs.co.uk/forum/threads/tongxin-motor-bearing-longevity.13652/
www.pedelecs.co.uk##.navTabs

! 9.9.2017, 18:56:08 https://www.rbb24.de/politik/wahl/bundestag/beitraege/kleine-parteien-demokratie-in-bewegung-dib.html
www.rbb24.de###header

! 9.9.2017, 19:03:08 https://www.mucbook.de/2017/08/08/partei-demokratie-bewegung-wahlkampf-bundestagswahl-dib-muenchen-2017-transparenz-politik-diesel-vw-kartellvorwurf/
www.mucbook.de##.sticky_animate.sticky.page_header.scrolled_not_transparent.stick.scroll_header_top_area.centered_logo

! 9.9.2017, 19:18:56 http://rotomshop.de/lager-und-supermarktzubehor/faltbare-kisten.html
||rotomshop.de/skin/frontend/default/rotom6_nl/images/bg-top-1px.png$image

! 9.9.2017, 19:19:15 http://rotomshop.de/lager-und-supermarktzubehor/faltbare-kisten.html
rotomshop.de##.header

! 9.9.2017, 19:24:36 https://www.camping-kaufhaus.com/outwell-collaps-faltkorb-stabil-gruen/a-72817/
www.camping-kaufhaus.com##.fixed.CategoryNavigation.w100.header_2

! 9.9.2017, 19:56:36 https://www.amazon.de/KLICKFix-Lenkerkorb-Feinmaschig-Schwarz-0305P/dp/B004CLM8XK/ref=pd_sbs_200_5/262-1985068-7118810?_encoding=UTF8&psc=1&refRID=NSN324866CPG5091BCJB
www.amazon.de###quickPromoBucketContent

! 9.9.2017, 19:56:56 https://www.amazon.de/KLICKFix-Lenkerkorb-Feinmaschig-Schwarz-0305P/dp/B004CLM8XK/ref=pd_sbs_200_5/262-1985068-7118810?_encoding=UTF8&psc=1&refRID=NSN324866CPG5091BCJB
www.amazon.de###sponsoredProducts_feature_div

! 9.9.2017, 19:57:29 https://www.amazon.de/KLICKFix-Lenkerkorb-Feinmaschig-Schwarz-0305P/dp/B004CLM8XK/ref=pd_sbs_200_5/262-1985068-7118810?_encoding=UTF8&psc=1&refRID=NSN324866CPG5091BCJB
www.amazon.de##.bucketDivider:nth-of-type(2)

! 10.9.2017, 12:33:24 http://3dprintingforbeginners.com/how-to-make-diy-filament-for-your-3d-printer/
3dprintingforbeginners.com##header

! 14.9.2017, 16:13:59 https://cart.payments.ebay.de/sc/view
cart.payments.ebay.de###gh-cart-n

! 15.9.2017, 01:12:33 http://www.pocketnc.com/
www.pocketnc.com###header

! 15.9.2017, 01:16:24 https://www.instructables.com/howto/5axis+cnc/
www.instructables.com##.search-header-inner

! 15.9.2017, 02:30:12 http://www.compact-dynamics.de/produktbeispiele/transversalflussmaschine/drive-system-formula-student/
www.compact-dynamics.de###kopf

! 15.9.2017, 02:33:52 https://duckduckgo.com/?q=transversalflussmotor&t=vivaldi&ia=web
duckduckgo.com###header_wrapper

! 15.9.2017, 02:37:04 http://ebike-news.de/tag/transversalfluss-motor/
ebike-news.de##.td-affix.td-header-gradient.td-header-menu-wrap

! 16.9.2017, 15:46:04 http://whnt.com/2017/09/15/huntsvilles-cimarron-makes-tanks-that-go-to-space/
whnt.com##.navbar-fixed-top.navbar-inverse.navbar

! 17.9.2017, 03:12:47 https://www.wood-machine.com/Product/veneer-peeling-machine/
www.wood-machine.com##.fusion-sticky-shadow.fusion-header

! 17.9.2017, 13:01:10 http://www.manager-magazin.de/finanzen/boerse/aktien-kaufen-warum-autoaktien-eine-ueberlegung-wert-sind-a-1167799.html
www.manager-magazin.de##.scroll-active.clearfix.main-nav

! 17.9.2017, 17:29:18 https://filterlists.com/
filterlists.com##.site-header

! 18.9.2017, 14:42:54 http://www.chicagotribune.com/news/opinion/chapman/ct-perspec-iphone-x-unabomber-technology-20170913-story.html
www.chicagotribune.com##.trb_nh

! 20.9.2017, 04:37:19 http://www.makeuseof.com/tag/ways-shut-down-linux-command-line/
www.makeuseof.com##.header-container

! 20.9.2017, 04:37:29 http://www.makeuseof.com/tag/ways-shut-down-linux-command-line/
www.makeuseof.com##.header-wrap

! 20.9.2017, 04:51:08 https://stackoverflow.com/questions/8354482/dialog-from-bash-script
stackoverflow.com##._scrolling._fixed.js-top-bar.top-bar

! 20.9.2017, 18:02:30 http://www.wetter.com/wetterkarten/niederschlagsradar/#geo:51.0802,10.4224,6
www.wetter.com###mainHeader

! 21.9.2017, 12:44:25 http://www.linuxportal.pl/wpisy/system-submenu-dla-shutdown-dialog-id131965
www.linuxportal.pl###naglowek

! 22.9.2017, 03:54:42 http://www.fineknitting.com/
www.fineknitting.com##.fusion-sticky-shadow.fusion-header

! 22.9.2017, 16:45:46 https://www.tecmint.com/best-clipboard-managers-for-linux/
www.tecmint.com##.link-overlay

! 22.9.2017, 16:46:01 https://www.tecmint.com/best-clipboard-managers-for-linux/
www.tecmint.com###quickiebarpro

! 23.9.2017, 15:06:50 http://www.architectureartdesigns.com/25-incredible-diy-repurposed-bike-wheels/
www.architectureartdesigns.com###ubermenu-main-2-primary

! 23.9.2017, 15:07:30 http://www.architectureartdesigns.com/25-incredible-diy-repurposed-bike-wheels/
www.architectureartdesigns.com###ubermenu-main-2-primary

! 23.9.2017, 15:07:49 http://www.architectureartdesigns.com/25-incredible-diy-repurposed-bike-wheels/
www.architectureartdesigns.com###header

! 23.9.2017, 20:00:44 https://ubuntu-mate.community/t/how-do-i-exit-gui/2713
ubuntu-mate.community##.clearfix.d-header

! 23.9.2017, 21:21:16 https://www.cyberciti.biz/faq/linux-command-to-suspend-hibernate-laptop-netbook-pc/
www.cyberciti.biz##.cfapps-welcome-bar

! 23.9.2017, 21:31:47 https://www.cyberciti.biz/faq/linux-command-to-suspend-hibernate-laptop-netbook-pc/
www.cyberciti.biz##.cfapps-welcome-bar

! 24.9.2017, 00:46:32 https://codedump.io/share/wJGKRKg1lVQ6/1/how-to-create-a-pop-window-using-pygtk
codedump.io##.navbar-fixed-top.navbar-inverse.navbar

! 24.9.2017, 18:19:59 http://www.directindustry.com/industrial-manufacturer/tilting-rotary-table-84443.html
www.directindustry.com###float-bar-container

! 24.9.2017, 21:34:17 http://bundestagswahl17.de/t/bundeswahlleiter/
bundestagswahl17.de##.header-main

! 24.9.2017, 21:36:50 https://www.bundeswahlleiter.de/bundestagswahlen/2017/ergebnisse/bund-99.html
www.bundeswahlleiter.de###header

! 24.9.2017, 21:37:21 https://www.bundeswahlleiter.de/bundestagswahlen/2017/ergebnisse/bund-99.html
www.bundeswahlleiter.de##.tablejigsaw-fixed-header-table.table-stimmen.tablesaw

! 24.9.2017, 21:37:38 https://www.bundeswahlleiter.de/bundestagswahlen/2017/ergebnisse/bund-99.html
www.bundeswahlleiter.de##.tablejigsaw-fixed-header-table.table-stimmen.tablesaw

! 25.9.2017, 01:03:09 http://www.rp-online.de/politik/deutschland/bundestagswahl/wahlergebnisse/
www.rp-online.de##._sticky

! 25.9.2017, 01:03:58 https://www.zvw.de/inhalt.bundestagswahl-2017-wer-sonst-noch-zur-wahl-steht.489c72a1-1289-4a14-865a-9b438ce131d8.html
www.zvw.de###main-nav

! 25.9.2017, 03:45:19 https://www.empoweredcycles.com/blogs/news/82418054-48-and-52-volt-battery-pack-fyi
www.empoweredcycles.com###mainNav

! 25.9.2017, 03:45:38 https://www.empoweredcycles.com/blogs/news/82418054-48-and-52-volt-battery-pack-fyi
||cdn.shopify.com/s/files/1/0514/3481/t/5/assets/lightNav_bkgd.png?7951196763757035208$image

! 25.9.2017, 03:45:51 https://www.empoweredcycles.com/blogs/news/82418054-48-and-52-volt-battery-pack-fyi
www.empoweredcycles.com###navWrapper

! 25.9.2017, 03:52:23 https://lunacycle.com/52v-panasonic-11-5ah-or-13-5ah-bottle-battery/
lunacycle.com##.header

! 26.9.2017, 03:24:26 http://www.practicalmachinist.com/vb/general/cheap-source-aluminum-flat-stock-236628/
www.practicalmachinist.com##.sticky.nav-div

! 26.9.2017, 14:44:31 https://wiki.gnome.org/Initiatives/Wayland/TryingIt
wiki.gnome.org###user_tab

! 26.9.2017, 17:42:15 https://glade.gnome.org/
glade.gnome.org###hdr

! 27.9.2017, 14:26:58 https://picclick.de/Schotklemme-Curryklemme-Seilklemme-Klemme-Seil-Tau-Schot-Tauwerk-321453136853.html
picclick.de##.navbar-fixed-top.navbar-default.navbar > .container-fluid

! 27.9.2017, 14:31:00 https://picclick.de/2x-ServoCleat-Schotklemme-Curryklemme-Seilklemme-Klemme-Seil-Schot-252620223711.html
picclick.de##.navbar-fixed-top.navbar-default.navbar

! 30.9.2017, 13:15:39 http://jeffskinnerbox.me/posts/2014/Apr/29/howto-using-xephyr-to-create-a-new-display-in-a-window/
jeffskinnerbox.me##.navbar-fixed-top.navbar-default.navbar

! 30.9.2017, 20:51:29 https://mg.mail.yahoo.com/?.src=neo&reason=bkt_myc
mg.mail.yahoo.com###yui_3_16_0_ym19_1_1506797344670_4983

! 30.9.2017, 20:51:39 https://mg.mail.yahoo.com/?.src=neo&reason=bkt_myc
mg.mail.yahoo.com###yui_3_16_0_ym19_1_1506797344670_4974

! 30.9.2017, 20:53:59 https://www.linuxquestions.org/questions/bedrock-linux-118/
www.linuxquestions.org##.page:nth-of-type(1) > .tborder:nth-of-type(3)

! 8.10.2017, 05:01:27 https://www.quantcast.com/sciencealert.com#trafficCard
www.quantcast.com###appNav

! 9.10.2017, 02:22:20 https://discourse.anbox.io/
discourse.anbox.io##.clearfix.d-header

! 9.10.2017, 19:24:47 https://www.salon.com/2017/10/08/against-mars-a-lago-why-spacexs-mars-colonization-plan-should-terrify-you/
www.salon.com##.DqBWg-Vvho_ZrxWqxa8ub

! 10.10.2017, 02:19:16 https://wildnotice.com/windows-10-mobile-no-longer-focus-microsoft
wildnotice.com###head-main-wrap

! 10.10.2017, 16:33:32 https://www.zmescience.com/science/facts-about-solar-energy/
www.zmescience.com###site-banner

! 11.10.2017, 00:40:07 https://icons8.com/icon/set/logout/all
icons8.com##.m-change-lang.c-line-backlink

! 11.10.2017, 00:40:17 https://icons8.com/icon/set/logout/all
icons8.com###navmenu

! 11.10.2017, 00:42:53 https://erikdubois.be/lock-log-suspend-hibernate-reboot-shutdown-one/
erikdubois.be###top-header

! 11.10.2017, 00:43:02 https://erikdubois.be/lock-log-suspend-hibernate-reboot-shutdown-one/
erikdubois.be###main-header

! 11.10.2017, 04:22:55 https://www.wholecloud.net/video/f69724f8a2773
www.wholecloud.net##body > .clearfix

! 12.10.2017, 15:42:33 https://www.2daygeek.com/rm-command-to-move-files-to-trash-can-rm-alias/
www.2daygeek.com###nav-topbar > .container.nav-wrap

! 12.10.2017, 15:42:54 https://www.2daygeek.com/rm-command-to-move-files-to-trash-can-rm-alias/
www.2daygeek.com###nav-topbar

! 13.10.2017, 20:36:42 https://www.quora.com/Why-dont-the-other-primates-have-long-hair
www.quora.com###__w2_at50n15_message

! 16.10.2017, 01:30:40 https://www.hexxiumcreations.com/projects/malicious-domain-blocking/
www.hexxiumcreations.com###masthead

! 17.10.2017, 02:28:11 https://www.arte.tv/de/videos/067846-016-A/mit-offenen-karten/
www.arte.tv##.next-topbar-nav

! 20.10.2017, 03:32:49 https://vrodo.de/windows-brillen-unterstuetzen-steamvr-oculus-unterstuetzung-moeglich-update/
vrodo.de###main_sticky > .no-padding.container-fluid:nth-of-type(2)

! 20.10.2017, 03:33:13 https://vrodo.de/windows-brillen-unterstuetzen-steamvr-oculus-unterstuetzung-moeglich-update/
vrodo.de###sticky-bar > .row > .col-md-12

! 20.10.2017, 03:33:21 https://vrodo.de/windows-brillen-unterstuetzen-steamvr-oculus-unterstuetzung-moeglich-update/
vrodo.de###sticky-bar

! 20.10.2017, 03:42:19 https://mspoweruser.com/this-hack-will-let-you-use-your-windows-mixed-reality-headset-on-your-poor-old-pc/
mspoweruser.com##.navbar-default.navbar-fixed-top.navbar.shunno-mm.shunno-header

! 21.10.2017, 00:33:25 https://freenode.net/
freenode.net##.navbar

**Comment by yourduskquibbles** [comment]
Thank you! Will inspect all of them and add the fix into the list.
