### ISSUE TITLE
twitter.com

### ISSUE THREAD

**Issue by KonoromiHimaries** [yourduskquibbles/webannoyances#71]
![2018-06-11-tag adblock na twitterze](https://user-images.githubusercontent.com/5884000/41206977-85ab7572-6d0d-11e8-84c8-2c08fb94b65f.png)
`https://twitter.com/hashtag/adblock?f=tweets&vertical=default`

broken site

**Comment by yourduskquibbles** [comment]
I think I have a solution, @KonoromiHimaries can you test and confirm with your screen settings? I tried various resolutions on desktop and confirmed no breakage on mobile.twitter.com as well with emulated mobile browser.
