### ISSUE TITLE
forum.xda-developers.com

### ISSUE THREAD

**Issue by KonoromiHimaries** [yourduskquibbles/webannoyances#77]
![2018-06-23-one hosts file to block them all - 1hosts _ android development and hacking](https://user-images.githubusercontent.com/5884000/41810576-3736487e-7701-11e8-8769-962ad5e835f3.png)
`https://forum.xda-developers.com/android/general/badmojr-one-host-file-to-block-t3713360`

header

<details><summary>my settings</summary>

my filters
https://gist.github.com/KonoromiHimaries/afab54402a6cc37a168c2e55a0ef6896

 uBO 1.16.10
 ND 14.58
 Chr 67.0.3396.87
</details>

**Comment by yourduskquibbles** [comment]
Nevermind, I see what you are saying with the header overlapping the thread information.
