### ISSUE TITLE
more sites, again

### ISSUE THREAD

**Issue by elypter** [yourduskquibbles/webannoyances#8]
i collected yet another few more sites. btw i created a userscript that uses your list to heuristically unsticky elements on all websites. https://github.com/elypter/BlockHead 

it also outputs generic rules in the javascript console of the content that it modified. its far from perfect but it might one day be useable to create rules just from visting a website and you just have to verify that they dont break anything,

! 17.11.2017, 08:52:17 https://www.gamingonlinux.com/articles/first-steps-with-openvr-and-the-vive-on-linux.7229/
www.gamingonlinux.com##.navigation-main

! 17.11.2017, 08:53:05 http://www.floridatoday.com/story/tech/science/space/2017/11/16/spacex-launch-secretive-zuma-mission-northrop-grumman-delayed-again-friday-ksc-florida/871242001/
www.floridatoday.com##.site-nav

! 17.11.2017, 12:53:55 https://www.youtube.com/watch?v=1Z68UxY_Xds
www.youtube.com###yt-consent-dialog > .yt-dialog-base

! 17.11.2017, 12:54:04 https://www.youtube.com/watch?v=1Z68UxY_Xds
www.youtube.com###yt-dialog-bg

! 17.11.2017, 16:08:25 https://www.zdf.de/comedy/neo-magazin-mit-jan-boehmermann
www.zdf.de##.m-slim.js-rb-attached.b-header

! 18.11.2017, 09:45:50 https://www.wsj.com/articles/reddit-ceo-cracks-down-on-abusive-content-to-protect-users-attract-advertisers-1510853654?mod=e2tw
www.wsj.com##.style__at12units_UBXdDqMqvscHidlpmQZ6h.style__stick-cust-nav_1TmM50QDDL_l8iqfGHP_C3.style__scrolled_S35y-Q2jaGv7Ns7p4t74E.style__wsj-header_22l5Z8m7UC9IqccfdULTJ6

! 18.11.2017, 09:55:24 https://www.sciencedaily.com/releases/2017/11/171116132657.htm
www.sciencedaily.com##.navbar-custom.navbar-static.navbar-default.yamm.navbar

! 21.11.2017, 09:08:08 http://www.ketv.com/article/amber-alert-13-year-old-abducts-12-year-old/13812103
www.ketv.com##.slim.header

! 21.11.2017, 09:08:26 http://www.ketv.com/article/amber-alert-13-year-old-abducts-12-year-old/13812103
www.ketv.com##.article-sidelist--header

! 21.11.2017, 09:08:35 http://www.ketv.com/article/amber-alert-13-year-old-abducts-12-year-old/13812103
www.ketv.com##.slim-headline

! 21.11.2017, 09:27:02 https://www.bleepingcomputer.com/news/microsoft/microsoft-appears-to-have-lost-the-source-code-of-an-office-component/
www.bleepingcomputer.com##header

! 25.11.2017, 16:02:36 https://discourse.mozilla.org/t/support-umatrix/5131/19
discourse.mozilla.org##.clearfix.d-header > .wrap

! 25.11.2017, 16:03:00 https://discourse.mozilla.org/t/support-umatrix/5131/25
discourse.mozilla.org##.clearfix.d-header

! 28.11.2017, 12:42:27 https://duckduckgo.com/?q=flexible+teg&ia=web
duckduckgo.com###header_wrapper

! 28.11.2017, 16:07:14 https://itsfoss.com/privacy-search-engines/
itsfoss.com##.site-header

! 30.11.2017, 03:48:16 https://www.bloomberg.com/news/articles/2017-11-29/fake-views-444-938-russian-emails-among-suspect-comments-to-fcc
www.bloomberg.com##.persist-nav

! 30.11.2017, 15:44:31 https://www.quora.com/Can-birds-fly-in-outer-space
www.quora.com##.SiteHeader

! 1.12.2017, 04:55:47 https://filterlists.com/
filterlists.com##.site-header

! 1.12.2017, 21:20:27 http://www.tribonet.org/super-ballistic-electron-flow-confirmed/
www.tribonet.org###wpadminbar

! 5.12.2017, 13:49:58 http://listverse.com/2007/07/03/top-10-worst-living-dictators/
listverse.com##.toolbar

! 5.12.2017, 13:52:16 https://answers.yahoo.com/question/index?qid=20080913062100AA5Xwva
answers.yahoo.com###UH

! 5.12.2017, 14:06:12 https://www.sciencenews.org/article/new-physics-books-dont-censor-math-behind-reality
www.sciencenews.org###zone-nav-wrapper

! 5.12.2017, 19:42:10 https://gitlab.com/xuhaiyang1234/AAK-Cont
gitlab.com##.navbar

! 5.12.2017, 21:19:08 https://github.com/elypter
github.com##.is-stuck

! 8.12.2017, 15:30:41 https://support.google.com/chrome_webstore/answer/2664769?hl=en
support.google.com##.material-bar

! 8.12.2017, 15:33:03 https://stackoverflow.com/questions/4845215/making-a-chrome-extension-download-a-file
stackoverflow.com##._fixed.js-top-bar.top-bar

! 8.12.2017, 18:02:21 https://wiki.lineageos.org/devices/
wiki.lineageos.org##.navbar-fixed-top.navbar-white.navbar

! 8.12.2017, 19:52:48 https://www.chefkoch.de/rezepte/2570811402502140/Coleslaw-Atlanta-Style.html
www.chefkoch.de##.js-site-header.site-header

! 8.12.2017, 20:05:42 https://www.wikihow.com/Remove-Sticker-Residue
www.wikihow.com###header_outer

! 8.12.2017, 20:06:08 https://www.wikihow.com/Remove-Sticker-Residue
www.wikihow.com##.sticking

! 8.12.2017, 20:08:03 https://www.wikihow.com/Remove-Sticker-Residue
www.wikihow.com##.sticking

! 8.12.2017, 20:08:33 https://www.wikihow.com/Remove-Sticker-Residue
www.wikihow.com##.sticking

! 8.12.2017, 20:23:21 https://www.w3schools.com/cssref/sel_element.asp
www.w3schools.com###topnav > div

! 8.12.2017, 21:13:30 https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleDeclaration
developer.mozilla.org###toc > .center

! 9.12.2017, 03:35:00 http://isebaro.com/viewtube/?ln=en
isebaro.com##.header

! 9.12.2017, 20:23:47 https://www.privacytools.io/
www.privacytools.io##.navbar-fixed-top.navbar-inverse.navbar

! 10.12.2017, 03:52:12 https://www.smithsonianmag.com/innovation/how-wii-handset-inspired-low-cost-3d-ultrasound-180967426/
www.smithsonianmag.com###Scroll-Nav

! 10.12.2017, 03:56:12 http://agnnews.com/indian-americans-criticize-ajit-pai-stand-net-neutrality/
agnnews.com###site-navigation

! 10.12.2017, 03:58:52 http://thehill.com/policy/technology/363988-fcc-rejects-ny-ags-probe-into-net-neutrality-comments
thehill.com###navigation

! 10.12.2017, 04:02:19 http://www.independent.co.uk/news/world/asia/south-korea-decapitation-unit-kim-jong-un-overthrow-north-korea-latest-a8097016.html
www.independent.co.uk###masthead

! 10.12.2017, 08:05:06 https://www.reuters.com/article/us-mideast-crisis-iraq-islamicstate/iraq-declares-final-victory-over-islamic-state-idUSKBN1E30B9
www.reuters.com##.Header_container_O7Vma

! 10.12.2017, 08:05:22 https://www.reuters.com/article/us-mideast-crisis-iraq-islamicstate/iraq-declares-final-victory-over-islamic-state-idUSKBN1E30B9
www.reuters.com##.Header_is-fixed_3OnFb.Header_header_1xhmD

! 11.12.2017, 20:03:14 https://www.designnews.com/content/7-reasons-open-source-software-should-be-avoided/100858102757881
www.designnews.com###block-views-related-content-block

**Comment by yourduskquibbles** [comment]
Thank you! I will also have to check out your script and see how it works out.

**Comment by elypter** [comment]
i advanced the script quite a bit. the collected rules make more sense now and are an optional setting. in tampermonkey go to the overview and click on Blockhead and then the memory tab. turn save_generated_rules to 1 and they will be saved. to look at the rules either go to the memory tab again or open any url that contains "blockhead-rules" in the browser
