### ISSUE TITLE
reddit.com

### ISSUE THREAD

**Issue by joejordan** [yourduskquibbles/webannoyances#81]
Issue with reddit search:
https://www.reddit.com/search?q=hello&sort=relevance&t=all
![image](https://user-images.githubusercontent.com/997952/45000234-363ebc80-af91-11e8-9ec8-26175d52d1b8.png)

**Comment by yourduskquibbles** [comment]
Thanks for reporting @joejordan! I've had some issues preventing me from being able to work on the list the last few days but will get this fixed as soon as possible.
