### ISSUE TITLE
New logo proposal

### ISSUE THREAD

**Issue by twingenious** [yourduskquibbles/webannoyances#85]
Greetings, @yourduskquibbles 

Sorry if this isn't the appropriate channel for this, I'm a graphic designer in development and an open source enthusiast who exploring GitHub found your awesome project and would like to offer a logo for it. In case you agree, we would be working together to create the design that fits best with your project. And of course, you can quit whenever you want at whatever stage of the process we're at. If the answer is 'yes', I would like to hear from you any ideas you may have (shapes, colors, etc).

Keep up the great work, kind regards.

**Comment by yourduskquibbles** [comment]
Thanks for putting something together! 

I like your idea of the window boxes, maybe also include an icon within one of the windows that looks like a social network icon too? 

What is the significance of the padlock? Maybe in place of the padlock, have something like an eraser icon or a circle slash or bullseye/target symbol indicating that the annoyances are being removed by the list? 

What do you think of those ideas?

**Comment by twingenious** [comment]
well, the meaning of the padlock is he is blocking the windows, but as I said, I'm open to any idea.
I think the eraser is a good idea like the circle slash. 
are you saying that within the windows we can insert a social media symbol? what do you think like an icon of publicity inside the windows like "Buy it now"?

the logo may overload with the icon within the window

**Comment by twingenious** [comment]
sure, here is another idea

![webannoyances test 2](https://user-images.githubusercontent.com/43223329/46565200-fdb93800-c8da-11e8-97a1-0547367691a5.png)

What do you think?

**Comment by KonoromiHimaries** [comment]
> What do you think?

good for parental filter

**Comment by KonoromiHimaries** [comment]
try create monochromatic logo wothout any lock icon : P

**Comment by yourduskquibbles** [comment]
I've thought about this some, I like the two windows and the circle slash icon but not sure how I feel about the people icon - it looks to me like it is almost a "bumper sticker family" that we are putting the circle slash through.

**Comment by twingenious** [comment]
![webannoyances icons](https://user-images.githubusercontent.com/43223329/46830795-9e8e7400-cd6f-11e8-9fd2-dc7cd6cb0635.png)

What icon do you like most?. which one are you thinking?

**Comment by yourduskquibbles** [comment]
@twingenious That share icon one looks great to me!


Do you think it would look too busy if there was a modal SUBSCRIBE overlay with grey background to the top or bottom window of the icon? I'm thinking it may be difficult to convey that concept in a small pixel environment but wanted to get your opinion.

**Comment by twingenious** [comment]
![webannoyances3](https://user-images.githubusercontent.com/43223329/46900284-a0d6f800-ce6d-11e8-8013-bc2ccf1b89a0.png)

both looks good!!. is your choice man
:smiley:

**Comment by KonoromiHimaries** [comment]
😂 try create new logo with a Material Design

Design  Develop  Tools
 <https://material.io/>

**Comment by twingenious** [comment]
@konoromihimaries well, the material design is too minimalist and does not catch the 90s web feel . they looks more like google web pages

**Comment by KonoromiHimaries** [comment]
> does not catch the 90s web feel . they looks more like google web pages

that's what I expect, try to do it 👍 and getting the web faster at than in 90s
