### ISSUE TITLE
Can't deactivate Facebook account. Prompts not shown at https://www.facebook.com/deactivate/

### ISSUE THREAD

**Issue by AmperAndSand** [yourduskquibbles/webannoyances#88]
### URL(s) where the issue occurs
(must be logged in to access)
https://www.facebook.com/deactivate/

### Describe the issue

I can't deactivate my Facebook account at https://www.facebook.com/deactivate/. If Web Annoyances Ultralist​​​​​ is enabled​​​​, the prompts that are normally shown in that page ('Give Feedback' and 'Deactivate Now') are not shown, preventing one from proceeding to deactivate their account. Clicking on the blue 'Deactivate' button on the lower left does nothing.

### Screenshot(s)

This is a screenshot of the prompts that are normally shown if Web Annoyances Ultralist​​​​​ is not enabled:
![web annoyances ultralist - cant deactivate facebook](https://user-images.githubusercontent.com/1404745/46456659-3aedcf00-c7e2-11e8-9a1c-855f0c7747f4.png)

### Versions

- Browser/version: Chrome 69.0.3497.100 (Official Build) (64-bit)
- uBlock Origin version: 1.17.0

### Settings
In uBO, all options in Privacy are enabled. Nothing in Default behavior is enabled. In Filter Lists, all the filters in the Built-in, Ads, Privacy, Malware Domains, Annoyances and Multipurpose sections are enabled, except for Fanboy’s Social Blocking List​​​​​​​​​. Nothing in the Regions, languages section is enabled.

### Notes

The issue does not happen if Web Annoyances Ultralist​​​​​ is disabled.

**Comment by yourduskquibbles** [comment]
Thanks for the detailed report @AmperAndSand ! This should be fixed but please let me know if you experience otherwise.

This is a core functionality break of Facebook, one should always be able to checkout and leave unlike Hotel California :)
