### ISSUE TITLE
even more sites

### ISSUE THREAD

**Issue by elypter** [yourduskquibbles/webannoyances#9]
! 26.12.2017, 04:08:31 https://www.csmonitor.com/Environment/2017/1222/Drought-tolerant-corn-offers-Uganda-s-farmers-a-lifeline
www.csmonitor.com###csm-page-bound > .layer-fixed:nth-of-type(1)

! 26.12.2017, 19:49:57 http://www.zerohedge.com/news/2017-12-25/nsa-whistleblower-snowden-launches-mobile-app-paranoid-people
www.zerohedge.com###site-header

! 26.12.2017, 20:48:40 https://www.bleepingcomputer.com/news/software/thunderbird-will-phase-out-legacy-add-ons-will-support-webextensions/
www.bleepingcomputer.com##header

! 26.12.2017, 21:13:29 https://www.inverse.com/article/39671-in-the-wake-of-net-neutrality-prepare-for-internet-fast-lanes
www.inverse.com##.sticky.header-container

! 26.12.2017, 23:00:37 https://hooktube.com/watch?v=vY3Cy7NCEQ0
hooktube.com##.show.fade.modal-backdrop

! 26.12.2017, 23:06:08 https://hooktube.com/watch?v=vY3Cy7NCEQ0
hooktube.com##.show.fade.modal-backdrop

! 27.12.2017, 00:58:05 https://uploadvr.com/siggraph-neurable-lets-control-virtual-world-thought/
uploadvr.com###sticky-bar > .row

! 27.12.2017, 14:59:22 https://futurism.com/new-trial-scotland-bring-universal-basic-income-life/
futurism.com##.headroom--not-top.headroom.main-nav

! 27.12.2017, 15:04:26 https://userstyles.org/
userstyles.org###header

! 27.12.2017, 15:38:28 https://copenhagensuborbitals.com/
copenhagensuborbitals.com##.hestia_left.navbar-fixed-top.navbar-default.navbar

! 27.12.2017, 22:57:35 http://www.emailtester.de/freemail/vergleich.php
www.emailtester.de###header

! 27.12.2017, 22:57:47 http://www.emailtester.de/freemail/vergleich.php
www.emailtester.de###cssmenu > ul

! 28.12.2017, 02:21:50 https://forum.freecodecamp.org/t/chrome-61-adds-native-support-for-javascript-modules/146532
forum.freecodecamp.org##.clearfix.d-header

! 28.12.2017, 04:23:47 http://www.chip.de/bildergalerie/Die-50-besten-Userscripts-fuer-Chrome-und-Firefox-Galerie_55779726.html
www.chip.de##.Header--Sticky.Header--Elevated.Header

! 28.12.2017, 06:19:46 https://www.zdf.de/dokumentation/zdfinfo-doku/wunder-der-wissenschaft-rollende-spinnen-und-seestern-zerstoerer-100.html
www.zdf.de##.m-slim.js-rb-attached.b-header

! 28.12.2017, 13:00:27 https://www.techwalla.com/articles/how-to-change-the-default-media-player-in-firefox
www.techwalla.com###header-dinosaur > .container

! 28.12.2017, 13:00:42 https://www.techwalla.com/articles/how-to-change-the-default-media-player-in-firefox
www.techwalla.com###header-dinosaur

! 28.12.2017, 13:09:03 http://blog.teamtreehouse.com/building-custom-controls-for-html5-videos
blog.teamtreehouse.com##nav

! 28.12.2017, 16:38:43 https://developer.mozilla.org/en-US/Apps/Fundamentals/Audio_and_video_delivery/Video_player_styling_basics
developer.mozilla.org###toc > .center

! 5.1.2018, 08:04:27 https://www.spacetelescope.org/news/heic1620/
www.spacetelescope.org##.navbar-general-wrapper

! 5.1.2018, 22:33:58 https://wordpress.org/plugins/list-plugins/
wordpress.org###wpadminbar

! 10.1.2018, 08:20:23 https://lineageos.org/
lineageos.org##.navbar-fixed-top.navbar-transparent.navbar

! 10.1.2018, 10:15:46 https://fossbytes.com/postmarketos-linux-distro-smartphones-plasma-xfce-real/
fossbytes.com##.td-affix.td-header-main-menu.td-header-row

! 12.1.2018, 16:49:42 https://treato.com/Alkaline+Batteries,Toxicity/?a=s
treato.com###modal-bg

! 12.1.2018, 16:49:51 https://treato.com/Alkaline+Batteries,Toxicity/?a=s
treato.com###drug-review-increase-sp

! 12.1.2018, 16:50:03 https://treato.com/Alkaline+Batteries,Toxicity/?a=s
treato.com##.treatoSqueezePagePopupWrap

! 15.1.2018, 09:40:58 http://www.giga.de/smartphones/lg-g3/tipps/lg-g3-hard-reset-soft-reset-und-safe-mode-oeffnen/
www.giga.de##.visible-lg.navbar-fixed-top.navbar-sub.navbar

! 15.1.2018, 09:41:07 http://www.giga.de/smartphones/lg-g3/tipps/lg-g3-hard-reset-soft-reset-und-safe-mode-oeffnen/
www.giga.de##.navbar-fixed-top.navbar-main.navbar-default.navbar

! 15.1.2018, 14:24:14 https://riftcat.com/vridge
riftcat.com###header

! 15.1.2018, 14:35:08 https://www.trinusvirtualreality.com/
www.trinusvirtualreality.com##header

! 16.1.2018, 10:29:29 https://assetstore.unity.com/packages/tools/visual-scripting/playmaker-368
assetstore.unity.com##._1n3NdZ51JV1jcfoLc-8DYJ:nth-of-type(1) > .dark._1cr_j_XgisBIu_-LSKWuiB

! 16.1.2018, 10:29:36 https://assetstore.unity.com/packages/tools/visual-scripting/playmaker-368
assetstore.unity.com##._1n3NdZ51JV1jcfoLc-8DYJ:nth-of-type(2) > .dark._1cr_j_XgisBIu_-LSKWuiB

! 16.1.2018, 15:05:26 https://vrchat.com/community
vrchat.com###bs-example-navbar-collapse-1

! 16.1.2018, 15:05:38 https://vrchat.com/community
vrchat.com##.container-fluid

! 16.1.2018, 16:01:28 http://www.vrpill.com/go-down-the-rabbit-hole/
www.vrpill.com##.navbar-primary-nav

**Comment by yourduskquibbles** [comment]
Thanks!

**Comment by Ravizz** [comment]
Sorry for off-topic, but I'm just testing if I can comment in this issue, hmm I can.
