### ISSUE TITLE
chrome.google.com

### ISSUE THREAD

**Issue by KonoromiHimaries** [yourduskquibbles/webannoyances#92]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

`https://chrome.google.com/webstore/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm`

### Describe the issue

header

**Comment by yourduskquibbles** [comment]
Does `chrome.google.com##.F-f-k:style(position: relative !important; overflow: unset !important;)` work for you?

Note: This filter will only work if viewed in a browser **besides** Chrome. Chrome doesn't allow extensions to run on it it's webstore.

**Comment by KonoromiHimaries** [comment]
not work

**Comment by yourduskquibbles** [comment]
@KonoromiHimaries I saw you posted a not working comment, but looks like it was deleted - are you able to test the filter on firefox or edge to confirm if it works?
