### ISSUE TITLE
Craigslist "continue" button hidden by filter

### ISSUE THREAD

**Issue by joejordan** [yourduskquibbles/webannoyances#94]
### URL(s) where the issue occurs
`https://post.craigslist.org/`

### Describe the issue
Continue button being hidden by filter, making it impossible to progress with a craigslist posting with the filter enabled. Element is below:

<button type="submit" name="go" value="continue" class="go big-button submit-button" tabindex="1">continue</button>

### Versions

- Browser/version: Firefox 62
- uBlock Origin version: 1.17.0

**Comment by yourduskquibbles** [comment]
Thanks for reporting
