### ISSUE TITLE
play.google.com

### ISSUE THREAD

**Issue by KonoromiHimaries** [yourduskquibbles/webannoyances#99]
### URL(s) where the issue occurs

`https://play.google.com/store/apps/details?id=com.hv.replaio`

### Describe the issue

i do not can send my opinnion about that app

### Screenshot(s)

![2018-11-02-polskie radio internetowe replaio aplikacje w google play](https://user-images.githubusercontent.com/5884000/47893151-cdbe6f80-de5b-11e8-8091-f4d66d38f111.png)

### Versions
Browser/version: [here] chrome latest release
uBlock Origin version: [here] latest release

### Settings
https://gist.github.com/KonoromiHimaries/ce463027dda8ce57b01bb5639009f21e

**Comment by yourduskquibbles** [comment]
I don't have an android phone that I can install this on to test (review option isn't even given if you don't have the app installed). 

Do you know what filter is causing the issue? Is it a generic cosmetic filter or domain specific filter targeted at `play.google.com` or `google.com`?
